graphprotocol/graph-node

README.md

Reccomend `--release` in the README.

---

docs/getting-started.md

- Consolidates build and compile steps in getting started
- Adds a note about `Store.set` and `Entity.unset` API to indicate that attributes not explicitly set (or unset) will not be overwritten.

docs: Minor getting started improvements

---

docs/subgraph-manifest.md

docs: fix broken links

---

datasource/ethereum/tests/adapter.rs
graph/src/components/server.rs
graph/src/data/query/error.rs
graph/src/data/store/mod.rs
graph/src/data/subgraph.rs
graphql/src/query/execution.rs
graphql/src/store/query.rs
graphql/src/store/resolver.rs
graphql/tests/query.rs
mock/src/server.rs
runtime/wasm/src/asc_abi/test.rs
runtime/wasm/src/module.rs
server/http/src/request.rs
server/http/src/server.rs
server/http/src/service.rs
store/postgres/tests/store.rs

rustfmt version `0.8.2-stable` changed some things.

*: Format for Rust 1.28

---

runtime/wasm/src/host.rs

Fix regression reported by @Ford where the tokio upgrade caused us to only process one event, because waiting on one event stream permanently blocked all others.
This is done by merging all of the event streams and then waiting on the unified stream, allowing for receiving interleaved events which also improves performance.

runtime: Handle all events, merge event streams

---

.github/ISSUE_TEMPLATE.md

github: Add ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md

---

core/src/subgraph/provider.rs
graph/src/components/subgraph/provider.rs
graph/src/data/subgraph.rs
node/src/main.rs
server/http/src/server.rs
server/json-rpc/src/lib.rs

Suport subgraph removal, rename `subgraph_add` to `subgraph_deploy`

---

runtime/wasm/src/module.rs

Traps if the `BigInt` is of the wrong size.
cli PR https://github.com/graphprotocol/graph-cli/pull/111

runtime: Export `typeConversion.bigIntToInt256`

---

node/src/main.rs

Spawn the IPFS connection test on a tokio task, removing the use of `.wait()`. This has the downside of a failure not crashing the node, but that will be fixed by #314. This should be safe to merge regardless of the issues we had before, because even if this somehow still blocks forever, it will not prevent the node from starting up normally.

node: do not block on IPFS connection test

---

datasource/ethereum/src/ethereum_adapter.rs

datasource/ethereum: Add contract address to event filter

---

graph/src/components/ethereum/adapter.rs
graph/src/components/ethereum/mod.rs
graph/src/lib.rs

Ported from tim/block-processing

Add EthereumBlockPointer type

---

docs/getting-started.md

@Jannis done, let me know what you think.

docs: Update info about store.get

---

.travis.yml

It has "rust" in it. And fixes our builds (no idea why).

travis: Go back to trusty

---

Cargo.lock
store/postgres/Cargo.toml
store/postgres/src/filter.rs
store/postgres/src/store.rs
store/postgres/tests/store.rs

Fixes #415. I suspected that list equality was also affected but it's not.
I added a test but store tests are currently borked.

Fix bytes filters

---

README.md
docs/getting-started.md
docs/graphql-api.md

Looking to just get some input on if there is anything I have missed. Please also check out for typos, bad grammar, or repetitiveness. 
I will be testing these on dharma this week, so I will be able to catch any errors as I go through the docs.
Resolves #388

Dave update getting started docs, and other supplimentary docs

---

datasource/ethereum/src/ethereum_adapter.rs
graph/src/components/ethereum/adapter.rs
runtime/wasm/src/module/mod.rs

Fix eth_call retrying problem (on ethsf)
See #446

Run eth_call on tokio runtime (on ethsf)

---

datasource/ethereum/src/ethereum_adapter.rs
graph/src/components/ethereum/adapter.rs
runtime/wasm/src/module/mod.rs

Run eth_call on tokio runtime (on master)

---

datasource/ethereum/src/block_ingestor.rs
store/postgres/migrations/2018-08-22-140000_create_chain_head_update_procedure/up.sql

Same as https://github.com/graphprotocol/graph-node/pull/469 but for master branch

datasource, store: Fix block ingestion on short chains

---

datasource/ethereum/src/block_ingestor.rs
graph/src/components/store.rs
graph/src/lib.rs
graph/src/util/futures.rs
mock/src/store.rs
store/postgres/src/store.rs

Cherry pick commits to ethsf branch

Cherry pick block ingestor fixes to ethsf

---

README.md

Connects to: https://github.com/graphprotocol/graph-node/issues/410
Resolves: https://github.com/graphprotocol/graph-node/issues/410

Readme: Update Ethereum flags

---

datasource/ethereum/src/block_ingestor.rs
datasource/ethereum/src/block_stream.rs
mock/src/server.rs
server/http/src/server.rs
server/websocket/src/server.rs

Capitalize logs

---

.travis.yml

Using tricks I learned from the [diesel travis](https://github.com/diesel-rs/diesel/blob/master/.travis.yml#L40) to fix and cleanup our included builds. Also pin the rustfmt version so we're not forced to upgrade as soon as Rust upgrades.

travis: Fix and refactor style check and release building

---

.travis.yml
datasource/ethereum/src/block_ingestor.rs
datasource/ethereum/src/block_stream.rs
datasource/ethereum/src/ethereum_adapter.rs
graphql/tests/query.rs
server/json-rpc/src/lib.rs
store/postgres/src/filter.rs
store/postgres/src/store.rs

Fixing our CI. Also add Rust 1.29 to our travis matrix.

Update formatting to Rust 1.30

---

runtime/wasm/src/host_exports.rs

Saw a user hit this so maybe we can improve it.

runtime: Make error message more user friendly

---

Cargo.lock
core/src/subgraph/provider.rs
graph/Cargo.toml
graph/src/components/store.rs
graph/src/data/subgraph/schema.rs
graph/src/lib.rs
graphql/src/store/resolver.rs
graphql/tests/query.rs
mock/src/store.rs
server/http/src/service.rs
server/websocket/src/server.rs
store/postgres/src/store.rs

In preparation for addition of subgraph status fields.
Part of #584

Refactor subgraph entity logic 

---

Cargo.lock
store/postgres/Cargo.toml
store/postgres/src/store.rs
store/postgres/tests/store.rs

Resolves #396. I didn't tweak the pool configurations, in the spirit of "any pooling is better than no pooling". But it'd be good if those who know more about DBs could take a look at the [builder defaults](https://docs.diesel.rs/r2d2/struct.Builder.html) and check if they're ok for our use. We can fine tune later.

Use a DB connection pool

---

README.md
docs/getting-started.md
docs/graphql-api.md
docs/subgraph-manifest.md

I have completed the edits to four documents.

S mason/docs december

---

store/postgres/migrations/2019-02-01-045927_add_entities_indexes/down.sql
store/postgres/migrations/2019-02-01-045927_add_entities_indexes/up.sql

Add multicolumn index to entities table on the subgraph and entity columns

---

README.md
docs/getting-started.md

Small updates to the docs that update them to latest commands

---

graph/src/components/store.rs
graph/src/data/subgraph/schema.rs
graphql/src/store/query.rs
graphql/src/store/resolver.rs
server/http/src/service.rs
store/postgres/src/store.rs
store/postgres/tests/store.rs

By accident, #809 made the internal queries for subgraph of subgraph entities be limited to 100 results.
Thanks @lutter for catching this in review.

graph, store: Fix EntityRange

---

graphql/src/schema/api.rs
graphql/src/store/query.rs
graphql/tests/query.rs

Also test and fix behaviour for `skip`.

Make `first` nullable

---

docs/subgraph-manifest.md
graph/src/components/ethereum/adapter.rs
graph/src/data/graphql/values.rs
graph/src/data/subgraph/mod.rs
graph/src/data/subgraph/schema.rs
runtime/wasm/src/host.rs
store/postgres/src/subgraphs.graphql

Resolves https://github.com/graphprotocol/graph-node/issues/756. I haven't properly tested this yet. @davekaj would you have time to also give this a shot, along with https://github.com/graphprotocol/graph-cli/pull/246?

Custom topic0

---

store/postgres/src/store.rs

When we make changes to the database schema, we should reset the query
statistics as old statistics might be misleading.

store/postgres: reset pg_stat_statements after a database migration

---

store/postgres/src/store.rs

We had the problem that if multiple graph-nodes started up simultaneously,
all of them would try to run database migrations. Only one of them would
succeed, and the others would have their migrations rolled back. That
causes issues with slow or expensive migrations because it forces the
database to do a lot of unnecessary work.
With this change, only one graph-node will migrate the database, all the
others will wait for it to finish by blocking on a new
__graph_node_global_lock table.

store/postgres: make sure only one graph-node runs database migrations

---

graph/src/log/elastic.rs

Log arguments are sent to ElasticSearch as a comma separated list appended to the log message. To create panels in Grafana from the log arguments they need to be accessible as a property in the log's JSON record.

Include arguments to log in ElasticSearch log as a map

---

graph/src/data/subgraph/schema.rs

We only created indexes for fields whose type was a scalar, which left out
fields that reference other entities. This PR makes sure we also create
indexes on such fields.
Fixes https://github.com/graphprotocol/graph-node/issues/916

graph/data: Ensure we index foreign keys in the GraphQL schema

---

store/postgres/src/notification_listener.rs

The locks we need to acquire to clean up old large notifications can make a
transaction wait for one (or several) slow transactions, stalling the whole
system, or even lead to a deadlock.
With this change, we only clean up old large notifications that are not
currently locked by other transactions so that we will never wait for
them.
Fixes https://github.com/graphprotocol/graph-node/issues/987

store/postgres: Reduce locking when cleaning up large notifications

---

graph/src/components/ethereum/types.rs
runtime/wasm/src/asc_abi/class.rs
runtime/wasm/src/module/mod.rs
runtime/wasm/src/to_from/external.rs

Gives a mapping sender of the `EthereumCall` it is triggering on.

Add ethereum call `from`

---

store/postgres/src/entities.rs

Partial fix for https://github.com/graphprotocol/graph-node/issues/995

store/postgres: Index BigInt/BigDecimal attributes as numbers

---

Cargo.lock
graph/Cargo.toml
graph/src/data/store/scalar.rs
runtime/wasm/src/host_exports.rs
runtime/wasm/src/module/mod.rs

See https://github.com/graphprotocol/graph-ts/pull/69.

Add `bigInt.pow` export

---

docs/environment-variables.md

The docs have been out of date for this env var.

Update docs for GRAPH_MAPPING_HANDLER_TIMEOUT

---

store/postgres/src/relational.rs

We make sure that the type and attribute names from GraphQL schemas are
safe to use in SQL, but users may use names that conflict with reserved
words in SQL; for example, a type 'User' will result in the creation of a
table 'user'. That causes a syntax error in Postgres, and we therefore need
to enclose these names in double-quotes during schema creation. Proper
queries do not have this problem since we have Diesel escape them as
identifiers already.

store: Quote table and column names when creating relational schema

---

Cargo.lock
graph/Cargo.toml
graph/src/log/elastic.rs
node/Cargo.toml
node/src/main.rs
server/http/Cargo.toml
server/http/src/lib.rs

Remove itertools dependency

---

graph/src/components/store.rs
graph/src/lib.rs
store/postgres/src/block_range.rs
store/postgres/src/entities.rs
store/postgres/src/history_event.rs
store/postgres/src/lib.rs
store/postgres/src/relational.rs
store/postgres/src/relational_queries.rs
store/postgres/src/store.rs
store/postgres/tests/relational.rs
store/test-store/src/lib.rs

These patches do not affect functionality, they mostly clean up and refactor some of the store code, partly in preparation for #1188

Clean up of some of the store code

---

store/postgres/src/relational.rs
store/postgres/src/relational_queries.rs

Add a generated primary key to all entities

---

store/postgres/src/entities.rs
store/postgres/src/filter.rs

These two changes improve the performance of a number of queries; especially the first one will take a lot of load off the database.

Two performance improvements

---

core/src/subgraph/instance_manager.rs
datasource/ethereum/src/block_stream.rs

We were almost doing this correctly, but not quite.

Check templates to decide if calls should be included in block

---

graph/src/components/store.rs
graph/src/data/subgraph/schema.rs
mock/src/store.rs
store/postgres/src/functions.rs
store/postgres/src/lib.rs
store/postgres/src/relational.rs
store/postgres/src/store.rs

This should help in getting to the bottom of why we sporadically see #1093

Include more detail in 'update did not change any rows' error

---

store/postgres/src/store.rs

When we send a StoreEvent via pg_notify, Postgres takes an
AccessExclusiveLock on its internal notification queue. Us holding that
lock for too long is most likely the reason for
https://github.com/graphprotocol/graph-node/issues/1248 as other
connections who also want to send notifications can get blocked behind a
slow store transaction.
To make this less likely, we rearrange the code so that notifications are
send just before we are going to finish our transaction, after all other
database work has been done.

store: Defer sending StoreEvent until we are about to commit

---

graph/src/data/graphql/validation.rs

These validations follow the corresponding validations in graph-cli, and make sure users do not deploy invalid subgraphs, e.g., because they have not updated their subgraph or graph-cli
Fixes https://github.com/graphprotocol/graph-node/issues/1213

graph: Validate @derivedFrom directives on subgraph schemas

---

README.md

These commands in the readme don't match the ens subgraph repo

docs: Update ens interface

---

store/postgres/src/subgraphs.graphql

Everywhere else this is `startBlock`.

Fix name of start block field in schema

---

store/postgres/src/relational.rs

That does not work in Postgres 9.6

store: Do not index columns of type array of enum

---

runtime/wasm/src/module/mod.rs

To reduce the overhead of this check. It's still effective, since an infinite loop would call this infinite times.
Resolves #1337.

Reduce frequency of timeout checks

---

core/src/subgraph/instance_manager.rs

Addresses https://github.com/graphprotocol/support/issues/38

Log the transaction hash for the trigger when it fails to run

---

node/src/main.rs

The root cause is still the same, but even without the `.wait()` the future would still block itself, wrapping everything in a `tokio::spawn` fixed it.

Fix hanging on startup (for real this time)

---

chain/ethereum/src/block_stream.rs

This is a better fix for #1359, for our quick start guide and Ganache chains in general. Instead of panicking, gracefully handle the situation by assuming genesis can't be reorged.

Better solution for reorg threshold on short chains

---

graphql/src/query/mod.rs

That will make it possible to analyse which queries are taking a lot of time.

graphql: Log the time it took to run a query together with the query

---

chain/ethereum/src/block_ingestor.rs
docs/environment-variables.md
graph/src/components/store.rs
graph/src/log/mod.rs
mock/src/store.rs
node/src/main.rs
store/postgres/src/store.rs

Fixes https://github.com/graphprotocol/support/issues/45

node, graph, store, chain: Remove unneeded blocks from the block cache

---

store/postgres/src/relational_queries.rs

store: Speed up simple queries by delaying JSONB generation in the database

---

Cargo.lock
graph/Cargo.toml
graph/src/components/server/subscription.rs
graph/src/lib.rs
node/src/main.rs
runtime/wasm/Cargo.toml
server/websocket/Cargo.toml
server/websocket/src/connection.rs
server/websocket/src/server.rs

Our version is really old. This fixes an issue where our 404 responses where instead immediately closing the connection.
Tested locally that subscriptions still work. We should check on staging that this resolves the issue.

Update tokio tungstenite

---

store/postgres/src/relational.rs

Small improvement to help out Ziggy

store: Log the number of entities retrieved with a SQL query

---

store/postgres/src/notification_listener.rs

Right now, we try to cleanup large notifications every time one is sent. That is way too often; instead, only do the cleanup once per the configured notification interval.
This change makes sense regardless, but I am also hoping that it will reduce how often we see very slow commits in production.

store: Only try to cleanup large notifications once per cleanup interval

---

store/postgres/src/relational_queries.rs

If a window connected children to parents through a list of child id's
stored in the parent, and if all parents in a query had an empty list, we
would generate `array[]::text[][]` which is wrong since we need to produce
a two-dimenional array. It does not seem possible to produce an entirely
empty two-dimensional array (a 0x0 matrix), instead we produce a 1x1 matrix
with an entry `null` as `array[array[null]]::text[][]`.

store: Produce correct empty array in FilterWindow.expand_parents

---

tests/integration-tests/data-source-context/src/mapping.ts

Depends on https://github.com/graphprotocol/graph-ts/pull/108.

Use `DataSourceContext` class

---

NEWS.md
docs/environment-variables.md
graph/src/log/mod.rs
graphql/src/query/mod.rs
store/postgres/src/relational.rs

graph, graphql, store: Control query timing logs with environment variable

---

Cargo.lock
chain/ethereum/src/network_indexer/subgraph.rs
core/Cargo.toml
core/src/subgraph/instance_manager.rs
core/src/subgraph/registrar.rs
docs/subgraph-manifest.md
graph/Cargo.toml
graph/src/components/store.rs
graph/src/data/subgraph/mod.rs
graph/src/data/subgraph/schema.rs
graph/tests/manifest.rs
graphql/tests/query.rs
mock/src/store.rs
store/postgres/examples/layout.rs
store/postgres/migrations/2020-03-25-170527_deployment_graft_base/down.sql
store/postgres/migrations/2020-03-25-170527_deployment_graft_base/up.sql
store/postgres/migrations/2020-04-04-002817_change_deployment_state/down.sql
store/postgres/migrations/2020-04-04-002817_change_deployment_state/up.sql
store/postgres/src/copy_dds.sql
store/postgres/src/entities.rs
store/postgres/src/lib.rs
store/postgres/src/metadata.rs
store/postgres/src/relational.rs
store/postgres/src/relational_queries.rs
store/postgres/src/store.rs
store/postgres/src/subgraphs.graphql
store/postgres/tests/graft.rs
store/postgres/tests/store.rs
store/test-store/src/lib.rs

This PR implements subgraph grafting as described in this [engineering plan](https://github.com/graphprotocol/rfcs/blob/master/engineering-plans/0004-subgraph-grafting.md)

Grafting of subgraphs

---

store/postgres/src/notification_listener.rs

Catch panics so we can exit the process and not just the thread. Disable whitespace diff to read it.

notification listener: Exit process on panic

---

store/postgres/src/relational.rs
store/postgres/src/relational_queries.rs

The reasoning behind these changes is in https://github.com/graphprotocol/graph-node/issues/1415

Add BRIN indexes to speed up reverts

---

graph/src/components/subgraph/proof_of_indexing/event.rs
graph/src/data/subgraph/mod.rs
graph/src/lib.rs
graph/src/log/codes.rs
graph/src/log/mod.rs

Just makes it easier to impl slog::Value

graph: sugar for impl slog::Value

---

core/tests/interfaces.rs
graphql/src/execution/execution.rs

Fix aliased scalar fields

---

node/src/main.rs

Increase the maximum number of blocking threads

---

store/postgres/src/relational_queries.rs

This helps greatly in speeding up one of hte problematic queries we see in
production, bringing execution time down from 13s to 1.2s

store: Speed queries of type A up by adding a redundant clause

---

graph/src/data/graphql/effort.rs
server/websocket/src/connection.rs
store/postgres/src/relational_queries.rs

Erroneous logic in how we step down the `kill_rate` caused it to never fully go to 0

Correctly resolve overload situation

---

server/http/src/service.rs

This is a relatively cheap DB operation, but at the volume of thousands of queries per second this could clog the tokio threadpool.

Resolve subgraph names in a blocking task

---

Cargo.lock
runtime/wasm/Cargo.toml
store/postgres/Cargo.toml

And remove dead dependency in the runtime crate.

Update `MaybeOwned` dependency

---

store/postgres/src/relational_queries.rs

Instead of checking whether an entity is in a list of entities with
id = any($ids)
perform the check with
exists (select 1 from unnest($ids) as p(id) where id = p.id)
since the latter makes the exclusion index on (id, block_range) usable for
the FindMany query
For one subgraph, that reduces query time from ~ 5 minutes to 500ms

store: Speed up the FindMany query

---

runtime/wasm/src/host.rs

See #1841, if we print the raw data this gives us a shot at reproducing the error.

Log failed output decoding

---

graph/src/components/ethereum/adapter.rs

We have some index nodes crashing on this unwrap.

Replace unwrap with error

---

chain/ethereum/src/ethereum_adapter.rs

This is useful for debugging, especially when suspecting that the issue is with the Ethereum provider, since it allows fully reproducing the eth_call request.

Optional full eth_call logging

---

chain/ethereum/src/block_stream.rs
graph/src/components/ethereum/adapter.rs
graph/src/components/ethereum/types.rs

Skip trace_filter on empty block

---

store/postgres/src/relational.rs

For some subgraphs, this query takes several minutes; this index helps speed that query up quite a bit.

store: Create an index that helps with the RevertClampQuery

---

store/postgres/src/relational_queries.rs

Consider empty list when constructing tsvectors

---

graph/src/data/subgraph/schema.rs

Right now on every graph node restart a new error entity is created for every failed subgraph, which is an unnecessary amount of bloat. Use the hash of the contents as the error id so that they are no longer duplicated.

metadata: Dont duplicate errors

---

store/postgres/src/store.rs

Remove note to self

---

core/src/subgraph/instance_manager.rs
core/src/subgraph/provider.rs
graph/src/components/store.rs
graph/src/data/subgraph/schema.rs
mock/src/store.rs
node/src/main.rs
store/postgres/src/metadata.rs
store/postgres/src/network_store.rs
store/postgres/src/store.rs
store/postgres/tests/store.rs
store/test-store/src/lib.rs

This is from lutter/shard, but it's also very useful for the non-fatal errors work so it's worth merging these separately.

Cherry pick unfail logic

---

Cargo.lock
runtime/wasm/Cargo.toml

Ran `cargo update` for a security audit

*: Upgraded dependencies

---

graph/src/components/store.rs
graph/src/data/subgraph/schema.rs
store/postgres/src/metadata.rs
store/postgres/src/store.rs
store/postgres/tests/subgraph.rs

There's a special treat in this PR ;)

Address corner cases of deploying that the new logic got wrong

---

store/postgres/src/metadata.rs

We call `deployment_synced` a lot, and most of the time, it does not do
anything. If we did not make any changes, there is also no reason to clean
up unused assignments, which is a somewhat expensive query.

store: Reduce how often we try to clean up unused assignments

---

store/postgres/src/detail.rs

store: Don't trip over old errors with invalid block hash/range combinations

---

store/postgres/src/sharded_store.rs

By holding connections for the minimum scope necessary, preferably as temporary values. This doesn't solve all identified deadlocks, but it's an attempt at improving the short term situation.

Avoid some potential deadlocks in the sharded store

---

Cargo.lock
store/postgres/Cargo.toml
store/postgres/src/connection_pool.rs
store/postgres/src/store.rs

This should help with debugging connection pool deadlocks.

Print backtrace on connection get stall

---

Cargo.lock
graph/Cargo.toml
graph/src/util/timed_rw_lock.rs

We need a fair RwLock for the cache.

Use parking-lot for cache locks

---

graphql/src/execution/execution.rs

We don't have that many more writers than readers, and the read section is shorter than the write section, so I don't believe the overhead of an RwLock is justified. Empirically we see a ton of contention on the RwLock cache but none on the Mutex cache.

Swap RwLock for Mutex on query cache

---

graphql/src/runner.rs
graphql/src/subscription/mod.rs
graphql/tests/query.rs

The overall effect will be that subscriptions will be deduplicated

Make subscription queries cacheable

---

.github/workflows/audit.yml
.github/workflows/ci.yml
chain/ethereum/src/block_stream.rs

I am not sure how to run these actions without committing them, this PR is likely just a start at getting them right.

Security audit and CI actions

---

graph/src/data/schema.rs
graphql/src/store/resolver.rs
graphql/tests/query.rs

Fixes https://github.com/graphprotocol/graph-node/issues/2106

graphql: Resolve __typename in _meta field

---

graphql/src/execution/execution.rs

The same way that was done for the generational cache.

Shard LFU cache

---

core/src/subgraph/loader.rs
store/postgres/src/dynds.rs

It seems ordering by vid was not sufficent for some subgraphs in hosted.

Ensure data sources are loaded in creation order

---

store/postgres/src/sql_value.rs

Somehow a subgraph is triggering these panics and crashing nodes.

Replace panic with error in the store

---

core/tests/interfaces.rs
graph/src/components/server/index_node.rs
graph/src/components/store.rs
graph/src/data/query/result.rs
graphql/src/runner.rs
graphql/tests/query.rs
mock/src/store.rs
server/index-node/src/explorer.rs
store/postgres/migrations/2021-01-14-193022_deployment_schemas_network_not_null/down.sql
store/postgres/migrations/2021-01-14-193022_deployment_schemas_network_not_null/up.sql
store/postgres/src/deployment.rs
store/postgres/src/network_store.rs
store/postgres/src/primary.rs
store/postgres/src/query_store.rs
store/postgres/src/sharded_store.rs
store/postgres/src/store.rs
store/postgres/tests/subgraph.rs
store/test-store/src/store.rs

This is the second part of the work mentioned in PR #2117

Make `deployment_schemas.network` mandatory

---

docker/Dockerfile
docker/start

This PR will allow to optionally specify ethereum poll interval when using graph-node's docker image

docker: Allow custom ethereum poll interval

---

graphql/src/execution/cache.rs

The correct place to measure this is in `CacheByBlock`, not in the `QueryBlockCache`.

Fix cache timing recording

---

runtime/wasm/src/mapping.rs

I have this on in the integration test cluster to be able to better audit the inputs to mappings.

Option to log trigger data

---

graph/src/data/store/scalar.rs
runtime/wasm/src/host_exports.rs
runtime/wasm/src/module/mod.rs
tests/integration-tests/big-decimal/src/mapping.ts

Hello! This is my first Pull Request here, I am trying to solve this issue https://github.com/graphprotocol/graph-node/issues/2145.
I don't know much about the project, so correct me if I am doing anything wrong :slightly_smiling_face:

runtime: Add missing BigInt host exports

---

store/postgres/src/chain_store.rs
store/postgres/tests/chain_head.rs

Fixes https://github.com/graphprotocol/graph-node/issues/2168

store: Fix call_cache queries when the chain is in a separate namespace

---

tests/integration-tests/big-decimal/src/mapping.ts

Fix big decimal test

---

store/postgres/src/relational_queries.rs

When ORDER_BY_BLOCK_RANGE is set to '1' in the environment, add
`block_range` to `order by id`. That makes Postgres use the index on `(id,
block_range)` and can dramatically speed up some queries.

store: Add `block_range` to `order by id` clauses (feature flagged)

---

.github/workflows/ci.yml

Update nodejs from v11 to v14

---

Cargo.lock
NEWS.md
chain/arweave/Cargo.toml
chain/ethereum/Cargo.toml
core/Cargo.toml
graph/Cargo.toml
graphql/Cargo.toml
mock/Cargo.toml
node/Cargo.toml
runtime/derive/Cargo.toml
runtime/wasm/Cargo.toml
server/http/Cargo.toml
server/index-node/Cargo.toml
server/json-rpc/Cargo.toml
server/metrics/Cargo.toml
server/websocket/Cargo.toml
store/postgres/Cargo.toml
store/test-store/Cargo.toml
tests/Cargo.toml

Bumping crate versions and updating NEWS.md.

Release 0.22

---

graph/src/data/subgraph/mod.rs

Better error messages for `SubgraphManifestValidationError`

---

runtime/wasm/src/host_exports.rs

It's best to retry transient errors.

Retry contract call timeout

---

server/http/src/service.rs
server/index-node/src/service.rs
server/websocket/src/server.rs

Add Content Type headers

---

store/postgres/src/store_events.rs

It is possible to receive invalid store events when a node is starting up
because Postgres still has events sent by a previous version of the
code. In that case, the best we can do is ignore these events.
Once we've seen enough valid events, go back to panicing on invalid events.

store: Do not crash the node on invalid StoreEvent

---

server/http/src/service.rs
server/index-node/src/service.rs

server: parameterize content type in `serve_file` function

---

chain/ethereum/src/block_stream.rs
chain/ethereum/src/ethereum_adapter.rs
graph/src/components/ethereum/adapter.rs

Three independent commits with improvements related to start blocks. Resolves #2007.

Improvements to start block handling

---

core/src/subgraph/instance_manager.rs

Otherwise an error during reprocessing would always be considered non-fatal, even if the subgraph doesn't have the feature enabled.

Move fatal errors check

---

server/index-node/src/explorer.rs

The test is now independent of how fast the test runs; that will avoid spurious failures in CI

server: Fix flaky explorer cache test

---

store/postgres/src/deployment_store.rs
store/postgres/src/relational.rs
store/postgres/src/relational_queries.rs
store/postgres/tests/relational.rs
store/postgres/tests/relational_bytes.rs

Optimize entity modifications queries

---

runtime/wasm/src/host_exports.rs
runtime/wasm/src/module/mod.rs

The new section names created by this PR are:
```
- host_export_store_set__proof_of_indexing
- host_export_store_set__insert_id
- host_export_store_set__validation
- host_export_store_set__post_validation
- host_export_store_set__wasm_instance_context_store_set
```

New stopwatch sections

---

README.md

Would have saved me a lot of time.

note about supported ipfs version

---

chain/ethereum/src/block_stream.rs

This isn't really `info!` worthy.

Change log level to `debug`

---

chain/ethereum/src/block_stream.rs

We've seen these panic in production. Also this is why nobody misses futures 0.1.

Remove some unwraps in the block stream

---

Cargo.lock
chain/ethereum/Cargo.toml
chain/ethereum/src/config.rs
node/Cargo.toml

Replace dirs with dirs-next

---

runtime/wasm/src/module/mod.rs

Thankfully no subgraph is using this. Read with whitespace diff disabled.

Disallow `eth_call` on wasm start

---

store/postgres/src/notification_listener.rs

This way we can inspect any notification queue buildup.

Log if the notification queue is large

---

NEWS.md

Added related `NEWS.md` for: https://github.com/graphprotocol/graph-node/pull/2348

news: add Ethereum ABI functionality

---

chain/ethereum/src/block_stream.rs

How it happens is unclear, but this panic has been observed. Maybe the block stream is able to recover if this doesn't panic.

block stream: Remove panic

---

node/src/manager/commands/query.rs

Master isn't building right now.

graphman: Fix build

---

graph/src/components/metrics/mod.rs
graph/src/data/graphql/effort.rs
graph/src/data/graphql/values.rs
graph/src/data/query/result.rs
graph/src/data/schema.rs
graph/src/data/store/mod.rs
graph/src/util/futures.rs
graphql/src/execution/execution.rs
graphql/src/schema/api.rs
graphql/src/store/prefetch.rs
graphql/src/store/query.rs
graphql/src/store/resolver.rs
store/postgres/src/block_store.rs
store/postgres/src/deployment_store.rs
store/test-store/src/store.rs

[Related Clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure)

graph, graphql, store: Remove redundant closures

---

graph/src/blockchain/mod.rs
graph/src/data/schema.rs
graph/src/data/store/mod.rs
graph/src/data/subgraph/data_source.rs
graph/src/log/elastic.rs

This small PR removes some redundant clones

graph: Remove unnecessary clones

---

README.md

readme: Fix example subgraph link (ENS -> Gravatar)

---

chain/ethereum/src/ethereum_adapter.rs

The call cache table can get very large, and therefore inserts can get slow. And when you think about it this is the only code path that writes to the DB during handler execution. So this might be a relevant optimization.

Write to the call cache concurrently to handler execution

---

graph/src/components/metrics/mod.rs
graph/src/data/schema.rs

graph: Remove left-over clones

---

chain/ethereum/src/chain.rs
chain/ethereum/src/ethereum_adapter.rs
chain/ethereum/src/lib.rs
core/src/subgraph/instance.rs
core/src/subgraph/instance_manager.rs
graph/src/blockchain/block_stream.rs
node/src/main.rs

Part of multiblockchain refactor.

instance manager: Abstract over `Blockchain::TriggersAdapter`

---

core/src/subgraph/instance.rs
core/src/subgraph/instance_manager.rs
graph/src/components/subgraph/host.rs
runtime/wasm/src/host.rs

This doesn't do anything with the type parameter yet, just adds it to declarations.

runtime host: Add chain type parameter

---

chain/ethereum/src/adapter.rs
chain/ethereum/src/chain.rs
chain/ethereum/src/ethereum_adapter.rs
chain/ethereum/src/lib.rs
core/src/subgraph/instance_manager.rs
graph/src/blockchain/mod.rs
graph/src/components/ethereum/mod.rs
graph/src/components/ethereum/types.rs
graph/src/lib.rs

And other improvements towards multiblockchain.

Remove ethereum block with triggers

---

graph/src/components/ethereum/types.rs

The block is too verbose, and also this will allow for diffing with commits previous to the one in which the `block` field was introduced.

Log MappingTrigger without the block

---

chain/ethereum/src/ethereum_adapter.rs

This fixes a logic error introduced in commit fad1679b

chain: Fix error in EthereumAdapter.get_calls

---

chain/ethereum/src/chain.rs
chain/ethereum/src/data_source.rs
chain/ethereum/src/network_indexer/subgraph.rs
core/src/subgraph/instance.rs
core/src/subgraph/registrar.rs
graph/src/blockchain/mod.rs
graph/src/data/subgraph/mod.rs
graph/src/data/subgraph/schema.rs
graph/tests/manifest.rs
graphql/tests/query.rs
store/postgres/tests/graft.rs
store/postgres/tests/store.rs
store/postgres/tests/subgraph.rs
store/test-store/src/store.rs

Also, move the current UnresolvedDataSource impl to chain::ethereum
This was a fun mudwrestle with the typechcecker.

all: Parametrize blockchain on UnresolvedDataSource

---

chain/ethereum/src/chain.rs
chain/ethereum/src/data_source.rs
chain/ethereum/src/lib.rs
core/src/subgraph/instance.rs
core/src/subgraph/instance_manager.rs
core/src/subgraph/loader.rs
core/src/subgraph/registrar.rs
graph/src/blockchain/mod.rs
graph/src/components/store.rs
graph/src/components/subgraph/host.rs
graph/src/components/subgraph/instance.rs
graph/src/data/subgraph/mod.rs
graph/src/lib.rs
node/src/main.rs
runtime/wasm/src/host.rs
runtime/wasm/src/host_exports.rs
runtime/wasm/src/mapping.rs
runtime/wasm/src/module/mod.rs
runtime/wasm/src/module/test.rs
store/postgres/tests/store.rs

This PR does two things:
* Move data source templates from graph to chain::ethereum
* Parametrizes the SubgraphRegistrar on `Blockchain`

More blockchain refactorings

---

Cargo.lock

Update hyper to 0.12.36

---

store/postgres/src/relational.rs

While we roll the new way of doing things out to production, we still need
to pay attention to the old setting, otherwise there's a period of time
with query performance regression

store: Restore using GRAPH_ACCOUNT_TABLES

---

store/postgres/Cargo.toml
store/postgres/migrations/2021-05-20-130220_graph_node_version/down.sql
store/postgres/migrations/2021-05-20-130220_graph_node_version/up.sql
store/postgres/src/deployment.rs
store/postgres/src/detail.rs

Persist graph node version on subgraph deployment

---

store/postgres/src/deployment.rs

In the common case where we know at which block we are looking for non-fatal errors, do not involve subgraph_deployment since it's a very busy table, we do this lookup a lot, and there seem to be lock waits because of it

store: Avoid using subgraph_deployment when looking for non fatal errors

---

chain/ethereum/src/chain.rs

ethereum: remove panic

---

Cargo.lock
NEWS.md
chain/arweave/Cargo.toml
chain/ethereum/Cargo.toml
core/Cargo.toml
graph/Cargo.toml
graphql/Cargo.toml
graphql/src/store/prefetch.rs
mock/Cargo.toml
node/Cargo.toml
runtime/derive/Cargo.toml
runtime/test/Cargo.toml
runtime/wasm/Cargo.toml
server/http/Cargo.toml
server/index-node/Cargo.toml
server/json-rpc/Cargo.toml
server/metrics/Cargo.toml
server/websocket/Cargo.toml
store/postgres/Cargo.toml
store/test-store/Cargo.toml
tests/Cargo.toml

Prepare 0.23 release

---

graph/src/blockchain/block_stream.rs

Even I was confused about this, so very much worth documenting what's going on.

block stream: Clarify comment

---

graph/src/components/graphql.rs
graphql/src/execution/execution.rs
graphql/src/query/mod.rs
graphql/src/runner.rs
graphql/src/subscription/mod.rs
graphql/tests/introspection.rs
graphql/tests/query.rs
node/src/manager/commands/query.rs
server/http/src/service.rs
server/http/tests/server.rs
server/index-node/src/resolver.rs
server/index-node/src/service.rs
store/test-store/src/store.rs

Remove bits of code that are no longer necessary since #2017.

Remove dead nested_resolver field

---

chain/ethereum/src/chain.rs
chain/ethereum/src/data_source.rs
chain/ethereum/src/ethereum_adapter.rs
chain/ethereum/src/lib.rs
chain/ethereum/src/tests.rs
graph/src/components/ethereum/mod.rs
graph/src/components/ethereum/types.rs
graph/src/lib.rs

All it took was moving `BlockFinality` from `graph` to `ethereum`.

multichain: Remove WrappedBlockFinality

---

chain/ethereum/src/ethereum_adapter.rs

ethereum: Detect out of gas as call revert

---

node/src/config.rs

this pull request implements to changes requested in the following issue
https://github.com/graphprotocol/graph-node/issues/2597#issuecomment-869805535

expand environment variables in ethereum rpc urls in config toml

---

chain/ethereum/src/data_source.rs
core/src/subgraph/instance_manager.rs
core/src/subgraph/loader.rs
graph/src/blockchain/mod.rs

This mostly just moves some logic in `loader.rs` to a `fn from_stored_dynamic_data_source` method on the `DataSource` trait.

Remove ethdep on DataSourceTemplate

---

graph/src/data/graphql/ext.rs
graphql/src/schema/ast.rs
graphql/src/store/prefetch.rs
store/postgres/src/relational.rs

Closes #2464 
Thanks @Xunjin for the help with this PR 😊

Add `is_derived` to `DirectiveFinder`

---

chain/ethereum/src/ethereum_adapter.rs
graph/src/blockchain/block_ingestor.rs

These can be useful to debug block ingestion.

block-ingestor: Upgrade some logs to info

---

chain/ethereum/src/ethereum_adapter.rs

During pre-release testing it was caught that Erigon hadn't updated the rpc gas limit to 50 million. This would cause it to return `out of gas` at a gas usage that would succeed for other clients, which is non-deterministic because a `try_` call would fail.
This removes "out of gas" from the hardcoded deterministic error list, but it can now be added through an env var, so that environments that do not use Erigon such as the hosted service can continue to detect it.
A PR has been opened to fix this within Erigon https://github.com/ledgerwatch/erigon/pull/2572.

ethereum: Make eth call errors configurable

---

chain/ethereum/src/network.rs

ethereum: Fix cheapest_with

---

chain/ethereum/src/network_indexer/network_indexer.rs
graph/src/components/store.rs
store/postgres/src/deployment_store.rs
store/postgres/src/subgraph_store.rs
store/postgres/tests/store.rs

store, graph, chain: make `WritableStore::get` receive borrowed keys

---

store/postgres/src/deployment.rs
store/postgres/src/deployment_store.rs
store/postgres/src/detail.rs

Make unfail work for non-deterministic errors

---

README.md

Fixing README docs missing param in the Running a Local Graph Node section.

Fix README.md param issue

---

graph/src/util/timed_rw_lock.rs
store/postgres/src/chain_head_listener.rs

To rule out the possibility of a deadlock, though I don't believe this is the case. This also changes the TimedRwLock to not block forever on read/write, so that it logs even in the case of deadlock.

chain head listener: Used timed rwlock

---

docs/adding-a-new-api-version.md
docs/api-version-update-and-release.md

This is a work in progress. Feel free to add/remove info as needed.

Document apiVersion update and release process

---

README.md

Mention rustfmt requirement in the README

---

chain/ethereum/src/ethereum_adapter.rs

Hardhat is reported here https://github.com/graphprotocol/graph-node/issues/2949#issuecomment-958092933. And Moonbeam/river reports the same as Ganache, so this unifies the Ganache check with the Geth check.

ethereum: Add eth_call revert cases

---

docs/environment-variables.md
graph/src/data/subgraph/mod.rs

This PR depends on #2855 and #2835.

Bump GRAPH_MAX_API_VERSION to 0.0.6

---

chain/ethereum/src/adapter.rs

Combined with #2997, this resolves #2616.

ethereum: Batch eth_getLogs over 1000 contracts

---

graph/src/blockchain/polling_block_stream.rs

The desirable behaviour on an error is to reset the range size to the minimum of 1, in an attempt to resolve the error. However the current behaviour of estting the `previous_block_range_size` to 1 on error will end up resetting the range to 10. This PR will instead set `previous_triggers_per_block` to its starting value, effectively reducing the range to 1. This may help with https://github.com/graphprotocol/graph-node/issues/2616.

polling block stream: Reset block range size to 1

---

chain/ethereum/src/chain.rs
store/postgres/src/chain_store.rs

This wallpapers over an issue introduced by PR #2886

chain, store: Adapt to different serialization forms for a block

---

chain/ethereum/src/adapter.rs
graph/src/env.rs

Hosted service getLogs calls more than double at the value of 1000, so a default of 2000 might be a better balance.

ethereum: Env var for getLogs batch, lower default

---

chain/near/proto/codec.proto
chain/near/src/chain.rs
chain/near/src/codec.rs
chain/near/src/protobuf/sf.near.codec.v1.rs
chain/near/src/runtime/abi.rs
chain/near/src/trigger.rs

This updates `graph-node` code to use the latest protobuf format.
We will require synchronization between StreamingFast and Edge&Node for the hosted service to continue without any problem.

Updated protobuf to latest version for NEAR

---

chain/ethereum/src/network_indexer/network_indexer.rs
core/src/subgraph/instance_manager.rs
graph/src/components/store.rs
graph/src/components/subgraph/instance.rs
graph/src/data/store/mod.rs
graph/src/util/lfu_cache.rs
graph/tests/entity_cache.rs
store/postgres/src/deployment_store.rs
store/postgres/src/relational.rs
store/postgres/src/relational_queries.rs
store/postgres/src/subgraph_store.rs
store/postgres/tests/relational.rs
store/postgres/tests/relational_bytes.rs
store/postgres/tests/store.rs
store/test-store/src/store.rs

This reverts https://github.com/graphprotocol/graph-node/pull/2916
Obs: I didn't revert any of the `ethabi` changes contained in the PR linked above ☝️

Revert vid optimization

---

docker/README.md

Until we build native images.
Related: https://github.com/graphprotocol/graph-node/issues/3000

Build locally on an M1

---

chain/near/src/runtime/abi.rs
chain/near/src/trigger.rs
core/src/subgraph/instance_manager.rs
graph/src/components/subgraph/host.rs
graph/src/runtime/asc_ptr.rs
graph/src/runtime/gas/mod.rs
graph/src/runtime/mod.rs
runtime/derive/src/lib.rs
runtime/wasm/src/asc_abi/v0_0_4.rs
runtime/wasm/src/asc_abi/v0_0_5.rs
runtime/wasm/src/error.rs
runtime/wasm/src/host_exports.rs
runtime/wasm/src/module/mod.rs
runtime/wasm/src/to_from/external.rs
runtime/wasm/src/to_from/mod.rs

This is the safest until we've assessed the impact in the wild and are comfortable with the numbers.

Mark gas error as non-deterministic for now

---

store/postgres/src/subgraph_store.rs

The error was introduced in commit 1e1aca88 (PR #3094)

store: Fix logic error in SubgraphStore.remove_deployment

---

graphql/src/execution/ast.rs
graphql/src/execution/execution.rs
graphql/src/execution/query.rs
graphql/src/store/query.rs
graphql/src/store/resolver.rs
graphql/tests/query.rs

This PR turns user-reachable panics into errors. Thanks to @dotansimha for pointing out that that is possible.

Avoid some panics while queries are not fully validated

---

chain/ethereum/src/ethereum_adapter.rs
docs/environment-variables.md

This is being done because of DNS issues.
@VIVelev if you want to take a look as well since you were having the same issue 🙂

Fix MacOS DNS issues on block ingestion

---

core/src/subgraph/runner.rs

Issue #3028 
This should primarily improve the performance of indexing on:
- NEAR + firehose (we used to update on every pointer)
- sparse subgraphs (where entity updates would happen with a big gap
between block numbers)
⚠️ Still doing local testing on this ⚠️ 
**Edit**: [Benchmarks](https://github.com/graphprotocol/graph-node/issues/3028#issuecomment-1047597152) done ✅

Skip block updates when triggers are empty

---

runtime/wasm/src/asc_abi/v0_0_4.rs
runtime/wasm/src/asc_abi/v0_0_5.rs

This change will allow for more thorough unit testing

changed to_vec access modifier to public for TypedArray

---

graph/build.rs
graph/proto/transforms.proto
graph/src/firehose/sf.ethereum.transforms.v1.rs

Part of https://github.com/graphprotocol/graph-node/issues/2980

add firehose transform proto

---

chain/ethereum/Cargo.toml
chain/near/Cargo.toml
core/Cargo.toml
graphql/Cargo.toml
mock/Cargo.toml
node/Cargo.toml
runtime/derive/Cargo.toml
runtime/derive/src/lib.rs
runtime/test/Cargo.toml
runtime/wasm/Cargo.toml
server/http/Cargo.toml
server/index-node/Cargo.toml
server/json-rpc/Cargo.toml
server/metrics/Cargo.toml
server/websocket/Cargo.toml
store/postgres/Cargo.toml
store/test-store/Cargo.toml
tests/Cargo.toml

Bumps all crates to edition 2021.

Cargo.toml: Bump Rust edition

---

core/src/subgraph/runner.rs
graph/src/components/store.rs
graph/src/lib.rs
graph/tests/entity_cache.rs
store/postgres/src/deployment_store.rs
store/postgres/src/writable.rs
store/postgres/tests/subgraph.rs

Reset BlockStream on error

---

chain/ethereum/src/adapter.rs
chain/near/src/adapter.rs
core/src/subgraph/inputs.rs
core/src/subgraph/instance_manager.rs
core/src/subgraph/runner.rs
graph/src/blockchain/mock.rs
graph/src/blockchain/mod.rs
node/src/main.rs
node/src/manager/commands/run.rs

Fixes https://github.com/graphprotocol/graph-node/issues/3257

subgraph: Add template handlers to filters

---

docs/environment-variables.md
node/src/chain.rs
node/src/main.rs
node/src/manager/commands/run.rs

ethereum: increase default reorg threshold to 250

---

graph/src/blockchain/firehose_block_stream.rs

FirehoseBlockStream needs to peform a chain continuity check when starting from a subgraph's existing block ptr because we cannot be sure to respect chain continuity when switching from RPC syncing to Firehose syncing in Ethereum.
However, the previous logic to check this was a little bit flawed. Indeed, the assumption that a `None` subgraph current block would mean the subgraph was never synced never actually match. Indeed, at deployment, even before the subgraph has synced something, the subgraph current block is set to the parent of the manifest's start block number. This means we were always doing the check if the subgraph was freshly deployed.
We now changed the logic. If the subgraph ptr is set but is < than the manifest start block num, it means the subgraph never synced anything …

Avoid checking chain continuity with subgraph block ptr if subgraph never processed any block

---

Cargo.lock
server/index-node/Cargo.toml
store/postgres/Cargo.toml
store/postgres/src/lib.rs

Also update blake3 and remove some `extern crate` declarations.

store: Remove dead dep

---

graphql/src/execution/execution.rs

Fixes cache utilization when the env var is set to `*`.

Fix caching issues due to `GRAPH_CACHED_SUBGRAPH_IDS` logic

---

chain/ethereum/src/adapter.rs
chain/ethereum/src/ethereum_adapter.rs

This should make it less mysterious which eth rpc providers are being used and which ones failed during node startup

chain: Instrument provider initialization

---

core/src/subgraph/instance_manager.rs

Fixes https://github.com/graphprotocol/graph-node/pull/3425/files/f6c4a14f307e889a0daf18f2fc0d09e1ef568aa6#r844017172

add resolver retry

---

graphql/src/execution/execution.rs

The previous code didn't correctly calculate the shard on the read path and
caused panics. Encapsulating the cache size should guard against such
mistakes.

graphql: Encapsulate access to the LfuCache

---

node/src/bin/manager.rs
node/src/manager/commands/stats.rs
store/postgres/src/deployment_store.rs
store/postgres/src/subgraph_store.rs

Run `ANALYZE` after grafting

---

graphql/src/store/resolver.rs
graphql/tests/query.rs
store/postgres/src/store.rs
store/test-store/src/store.rs

Fixes https://github.com/graphprotocol/graph-node/issues/3510

fix graphql SG block check

---

chain/ethereum/src/ethereum_adapter.rs
graph/src/blockchain/types.rs
graph/src/components/store/traits.rs
graph/src/data/graphql/values.rs
graph/src/data/store/ethereum.rs
graphql/src/query/ext.rs
graphql/src/store/resolver.rs
node/src/manager/commands/check_blocks.rs
node/src/manager/commands/copy.rs
node/src/manager/commands/rewind.rs
server/index-node/src/resolver.rs
store/postgres/src/chain_store.rs
store/postgres/src/query_store.rs
store/postgres/tests/chain_head.rs
store/test-store/src/block_store.rs

This is an attempt to fix #3607 by replacing H256 by BlockHash in a bunch of places.

chain store: replace H256 by BlockHash

---

chain/ethereum/proto/codec.proto
chain/ethereum/src/adapter.rs
chain/ethereum/src/codec.rs
chain/ethereum/src/protobuf/sf.ethereum.r#type.v1.rs
graph/proto/ethereum/transforms.proto
graph/src/firehose/sf.ethereum.transform.v1.rs

Fixes https://github.com/graphprotocol/graph-node/issues/3606

Update eth firehose filters

---

chain/ethereum/tests/manifest.rs
graph/src/components/store/traits.rs
graph/src/data/subgraph/mod.rs
store/postgres/src/subgraph_store.rs
store/postgres/tests/graft.rs

Fixes https://github.com/graphprotocol/graph-node/issues/3501

Add validation for grafts created at failed block

---

tests/src/fixture.rs
tests/src/fixture/ethereum.rs
tests/tests/runner.rs

And add some ethereum helpers to `fixture::ethereum`.

tests: make fixture chain agnostic

---

graph/src/env/graphql.rs

graphql: disable validations by default

---

chain/arweave/src/chain.rs
chain/cosmos/src/chain.rs
chain/ethereum/src/chain.rs
chain/near/src/chain.rs
core/src/subgraph/runner.rs
graph/src/blockchain/block_stream.rs
graph/src/blockchain/firehose_block_stream.rs
graph/src/blockchain/mock.rs
graph/src/blockchain/mod.rs
graph/src/components/store/traits.rs
graph/tests/entity_cache.rs
store/postgres/src/deployment.rs
store/postgres/src/deployment_store.rs
store/postgres/src/writable.rs
store/postgres/tests/graft.rs
store/postgres/tests/store.rs
store/postgres/tests/writable.rs
store/test-store/src/store.rs
tests/src/fixture.rs

Firehose cursor newtype

---

docs/environment-variables.md

Added 'defaults to 500' for GRAPH_ETHEREUM_MAX_EVENT_ONLY_RANGE

Updated doc: environment-variables.md 

---

docker/start

fix: default vairables in start script

---

store/postgres/tests/graft.rs

This just might fix the flakiness we've seen in these tests.

test(store): Fix race condition in graft test

---

graph/src/firehose/endpoints.rs

To detect firehose restarts and such.

firehose: Set tcp keepalive

---

Cargo.lock
chain/substreams/Cargo.toml
chain/substreams/src/block_stream.rs
chain/substreams/src/chain.rs
chain/substreams/src/lib.rs
chain/substreams/src/trigger.rs
core/Cargo.toml
core/src/lib.rs
core/src/subgraph/context.rs
core/src/subgraph/instance.rs
core/src/subgraph/instance_manager.rs
core/src/subgraph/mod.rs
core/src/subgraph/registrar.rs
core/src/subgraph/runner.rs
core/src/subgraph/trigger_processor.rs
graph/src/components/metrics/mod.rs
graph/src/components/metrics/subgraph.rs
graph/src/components/mod.rs
graph/src/components/trigger_processor.rs
graph/src/lib.rs

Enable substreams trigger processor and manifest handling

wire substreams

---

store/postgres/src/dynds/private.rs

Dynamic data sources created on a same block should process triggers in insertion order. This was missing from #3851.

fix(store): Order data sources within a same block by vid

---

docs/getting-started.md

Fix: typos

---

store/postgres/src/connection_pool.rs

Startup of `graph-node` can be very slow because it is doing _something_ when setting up connection pools; these logs hopefully help in figuring what is slow.

store: Log more detail during connection setup

---

core/src/subgraph/trigger_processor.rs
store/postgres/src/subgraph_store.rs
tests/integration-tests/dynamic-data-source/abis/Contract.abi
tests/integration-tests/dynamic-data-source/package.json
tests/integration-tests/dynamic-data-source/schema.graphql
tests/integration-tests/dynamic-data-source/src/mapping.ts
tests/integration-tests/dynamic-data-source/subgraph.yaml
tests/integration-tests/package.json
tests/src/fixture.rs
tests/tests/runner.rs

https://github.com/graphprotocol/graph-node/issues/3963

fix false positive POI

---

core/src/polling_monitor/mod.rs

This fixes an issue where if a not found id was pushed back on the queue, that would would not wake up the queue stream. Now any push will unconditionally send a wakeup to the queue.
As a side effect dropping the `PollingMonitor` no longer cancels the polling task, but since `OffchainMonitor` also holds the receiver it is sufficient to cancel on receiver drop. The second commit improves the detection of a receiver drop so that timely cancellation is ensured.

fix(offchain): Always wake request queue on push

---

.gitignore
Cargo.lock
core/Cargo.toml
core/src/polling_monitor/ipfs_service.rs
core/src/subgraph/context.rs
core/src/subgraph/context/instance.rs
core/tests/fixtures/ipfs_folder/hello.txt
graph/src/components/store/mod.rs
graph/src/data_source/offchain.rs
graph/src/ipfs_client.rs
tests/tests/runner.rs

https://github.com/graphprotocol/graph-node/issues/3948

ipfs_service: Add support for folders

---

docs/getting-started.md

fix dead links of `Schema API` & `Query API` in `getting-started.md` file

docs: fix dead links

---

Cargo.lock
chain/substreams/Cargo.toml
chain/substreams/examples/substreams.rs
chain/substreams/proto/codec.proto
chain/substreams/src/chain.rs
chain/substreams/src/lib.rs
chain/substreams/src/mapper.rs
chain/substreams/src/protobuf/substreams.entity.v1.rs
chain/substreams/src/trigger.rs
graph/src/blockchain/block_stream.rs

Switches substreams encoding to the new protobuf structure
Cleans previous hacks
Removes all unwrap usage

New substreams encoding

---

tests/src/fixture.rs
tests/src/fixture/ethereum.rs
tests/tests/runner.rs

tests: Improve `file_data_sources` raciness

---

core/src/subgraph/runner.rs
graph/src/data_source/mod.rs
graph/src/data_source/offchain.rs
graph/src/util/error.rs
tests/integration-tests/file-data-sources/src/mapping.ts

feat(offchain): Ignore ds created with invalid cid

---

core/src/subgraph/instance_manager.rs
core/src/subgraph/runner.rs

Expose a way of building the subgraph runner without having to start it. Useful for testing
Fixes https://github.com/graphprotocol/graph-node/issues/4129

split runner build and start

---

store/postgres/src/connection_pool.rs

Better error message if missing PostgreSQL password

---

docker/hooks/post_checkout

I don't think anybody on the team uses it (correct me if I'm wrong); let's nuke it.

Remove unused post-checkout hook

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
chain/arweave/Cargo.toml
chain/arweave/src/protobuf/sf.arweave.r#type.v1.rs
chain/cosmos/Cargo.toml
chain/cosmos/src/protobuf/sf.cosmos.r#type.v1.rs
chain/ethereum/Cargo.toml
chain/ethereum/src/protobuf/sf.ethereum.r#type.v2.rs
chain/near/Cargo.toml
chain/near/src/protobuf/sf.near.codec.v1.rs
chain/substreams/Cargo.toml
chain/substreams/build.rs
chain/substreams/src/protobuf/substreams.entity.v1.rs
graph/Cargo.toml
graph/build.rs
graph/src/firehose/endpoints.rs
graph/src/firehose/sf.cosmos.transform.v1.rs
graph/src/firehose/sf.ethereum.transform.v1.rs
graph/src/firehose/sf.firehose.v2.rs
graph/src/firehose/sf.near.transform.v1.rs
graph/src/substreams/sf.substreams.v1.rs
store/test-store/Cargo.toml

* Bump prost and prost-types to 0.11.5
* Bump tonic to 0.8.3
* Bump tonic-build to 0.8.4
* Move version definition to workspace Cargo.toml

Update protobuf-related dependencies

---

core/src/subgraph/instance_manager.rs

Otherwise a single ipfs.cat failure could prevent a grafted subgraph from starting on graph node restart.

fix: Include graft ipfs lookup for raw_yaml in infinite retries

---

chain/substreams/src/trigger.rs

* This PR makes graph-node handle "strings" from substreams the same way it handles the ones coming from wasm execution: by stripping all 'null' bytes.
* Null bytes are usually not wanted in a string, but especially in PostgreSQL
Reference to current implementation of conversion of string from wasm:
https://github.com/graphprotocol/graph-node/blob/e406ae06f5a412a9f643b2c3ef816c90e3f4d1bc/runtime/wasm/src/to_from/mod.rs#L79-L82

strip all null bytes from utf8 strings from substreams

---

chain/ethereum/src/ingestor.rs

We've seen that a provider that goes back can cause ripple effects that put enormous load on the block cache. While the mechanism by which load increases is unknown, this change would make us ignore any response from a provider that goes backwards.

chain: Ignore a latest block that would make us go back

---

store/postgres/src/writable.rs
store/postgres/tests/graft.rs

When we check whether we should perform on_sync actions, tolerate the source having been deleted.

store: Tolerate a missing source for a copy

---

chain/ethereum/src/capabilities.rs

Remove unused `FromStr` implementation in `capabilities.rs`

---

graphql/src/store/prefetch.rs

Just removing some dead code; no functional changes.

Remove some unused lazy statics in `prefetch.rs`

---

graph/src/data/store/mod.rs
graph/src/data/store/sql.rs
store/postgres/src/lib.rs
store/postgres/src/relational_queries.rs

The indirection just caused some unneeded allocations

graph, store: Remove SqlValue, implement ToSql directly for Value

---

core/src/subgraph/runner.rs

May or may not help with https://github.com/graphprotocol/graph-node/issues/4544

core: Add more stopwatch sections to runner process

---

chain/substreams/examples/substreams.rs
chain/substreams/src/block_stream.rs
graph/src/blockchain/substreams_block_stream.rs

Fixes https://github.com/graphprotocol/graph-node/issues/4565

graph: Add adapter balancing to substreams

---

chain/ethereum/src/adapter.rs
chain/ethereum/src/env.rs
chain/ethereum/src/ethereum_adapter.rs
chain/ethereum/src/runtime/runtime_adapter.rs
node/src/main.rs
node/src/manager/commands/run.rs
store/postgres/src/chain_store.rs

chain,node: Add support to skip setting gas field for certain chains

---

NEWS.md
node/src/bin/manager.rs
node/src/manager/commands/rewind.rs
store/postgres/src/deployment_store.rs
store/postgres/src/relational.rs
store/postgres/src/subgraph_store.rs

Fixes https://github.com/graphprotocol/graph-node/issues/4237

node: Add start block flag to graphman rewind

---

runtime/wasm/src/mapping.rs

Fix oneshot cancelled errors

---

graph/src/data/subgraph/status.rs
server/index-node/src/schema.graphql
store/postgres/src/detail.rs

Closes [#4482](https://github.com/graphprotocol/graph-node/issues/4482)

graph, store - expose history_blocks in index-node API

---

graph/src/components/store/entity_cache.rs
tests/integration-tests/derived-loaders/abis/Contract.abi
tests/integration-tests/derived-loaders/package.json
tests/integration-tests/derived-loaders/schema.graphql
tests/integration-tests/derived-loaders/src/mapping.ts
tests/integration-tests/derived-loaders/subgraph.yaml
tests/integration-tests/derived-loaders/test/test.js
tests/integration-tests/derived-loaders/truffle.js
tests/integration-tests/package.json
tests/tests/integration_tests.rs

Fix derived loader not working on certain fields

---

docs/implementation/offchain.md

This should aid implementors of new offchain data source kinds.

docs: Add offchain data sources implementation guide

---

node/src/chain.rs

This is the same we do for the RPC connection test, which is to allow retries but set a timeout of 30 seconds.

fix(firehose): Add retry around firehose connection test

---

node/src/main.rs

Enable substreams support for already supported networks
Partially resolves https://github.com/graphprotocol/graph-node/issues/4302

Enable support for substreams on already supported networks

---

.github/workflows/code-coverage.yml

`protobuf-compiler` needs to be installed.

Fix nightly code coverage run

---

graph/src/components/store/entity_cache.rs
graph/src/components/store/mod.rs
graph/src/schema/input_schema.rs
store/postgres/src/relational_queries.rs
tests/integration-tests/derived-loaders/schema.graphql
tests/integration-tests/derived-loaders/src/mapping.ts
tests/integration-tests/derived-loaders/test/test.js

Fix loadRelated not working with `Bytes` as ids

---

graph/src/components/subgraph/proof_of_indexing/online.rs

graph: add block number and hash to POI logs

---

store/postgres/src/primary.rs
store/test-store/tests/postgres/subgraph.rs

Closes https://github.com/graphprotocol/graph-node/issues/4793

Remove the entry from `subgraph_features` table when a subgraph is removed

---

chain/substreams/src/trigger.rs
graph/src/components/store/entity_cache.rs
graph/src/components/store/err.rs
graph/src/data/store/mod.rs
graph/src/schema/ast.rs
graph/src/schema/input_schema.rs
graph/src/util/intern.rs
runtime/test/src/test.rs
runtime/wasm/src/host_exports.rs
store/postgres/src/fork.rs

Validate field exists in schema before setting entity

---

docker/Dockerfile
docker/start

Enable ssl mode for postgres to be configurable with other options in connection string

set sslmode paramater in dockerfile

---

graph/src/components/store/err.rs
graph/src/data/query/error.rs
store/postgres/src/relational_queries.rs

Closes https://github.com/graphprotocol/graph-node/issues/4775

graph: Adds attestable ChildFilterNestingNotSupportedError

---

store/postgres/src/catalog.rs
store/postgres/src/connection_pool.rs

Fixes https://github.com/graphprotocol/graph-node/issues/4719

store: Map other shards into a new shard on startup

---

CONTRIBUTING.md

I've changes the spelling  of History from Hostory which led to confused anyone who read the documentation in the Contribution.md file.
thnx to allow me to contribute ......looking forward to contribute in "The Graph" Protocol

Changes the spelling of History from Hostory

---

server/http/src/service.rs

 Allow querying subgraphs with more than one '/' in their name

---

server/http/assets/index.html

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#crossorigin

fix(graphql): add crossorigin prop

---

Cargo.lock
chain/substreams/src/lib.rs
server/index-node/Cargo.toml
server/index-node/src/resolver.rs

lazy load features from ipfs when a subgraph is not deployed

---

store/postgres/src/deployment_store.rs

Fix graphman not accepting table names

---

tests/src/fixture/ethereum.rs
tests/src/fixture/mod.rs
tests/tests/runner_tests.rs

Hopefully, this will make it a little easier to understand runner test failures

runner tests: Tag all log lines with the test name

---

core/src/subgraph/instance_manager.rs
graph/src/components/metrics/stopwatch.rs
runtime/test/src/test.rs
store/postgres/src/writable.rs
store/test-store/src/store.rs
store/test-store/tests/postgres/relational.rs
store/test-store/tests/postgres/relational_bytes.rs
store/test-store/tests/postgres/store.rs

Addressing https://github.com/graphprotocol/graph-node/issues/4943

Add more labels to `deployment_sync_secs`

---

NEWS.md
docs/environment-variables.md

This is a rebased and squashed version of PR #4884

docs: Fix typos

---

docs/environment-variables.md
graph/src/env/mod.rs
node/src/main.rs

Configurable timeout for GRAPH_KILL_IF_UNRESPONSIVE

---

graph/src/util/futures.rs

These actually hanged locally a couple of times.

refactor: Modernize a few util::futures tests

---

chain/ethereum/src/runtime/runtime_adapter.rs
graph/src/blockchain/mod.rs
graph/src/components/subgraph/host.rs
runtime/wasm/src/module/mod.rs

Label the specific method in eth_call metrics

---

core/src/subgraph/runner.rs
core/src/subgraph/state.rs

Optimise `cached_head_ptr` calls within process block

---

tests/README.md
tests/integration-tests/api-version-v0-0-4/package.json
tests/integration-tests/block-handlers/package.json
tests/integration-tests/ganache-reverts/package.json
tests/integration-tests/host-exports/package.json
tests/integration-tests/int8/package.json
tests/integration-tests/non-fatal-errors/package.json
tests/integration-tests/overloaded-functions/package.json
tests/integration-tests/poi-for-failed-subgraph/package.json
tests/integration-tests/remove-then-update/package.json
tests/integration-tests/value-roundtrip/package.json
tests/integration-tests/yarn.lock
tests/src/config.rs

also, updated all existing tests to use latest version of the CLI.

test: allow integration tests to run with different version of the `graph` cli

---

runtime/wasm/src/module/mod.rs

Make `function not found` a deterministic

---

store/postgres/src/chain_store.rs

This changes the `RecentBlocksCache` to be just a map from block number to block that keeps the `capacity` last entries.
The current data structure, a `BTreeMap` is probably not ideal for this seeing how few entries this cache usually has, and a `Vec<(BlockNumber, Box<JsonBlock>)>` would probably perform better since the whole cache would fit into a few cache lines.

Make the RecentBlocksCache very dumb

---

README.md

fix initdb with correct parameters (`locale=C`)

Update initialising database command for README.MD

---

store/postgres/src/deployment_store.rs

When manually rewinding, sometimes we need to do strange things such as rewinding past a graft block. This is very likely to result in an incorrect PoI, but we have a situation right now where we just need to do this to work around a bug in grafting.
The sanity check is kept for normal reverts.

fix(graphman): Allow rewinding past the graft block

---

store/postgres/migrations/2024-01-05-170000_ds_corruption_fix_up/down.sql
store/postgres/migrations/2024-01-05-170000_ds_corruption_fix_up/up.sql

This is a script by @avandras which we've tested with manual runs. Because the bug it fixes is present in version 0.33, it's important that we get this in for version 0.34.

migration: Fix up any inconsistent data_sources tables

---

chain/ethereum/src/runtime/runtime_adapter.rs
graph/src/components/subgraph/host.rs
graph/src/env/mod.rs

Disable eth_call_execution_time metric by default

---

docs/config.md

Some additions prompted by #5193

Update provider docs

---

graph/src/components/store/mod.rs
store/postgres/src/catalog.rs

fix(pruning): Fix version stats for huge number of versions

---

chain/substreams/src/block_ingestor.rs
graph/src/blockchain/firehose_block_ingestor.rs

Fixes #4976
Re-implemented this stale PR to include new integration tests: https://github.com/graphprotocol/graph-node/pull/4977

Reset substreams/firehose block ingestor backoff

---

runtime/derive/src/lib.rs

Rust 1.77 started complaining about that

runtime: Remove dead code

---

graph/src/data/query/cache_status.rs
graph/src/data/query/result.rs
graph/src/data/query/trace.rs
graphql/src/execution/execution.rs
graphql/src/execution/query.rs
graphql/src/query/mod.rs
graphql/src/runner.rs
graphql/src/store/prefetch.rs
node/src/manager/commands/query.rs
server/http/src/service.rs
server/index-node/src/service.rs
store/test-store/src/store.rs
store/test-store/tests/graphql/introspection.rs
store/test-store/tests/graphql/query.rs

Query tracing did not handle multiple block constraints properly.

Improve query traces

---

Cargo.lock
Cargo.toml
NEWS.md

- Updated NEWS.MD with release notes for v0.35.0
- Updated workspace crate version to v0.35.0

v0.35.0 release

---

chain/ethereum/src/data_source.rs

chain/ethereum: add exceptional case for transaction less event in zksync-era

---

Cargo.lock
server/websocket/Cargo.toml
server/websocket/src/connection.rs
server/websocket/src/server.rs

server/websocket: Update tokio-tungstenite

---

store/postgres/src/relational_queries.rs

The 'select by specific attributes' code had overlooked one place where we do a `select *`

store: Select specific attributes for query_window_one_entity

---

chain/near/src/chain.rs
chain/substreams/examples/substreams.rs
chain/substreams/src/block_ingestor.rs
chain/substreams/src/block_stream.rs
graph/src/blockchain/substreams_block_stream.rs

Fixes https://github.com/graphprotocol/graph-node/issues/5225

check substreams module name

---

core/src/subgraph/runner.rs
tests/src/fixture/mod.rs

This reverts commit 2649a4e927cb1c18a18cd1392b5685cce03afd83.

Revert "fix: Check if head exists before trying to unfail"

---

graph/src/env/mod.rs
graph/src/firehose/endpoints.rs

Increase max decoding size after near testnet failure

Increase firehose grpc max decode size

---

node/src/bin/manager.rs
node/src/manager/commands/rewind.rs

graphman: Fix rewind for deployment with multiple names

---

chain/substreams/src/data_source.rs
graph/src/data/subgraph/mod.rs

chain/substreams: implement is_duplicate_of

---

chain/ethereum/src/data_source.rs
store/test-store/tests/chain/ethereum/manifest.rs

Enable "hard-coded" values in declarative eth_calls

---

docker/cloudbuild.yaml

Reverts graphprotocol/graph-node#5541

Revert "upgrade cloudbuild machine"

---

chain/ethereum/src/env.rs

This PR adds  arbitrum-sepolia chain ID to GRAPH_ETH_CALL_NO_GAS default value

Add arbitrum-sepolia chain ID to GRAPH_ETH_CALL_NO_GAS default value

---

tests/tests/integration_tests.rs

This will be helpful for lcoal development

tests: allow running a single test case for integration tests

---

chain/substreams/src/data_source.rs

Fixes https://github.com/graphprotocol/graph-node/issues/5615

Respect substreams datasource startBlock

---

node/src/bin/manager.rs

fix description not displaying for deploy on `graphman --help`

---

runtime/wasm/src/host_exports.rs

add log message on critical logs

---

node/src/manager/commands/deployment/pause.rs
server/graphman/src/resolvers/deployment_mutation/pause.rs

improve error handling when restarting paused subgraphs
