graph/src/util/ethereum.rs
Resolves #229 
The event signature specified in the event handler of the subgraph manifest is compared against Ethereum events by comparing the hash.  The comparison process was sensitive to whitespace which has made it more difficult to debug event signature mismatch errors.  Rather than require developers to remove all whitespace we are stripping whitespace when the event signature hash is built from the user provided string.
=> Improve event signature matching: event handlers.event no longer sensitive to whitespace

LICENSE-APACHE, README.md
Boilerplate copyright specification was still hidden in the bottom of the Apache license. It has been updated to include the year and copyright owner.
=> Update Apache license to include Graph Protocol copyright specifics

core/src/subgraph/manager.rs, graph/src/components/store.rs, graph/src/components/subgraph/host.rs, graph/src/lib.rs, runtime/wasm/src/module.rs
Resolves #259 
The Ethereum `block_hash` is needed to track the source of events and revert entity changes in the event of a block reorganization.  This PR updates the `RuntimeHostEvents` to now include `EventSource::EthereumBlock(block_hash)`  along with `StoreKey` and `Entity` data.
=> Include block_hash in RuntimeHostEvents

core/src/subgraph/manager.rs, graph/src/lib.rs, runtime/wasm/src/module.rs
The recent changes to the `RuntimeHostEvent` definition and implementations were not formatted using the latest version of rustfmt.  This PR uses `Rust 1.28.0` to format the code, which now passes all tests in `Travis CI`.
=> Update code formatting to Rust 1.28.0 standards

runtime/wasm/src/module.rs
This adds and exports the `stringToH160` type conversion function needed for graphprotocol/graph-cli#86 (and the corresponding PR: graphprotocol/graph-cli#87).
=> Export typeConversion.stringToH160(String): H160 function

core/tests/tests.rs, datasource/ethereum/src/ethereum_adapter.rs, graph/src/components/ethereum/adapter.rs
And refactor the errors to use `failure`.
=> Improve contract call type mismatch error

Cargo.lock, core/Cargo.toml, core/src/subgraph/provider.rs, core/tests/tests.rs, graph/src/components/subgraph/provider.rs, graph/src/data/schema.rs, graph/src/data/subgraph.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, mock/src/server.rs, mock/src/subgraph.rs, runtime/wasm/src/module.rs, server/http/Cargo.toml, server/http/assets/index.html, server/http/src/lib.rs, server/http/src/request.rs, server/http/src/server.rs, server/http/src/service.rs, server/http/tests/server.rs, server/json-rpc/src/lib.rs
This is a first implementation of support for hosting multiple subgraphs, according to [this plan](https://github.com/graphprotocol/graph-node/issues/227#issuecomment-413149755).
Only the `add` operation is supported. Subgraph must have a name when added, and the GraphQL server keeps a map from name to schema. Each subgraph is mounted relative to it's name, so graphiql for subgraph "foo" is mounted at `/foo/`. Because we don't have an index page yet and to not disrupt the current workflow, if only one subgraph is hosted then the root will redirect to it.
At the store level we're already selecting by subgraph id as @fordN informs me so no changes seem necessary there.
Notably remaining work is to support more operations #282 and to have an index page for subgraphs #303.
resolves #226
=> Initial multiple subgraph support

Cargo.lock, graph/Cargo.toml, graph/src/lib.rs, graph/src/util/log.rs, node/src/main.rs
Resolves #268 
Return clear error messaging to the user if the IPFS connection fails on startup.  
An attempt to add a file to the IPFS node is used to test the connection before moving on to the rest of the node setup. To facilitate the improved error messaging a few general changes were also made: 
- implement custom panic hook 
- use guarded async slog in panic logging to ensure logs are returned to the user
=> Improve IPFS startup errors and implement custom panic hook with guarded logger

runtime/wasm/src/host.rs, runtime/wasm/src/module.rs
Resolve graphprotocol/graph-cli#96
Add detail to logging of Ethereum event subscriptions, event receipt, event handling, and contract calls. 
- Prepare subscription  --> now logging event name and handler name
- Subscribe to event --> now logging subscription id
- Ethereum event received --> now logging event signature
- Contract call --> now logging block hash and function name
- Call event handler --> now logging event signature
=> Detailed logging of ethereum event handling

core/src/subgraph/manager.rs, core/src/subgraph/provider.rs, graph/src/components/subgraph/provider.rs, runtime/wasm/src/host.rs, server/http/src/server.rs
If the admin endpoint `subgraph_add` is called twice with the same subgraph name, it will shutdown the previous subgraph and host the new one.
Open question: Do we want to separate the `update` endpoint or keep it unified with `add`? If they are unified, should it be renamed to `set` or some other name? Opinions welcome, I'd like to settle this before merging. Ping @html5cat you might have an opinion on API design.
The implementation consists of:
- Properly shutting down the host thread when the host is dropped.
- Keeping track of added sugraphs in `SubgraphProvider` and sending a message to the `RuntimeManager` signaling the removal of the old subgraph when a subgraph is overwritten.
The "update" part of #282
=> Support updating subgraphs

node/src/main.rs
Resolves #269 
In the case of an invalid Ethereum endpoint being supplied the application previously did not fail quickly, instead providing RPC errors on each event subscription call.  The continued operation and indirect errors made for inobvious debugging of a simple programmer error. 
Now a test call is made immediately after creating the Ethereum Adapter that gets the current block_number or upon an error stops the application and returns a helpful error.  
Unfortunately Web3 also logs a `WebSocketError` which I could not keep from firing.
=> Test Ethereum endpoint with get current block_number call

Cargo.lock, graph/src/components/server/admin.rs, server/http/tests/server.rs, server/json-rpc/Cargo.toml, server/json-rpc/src/lib.rs
If the `GRAPH_MASTER_TOKEN` is not set, no auth will be checked. If it is set, then first to authorize the deployment of a subgraph the `subgraph_authorize` endpoint must be called with a `name` parameter which will return a fresh token that must be sent along any deploy or remove requests for a subgraph with that name. All auth tokens must be provided with the header `Authorization: Bearer TOKEN`.
Right now removal by id doesn't make sense since we need the name to authorize, but it's still supported by the rest of the codebase since we don't yet have a final design for auth.
Resolves #304 at least for now.
=> Simple auth

Cargo.lock, server/json-rpc/Cargo.toml, server/json-rpc/src/lib.rs
Auth should be done with a POST to the json-rpc port with a body such as:
```
{
"jsonrpc":"2.0",
"method":"subgraph_authorize",
"params":{
"subgraph_api_keys":{
"brubels":"secret",
"such_auth": "much_safe"
}
},
"id":"1"
}
```
=> json-rpc: Take auth list directly

node/src/main.rs
It's lighter and we can use it with read-only nodes.
The previous test was causing issues for users, hopefully this fixes it.
=> node: Use `version` instead of `add` to test ipfs connectivity

store/postgres/migrations/2018-07-10-062730_create_revert_procedures/up.sql, store/postgres/src/functions.rs, store/postgres/src/store.rs
Let's get this in master and then we can bring it up to feature/block-stream
=> store/postgres: Include subgraph id as input to block revert functions

.travis.yml
ipfs-api is regressed on 1.30 beta, ignore that until it's un-regressed.
=> Allow failures on Rust beta

runtime/wasm/src/asc_abi/class.rs, runtime/wasm/src/lib.rs, runtime/wasm/src/module.rs, runtime/wasm/src/to_from/external.rs
We already have that information in the `self.block_hash` field. Breaks compatibility with older versions of graph-cli.
=> runtime: Remove `block_hash` param from contract calls

docs/graphql-api.md
Resolves #402 
Other docs changes for `@entity` directive had already been made.
=> docs: Add note about missing @entity directive error

datasource/ethereum/src/block_stream.rs, datasource/ethereum/src/ethereum_adapter.rs, datasource/ethereum/src/transport.rs
Overlay block loading with block processing to keep as many Ethereum RPC calls in flight as possible. Also, increase Web3 parallel request limit from 64 to 2048.
Resolves #425
=> Faster block loading

graph/src/ext/futures.rs, server/websocket/src/connection.rs, server/websocket/src/server.rs
`cancelabe` takes the guard as an argument, so cancelling multiple things with one guard is supported. It's also nice that we no longer return tuples allowing `cancelable` to be chained with other methods.
Resolves #392.
=> Improve cancellation helpers

.travis.yml
This sets things up so that we make a github release whenever a tag is pushed and attach a linux binary to it, built in release mode. We'll also want osx but I'd rather leave that to a follow up PR since we don't currently test on osx.
[This test](https://github.com/graphprotocol/graph-node/releases/tag/TEST_TAG) shows that it works.
Part of #403
=> travis: Upload binaries to github releases

core/src/subgraph/instance_manager.rs, datasource/ethereum/src/block_stream.rs, graph/src/ext/futures.rs, graph/src/lib.rs
Shut down block stream gracefully when subgraph is removed.
Resolves #427
=> Use cancelable to shut down BlockStream

graph/src/util/log.rs, node/src/main.rs
Default logging level is INFO.
Passing a `--debug` flag sets logging level to DEBUG.
Set a `GRAPH_LOG` environment variable to override the above to any
logging level.
`GRAPH_LOG` supports per-module configuration just like `RUST_LOG`.
=> Add GRAPH_LOG env var, --debug flag (on master)

graph/src/util/log.rs, node/src/main.rs
Default logging level is INFO.
Passing a `--debug` flag sets logging level to DEBUG.
Set a `GRAPH_LOG` environment variable to override the above to any
logging level.
`GRAPH_LOG` supports per-module configuration just like `RUST_LOG`.
=> Add GRAPH_LOG env var, --debug flag (on ethsf)

docs/getting-started.md
I found this entertaining / ironic because you later go on to say "The name `ERC721` under `source > abi` must match the name of the displayed underneath `abis >name`"
=> Fix typo in documentation

datasource/ethereum/src/block_ingestor.rs, store/postgres/migrations/2018-08-22-140000_create_chain_head_update_procedure/up.sql
Should solve issue with Parity dev nodes returning "no block returned from Ethereum".
=> datasource, store: Fix block ingestion on short chains

datasource/ethereum/src/block_ingestor.rs, datasource/ethereum/src/ethereum_adapter.rs, graph/src/util/futures.rs
It looks like the tokio retry crate doesn't do as much as I thought it did, so this adds a 60-second `deadline` to the `with_retry` util, which should help with Eth RPC calls getting stuck sometimes.
=> datasource, graph: Add retry deadline

runtime/wasm/src/module/mod.rs
Resolves #386
`Store.set()` uses input to add an `id` attribute to the `entity` or if already exists ensures they  are equal.
=> Store.set() merges id into the entity before pushing the `EntityOperation`

graph/src/util/log.rs
Previously it would only report formatted strings.
=> Fix panic reporting to also report constant strings

datasource/ethereum/src/block_ingestor.rs, graph/src/lib.rs, graph/src/util/futures.rs
Previous PR handled case where transactions were excluded from the main chain in a reorg, then readded in a different block. This PR handles the case where those transactions never make it back into the main chain. Annoyingly, it's hard to distinguish this case from the case where a receipt is missing because it is not yet available. To work around that, this retries getting the receipt for a reasonable amount of time before giving up and retrying the whole block.
Aside: there seems to be a fundamental limitation of Ethereum RPC -- you can only get tx receipts for blocks that the Ethereum node currently considers to be part of the main chain.
Resolves #491
=> Handle transaction removed from main chain

.travis.yml
The issue in Rust has since been fixed.
=> travis: Deny failures on beta

datasource/ethereum/src/block_stream.rs
This is not an error but expected behaviour when a subgraph is removed.
=> BlockStream: Change log from `error` to `info`

runtime/wasm/src/host_exports.rs, runtime/wasm/src/lib.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs
To make `module/mod.rs` thinner and to make it easier to add new exports, a new module `host_exports.rs` is created, with a function for each export dealing only with Rust types, so the corresponding function in `module/mod.rs` only needs to pull the arguments from the asc heap and then allocate the return value on the asc heap.
=> Refactor implementation of host exports into separate module

graph/src/data/store/scalar.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/test.rs
=> runtime: `big_int_to_hex` prints in big endian and trims zeros

store/postgres/src/store.rs
This PR uses `set_config()` to set a run-time configuration parameter, `current_event_source`, without it the` log_delete` trigger procedure cannot track the event source.
Revert operations were failing because block hashes were being stored in the db with differing formats, now all store operations convert the block hash to string using `hash_hex()`.
=> Store updates: log event source of removal operations and make string formatting of block hashes consistent

core/src/subgraph/provider_with_names.rs, core/tests/tests.rs, node/src/main.rs
This may or may not be the fix to the hanging on startup we've seen lately, but at least I wasn't able to reproduce it in a few attempts after this change.
=> node, core: Remove use of `wait` in main

core/src/subgraph/subgraphs.graphql, graph/src/components/store.rs, graph/src/data/query/error.rs, graph/src/data/subgraph/schema.rs, graphql/src/store/resolver.rs, graphql/tests/query.rs, mock/src/store.rs, store/postgres/src/store.rs
Resolves #583 (the url should be tracked in a different issue).
This adds the `entityCount` field. Instead of storing it with the data and incrementing on every entity insert, which would be error-prone, this introduces the concept of a "calculated field", which is a field of an entity that is not in the store but rather calculated on the fly. We can probably also use this for `__typename`.
=> graph, store, graphql: Add `entityCount` field to subgraph entities

graphql/src/execution/execution.rs, graphql/src/schema/api.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/test.rs
This makes it so we no longer add `__typename` to the schema (which does not conform to the spec) neither store it in the store (which is inefficient) but instead insert it at query time.
Fixes #431 for good. Alternative to #624.
=> Insert `__typename` at query time

core/src/subgraph/registrar.rs, core/tests/tests.rs, graph/src/components/subgraph/registrar.rs, graph/src/data/subgraph/mod.rs, graph/src/lib.rs, node/src/main.rs, server/json-rpc/src/lib.rs
This is so users of `subgraph_create` can then use the new ID (e.g. store them somewhere).
=> Return subgraph ID from `subgraph_create`

runtime/wasm/src/asc_abi/asc_ptr.rs, runtime/wasm/src/asc_abi/class.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/to_from/external.rs
We can use these now that they've been stabilized in Rust v1.32.0
=> Replace unsafe transmutes with safe equivalents

core/src/subgraph/registrar.rs
Previously if a subgraph failed to resolve, that would prevent the node from starting.
=> Allow failiure of subgraph at start

core/src/subgraph/registrar.rs, graph/src/components/store.rs
I believe this does what it should do. The policy for replacing current or pending with a new version now is: if there is no current version, or the current version is not synced, replace it with the new version. Otherwise, replace the pending version. I think the code could be simplified a little if it expressed these rules more clearly.
In particular, I'd subsume the logic around `current_version_id_opt.is_some()` and `current_is_synced` into a variable `replace_current` and structure the code according to that. But it might be better to do that as a separate change as it will be a bit more invasive than this PR.
=> Replace current version with new version if current is not fully synced yet

core/src/subgraph/instance_manager.rs, datasource/ethereum/src/block_stream.rs, graph/src/util/log.rs, runtime/wasm/src/host.rs
Resolves #743 
Make `INFO` logs less verbose by only showing logs relevant to the subgraph such as: 
- `block with relevant events found`, 
- `event handlers being called to process the events`,
- `entity operations being applied.` 
Logs concerning a block which do not necessarily contain a relevant event have been changed to `DEBUG`.
=> Make info logs less verbose: only show logs related to relevant blocks

Cargo.lock, graph/Cargo.toml, runtime/wasm/Cargo.toml
Decentraland does not work unless ethabi supports event overloading and being able to parse event fields that aren't bytes32, such as this: https://etherscan.io/tx/0xc760d94f4512aac26123ad4345b824cdf271d0b3c9529778a42d3329b88b35bc#eventlog
The branch we are pointing to, created by @leodasvacas are a combination of https://github.com/paritytech/ethabi/pull/145 and https://github.com/paritytech/ethabi/pull/140
Hopefully those get merged one day into parities upstream branch, but for now this is needed to make Decentraland work.
=> Point graph node to graphprotocol/ethabi/graph-patches to fix errors

store/postgres/migrations/2019-02-25-182843_add_pg_stat_statements/down.sql, store/postgres/migrations/2019-02-25-182843_add_pg_stat_statements/up.sql
One small wrinkle with this is that creating the extension requires that the pg user is a superuser; people would have hit this problem with the migration that adds the `pg_trgm` extension, but it's worth pointing out.
=> store/postgres: enable the pg_stat_statements extension

store/postgres/migrations/2019-02-26-182914_remove_unassigned_deployment_indexes_procedure/down.sql, store/postgres/migrations/2019-02-26-182914_remove_unassigned_deployment_indexes_procedure/up.sql, store/postgres/migrations/2019-02-26-183156_cleanup_unassigned_deployment_indexes/down.sql, store/postgres/migrations/2019-02-26-183156_cleanup_unassigned_deployment_indexes/up.sql
Many of the subgraphs stored in the database are not the current version of the deployment, so their subgraph entity indexes are an unnecessary load on the `entities` table.  The shear number of indexes has lead to shared memory issues during select statements that create a lock for each index on the `entities` table.  
This PR creates and uses a subgraph indexes cleanup function that:
- finds all subgraph deployments in the database without an assignment, 
- gets a list of their subgraph attribute indexes on the entities table, 
- and drops each of the indexes.
=> Cleanup indexes: remove subgraph entity indexes for unassigned subgraphs

store/postgres/migrations/2019-02-04-114900_remove_entity_change_triggers/up.sql
When dropping functions without inputs the `()` is optional for Postgres version 10 onwards. 
In order to maintain compatibility with older versions of Postgres the drop function statements in the `remove_entity_change_triggers` have been updated.
=> PSQL version compatibility: use entire function signature in drop function statements

store/postgres/migrations/2019-02-26-182914_remove_unassigned_deployment_indexes_procedure/up.sql
This PR fixes an issue with the index cleanup function incorrectly building drop index statements.  
In order to build the drop index statements correctly using the `record` type variable consumed in the for loop, the statements are built using string concatenation and executed otherwise the drop index function expects a table reference.
=> Build subgraph indexes cleanup function: build drop index statements using string concatenation

core/src/subgraph/instance_manager.rs
Fixes https://github.com/graphprotocol/graph-node/issues/759
=> core/subgraph: mark subgraphs as not failed when starting them

store/postgres/migrations/2019-02-28-190800_update_chain_head_update_procedure/down.sql, store/postgres/migrations/2019-02-28-190800_update_chain_head_update_procedure/up.sql
The queries in that stored proc caused several full table scans on ethereum_blocks, which becomes very costly when the database contains a lot of blocks.
The new queries use an index on `ethereum_blocks(network_name, number)` to make sure we only ever access the last `ancestor_count` rows in `ethereum_blocks`, yielding a very significant speedup.
Fixes https://github.com/graphprotocol/graph-node/issues/785
=> store/postgres: optimize stored proc attempt_chain_head_update

core/tests/tests.rs, graph/src/components/ethereum/listener.rs, graph/src/components/link_resolver.rs, graph/src/data/store/scalar.rs, graph/src/data/subgraph/mod.rs, graphql/src/schema/ast.rs, runtime/wasm/src/host_exports.rs
The warnings are all caused by the renaming of
String.trim_{left,right}_matches to String.trim{start,end}_matches.
=> Fix deprecation warnings for Rust 1.33

.travis.yml
We run into timeouts when the builder tries to update the build cache from
the current build.
=> travis: increase timeout for cahce pushes

.travis.yml, .travis/before_cache.sh
The target/debug/ directory is roughly 3.3G big; by removing the build
artifacts for graph-node itself, and especially the test binaries, we can
reduce the size of the cache to 1.6G, and therefore speed up how long
downloading and updating the build cache takes.
=> travis: reduce the amount of build data we cache

store/postgres/migrations/2019-03-04-235349_empty-ethereum-network-chain-head-update-fix/down.sql, store/postgres/migrations/2019-03-04-235349_empty-ethereum-network-chain-head-update-fix/up.sql
Infinite loop happens only when starting from a fresh graph node, fix the function to default the
number column to 0 when NULL
=> attempt_chain_head_update SQL function gets stuck in infinite loop

docs/environment-variables.md, graph/src/components/store.rs, graph/src/lib.rs, graphql/src/execution/resolver.rs, graphql/src/store/resolver.rs, mock/src/store.rs, store/postgres/src/store.rs, store/postgres/src/store_events.rs, store/postgres/tests/store.rs
This PR throttles subscription updates so that updates are generated at most every 500ms; at the same time, no `StoreEvent` is held for longer than 500ms.
There are two things that need improvement still:
* `throttle_while_syncing` now queries the `synced` status of a deployment every time a `StoreEvent` comes through. One way to avoid that would be to get the current chain head pointer when throttling is started, and compare it to the source for any event coming through. We would only requery the head pointer once we see event sources newer than the head pointer. We would then switch to querying the deployment status once we see the head pointer advancing very little when we requery (say by 100 blocks) and then switch to querying the deployment status.
* the throttle time for …
=> Throttle subscription updates

store/postgres/migrations/2019-03-07-171355_update_history_storage/down.sql, store/postgres/migrations/2019-03-07-171355_update_history_storage/up.sql, store/postgres/src/functions.rs, store/postgres/src/store.rs, store/postgres/src/store_events.rs, store/postgres/tests/store.rs
The main focus of this change is to stop recording entity_history for the
'subgraphs' subgraph, and to avoid recording history for changes that
actually do not change the entity. The history we recorded for these made
up about 75% of the storage needed in the hosted offering, and we never
need the data thus recorded.
This change also simplifies how the revert_block stored procedure works by
basing it off a single history query, and removes unused input parameters
for it.
The change also gets rid of a few stored procedures that were previously
used, but are not any longer.
More background on these changes can be found at
https://github.com/graphprotocol/graph-node/issues/807
=> Improve how we record and handle entity_history

store/postgres/migrations/2019-03-07-171355_update_history_storage/up.sql
Postgres 9.6 requires '()' after the name of a function when dropping it.
=> store/postgres: fix syntax error with Postgres 9.6

runtime/wasm/src/host_exports.rs
The hosted function exports `bytes_to_string()` and `json_from_bytes()` have been updated to return helpful error messages.  Since these parsing functions are called from  a subgraph mapping, context on the `graph-ts` function used can be essential for efficient debugging. 
Related to the `graph-ts` issue to [make toHex() more discoverable](https://github.com/graphprotocol/graph-ts/issues/41).
=> Improve data parsing errors in runtime hosted parsing functions

graphql/src/schema/api.rs, graphql/tests/query.rs
Making it required was a breaking change and should've prepared better.
=> Make `first` optional again (defaulting to 100)

graph/src/components/store.rs, graph/src/data/subgraph/schema.rs, mock/src/store.rs, store/postgres/src/filter.rs, store/postgres/src/jsonb.rs, store/postgres/src/lib.rs, store/postgres/src/store.rs
This reduces the db traffic caused by certain subgraph metadata updates from 3 (or more) to 1.
=> Reduce the number of db operations for updating a subgraph's block pointer

graph/src/data/subgraph/schema.rs, store/postgres/migrations/2019-03-28-004319_drop_entities_id_indexes/down.sql, store/postgres/migrations/2019-03-28-004319_drop_entities_id_indexes/up.sql, store/postgres/src/filter.rs
This PR makes sure we do not query `entities.id` via the `data` column, and instead always use `entities.id`. That allows us to get rid of ~ 260 attribute indexes in production, which the migration in this PR does.
=> Use entities.id rather than entities.data->'id'->>'data' in queries

store/postgres/migrations/2019-03-31-010824_short_chain_head_update/down.sql, store/postgres/migrations/2019-03-31-010824_short_chain_head_update/up.sql
For short chains, we would pull the genesis block into the query that
checks if we have parents for at least ancestor_count many blocks before
the new head. But the genesis block has no parent, and so this would fail
and we would report that the genesis block has a missing parent and never
make progress
=> store/postgres: fix bug in attempt_chain_head_update for short chains

graph/src/data/schema.rs, graphql/src/execution/execution.rs, graphql/src/introspection/schema.rs, graphql/src/query/mod.rs, graphql/src/subscription/mod.rs
With this PR, the decision which fields in a selection set require introspection and which ones require 'normal' data lookup is made based just on the root fields. That simplifies `ExecutionContext` as we can now just pass different contexts into query execution rather than have the context decide when to use an introspection schema and when to use the subgraph schema.
=> Change GraphQL query execution to decide whether introspection is needed upfront

Cargo.lock, core/src/subgraph/registrar.rs, graph/src/components/store.rs, graph/src/data/query/error.rs, graph/src/data/subgraph/schema.rs, mock/src/store.rs, store/postgres/Cargo.toml, store/postgres/migrations/2019-04-19-171709_split_entities/down.sql, store/postgres/migrations/2019-04-19-171709_split_entities/up.sql, store/postgres/migrations/2019-04-22-190022_remove_unneeded_stored_procs/down.sql, store/postgres/migrations/2019-04-22-190022_remove_unneeded_stored_procs/up.sql, store/postgres/src/db_schema.rs, store/postgres/src/entities.rs, store/postgres/src/filter.rs, store/postgres/src/functions.rs, store/postgres/src/lib.rs, store/postgres/src/sql_value.rs, store/postgres/src/store.rs, store/postgres/src/store_events.rs, store/postgres/tests/store.rs
This PR makes it so that newly deployed subgraphs will be stored in their own `entities` (and `entity_histroy`) table. Deploying a new subgraph will create a schema in Postgres, and store the data for the subgraph in that schema.
The PR does not migrate existing data; instead, queries (and changes) against existing data are still done against the existing `public.entities` table. Migrating data will be the subject of another PR.
(Opening this as draft as I haven't tested this other than running unit tests; will remove draft status once I've done that. The code is ready for review, though)
=> Split entities table into one table per subgraph

core/src/subgraph/instance_manager.rs, datasource/ethereum/src/block_stream.rs
A significant portion of the log volume has been taken up by messaging that is not strictly necessary for monitoring progress of the specific subgraph or tracking down errors.  
Many log lines were simply noting inaction such as: "0 events found in this block for this subgraph" or "Creating 0 dynamic data sources".
Removing these logs serves to cut down on the noise, making the logs easier to parse. Also, the overall volume reduction makes it more efficient to send the logs to a storage engine such as Elasticsearch.
=> Reduce logging volume by removing unnecessary logs

datasource/ethereum/src/block_stream.rs, datasource/ethereum/src/ethereum_adapter.rs, docs/environment-variables.md
Resolves #776. If we start getting this error even when requesting logs for a single block, we should re-evaluate in a new issue.
The first thing this does is have `ETHEREUM_FAST_SCAN_END` affect the block stream as a whole, we now multiply `ETHEREUM_BLOCK_RANGE_SIZE` by 10 if doing a fast scan. The one-size-fits-all nature of these values can be an issue, I also added a special case to go one block at a time if there are unconditional block triggers. We should at some point change the way we control the amount of triggers processed at a time.
The adaptive logic for log ranges first tries requesting the entire given range, if that doesn't work the step is reduced on each failure until we no longer get the 1000 logs error.
And then there are some refactors along the way.
=> Adaptive log range

datasource/ethereum/src/ethereum_adapter.rs, docs/environment-variables.md
Part #912, specifically item 1.
When the log range is shortened due to hitting the Infura limit, we start making parallel requests in order to retain performance. The env var `ETHEREUM_PARALLEL_BLOCK_RANGES` limits the amount of parallelism possible, defaulted to 100 (is that a reasonable default?).
Regarding the rest of #912, I think this should be enough to regain the performance of log scanning. At the default values of a block range of 10000 and 100 parallel requests, even when the step drops to 10 we're still simultaneously requesting a total range of 1000, which is what we hard coded before, no performance is lost. So I'd say that trying to proactively re-widen the log range is low-prority, we can leave it as an idea if we still have performance issues after this.
This could be …
=> Parallel get logs

graph/src/components/store.rs, graph/src/data/subgraph/mod.rs, graph/src/data/subgraph/schema.rs, graphql/src/store/resolver.rs, mock/src/store.rs, store/postgres/migrations/2019-05-03-164052_store_entity_count/down.sql, store/postgres/migrations/2019-05-03-164052_store_entity_count/up.sql, store/postgres/src/entities.rs, store/postgres/src/store.rs, store/postgres/src/subgraphs.graphql, store/postgres/tests/store.rs
This PR stores the `entityCount` as an attribute of the `SubgraphDeployment`, and keeps it updated as entities are added and removed from the subgraph.
=> Denormalize `entityCount`

store/postgres/migrations/2019-05-03-164052_store_entity_count/up.sql
In staging, we had an entry in `deployment_schemas` where the underlying
Postgres schema did not exist, causing the migration to fail. To make this
more robust, we will skip these entries. The issue was most likely caused
by manual changes in staging.
=> store/postgres: make store_entity_count migration more robust

graph/src/log/elastic.rs
The kvs are in the `Record` not the `OwnedKVList`
=> Fix source of log argument kvs for Elasticsearch

datasource/ethereum/src/block_ingestor.rs, datasource/ethereum/src/ethereum_adapter.rs, node/src/main.rs
This data is needed to filter out logs in the Grafana panels
=> Add network name to block ingestor logs

store/postgres/migrations/2019-05-14-200255_event_meta_data_source_index/down.sql, store/postgres/migrations/2019-05-14-200255_event_meta_data_source_index/up.sql
We find event_meta_data during block reversions by the source attribute,
and not having an index on it slows down those queries, and therefore block
reversion, dramatically. In one case, query time for a block reversion goes
from 18s to 5ms after adding the index.
=> store/postgres: Add an index on event_meta_data(source)

core/src/subgraph/instance_manager.rs, datasource/ethereum/src/block_stream.rs
The blockstream should faithfully attempt to produce blocks for a subgraph.
An error in the blockstream is non fatal and temporary, so the `SubgraphInstanceManager` should not fail the subgraph when these errors occur.
=> Handle block stream errors gracefully in SubgraphInstanceManager

Cargo.lock, core/src/subgraph/instance_manager.rs, core/tests/interfaces.rs, datasource/ethereum/src/block_stream.rs, graph/src/components/store.rs, graphql/tests/query.rs, mock/src/store.rs, store/postgres/Cargo.toml, store/postgres/migrations/2019-05-15-215022_migrate_entities/down.sql, store/postgres/migrations/2019-05-15-215022_migrate_entities/up.sql, store/postgres/src/entities.rs, store/postgres/src/lib.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs
This PR puts a framework in place to perform store migrations for subgraphs one at a time, and uses that to migrate existing subgraphs out of the `public.entities` table into dedicated tables for each subgraph.
I tested this by running it against a dump of the production database, and assigning the subgraphs for one of the mainnet indexing nodes to my graph-node instance. When a subgraph is picked for migration, indexing for that subgraph pauses and its data is successfully transferred into the new tables.
It is still possible for indexing of non-migrating subgraphs to stall; in my testing, these stalls didn't last very long, and block ingestion never fell farther than about 15 blocks behind.
Eventually, all assigned and non-failed subgraphs will be migrated. Subgraphs that are not …
=> Framework for per-subgraph db migrations and migrate existing subgraphs into their own entities tables

graphql/src/execution/execution.rs, graphql/src/execution/resolver.rs
Doing coercion in `complete_value` is more [in line with the spec](https://graphql.github.io/graphql-spec/draft/#CompleteValue()). Right now we only have one real resolver so it doesn't make much difference, but with #957 and #857 we might get more resolvers so this is an important refactoring.
=> Move coercion to completion

core/src/subgraph/registrar.rs, graph/src/components/subgraph/registrar.rs, server/json-rpc/src/lib.rs
Resolves #939 
This PR creates a JSON-RPC method for reassigning a subgraph to a different node.  The node that receives the JSON request will update the assignment entity and propagate the assignment removals and additions to all subscribing `graph-nodes`.  If the provided target `node_id` does not match any of the nodes in the system the subgraph will effectively be paused.
Example request: 
```
curl -H "content-type: application/json" --data '{"jsonrpc": "2.0", "method": "subgraph_reassign", "params": { "name": "username/SubgraphName", "ipfs_hash":"QmXxiWNWHtzap2hX8A5L6yJzKx23ypt6i4UVRqZmVR2jnO", "node_id":"default"}, "id": "1"}'
``` 
In the past, subgraph deployment reassignments could only be made by manually updating the now deprecated `subgraph_deployments` table which was …
=> Create subgraph deployment reassignment RPC endpoint

core/src/subgraph/registrar.rs
This PR updates the `subgraph_reassign` JSON RPC method to handle a subgraph deployment (IPFS hash) that has multiple versions.  We now use only versions marked as current to verify the request is valid before performing the reassignment.
=> core: Subgraph reassignment handles deployments with multiple versions

store/postgres/migrations/2019-06-05-214320_uncled_chain_head_update/down.sql, store/postgres/migrations/2019-06-05-214320_uncled_chain_head_update/up.sql
It is possible for us to pull an uncled block into the database that does
not have a valid parent on the chain. If such a block was within
ancestor_count of a new candidate head, we would refuse to advance the head
because of the missing parent, even though that parent is not needed.
This was ultimately caused by relying on block numbers to determine which
blocks must have a parent in the database. We now perform this check by
following the (hash, parent_hash) chain of blocks back from the candidate
head, rather than considering all blocks whose numbers are less than
ancestor_count from the candidate head.
Fixes https://github.com/graphprotocol/graph-node/issues/983
=> store/postgres: Do not demand that uncled blocks have a parent in the db

core/src/subgraph/registrar.rs, core/tests/interfaces.rs, graph/src/components/store.rs, graphql/tests/query.rs, mock/src/store.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs
Creating a subgraph can block all other subgraph writers if the creation
itself has to wait for its lock, e.g., because of an ongoing autovacuum of
event_meta_data. That wait can be long (an hour or more in the case of
autovacuum)
We now do subgraph creation in such a way that we wait for a lock only a
short time (2s) and then sleep for a bit so that other write activity can
proceed.
=> store/postgres: Make subgraph creation not block writers

graph/src/data/subgraph/mod.rs
Allow subgraph names where a part starts with a number, but still forbid
ones where a part does not contain a single letter (e.g., just a number)
Fixes https://github.com/graphprotocol/graph-node/issues/988
=> graph/data: Relax restrictions on subgraph names

store/postgres/src/store.rs
These statements cause a huge number of log entries to be written.
=> store/postgres: Remove trace logging of store events

store/postgres/src/entities.rs
We used to create indexes on string attributes as GIN indexes; with the way
we translate filters into SQL, these indexes do not get used. Since they
are only on individual attributes, there's no downside to using a standard
BTree index, which makes them usable for our filters.
=> store/postgres: Index string attributes as btrees

store/postgres/migrations/2019-06-26-164405_index_dynamic_ethereum_contract_data_source_deployment/down.sql, store/postgres/migrations/2019-06-26-164405_index_dynamic_ethereum_contract_data_source_deployment/up.sql
Our internal query to look up dynamic data sources repeatedly looks up a
DynamicEthereumContractDataSource by its deployment. Without this index,
this results in a full table scan of subgraphs.entities, which by now is
pretty sizeable (roughly 1M rows)
This index allows Postgres to use a more direct and much more efficient
query plan for these queries.
Fixes https://github.com/graphprotocol/graph-node/issues/999
=> store/postgres: Index DynamicEthereumContractDataSource.deployment

core/src/subgraph/registrar.rs, graph/src/components/subgraph/registrar.rs, graph/src/data/subgraph/mod.rs, server/json-rpc/src/lib.rs
The `AbortUnless` conditional operation being generated by the `subgraph_reassign` RPC method was only allowing deployments that are the current version to be reassigned. 
This PR updates the conditional simply to simply check if any existing deployment version matches the subgraph name and deployment id provided.
=> Update subgraph reassignment conditional to allow all deployment version types

store/postgres/src/notification_listener.rs
We used to silently ignore errors when reading notifications from the
database. We now log them to make it easier to tell if anything is going
wrong there, e.g., to at least get a message if the connection gets dropped
for whatever reason.
=> store/postgres: Log errors when reading db notifications

store/postgres/src/entities.rs
Resolves #1036 
Entity queries are each appended with an order by id filter, so query results are always consistent. This is useful for when no order by is specified or the field being ordered by has duplicates. 
----
| GraphQL Sorting Filter | SQL Order By |
|:-:|:-|
| (OrderBy: AttributeName)  | ORDER BY 'data'->AttributeName->>'data' ASC, id ASC  |
| ()  | ORDER BY id ASC  |
=> Order all entity queries by id to get deterministic ordering of results

server/http/src/response.rs
Resolves #1032 
GraphQL query responses from subgraph endpoints use the  application/json content type.
=> Include a "Content-type" header in http query response

core/src/subgraph/instance.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/registrar.rs, core/src/subgraph/validation.rs, core/tests/subgraphs/dummy/dummy.yaml, core/tests/subgraphs/two-datasources/two-datasources.yaml, core/tests/tests.rs, datasource/ethereum/src/block_stream.rs, graph/src/components/ethereum/stream.rs, graph/src/components/subgraph/host.rs, graph/src/data/subgraph/mod.rs, mock/src/block_stream.rs, node/src/main.rs, runtime/wasm/src/host.rs
Resolves #1018
Updating the graph-node to handle multiple, different Ethereum networks on a single instance allows for more flexibility in devops because one does not have to run separate nodes to support subgraphs on different Ethereum chains. 
Summary:
The `ethereum-rpc`, `ethereum-ipc`, `ethereum-ws` CLI arguments now accept multiple values each. These supplied Ethereum networks are used to create sets of stores, runtime host builders and block stream builders (containing one item per Ethereum network). The subgraph instance manager and the subgraph registrar now take these sets (implemented as HashMap) as input and when deploying a subgraph version will decide which store, runtime, and block stream to use based on the Ethereum network name defined in the subgraph's manifest.
=> Support connecting to multiple Ethereum networks on a single graph-node

core/src/subgraph/instance_manager.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs
The first commit fixes data sources created in `ipfs_map` being ignored, which was a straightforward fix.
The second fixes a more subtle and more general issue, that we'd only restart the block stream to pick up new data sources when receiving the _next_ block in the original data source. This could cause missed events or even the stream to never be restarted because there was only one event in the original data source.
Fixes #1067. Fixes #1035.
=> Allow creating data sources in `ipfs_map` and fix dynamic data sources missing events

store/postgres/src/notification_listener.rs
When the payload for a large notification was cleaned up too early and went
missing, the notification listener would panic because we
postgres::row::Rows::get panics when we try to access the nonexistent row
in the result.
We now check that the result is not empty before accessing values to avoid
that panic.
This partly addresses https://github.com/graphprotocol/graph-node/issues/1043
=> store/postgres: Make sure missing notification does not panic listener

store/postgres/migrations/2019-07-20-195916_remove_subgraph/down.sql, store/postgres/migrations/2019-07-20-195916_remove_subgraph/up.sql, store/postgres/src/entities.rs, store/postgres/src/subgraphs.graphql
This pull request does two things:
1. Remove the `public.entities` and `public.entity_history` table, together with all the metadata for the subgraphs that were stored there; we do keep the entries in `event_meta_data` for these entities since removing that causes a lot of headaches in hosted
2. Remove any Rust code related to storing entities in `public.entities`
I've tested this with a recent dump of the production database, and everything seems to be ok.
=> Remove public entities table

docker/README.md, docker/docker-compose.yml
Setting the default Ethereum network name to "mainnet" allows many subgraphs to be deployed to the node without modifications to their manifests; the network name must match the Ethereum network defined in the subgraph manifest.
Note: existing users relying on the docker-compose setup may already be using the `dev` network name for local testing, so this change could lead to issues deploying their subgraphs.
=> docker-compose: Update default Ethereum network name to "mainnet"

core/src/subgraph/loader.rs, graph/src/data/subgraph/schema.rs
Resolves #1084 
On node startup all existing deployments assigned to that node are picked up from the db to be redeployed; however, the block and call handlers that had been created with dynamic data sources were not being fetched.  
This PR adds the block and call handlers to the dynamic data sources query and adds handling of  Ethereum block handler filter values from the query results.
=> core,graph: Get dynamic block and call handlers on node restart

store/postgres/migrations/2019-08-02-001120_short_chain_head_update/down.sql, store/postgres/migrations/2019-08-02-001120_short_chain_head_update/up.sql, store/postgres/src/lib.rs, store/postgres/tests/chain_head.rs, store/test-store/src/lib.rs
In Ganache setups, we pull in the genesis block as the only block in the
beginning. That block does not have a valid parent, and we must not include
it in our parent checking.
This chainge also adds tests for various issues we've had with
attempt_chain_head_update to avoid repeating the same bugs.
Fixes https://github.com/graphprotocol/graph-node/issues/1088
=> store: Do not get stuck on genesis block's missing parent

datasource/ethereum/src/ethereum_adapter.rs, graph/src/components/ethereum/adapter.rs, graph/src/components/ethereum/types.rs, runtime/wasm/src/module/test.rs
This could previously collect a vector sized in GBs, by filtering and extracting the block pointer
before collecting, we can optimize the memory usage by at least 10x.
@olibearo could you please double check this code is still correct and I didn't take out anything important?
=> Optimize `blocks_with_calls` memory usage

docs/environment-variables.md, node/src/main.rs
It is useful to tune the Tokio thread pool count down to avoid opening too many file descriptors.
=> Add TOKIO_THREAD_COUNT env var

datasource/ethereum/src/ethereum_adapter.rs, docs/environment-variables.md
Those are expensive and could time out. Not much performance is lost in that case since in the default scenario we'll just do 50 requests of size 500 to cover 10000 blocks.
Tested locally on subgraphs with and without contract address.
=> Limit eth.getLogs range size with no contract address

Cargo.lock
Include updates to ethabi for Tuple array support which will work in concert with [graph-cli PR#320](https://github.com/graphprotocol/graph-cli/pull/320) and [graph-ts PR#73](https://github.com/graphprotocol/graph-ts/pull/73).
=> *: Update ethabi dependency (Tuple array support has been added)

graph/src/data/subgraph/mod.rs
To avoid breaking subgraphs that have a mistaken spec version.
=> Accept spec version 0.0.3

store/postgres/src/entities.rs, store/postgres/src/filter.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs
That avoids the problem described in issue #1133 
The changes should not lead to any observable change in behavior, except that when ordering by a string field, entries with very long values (> 2k characters) are only ordered by their prefix, not their full value.
=> Index only a prefix of string attributes

Cargo.lock, runtime/wasm/Cargo.toml, runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/lib.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, runtime/wasm/src/module/test/abi.rs
Resolves #1134 by requesting larger chunks from the AS allocator and managing them ourselves, and also leveraging the assumption of the arena allocator. 
In a release build, `asc_new` could take 1-2ms. Now it's under 1ms.
Also optimize `check_timeout` by not checking the env var each time.
=> Optimize WASM memory allocation

runtime/wasm/src/module/mod.rs
#1145 made the assumption that two consecutive `memory.allocate` calls would allocate contiguous memory. This is of course false if AS allocated any memory for itself between the calls. This would cause memory corruption on handlers that did a lot of things and needed to call `memory.allocate` more than once in `raw_new`. This was the case with the Betoken subgraph, I reproduced the error locally and verified that this PR fixes it.
=> Fix WASM memory allocation

docker/docker-compose.yml
This is needed so that we can enable pg_stat_statements the extension when
we create our schema
=> docker: Preload pg_stat_statements in Postgres

store/postgres/src/entities.rs, store/postgres/tests/store.rs
The foreign key constraint from a subgraph's entity_history table into
event_meta_data requires a lock on subgraph creation that prevents subgraph
deployment during an autovacuum of event_meta_data.
We remove the foreign key constraint so that subgraph deploys can proceed
even when event_meta_data is being autovacuumed.
=> store: Remove foreign key into event_meta_data

docker/README.md
Came across a small inconsistency in the docs where the 8545 was being used rather than the default Postgres port. Sharing a pull request with the relevant change
=> Update readme to reflect default Postgres port

store/postgres/src/entities.rs, store/postgres/src/relational.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs
With relational schemas, we need a bit of computation to go from the
GraphQL schema to the relational Layout. If possible, we cache the Layout
for the lifetime of the Store
Fixes https://github.com/graphprotocol/graph-node/issues/1177
=> store: Cache Storage objects in the Store

datasource/ethereum/src/ethereum_adapter.rs
The assertion assumes that events from `log_stream` are ordered by block number. We've observed that this isn't the case in production.
=> Remove assertion that events are ordered

core/src/subgraph/provider.rs, graph/src/components/store.rs, mock/src/store.rs, store/postgres/src/entities.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs
The `entities::Connection` struct looked like an instance would be used with any number of subgraphs, when we really only ever use it for one subgraph plus the metadata subgraph. These changes make that separation clearer and also remove some of the ugly back-and-forth between the store and the connection.
=> Improve separation of responsibilities between Store and entities::Connection

graphql/src/schema/api.rs, graphql/tests/query.rs
By adding the filters after the `where` types are added. Resolves https://github.com/graphprotocol/support/issues/25.
=> Allow nested filter

graph/src/data/store/mod.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs, store/postgres/tests/store.rs
Fixes https://github.com/graphprotocol/graph-node/issues/1137
The existing code already creates an index on `left(column, 2048)`, but queries didn't take advantage of that yet. This PR closes that gap.
=> store: Make partial index on text columns usable in comparisons

server/json-rpc/src/lib.rs
This will give us the full context of when an RPC command fails, especially for failed deploys, and hopefully make it easier to reproduce #1248 (or at the very least, help us rule out failed deploys as the root cause)
=> server: Log request params when a request results in an error

store/postgres/src/entities.rs, store/postgres/src/lib.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs, store/postgres/tests/store.rs
The previous size of 2k was the largest we could store in a Postgres BTree
index, but it's excessive for supporting normal string operations; anything
beyond a few hundred bytes is text, and very unlikely to be accessed
through 'hard' string comparisons; it's much more likely that such text
will be accessed through word searches and similar for which the BTree
index is of no use anyway.
We lower the prefix size to 256 to reduce the size of the index for
attributes that do store large text entries.
=> store: Reduce the size of string prefixes we index

Cargo.lock, core/src/subgraph/loader.rs, core/tests/interfaces.rs, graph/src/components/store.rs, graph/src/data/store/mod.rs, graphql/src/lib.rs, graphql/src/schema/ast.rs, mock/src/store.rs, runtime/wasm/Cargo.toml, runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, server/http/src/service.rs, server/index-node/src/resolver.rs, server/websocket/src/server.rs, store/postgres/src/entities.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs
These changes make it so that we now validate entities against the subgraph schema when mappings call `store.set`.
This is a user-visible change, and can lead to subgraphs that were previously working to now fail because of the additional validation - those subgraphs would have produced errors when invaid data was queried, but syncing would have seemingly worked.
Fixes https://github.com/graphprotocol/graph-node/issues/615
=> Validate entities on `store.set`

core/src/subgraph/registrar.rs, core/tests/interfaces.rs, graph/src/components/store.rs, graphql/tests/query.rs, mock/src/store.rs, runtime/wasm/src/module/test.rs, store/postgres/src/entities.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs
The first is something I ran into when I inadvertently updated ipfs on my machine.
The second, removing the lock timeout on graph deployment, is something I should have done as part of d4995c00 but didn't in case we needed to reintroduce the foreign key. Now that we have run without that for a while we can also remove the machinery around not failing subgraph deployments because of the foreign key.
=> Two smallish changes

store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs
When the EntityQuery explicitly ordered by id, we would generate a SQL
query that selected `id` twice which makes `order by id` ambiguous.
=> store: Produce correct query when ordering by id

core/src/subgraph/instance.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/registrar.rs, core/tests/tests.rs, datasource/ethereum/src/block_stream.rs, datasource/ethereum/src/ethereum_adapter.rs, datasource/ethereum/tests/adapter.rs, docs/environment-variables.md, graph/src/components/ethereum/adapter.rs, graph/src/components/ethereum/stream.rs, graph/src/components/ethereum/types.rs, graph/src/components/subgraph/host.rs, graph/src/data/graphql/values.rs, graph/src/data/subgraph/mod.rs, graph/src/data/subgraph/schema.rs, mock/src/block_stream.rs, mock/src/ethereum_adapter.rs, mock/src/lib.rs, node/src/main.rs, runtime/wasm/src/host.rs, runtime/wasm/src/module/test.rs, store/postgres/src/store.rs, store/postgres/src/subgraphs.graphql, store/postgres/tests/store.rs, store/test-store/src/lib.rs
Resolves #1131
Start blocks can now be defined per data source in the manifest and are used to resolve a subgraph wide earliest Ethereum block value.
The subgraph registrar logs warnings if the start blocks do not represent the block where the data source's contract (if specified) was created. 
The permissive nature of the start block validation allows flexibility for a subgraph owner to filter the chain as they see fit.
=> Define start_block in the subgraph manifest

docs/subgraph-manifest.md
Documentation for the recently added start block feature which is specified in the manifest.
=> Document source startBlock usage in subgraph manifest

store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs
Empty and/or clauses would generate a `()` which leads to SQL syntax
errors. This behavior is a backstop; what should really happen is that
and/or clauses always have at least one predicate in them.
With the previous behavior, we would generate queries like `select ... from
... where ()` which is not valid SQL.
=> store: Handle empty and/or filters in the relational schema

datasource/ethereum/src/ethereum_adapter.rs, docs/environment-variables.md
I noticed with erc20 that some eth_getLogs requests could take over a minute and still complete successfully.
=> Use an env var for json-rpc timeouts, increase default

runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs
Adds support for basic data source introspection. See https://github.com/graphprotocol/graph-ts/pull/90.
Resolves https://github.com/graphprotocol/support/issues/3. Resolves https://github.com/graphprotocol/support/issues/37.
=> Add `dataSource.address` and `.network` host exports

graph/src/components/store.rs, graph/src/data/subgraph/schema.rs, mock/src/store.rs, store/postgres/src/entities.rs, store/postgres/src/store.rs
Following up to #1308 with some more simplification.
The guard was only used in `update_ethereum_block_pointer_operations`, which in turn is only used in reverts or transact block.
For transact block, the guard was made totally redundant as we now fetch the block in the same transaction. For reverts, I was more conservative and just added an assert to replace the guard.
=> Refactor away `guard` from `MetadataOperation::Update`

store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
Solves the issue stemming from the fact that `to_snake_case()` is not idempotent for special cases containing numeric characters (see issue for details: https://github.com/whatisinternet/Inflector/issues/74). 
Now we do not apply the function to field names that are already in snake case format.
=> Ensure `to_snake_case()` is applied only once to entity fields in query results

store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs
We had a few places were query generation could fail because of an unknown
table or column. That then makes it impossible to print the failed query
for debugging purposes.
This commit changes things so that these errors are detected before we
construct QueryFragments.
=> store: Make sure query generation doesn't fail

store/postgres/src/notification_listener.rs
Events we listen for are important for the overall correctness of the system; for example, if we miss the assignment event for a subgraph, we will not index it, leaving the user to scratch their head why a newly deployed subgraph is not making progress.
Because of this, the safest and most robust thing is to immediately exit the process (with an error) if a notification listener ever loses its db connection. A process supervisor should be used to restart the process as is appropriate for the environment we are running in.
Fixes https://github.com/graphprotocol/graph-node/issues/1279
=> store: Exit with an error if the notification listener loses its connection

node/src/main.rs
This was causing the node to hang at startup if the `network_identifiers` calls had to retry, for example due to rate limits. Most of the diff is from having to indent the rest of main.
=> Remove use of `.wait()`

docs/subgraph-manifest.md
Resolves #1321  
This PR introduces an explanation of the call and block handlers, so that all Ethereum mapping handler types are now documents.  It also notes that although the different handlers are optional, at least one type of handler must be used in each Etheruem mapping.
=> Document call and block handlers

core/src/metrics/registry.rs, graph/src/components/metrics.rs, mock/src/metrics_registry.rs, store/postgres/src/store.rs
It wouldn't work in a multi-network node because the "generic store" would register the metric first and then the store which really owned the subgraph could not register. This removes the counters from the store and lets the metrics registry centralize keeping track of them.
=> Fix db contention metric, introduce global counters

graph/src/components/ethereum/adapter.rs
Addresses https://github.com/graphprotocol/support/issues/42
=> Fix extending EthereumCallFilter

core/src/subgraph/instance_manager.rs, runtime/wasm/src/host_exports.rs
If the entity that comes from the mapping is already valid, avoid going to the DB at all. Also add a metrics section for `as_modifications`, since some DB accesses shift from `store_set` to `as_modifications`. Part of #1381.
PR for grafana https://github.com/graphprotocol/instrumentation/pull/3.
=> Optimize store.set entity validation

chain/ethereum/src/block_stream.rs, docs/environment-variables.md
Use the amount of triggers found in the previous range to adjust the next range, trying to meet a configured target triggers per range. For dense subgraphs this allows the complexity of ethereum calls and memory usage to be kept under control, without compromising speed for cheap subgraphs or initial speed for subgraphs that are denser towards the end of the chain.
Testing with erc20, this was effective in keeping the trigger count around the default target of 1000. The memory usage sat at ~100mb, which seems ok for an actively syncing subgraph, and suggests that each trigger takes ~100kb in average. The range size was at about 3000 blocks, which is expected to decrease at higher block numbers.
Resolves #1350. The implementation is different from what I suggested in the issue in that the …
=> Dynamic block range based on triggers per range

Cargo.lock, core/tests/interfaces.rs, graph/src/components/store.rs, mock/src/store.rs, runtime/wasm/Cargo.toml, runtime/wasm/src/module/test.rs, runtime/wasm/src/module/test/abi.rs, store/postgres/src/entities.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/src/store.rs, store/test-store/Cargo.toml, store/test-store/src/lib.rs
Part of #1381. Local benchmark with erc20:
Most of the `store_set` work got moved into `as_modifications`. Now `store_set` doesn't show up in the top categories anymore, and `as_modifications` is barely there, so we can claim this combined with #1384 really did improve things, I'd say we got at least a 2x speedup at fetching entites for merging. My local sync got to block 4844255 vs 4729000 previously, which signals than things got overall faster.
I still need to check that it really works with JSON storage, but this is ready for review. I also switched the runtime tests to use the test-store so we could get test coverage for this.
=> Batch load entites when applying the entity cache

core/tests/interfaces.rs, graphql/src/store/prefetch.rs
The assertion in `prefetch.rs` that this PR removes was too aggressive, as there is no reason for it to be true in the situation created by the test `interface_inline_fragment_with_subquery` in `core/tests/interfaces.rs`
This change simply replaces that assertion by skipping the attempt to add children to a parent whose type is not mentioned in any join condition. The queries did the right thing already.
The reverse assertion on line 338 in `prefetch.rs` is still valid: if a child type is not mentioned in a join condition, that join condition should not even be there, which would indicate some logic error somewhere else in the code.
=> Fix error in GraphQL execution caused by overly aggressive assertion in prefetch

graph/src/data/query/query.rs, graphql/src/query/mod.rs
For some queries, there is huge variation in the time a query takes depending on the values of the variables passed in. Log GraphQL variables together with the query to make it easier to understand why a certain query is slow.
=> graph, graphql: Log variables passed into GraphQL query with query

chain/ethereum/src/block_stream.rs
This solution is not yet ideal because it's possible that the block is neither in the cache nor in the chain, for example if the node is shutdown for a long time before the revert is processed, but it's still expected that it will be in the cache.
=> Make sure to check the block cache in reverts

chain/ethereum/tests/network_indexer.rs
Mainly reduce the chain size in one of the tests from 1000 blocks to 50, but also tweak all test times a little, hoping that CI is still fast enough to meet those timeouts.
=> Ethereum: Speed up network indexer tests

Cargo.lock, store/postgres/Cargo.toml, store/postgres/examples/layout.rs, store/postgres/migrations/2020-01-14-235608_relational_metadata_views/down.sql, store/postgres/migrations/2020-01-14-235608_relational_metadata_views/up.sql, store/postgres/src/relational.rs, store/postgres/src/subgraphs.graphql
This PR does not change any of the `graph-node` logic, it merely puts views in place that have the same structure as the tables that we will use for the relational storage of subgraph metadata. Having these views while we still use JSONB storage makes it possible to update various bits of tooling that currently query `subgraphs.entities` without having them break once we do the actual update.
It would be good to get this merged and rolled out as quickly as possible so we can start updating the things that will be affected by the change in storage for subgraph metadata.
=> Create views that simulate relational storage of subgraph metadata

store/postgres/src/relational.rs
With the previous limit, StackDriver was still trimming lines itself
=> store: Reduce maximum size of logged SQL query to 20kB

store/postgres/migrations/2020-01-17-013633_remove_unused_procs/down.sql, store/postgres/migrations/2020-01-17-013633_remove_unused_procs/up.sql
This also gets rid of all stored procedures that still refer to `subgraphs.entities`
=> store: Remove unused stored procedures

chain/ethereum/src/block_stream.rs, chain/ethereum/src/ethereum_adapter.rs, core/src/subgraph/registrar.rs, graph/src/components/ethereum/adapter.rs, graph/src/components/store.rs, mock/src/store.rs, store/postgres/src/store.rs, store/postgres/tests/chain_head.rs
One thing I am unsure about with this is whether it will interfere with reverts, since during a revert, we'll have multiple blocks with the same number in the database. If doing the revert requires that the orphaned block remains in the database, this code could cause problems.
=> Use cached block for number -> hash mapping if that is unambiguous

store/postgres/src/notification_listener.rs
We are seeing a lot of commits taking 300ms or so in production; when that happens lots of commits pile up and it looks like they are all waiting for a lock on Postgres' internal notification queue. Forcing more notifications to be bounced through the `large_notifications` table should reduce the amount of work Postgres has to do for each notification internally during commit, and the hope is that this will reduce the contention on the notification queue.
=> store: Lower the threshold for a notification to be large to 128 bytes

store/postgres/src/notification_listener.rs
The lower threshold made things a lot worse in production (commits no hang
for almost a second sometimes when before it was more like 300ms)
This reverts commit 6ae99b55939c8b14f3ca6f8a3556f9de6856fb2d.
=> store: Go back to higher LARGE_NOTIFICATION_THRESHOLD

graphql/src/schema/api.rs
The initial implementation of fulltext search queries only supports the inclusion of one entity type, so the result type for a fulltext query is the type of the entity included.
=> Use monomorphic result type for fulltext searches

Cargo.lock
This reverts commit 14638abcc83e7f78bda2b0cc51b69759e32b5786.
=> Revert "build(deps): bump hyper from 0.13.1 to 0.13.2"

graph/src/components/store.rs, mock/src/store.rs, store/postgres/src/store.rs, store/postgres/tests/chain_head.rs
GraphQL queries that uses time-travel queries with a block hash would sometimes fail with an error of 'no block for this hash found' when that block clearly existed in the database. When we look up a block with a given hash, we look for a block with that hash and the store's network; that is wrong, as for queries the store's network and the subgraph's network might be different. Instead, we now determine the subgraph's network and use that when we check for the hash.
=> Use the correct network when resolving a block hash into a block number

store/postgres/src/jsonb_queries.rs, store/postgres/src/relational_queries.rs
If we pass an empty array, Postgres can not determine the type of the array by itself, and fails because it can't select the right variant of unnest. Explicitly state that the argument to unnest is a 'text[]' and the
argument to reduce_dim is 'text[][]'
For review, the important thing is to make sure that all calls of the form `unnest(_)` have been changed to `unnest(_::text[])` and calls to `reduce_dim(_)` have been changed to `reduce_dim(_::text[][])` I _think_ I caught them all, and got the various brakcets and parens in the right places, but would appreciate a good check of those aspects.
=> store: Add explicit types to arguments of unnest() and reduce_dim()

store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs
Noticed in the production logs that there are queries failing right now because of this bug.
=> store: Fix error when using EntityFilter::In with an empty array

store/postgres/src/relational.rs, store/postgres/src/store.rs
This change (besides a minor cleanup for relational schema code) makes it so that we print a deprecation warning for every JSONB subgraph that gets started.
The next release should include a note like
> JSONB storage is deprecated and will be removed in the next release. This only affects subgraphs that were deployed with a graph-node version before 0.16. Starting with this version, graph-node will print a warning for any subgraph that uses JSONB storage when that subgraph starts syncing. Please check your logs for this warning. You can remove the warning by redeploying the subgraph.
=> Print deprecation warning for JSONB subgraphs

store/postgres/src/entities.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
The way we used to revert metadata when a block was reverted was not
correct: the reversion would also revert metadata for unrelated subgraphs,
leading to potential loss of dynamic data sources.
This code now makes sure we only revert metadata for the subgraph for which
we are reverting a block.
=> store: Make sure metadata gets reverted only for one subgraph

graph/src/log/elastic.rs
If no `elasticsearch-user` is supplied with the `elasticsearch-url` on startup the logs will be flushed to the endpoint without using basic auth.
=> Support logs endpoint without HTTP basic auth

chain/ethereum/src/ethereum_adapter.rs
New versions of Ganache append the reason to the revert message.
=> Fix Ganache reverts

graph/src/data/schema.rs
Previously the step had a misplaced `!` that caused it to check for a string field that doesn't match the includes field name instead of validating that there is an entity field that _does_ match the includes field name.
=> graph/schema: Fix validation step that checks includes fields are valid

runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs
We are producing 5k - 20k of these messages _per minute_ in hosted, and I don't think they are particularly useful to anybody
=> runtime: Remove logging of time for store.get

chain/ethereum/src/ethereum_adapter.rs
That actually refers to https://github.com/graphprotocol/graph-ts/issues/85, so the repo is graph-ts not support. I figured we can just remove the reference to the issue, other than a historical note it's not very relevant.
=> Fix comment

core/src/graphql/runner.rs, core/src/subgraph/loader.rs, core/tests/interfaces.rs, graph/src/data/query/query.rs, graphql/src/execution/execution.rs, graphql/src/execution/mod.rs, graphql/src/execution/query.rs, graphql/src/introspection/mod.rs, graphql/src/introspection/schema.rs, graphql/src/query/mod.rs, graphql/src/store/prefetch.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, server/http/src/request.rs, server/index-node/src/request.rs, server/index-node/src/resolver.rs, server/websocket/src/connection.rs
There was quite a bit of code in GraphQL execution that only depended on the query, and was run before we ever executed anything. Some of the execution code was made less clear by the fact that it had to simultaneously destructure the GraphQL AST and perform logic depending on the structure. Some logic was duplicated, with minor variations, across query and subscription execution.
This PR introduces a new `execution::Query` struct whose construction does as much work as can be done before actual query execution starts, in particular, it does things like variable coercion, field validation, and query complexity checking.
This PR solely refactors code, and should not change any behavior of the system. It's ultimately motivated by needing to access the block at which a query is run in a more …
=> Refactor some of the GraphQL query execution

store/test-store/src/lib.rs
The tests were running out of connections and hanging on my machine with the current size.
=> Increase connection pool size

.gitignore, chain/ethereum/src/network_indexer/block_writer.rs, core/src/subgraph/instance_manager.rs, graph/src/components/store.rs, graph/src/components/subgraph/instance.rs, graph/tests/entity_cache.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/mapping.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, store/test-store/src/lib.rs, tests/integration-tests/remove-then-update/abis/Contract.abi, tests/integration-tests/remove-then-update/contracts/Contract.sol, tests/integration-tests/remove-then-update/contracts/Migrations.sol, tests/integration-tests/remove-then-update/migrations/1_initial_migration.js, tests/integration-tests/remove-then-update/migrations/2_deploy_contracts.js, tests/integration-tests/remove-then-update/package.json, tests/integration-tests/remove-then-update/schema.graphql, tests/integration-tests/remove-then-update/src/mapping.ts, tests/integration-tests/remove-then-update/subgraph.yaml, tests/integration-tests/remove-then-update/test/test.js, tests/integration-tests/remove-then-update/truffle.js, tests/tests/tests.rs
Previously we'd ignore the removal, merging the update with the version in the store.
The fix required changing the structure of `EntityCache` to explicitly keep track of entities which were removed at some point.
Resolves #1598. Includes integration test.
=> Fix entities updated after remove

chain/ethereum/src/network_indexer/ethereum.graphql, graph/src/data/store/mod.rs, graph/src/data/subgraph/schema.rs, graphql/src/schema/ast.rs, store/postgres/examples/layout.rs, store/postgres/src/entities.rs, store/postgres/src/jsonb_queries.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/src/sql_value.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs, store/postgres/tests/store.rs
These changes make it so that the `id` field of an entity can either be of type `String` or of type `Bytes` in the subgraph's GraphQL schema. For backwards compatibility, the type `ID` can also be used, though it is now officially a synonym for `String`.
The distinction between `Bytes` and `String` only affects how the `id` of entities is stored in the database, either in a `bytea` or a `text` column. The rest of the code (e.g., `Entity`) uses strings always.
Fixes #1414 
(Replaces PR #1445 as the code had changed a lot since that PR was opened)
=> Allow using `Bytes` for `ID` and switch block explorer to that

Cargo.lock, core/src/graphql/mod.rs, core/src/lib.rs, core/tests/interfaces.rs, graph/src/data/query/error.rs, graph/src/data/query/result.rs, graphql/Cargo.toml, graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/lib.rs, graphql/src/query/ext.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/src/store/prefetch.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, node/Cargo.toml, node/src/main.rs, server/index-node/src/resolver.rs, server/index-node/src/service.rs, store/test-store/Cargo.toml, store/test-store/src/lib.rs
With this PR, GraphQL query responses will now include information about the bock at which they were run. This PR also makes sure that GraphQL queries that do not explicitly specify a block are run in their entirety against a fixed block (the latest block of a subgraph)
The response will now contain
```json
{
"data" : "...",
"extensions": {
"subgraph": {
"blocks": [ {
"ethereum/mainnet": {
"hash": "ea3bc37eb909f29c897d7a3fe3de30abd86baa58619403941e14a9797063a479",
"number": 9892879 }
} ],
"id": "QmZo35amfokYndPeuRd91bSzF6EusfBKMuDQCvaq25FVUX"
}
}
```
Note that when the query constrains blocks by number, the hash will always be reported as "000..000" since we can not guarantee that the block is in our database cache (though we can still execute the query), plus we don't want people to use …
=> Report the block at which a query was run in the response

graphql/src/values/mod.rs, server/http/src/response.rs
The JSON that `serde_json` produces is already what we want. This adds tests that make sure that the serialization of responses remains what we expect, even if the underlying implementation changes.
=> server: Add test for canonical serialization of JSON responses

NEWS.md, graphql/src/runner.rs, graphql/tests/query.rs, store/test-store/src/lib.rs
While adding a description of how we indicate the block at which a query ran to the release notes, I noticed a small inconsistency. Fixed that and added a test to check the output format.
=> Fix format of 'extensions' field in GraphQL responses

store/postgres/src/connection_pool.rs
I was too hasty when I said we don't need to log about excessive waits when getting a connection from the database pool. Turns out when a node is going sideways it's useful to see when contention starts.
This PR adds logging about that back in, but done as a r2d2 event handler, and with a threshold of 100ms instead of 10ms. It also adds a Prometheus gauge that reports the number of currently checked-out connections.
=> Add logging of DB connection contention back in

core/src/subgraph/instance_manager.rs
This PR fixes an issue with looping through the subgraph assignment provider event stream that resulted in exiting after consuming just the first event. 
In the original implementation the expression being iterated over resolves to `Option<_>`.  Since `Option<_>` implements an `iterator` that yields 0 or 1 depending on the pattern, the `for...in` was simply iterating over the `Option<_>` from the first event and then exiting.  
Now a `while..let` loop is used to continue to poll the future until the channel closes or it returns an error.
=> core/subgraph: Use while loop to process assignment provider stream

store/postgres/src/relational.rs
There are more improvements we are working on for Proof-of-Indexing. Rather
than deal with an old and a new version out in the wild, we'll turn PoI off
until the new version is ready.
=> store: Turn Proof of Indexing off

Cargo.lock, graph/Cargo.toml, graph/src/data/store/mod.rs, graph/src/data/store/scalar.rs, runtime/wasm/src/asc_abi/mod.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, runtime/wasm/src/module/test/abi.rs, runtime/wasm/src/to_from/external.rs, runtime/wasm/src/to_from/mod.rs, store/postgres/src/filter.rs, store/postgres/src/relational_queries.rs, store/postgres/src/sql_value.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs, store/postgres/tests/store.rs
By putting any trailing zeros in the scale. This solves determinism issues because when an entity makes a roundtrip through the store it gets normalized by postgres anyways, at least in some cases.
This is mostly just plumbing through the impls for the `BigDecimal` newtype.
One strange consequence is that the workaround in https://github.com/graphprotocol/graph-node/pull/1182 is no longer necessary. It seems that issue only manifested in non-normalized BigDecimals.
=> Normalize BigDecimal values

graph/src/data/subgraph/mod.rs
Based on observations in hosted, subgraph grafting isn't quite ready for prime time yet for reasons that are only apparent once subgraphs are grafted on a system with lots of subgraphs and under decent load (like hosted)
The core problem is that the data copying for grafting happens in one transaction which can take hours. That has at least two bad side effects:
1. Because of the long running transaction, autovacuum can't remove garbage until after the txn finishes. That is especially bad for the `subgraph_deployment` table which becomes very bloated, directly impacting performance for everything
1. Any interruption of the long-running transaction will require that data copying starts from scratch. If a new version is rolled out a few hours into a copy transaction, the user will have just …
=> Disable subgraph grafting for now

store/postgres/src/store.rs, store/postgres/tests/store.rs
The query to determine the first block to remove in `cleanup_cached_blocks` was never adapted to relational metadata. The query would most likely also do bad things in a few corner cases.
Thanks to @Amxx for reporting the issue.
=> Fix a query in `cleanup_cached_blocks`

chain/ethereum/src/block_stream.rs, chain/ethereum/src/network_indexer/subgraph.rs, core/src/subgraph/registrar.rs, graph/src/data/subgraph/schema.rs, graphql/tests/query.rs, server/index-node/src/resolver.rs, store/postgres/migrations/2020-05-16-225611_add_deployment_detail_view/down.sql, store/postgres/migrations/2020-05-16-225611_add_deployment_detail_view/up.sql, store/postgres/src/subgraphs.graphql, store/postgres/tests/graft.rs, store/postgres/tests/store.rs, store/test-store/src/lib.rs
Storing it there requires that we update every subgraph deployment for a network whenever we get a new block for that network which causes a huge amount of writes to subgraphs.subgraph_deployment, and bloats the table.
The information is already available in ethereum_networks; instead of denormalizing that data, make it available to GraphQL queries through a view in the database. The view pretends to be an entity, though any attempt to write that entity will fail as it is not possible to write into this view.
=> all: Do not store the chain head block in SubgraphDeployment

store/postgres/examples/layout.rs, store/postgres/src/catalog.rs, store/postgres/src/entities.rs, store/postgres/src/lib.rs, store/postgres/src/relational.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs
We had a bug that if the GraphQL schema for a subgraph used an enum before it was defined, the generated database schema would have a 'text' column instead of an 'enum' column. Since that bug was (inadvertently) fixed in commit 3d23bccf, queries against such tables would fail if they tried to filter by the presumptive enum attribute.
With this commit, we check whether we have a text column where we should have an enum, and then switch the internal table representation to treat the enum as 'String' and not as an enum when querying or storing data.
Verifying that this actually fixes the problem is unfortunately a little complicated. [This gist](https://gist.github.com/lutter/70158472fc237b188e33ee8d6a1a201a) contains instructions on how to do that. I have also verified that …
=> Handle database tables that have `text` columns where they should have enums

Cargo.lock, graph/src/data/query/error.rs, graph/src/data/query/result.rs, graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, server/index-node/src/service.rs, store/test-store/Cargo.toml, store/test-store/src/lib.rs
This makes it possible to have different block constraints for different toplevel fields in GraphQL queries. It also removes the 'extensions' field in the response that reported the block against which a query was run.
=> all: Allow varying block constraints in GraphQL queries

docker/Dockerfile, docker/bin/create, docker/bin/debug, docker/bin/deploy, docker/bin/reassign, docker/build.sh, docker/cloudbuild.yaml, docker/debug, docker/start, docker/start-node, docker/tag.sh, docker/wait_for
These changes accomplish a few things:
* the `Dockerfile` produces three containers: a (very large) build container, a smaller `graph-ndoe` runtime container, and a `graph-node-dbg` debug container that can be used to investigate core dumps produced by the runtime container. The `docker/build.sh` script shows how to build the three containers using plain `docker` (resp `podman`) The `Dockerfile` expects that the current working directory for a build is the root of the repo
* the `start` script makes it possible to run an all-in-one `graph-node` (`ENV node_role=combined-node`, the default), or separate `query-node` or `index-node` containers. For `index-node`, it is possible to select which instance of such a container runs a block ingestor
* the `start` script will capture a core dump and …
=> Revamp how we build containers

store/postgres/src/relational.rs
Including the id column makes Postgres use this index when it really shouldn't and actually slows some queries down catastrophically from 50ms to 2s.
=> store: Do not include 'id' in BRIN indexes

core/src/subgraph/registrar.rs, graph/src/components/ethereum/listener.rs, graph/src/components/store.rs, graphql/src/subscription/mod.rs, node/src/main.rs, store/postgres/src/chain_head_listener.rs, store/postgres/src/lib.rs, store/postgres/src/store.rs, store/postgres/src/store_events.rs, store/postgres/tests/store.rs, store/test-store/src/lib.rs
Each `graph-node` process would have one `ChainHeadUpdateListener` and one `StoreEventListener` for each network that the process was dealing with. With 8 networks, that would eat up 16 database connections, which adds up if you run a lot of `graph-node` processes.
With these changes, each process only uses one listener each, independent of the number of networks that are being processed, so that we only need 2 database connections per process.
Thanks to @leoyvens for helping me with some gnarly futures issues with the `ChainHeadUpdateListener`
=> Refactor the event listeners

Cargo.lock, graphql/Cargo.toml, graphql/src/execution/execution.rs, graphql/src/execution/query.rs
Only for the subgraphs listed in the env var `GRAPH_CACHED_SUBGRAPH_IDS`, we keep a result cached for `GRAPH_CACHE_EXPIRY_SECS`. This might serve stale data but is useful as a way to temporarily alleviate pressure on the DB.
I did a manual test that this works as expected, logging `Query cache hit` on a second query, but expiring one minute after the first query.
=> Quick and dirty query cache

docker/cloudbuild.yaml, docker/tag.sh
We do not modify the 'latest' tag in Docker Hub if we build something that is not on the master branch.
=> docker: Only push builds on master to the 'latest' tag

chain/ethereum/src/ethereum_adapter.rs
The revert error message has changed in Geth 1.9.15 https://github.com/ethereum/go-ethereum/releases/tag/v1.9.15. I did not have an upgraded node available to test, but there isn't too much to go wrong in checking if the message contains ""execution reverted".
=> Support new Geth revert format

graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/query/mod.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/src/values/coercion.rs, graphql/tests/introspection.rs, server/index-node/src/resolver.rs
This does a pass at simplifying and optimizing our graphql execution. Non-prefetched execution is removed. I couldn't get very amazing numbers locally, maybe a 10% speed up and a 20% resource usage reduction, but we'll see how it goes in real workloads.
The commits can be read separately. The first commit makes so `coerce` doesn't clone. The annoying part here is that it has to return the value on a failure to coerce so we can have good errors, so most of the diff is about the change to a `Result<Value, Value>` return type.
The second commit completes values in place so we don't allocate a new vec for it.
The third commit is probably the most impactful one. It removes non-prefetched execution. The optimization is instead of passing down a reference to the prefetched parent object, only so …
=> Optimize graphql execution

server/index-node/src/resolver.rs, tests/integration-tests/fatal-error/test/test.js
This regressed in https://github.com/graphprotocol/graph-node/pull/1712. Instead of returning `null`, here we were returning `UnknownField`. Which makes no sense really, we check for unknown fields way up in the stack, before executing the field. As far as these resolvers care if they were not given the field value, then there is no value so return `Null`.
=> Fix regression in indexing status

Cargo.lock, runtime/wasm/Cargo.toml, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, tests/integration-tests/big-decimal/src/mapping.ts
The first commit is the regression test, plus a pure refactor which renames `WasmInstanceHandle` -> `WasmInstance`, and pulls the `wasmtime::Instance` to it. The other rename is `WasmInstance` -> `WasmInstanceContext`. These names hopefully better reflect the purpose of each struct.
The second commit is where it gets wild. To support calling host functions in the Wasm start function so that AS can use them when initializing globals, we lazily initialize the `WasmInstanceContext` in the host export if necessary, taking from the `Caller` the memory and the memory allocation function. I needed to patch wasmtime to support that last part. But wasmtime would rather not merge that upstream and instead suggests that AS makes changes on their side, that discussion will happen here …
=> Fix host functions in globals

store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs
This PR fixes an issue causing invalid insert queries to be constructed for fulltext fields.  
In the case of an insert of an entity with a fulltext field, an issue arose when all fields included in the fulltext field are null.  When walking the ast of the `QueryFragments` in an `InsertQuery` this led to an invalid query fragment, `())`, being constructed  [here](https://github.com/graphprotocol/graph-node/blob/master/store/postgres/src/relational_queries.rs#L367-L378).
=> Fix issue inserting fulltext fields when all included field values are null

server/http/src/service.rs, server/index-node/src/service.rs
We already have a metric for this and also the `GRAPH_LOG_QUERY_TIMING` env var which can be turned on. This log is noisy and not useful, and I could even measure a throughput increase of about 5% in fast queries by removing it.
=> Remove "Graphql query served" log

chain/ethereum/src/block_stream.rs, docs/environment-variables.md
Our defaults should optimize for compatibility, and Alchemy will soon make this their hard limit.
This may hurt performance especially for nodes with a high latency to the Ethereum node and for subgraphs that don't use `startBlock`, but overall I don't expect this lower default to be much of a problem.
=> Default max block range size 1000

core/tests/interfaces.rs, graphql/src/execution/execution.rs
This was a regression in the optimization to not clone all fields before resolving them. The problematic case is when the same scalar field redundantly appears in multiple response keys, in which we really have to clone the field. But we don't want to reverse the optimization and go back to cloning everything, so this checks which fields are duplicated and clones only those.
=> Fix duplicated scalar fields

chain/ethereum/tests/network_indexer.rs
I tried ignoring only a few of them, but really all of these tests are flaky.
=> Ignore flaky network indexers tests

chain/ethereum/src/ethereum_adapter.rs
I've seen eth_getLogs take about 140 seconds on Alchemy, and still respond successfully.
=> Increase default json rpc timeout

graph/src/data/store/mod.rs, graphql/src/execution/execution.rs, graphql/src/store/prefetch.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs
The first commit removes `merge_selection_sets`, because it does an expensive clone in `extend_from_slice`. This procedure turns out to not be necessary if we make `collect_fields` directly handle a sequence of selection sets, merging them into the collected fields. Read with whitespace diff disabled.
The second commit removes some completely unecessary clones, found by running `cargo flamegraph`.
There are other ideas such as caching the `collect_fields` procedure, but as far as easy optimizations go these were all I could identify.
=> Reduce cloning in graphql execution

graphql/src/execution/execution.rs, graphql/src/query/mod.rs, graphql/src/subscription/mod.rs
This makes prefetching and the cache use the same code path for regular queries and subscriptions.
=> Use `execute_root_selection_set` for subscriptions

graph/src/components/store.rs, graph/src/lib.rs, graphql/src/store/prefetch.rs, graphql/src/store/query.rs, store/postgres/src/jsonb_queries.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/relational_bytes.rs, store/postgres/tests/store.rs
When we query for children where we know that each parent can have at most one child, it is possible to simplify queries considerably. With this PR, we pass the necessary information to know whether we expect one or many children per parent into the store, and use it to generate better queries.
The background on why these queries look the way they do can be found in [the RFC](https://graphprotocol.github.io/rfcs/engineering-plans/0001-graphql-query-prefetching.html)
=> Optimize queries for single-object lookups

graph/src/components/store.rs, graphql/src/store/prefetch.rs, mock/src/store.rs, store/postgres/src/entities.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/src/store.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs
The purpose of this PR is to optimize the CPU usage of query nodes. There are no functional changes.
Currently, the conversions involved in serving a query result are:
jsonb (DB) -> json::Value (EntityData) -> Entity (prefetch) -> q::Value (graphql resolver)
After this PR it is:
jsonb (DB) -> json::Value (EntityData) -> q::Value (prefetch and graphql resolver)
Removing one round of conversion from `HashMap` to `BTreeMap`, which is heavy on allocations, and also avoids some conversions between `BigInt` and `Bytes` to string.
This make it so that the prefetch logic uses `q::Values` instead of entities, and abstracts a bit of the store so that it can serve queries as either `Vec<Entity>` or `Vec<q::Value>`. While `q::Value` has less information than `Entity`, we don't need the extra …
=> Prefetch directly as `q::Value` instead of `Entity`s

chain/ethereum/src/block_stream.rs, core/src/subgraph/registrar.rs, graph/src/components/store.rs, graph/src/data/query/error.rs, graphql/src/store/resolver.rs, mock/src/store.rs, node/src/main.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs, store/test-store/src/lib.rs
This is useful when running a Graph Node against a Postgres read replica.
It disables:
- Chain head listeners.
- All indexing functionality.
- The JSON-RPC admin server.
- The GraphQL subscription server (which currently relies on Postgres `LISTEN`/`NOTIFY`, which doesn't work with replicas).
=> Allow to run against read-only Postgres replicas

graphql/src/execution/execution.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, server/index-node/src/service.rs, store/test-store/src/lib.rs
The current one may serve stale data, since the expiry is time-based, and also has a bug where it wasn't evicting entries, and even if that was fixed the eviction would be slow because the used library did a linear scan to evict entries.
This revamps the query cache so that entries are cached by block pointer. It is designed with the assumption that most queries are for the latest block, so historical queries are not cached. This is implemented with a ring buffer of caches per block, the buffer has a configurable length corresponding to the amount of recent blocks we wish to keep cached. I suggest we start with length 1 when trying it in a production setting.
Because of the way the code is structured right now, subscriptions are no longer cached.
Adds a config option to turn on the cache …
=> Better query cache

graph/src/data/query/error.rs, graphql/src/query/mod.rs, graphql/src/query/shape_hash.rs, graphql/src/runner.rs, graphql/tests/query.rs, node/src/main.rs
We now read a file `/etc/graph-node/expensive-queries.txt`; if the file exists, it has to contain one GraphQL query per line.
We respond to any query that has the same `ShapeHash` as one of the queries from the file with a `TooExpensive` error. Queries have the same `ShapeHash` if they are identical except that they can differ in the query name, the values for any field arguments (filters), and field aliases.
=> Add a facility to not query certain queries

chain/ethereum/src/block_stream.rs, core/src/subgraph/registrar.rs, graph/src/components/store.rs, graph/src/data/query/error.rs, graphql/src/store/resolver.rs, mock/src/store.rs, node/src/main.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs, store/test-store/src/lib.rs
We're now going for every query node having read access, and optionally having additional access to a read replica.
=> Revert experimental read only

graphql/src/execution/query.rs, graphql/src/query/mod.rs
Adds a `complexity` field to the `Query` object and includes it in the query execution logging.
=> Log the calculated complexity of each query executed 

store/postgres/src/chain_head_listener.rs, store/postgres/src/connection_pool.rs, store/postgres/src/relational_queries.rs, store/postgres/src/store.rs, store/postgres/src/store_events.rs
These log statements are either already captured by Prometheus metrics by themselves, or are not very useful on their own.
=> Remove various log statements from the store

store/postgres/src/relational_queries.rs
In production, this change actually slows queries that look up
a large number of children (500+) down tremendously; could be
because evaluating the clause 'c.{parent_field} && {parent_ids}'
becomes very slow with a large number of parent ids.
This reverts commit e566447ab312e2a86edba372331068c015d3aae9.
=> Revert "store: Speed queries of type A up by adding a redundant clause"

core/src/subgraph/loader.rs, core/tests/interfaces.rs, graph/src/data/query/query.rs, graph/src/data/subgraph/schema/queries.rs, graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, mock/src/store.rs, server/http/src/request.rs, server/http/src/service.rs, server/index-node/src/request.rs, server/index-node/src/resolver.rs, server/websocket/src/connection.rs
The cache has a major flaw that it mixes block numbers from different networks, this makes so that each network has its own cache. This was easy thanks to the existing `network_name` store method.
=> Separate query cache by network

chain/ethereum/src/block_stream.rs
Warning introduced in Rust 1.45.
=> Fix warning

store/postgres/src/notification_listener.rs, store/postgres/src/store_events.rs
This PR improves a few things to rule them out as a cause of trouble under load:
- Reduce the size of the notifications channel from 1000 to 100, in case that buffer could ever use too much memory.
- Make the task that distributes store events to subscriptions a blocking one, just in case it's using too much CPU and causing contention.
- In `fn subscription`, Remove the duplicate UUID check which takes a lock and is unnecessary. Also do some refactoring in that method.
=> Use blocking task for store events

node/src/main.rs
This PR adds the option to pass sensitive arguments like database passwords to the application without leaking them in bash history, docker logs or process managers (like `htop` / `top`).
Related discussion: https://github.com/graphprotocol/graph-node/issues/849#issuecomment-658731288
=> Add env variable options for sensitive arguments

graphql/src/execution/query.rs, graphql/src/query/ext.rs, graphql/tests/query.rs
So far, it was not possible to use a variable in a block constraint. As it turns out, after various refactorings over the last few months, fixing #1460 was rather easy.
=> Allow using variables in block constraints

core/src/metrics/registry.rs, graph/src/components/metrics/mod.rs, graph/src/components/store.rs, graph/src/lib.rs, graphql/src/execution/resolver.rs, graphql/src/runner.rs, graphql/src/store/prefetch.rs, graphql/src/store/resolver.rs, graphql/tests/query.rs, mock/src/metrics_registry.rs, mock/src/store.rs, node/src/main.rs, store/postgres/src/connection_pool.rs, store/postgres/src/lib.rs, store/postgres/src/query_store.rs, store/postgres/src/store.rs, store/postgres/tests/store.rs, store/test-store/src/lib.rs
This adds a configuration to pass in a sequence of postgres urls for replicas, which is turned into a sequence of DB connections pools passed to each store. In the store, each use of a connection is either in `ConnMode::Read` or `ConnMode::Write`. Writes always use the main DB. Reads are distributed between all available DBs, including the main one.
=> Support read replicas

Cargo.lock, graph/src/util/ethereum.rs
Resolves #1800 by updating our ethabi to the latest version of our fork, which includes https://github.com/graphprotocol/ethabi/pull/14.
I've tested this locally with https://github.com/gelatodigital/gelato-subgraph, which has a `LogTaskSubmitted` event that was previously broken and now works.
=> Update our ethabi fork to tuple[] support

graph/src/data/graphql/effort.rs
On Mac OSX, Instant::now() is the time since the last boot, which might
have been less than a day ago, in which case KillState::new would panic. We
now use 'now - 60s' as a time in the past for initialization, and if that
fails, we'll use just 'now'. There's not much danger in using 'now', it
might just lead to spurious logging and a too-soon update of the kill_rate
if the node becomes immediately overloaded after starting.
Thanks to kevholder for root-causing the issue and demonstrating a fix.
Fixes https://github.com/graphprotocol/graph-node/issues/1805
=> graph: Fix an error in KillState::new

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/config.rs, chain/ethereum/src/lib.rs, chain/ethereum/src/transport.rs, docs/ethereum-config.md, graph/Cargo.toml
This adds support for an Ethereum config file in one (or all of the following locations):
```
/etc/graph-node/ethereum.toml
$HOME/.config/graph-node/ethereum.toml (Linux)
$HOME/Library/Application Support/graph-node/ethereum.toml (macOS)
... and whatever Windows does for config files
```
These files have to have the following structure:
```toml
[rpc."http://url.of.the/ethereum/node"]
http_headers = { authorization: "bearer foo", ... }
[rpc."http://url.of.another/ethereum/node"]
http_headers = { authorization: "bearer bar", ... }
```
Right now, the file format is limited to adding custom HTTP headers to `rpc` endpoints provided via e.g. `--ethereum-rpc`. In the future, we can add more here, like node capabilities etc.
=> Add an experimental Ethereum node config file

graph/src/data/graphql/effort.rs, graph/src/data/query/error.rs, graphql/src/runner.rs
We used to always produce 'query too expensive' when the load manager
decided to decline running a query, which made users think there was
something wrong with their query.
We now return 'query too expensive' for queries that have been blocked
wholesale because we decided they were too expensive. For queries that we
will not run because the service is overloaded, we now return an error that
says that and makes it clear that that is a temporary condition.
=> graph, graphql: Better error message when we decline to run a query

graph/src/data/graphql/effort.rs
Commit 1d3b54e2 reversed the logic for blocked queries. This change does
indeed block them again.
=> graph: Actually block blocked queries

chain/ethereum/src/ethereum_adapter.rs, graph/src/components/ethereum/adapter.rs, node/src/main.rs
Now that we support multiple endpoints, this can happen if the call goes to an endpoint that's behind.
=> Replace unwrap with error in block stream

docs/environment-variables.md, graphql/src/execution/execution.rs
Also bump the default query cache size to 1GB, since 100MB is excessively conservative.
=> Document query cache env vars

graph/src/data/subgraph/mod.rs, runtime/wasm/src/host.rs
Subgraph Ethereum node capability requirements are parsed from each data source when buiding the runtime hosts.  A typo that mixed up `traces` and `archive` requirements led to incorrect parsing and ultimately false rejections of valid subgraph deployments.
=> Fix required capability parsing from subgraph manifest in runtime host builder

store/postgres/src/block_range.rs, store/postgres/src/relational_queries.rs
The BlockRangeContainsClause used to expand to just `block_range @> {block}`; it now expands to that plus redundant clauses that make the BRIN index on block_range usable.
The redundant clauses are useful in situations where relatively few entities are updated a lot since the BRIN index is very effective in narrowing down where matching entities can actually be found in the heap.
For some problematic queries this can bring execution time from 10+s down to 500ms. It doesn't seem to increase execution times for queries that don't strictly need the extra clauses, but setting `DISABLE_BRIN_BLOCK_RANGE` in the environment can be used to turn this change off in case it does adversely affect query performance.
=> Tweak the BlockRangeContainsClause to make BRIN indexes usable

store/postgres/src/block_range.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
For entities that are transaction-like in that entities are rarely, if ever, updated, adding redundant `block_range` clauses from PR #1854 slows queries down to the point where the overall performance of the system suffers. At the same time, for entities that are account like in that entities are updated frequently, adding redundant `block_range` clauses is indeed beneficial.
This reverts commit 9d72f3b82212b385a015230769045ab368a8981c and introduces a setting where account-like tables can be specified explicitly. Ultimately, we would like to automatically detect such tables, but to make sure that this is in fact a useful heuristic, we allow setting which tables to treat special in the environment to make it possible to test this hypothesis under load.
=> store: Do not add redundant clauses to BlockRangeContainsClause

Cargo.lock, core/src/metrics/registry.rs, graph/src/components/metrics/mod.rs, mock/src/metrics_registry.rs, node/src/main.rs, store/postgres/Cargo.toml, store/postgres/src/connection_pool.rs, store/postgres/src/store.rs, store/test-store/src/lib.rs
We identify pools as either 'main' or 'replicaN' in the labels
Fixes https://github.com/graphprotocol/graph-node/issues/1861
=> all: Label connection pool metrics with the pool they come from

store/postgres/src/relational_queries.rs
This makes it possible to support reversion with an index
```
create index concurrently manual_revert_clamp
on <table>(coalesce(upper(block_range), 2147483647))
where coalesce(upper(block_range), 2147483647) < 2147483647;
```
for subgraphs where `RevertClampQuery` runs slow
=> store: Include a redundant clause in RevertClampQuery

graphql/src/execution/query.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, server/index-node/src/service.rs, store/test-store/src/lib.rs
Because block constraints might cause us to execute a GraphQL query in several steps, we used to log the entire query for each of these steps. That leads to inaccurate query execution counts and times, and to logs that are hugely inflated in size.
We now log the overall query execution only once. To get insight into cache usage, we also log cache usage information separately from the overall query execution. To keep log size manageable, we do not log the query text with the cache information. That would have to be inferred from the `query_id` logged with both log statements.
=> Log GraphQL queries only once

docs/environment-variables.md, graphql/src/execution/execution.rs
We see a lot of historical queries in the hosted service, and our cache performs poorly for those. Add an `LfuCache` of query results for those to improve the cache hit ratio.
=> Add an LfuCache for historical queries

tests/integration-tests/arweave-and-3box/src/mapping.ts
That was relying on a 3box profile we don't control not changing their spirit animal. It seems they had a change of spirit.
=> Fix broken test

Cargo.lock, graph/Cargo.toml, graph/examples/stress.rs, graph/src/util/cache_weight.rs, graph/src/util/lfu_cache.rs
This PR improves the estimates that `LfuCache` uses to determine how big a cache entry is. Under heavy load, `LfuCache` would appear to leak memory. At least part of that apparent leak was that `LfuCache` underestimated how much memory cache entries use, which would lead to the cache growing much bigger than intended. In some cases, for example for small `BTreeMap`s, the estimate was off by more than an order of magnitude, which in practice has the same consequences as an actual leak.
With the tweaks to memory estimates, `LfuCache` now mostly overestimates the amount of memory an entry takes, though running the `stress` example still shows that overall memory usage can be a factor of 3 larger than the estimate that the cache tracks, for example, when caching strings less than 50 bytes …
=> Improve estimate of how much memory is used by an LfuCache

graph/src/util/ethereum.rs, runtime/wasm/src/host.rs
Resolves #1841 
This PR fixes a bug in `contract_function_with_signature()` which allowed for false positives to be returned. This inconsistency led to incorrect function abis being used in function param decoding leading to `invalid data` errors in [ethabi](https://github.com/graphprotocol/ethabi). 
I've also restructured `contract_function_with_signature()` to reduce unnecessary work building function signature hashes for functions that can be excluded early because they are `view` or `pure` functions.
=> Bug fix: Fetch correct function abi from contract abi 

Cargo.lock, chain/ethereum/src/block_ingestor.rs, chain/ethereum/src/network_indexer/block_writer.rs, chain/ethereum/src/network_indexer/metrics.rs, chain/ethereum/src/network_indexer/network_indexer.rs, core/Cargo.toml, core/src/metrics/registry.rs, core/src/subgraph/instance_manager.rs, graph/src/components/ethereum/adapter.rs, graph/src/components/metrics/aggregate.rs, graph/src/components/metrics/mod.rs, graph/src/components/metrics/stopwatch.rs, graph/src/components/subgraph/host.rs, graph/src/data/graphql/effort.rs, mock/src/metrics_registry.rs, runtime/wasm/src/module/test.rs, server/http/src/service.rs, store/postgres/src/connection_pool.rs, store/postgres/src/store.rs
The biggest change in this PR is that metrics no longer have dynamically constructed names; instead, names are fixed, and labels are used to attach, e.g. the subgraph to the metric.
The PR also changes the `MetricsRegistry` trait a bit to make the various constructor methods a little more ergonomic and clearer in what they should be used for (like `new_counter` vs `new_subgraph_counter`)
=> Revamp how we handle Prometheus metrics

docs/environment-variables.md, graph/src/data/graphql/effort.rs, graph/src/data/query/cache_status.rs, graph/src/data/query/mod.rs, graph/src/log/mod.rs, graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/query/mod.rs
We currently use a Google cloud log-based metric, but that is both wasteful and seems to be inaccurate. With this PR, it is still possible to log the cache status of queries, but it will also be recorded in a Prometheus metric so that log analysis should in general not be necessary.
=> Move tracking the cache status of queries to a Prometheus metric

graph/src/components/store.rs, store/postgres/src/store.rs
When a subgraph is indexed by two or more graph nodes that share a database, we're currently crashing nodes when they run into from/to block conflicts. What we should do (and what this PR does) is only make the subgraph fail and also print a message that points out the likely cause of the issue: that multiple nodes are indexing the same subgraph.
=> Don't crash node and show better error on invalid subgraph transitions

Cargo.lock, core/Cargo.toml, core/tests/interfaces.rs, graph/src/data/graphql/ext.rs, graph/src/data/graphql/mod.rs, graph/src/data/graphql/object_or_interface.rs, graphql/src/execution/execution.rs, graphql/src/execution/mod.rs, graphql/src/execution/query.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/lib.rs, graphql/src/schema/ast.rs, graphql/src/store/prefetch.rs, graphql/src/store/query.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, server/index-node/src/resolver.rs
This fixes issues in how prefetch handles redundant selections in fragments. The changes are mostly around field collection, which will now have a single group of fields for response keys of objects, and for response keys of interfaces it will have a group of fields for the interface and one for each concrete type that appears in a type condition in the query.
Field collection in `execution.rs` was also refactored, even though it's not directly related to the issues.
This also changes where field collection happens, to make selecting only the relevant fields from the DB in a future patch easier.
Resolves #1816.
=> Fix fragment bugs

docs/environment-variables.md, graph/src/components/graphql.rs, graphql/src/execution/execution.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/src/store/prefetch.rs, graphql/src/store/query.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, server/http/src/service.rs, server/http/tests/server.rs, server/index-node/src/resolver.rs, server/index-node/src/service.rs, store/test-store/src/lib.rs
This change adds the ability to enforce a global limit on the `skip` parameter in queries, in the same way that we limit `first`. This is prompted by the hosted service where we see queries with absurdly high `skip` values (10000 and more) Since `GRAPH_GRAPHQL_MAX_SKIP` defaults to `u32::MAX` this change will not do anything for now, though we should absolutely limit `skip` to something like 2000. Apps should only page through collections with `first`/`skip` to display them to humans, where 2000 items is more than any human will ever want to look at.
If an app needs to download an entire collection, it should not do that with `first`/`skip` as that will perform very badly for larger collections. Instead, it should follow the approach described …
=> all: Limit the 'skip' parameter in the same way as 'first'

chain/ethereum/src/block_stream.rs
This is limited for compatibility with Alchemy's limit, which was of 1000 blocks and was now increased to 2000 blocks.
=> Bump max block range size default

chain/ethereum/src/block_stream.rs
This helps with not waiting too long to retry on an intermittent error.
=> block_stream: reset error count correctly

.dockerignore
When I'm building docker images locally for development, the .git folder and the target folder contributes a whole bunch to the initial startup time to build, so this helps with the development workflow. Dunno if this breaks anything though, but it seems to work for me :shrug:
=> Ignore .git and Docker output folder when building images

graph/src/components/graphql.rs, graphql/src/execution/execution.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, server/http/src/service.rs, server/http/tests/server.rs, server/index-node/src/resolver.rs, server/index-node/src/service.rs, store/test-store/src/lib.rs
That happened when the indexing status resolver called the store resolver, and could potentially deadlock.
In passing also fix getting `panic processing query: internal error: entered unreachable code` when querying the indexing status of a non-existing subgraph.
=> Don't reenter the load manager semaphore

store/postgres/src/relational_queries.rs, store/test-store/src/lib.rs
We were unconditionally importing things that were only necessary in release mode. Resolves #1949.
=> test-store: Fix warnings with --release

Cargo.lock, runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/mapping.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, runtime/wasm/src/module/test/abi.rs
In preparation for the network, where the current IPFS API will not be usable.
=> Disable `ipfs.cat` by default

chain/ethereum/src/block_stream.rs, graph/src/components/ethereum/adapter.rs
We've seen reports of subgraphs jumping to the future and past blocks being processed again, having these checks helps narrow the cause. This also asyncifies `blocks_with_triggers`.
=> Check trigger boundaries

core/src/subgraph/loader.rs, core/tests/interfaces.rs, graph/src/components/graphql.rs, graph/src/data/query/error.rs, graph/src/data/query/result.rs, graph/src/data/subgraph/schema/queries.rs, graph/src/util/cache_weight.rs, graphql/src/execution/execution.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, server/http/src/service.rs, server/http/tests/response.rs, server/http/tests/server.rs, server/index-node/src/resolver.rs
When a GraphQL query contains different block constraints, we run and cache the toplevel fields grouped by the block constraint separately, and assemble the response from those partials. We now see a lot of large GraphQL queries with different block constraints - on average we run 3-4 toplevel queries for each GraphQL request.
Assembling the response used to involve cloning all the partial responses. This PR changes that so that we will not clone at all, and rather pass the partial results around behind in an `Arc`; assembling the entire response is only done when we serialize the response to JSON (that's another clone-heavy part of request processing, but is not addressed by this PR)
=> Avoid cloning results assembled from partial results

graph/src/data/graphql/ext.rs, graph/src/data/graphql/object_or_interface.rs, graph/src/data/schema.rs, graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/runner.rs, graphql/src/schema/api.rs, graphql/src/schema/meta.graphql, graphql/src/store/prefetch.rs, graphql/src/store/resolver.rs, graphql/tests/query.rs, store/test-store/src/lib.rs
This PR makes it possible to include a `_meta` field at the toplevel of queries that reports the block against which the query was run and the deployment id. A query like
```
query {
_meta {
block {
number
hash
}
deployment
}
things(..) { }
}
```
will return the block number and hash of the latest block that the subgraph has indexed, as well as the deployment ID for the subgraph.
=> Add a _meta field

docker/README.md, docker/start
The current start script allows custom ports in postgres_host but still uses the default `5432` for checking if the database is available. This small fix introduces a new variable `postgres_port` which is `5432` by default, causing no breaking changes for previous docker setups.
Background: We're running a self-hosted graph node on a managed Digital Ocean database cluster which has a custom post.
=> docker: Make postgres_port configurable

chain/ethereum/src/block_stream.rs
In case the Ethereum node is returning errors due to overly expensive requests, resetting the range size might help the subgraph recover from a retry loop. If we can infer that resetting the block range size worked, reduce the maximum block range size in an attempt to prevent the error from happening again.
=> Reset block range size on error

Cargo.lock, core/Cargo.toml, core/src/subgraph/instance_manager.rs, core/src/subgraph/provider.rs, graph/Cargo.toml, graph/src/components/subgraph/host.rs, graph/src/data/subgraph/schema.rs, graph/src/ext/futures.rs, graph/src/lib.rs, runtime/wasm/Cargo.toml, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql, store/postgres/migrations/2020-10-31-150000_deterministic_errors/down.sql, store/postgres/migrations/2020-10-31-150000_deterministic_errors/up.sql, store/postgres/src/subgraphs.graphql, tests/integration-tests/fatal-error/test/test.js
This marks as determinstic few common reasons for subgraph failures, for example:
- An `unreachable` wasm trap which is caused by an array access out of bounds.
- An `abort` which AssemblyScript uses for multiple reasons including failed assert.
- Some uncontroversial host export erros such as division by zero.
There may be more cases we'd like to cover, but those can be added as long as we consider it a breaking change and bump the `specVersion` (or `apiVersion`?). Deterministic errors are flagged by a boolean in the metadata which can be accessed through the indexing status API.
=> Deterministic errors

Cargo.lock, chain/ethereum/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, node/Cargo.toml, server/websocket/Cargo.toml
I just ran [`cargo udeps`](https://github.com/est31/cargo-udeps) over our code base - it turned up a few unused/unneeded depencies, though nothing really dramatic
=> all: Remove unused dependencies

docker/docker-compose.yml
it looks like the following [PR](https://github.com/graphprotocol/graph-node/pull/1975) introduced a variable ``` postgres_port``` which is 5432 by default, which in turn causes the current docker-compose to break as it also defines a default port for postgres, hence causing the following error:
```url: postgresql://graph-node:let-me-in@postgres:5432:5432/graph-node, at 'failed to connect notification listener to Postgres: Error(ConnectParams("Invalid \':\' in authority."))', store/postgres/src/notification_listener.rs:122:22```
The current PR proposes a fix by removing the port from ```environment.postgres_host```
=> docker: fix bug in docker-compose set up for postgres

.travis.yml, Cargo.lock, node/src/main.rs
Adds `cargo-audit` to the build process and ran `cargo generate-lockfile` to remove two insecure dependencies
=> Dependency vulnerabilities

node/src/opt.rs
This was missed in moving to StructOpt in commit 2f1fc7ea
Note that other arguments that take multiple values do not accept
comma-separated values
=> node: Allow comma-separated arrays for secondary hosts and weights

Cargo.lock, core/Cargo.toml, node/Cargo.toml, node/src/main.rs, runtime/wasm/Cargo.toml
It's causing problems with the IPFS version we currently use with graph-node.
=> Cargo.lock: Revert ipfs-api update

graph/src/components/store.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, store/postgres/src/query_store.rs, store/test-store/src/lib.rs
Make queries more consistent when replication is in use. We were using a
different QueryStore for each block constraint, and were also resolving
block pointers against the primary. This could lead to us mixing data from
different states of indexing a subgraph, without us even knowing.
=> graphql: Use the same QueryStore for the entire query

graphql/src/execution/query.rs
That makes it so that two queries that have the same query text and the
same variables text have a query id whose second part is identical. This is
useful in logs to tell if two queries are identical.
=> graphql: Include the hash of the variables in the query hash

Cargo.lock, README.md, docs/multiple-databases.md, node/Cargo.toml, node/src/config.rs, node/src/main.rs, node/src/opt.rs, node/src/store_builder.rs
This PR adds support for configuring different stores, as an alternative to the command line switches we use so far. Existing ways to start `graph-node` will still work with this change, but it makes it possible to configure more complex database topologies. This PR is only about handling the configuration (and will work as an alternative to the command line switches for a single database), but does not actually use multiple databases yet.
Note that this PR applies on top of PR #1994
=> Introduce a configuration file for multidatabase support

store/postgres/src/detail.rs
The column subgraph_deployment_detail.ethereum_head_block_number is an int8
in the database, not a numeric
=> store: Fix mapping error in subgraph_deployment_detail

graph/src/data/subgraph/mod.rs, graph/src/data/subgraph/schema.rs, graphql/examples/schema.rs, graphql/src/schema/api.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, mock/src/store.rs, store/postgres/migrations/2020-12-11-142000_subgraph_manifest_features/down.sql, store/postgres/migrations/2020-12-11-142000_subgraph_manifest_features/up.sql, store/postgres/src/metadata.rs, store/postgres/src/store.rs, store/postgres/src/subgraphs.graphql
We saw an issue in a graphql client that is avoided by doing this. And it is generally more correct to only include it if the subgraph opts in. This requires storing the `features` field in the metadata, which we should be doing anyways.
=> Add `subgraphError` argument only when the feature is present

.travis.yml
This takes up build time and provides little value since Rust has been very stable.
=> travis: Don't build on nightly

NEWS.md
The release will be tagged at https://github.com/graphprotocol/graph-node/commit/47a4a1088573cdd4db4c596e785292b9b5501936 after these notes are approved and merged.
=> NEWS: 0.20 release

store/postgres/src/sharded_store.rs, store/postgres/src/store.rs
We call this for every new subscription
=> store: Avoid holding two conns in ShardedStore.deployment_state_from_name

chain/ethereum/src/network_indexer/subgraph.rs, core/src/subgraph/instance.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/loader.rs, graph/src/data/subgraph/mod.rs, graph/src/data/subgraph/schema.rs, graph/tests/manifest.rs, runtime/wasm/src/host.rs, runtime/wasm/src/module/test.rs, store/postgres/examples/layout.rs, store/postgres/migrations/2020-12-15-000000_remove_nested_templates/down.sql, store/postgres/migrations/2020-12-15-000000_remove_nested_templates/up.sql, store/postgres/src/copy_dds.sql, store/postgres/src/deployment.rs, store/postgres/src/dynds.rs, store/postgres/src/subgraphs.graphql, store/postgres/tests/store.rs
We've already dropped support for it, this is doing a cleanup removing related code. specVersion 0.0.1 is no longer accepted. There are only 11 subgraphs on the hosted service that are still on that, and they do not get any queries.
=> Remove templates nested in data sources

graph/src/util/mod.rs, graph/src/util/timed_rw_lock.rs, graphql/src/execution/cache.rs, graphql/src/execution/execution.rs
On Linux, readers will by [default starve writers](https://man7.org/linux/man-pages/man3/pthread_rwlockattr_setkind_np.3.html).
> As long as there are readers, the writer will be starved.
The query cache is a very busy lock and it runs in a non-blocking task, so we want to log any contention on it.
=> Instrument RwLock cache

graphql/src/execution/execution.rs
Previously we'd request the QUERY_LFU_CACHE while holding the QUERY_BLOCK_CACHE. This makes the QUERY_BLOCK_CACHE lock a temporary.
=> Don't hold two cache locks at once

tests/tests/tests.rs
It's failing our CI because their gateway is having issues as can be seen [here](https://arweave.net/tx/W2czhcswOAe4TgL4Q8kHHqoZ1jbFBntUCrtamYX_rOU/data.).
=> Temporarily ignore the arweave test

graphql/src/execution/execution.rs
This should cut the queue on a lock proportionally to `QUERY_BLOCK_CACHE_SHARDS` which defaults to 10.
=> Shard query block cache

graphql/src/execution/cache.rs, graphql/src/execution/execution.rs, graphql/src/execution/mod.rs
This logs details about the generational query cache operating conditions. The second commit moves it into the `cache.rs` module and refactors it a bit.
=> Query cache stats

README.md
There are now multiple options for ethereum node providers, and discussing that is outside the scope of the README.
=> README: Remove Infura mention

Cargo.lock, chain/arweave/Cargo.toml, chain/ethereum/Cargo.toml, core/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, mock/Cargo.toml, node/Cargo.toml, runtime/derive/Cargo.toml, runtime/wasm/Cargo.toml, server/http/Cargo.toml, server/index-node/Cargo.toml, server/json-rpc/Cargo.toml, server/metrics/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml, store/test-store/Cargo.toml, tests/Cargo.toml
We can't change that the 0.20 tag had 0.19.2 crate versions, but we can at least bump the version now. See #2083.
=> Bump package versions to 0.20.0

graph/src/components/store.rs, graph/src/data/graphql/values.rs, mock/src/store.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql, store/postgres/src/network_store.rs, store/postgres/src/sharded_store.rs, store/postgres/src/store.rs
This is to avoid `null` POIs if the block hash isn't found in the block store (which could be the case on one indexer but not on another). This can lead to indexers losing rewards despite indexing a subgraph correctly.
By requiring e.g. the indexer agent to always provide block number and hash in `proofOfIndexing` queries, we can compute the POI on any indexer, regardless of what is in their block store. This is easier than resolving the block hash -> number on-demand in the `proofOfIndexing` resolver. The agent already knows both values anyway.
Part of fixing https://github.com/graphprotocol/indexer/issues/186.
_Note: This is a breaking change but I didn't want to make the block number argument optional, as that just adds unnecessary complexity._
=> *: Require a block number in `proofOfIndexing` queries

core/src/subgraph/provider.rs, node/src/main.rs
It's problematic to register subgraph start errors as a subgraph failure, since we could be processing a request to start a subgraph that is already running.
Generally, I think the ideal situation would be that only deterministic failures are recorded as subgraph errors, and transient failures can either be retried or just logged for the operation to be retried when the index node is reset.
=> Startup failure should not fail the subgraph

server/index-node/src/schema.graphql
This was causing JS clients (such as indexer-service) to fail with the
following error:
Error: Decorated type deeper than introspection query.
With this fix, that no longer happens.
=> server/index-node: Fix missing `scalar Int` in the GraphQL schema

.travis.yml
We ran `cargo generate-lockfile` as part of running `cargo audit` which
meant that our tests were against different versions of dependencies than
what we actually use in our public builds.
We'll need to revisit scanning of dependency vulnerabilities in some other
way.
=> travis: Remove `cargo audit`

graph/src/data/store/mod.rs, graphql/src/schema/api.rs, store/postgres/src/relational.rs
An amusing oddity that we are considering the string `"List"` as representing a list type, but that's never the case. This was discovered because a user tried using a `type List @entity { ... }` and this caused an error.
=> Allow type named 'List'

store/postgres/migrations/2021-01-14-175654_add_network_to_deployment_schemas/down.sql, store/postgres/migrations/2021-01-14-175654_add_network_to_deployment_schemas/up.sql, store/postgres/src/primary.rs, store/postgres/src/sharded_store.rs, store/test-store/src/block_store.rs
For some of the upcoming changes, we need to know the network for each subgraph, rather than leave that as an `Option` - we already know that, but don't store it in the primary. This change just records a subgraph's network in the primary in `deployment_schemas` and fills in the data for existing deployments.
For non-sharded setups, that's the end of the story. For sharded setups (which it is safe to assume is only hosted at this point), we will need to manually fill `deployment_schemas.network` for existing deployments that are not in the primary shard. 
A follow-up PR will then make `deployment_schemas.network` not nullable, and use it rather than `ethereum_contract_data_source.network` which is somewhat hard to get to.
=> store: Save the network to which a subgraph belongs in the primary

chain/ethereum/src/block_stream.rs
Depending if this is built with the `failpoints` feature turned on or not, it can trigger a warning.
=> Fix unused variable warning

Cargo.lock, core/src/subgraph/instance_manager.rs, graph/src/components/subgraph/host.rs, graph/src/data/graphql/shape_hash.rs, runtime/derive/src/lib.rs, runtime/wasm/Cargo.toml, runtime/wasm/src/asc_abi/asc_ptr.rs, runtime/wasm/src/asc_abi/class.rs, runtime/wasm/src/asc_abi/mod.rs, runtime/wasm/src/error.rs, runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/lib.rs, runtime/wasm/src/mapping.rs, runtime/wasm/src/module/into_wasm_ret.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, runtime/wasm/src/module/test/abi.rs, runtime/wasm/src/to_from/external.rs, runtime/wasm/src/to_from/mod.rs
**Error Determinism**
-  Introduced determinism in error types
- Before this would set deterministic_host_trap, but access to this value may not be available in many cases where the error originates or may use shared references forcing atomics
- anyhow errors are necessarily considered non-deterministic until proven otherwise.
- Anyhow is dangerous for our use-case because it hides information by design. (This extends to any use-case which handles errors) There's not much that can be done here in the short term.
- Lots of anyhow errors have been converted to deterministic ones (eg: json parsing, type conversions, math, and most other host exports are deterministic)
- Note that like anyhow, panics do not carry determinism information. These must be treated as non-deterministic and should …
=> *: Deterministic error work in preparation for gas

graphql/src/execution/execution.rs
Must be a copy paste artifact, it doesn't make sense.
=> Remove stray comment

core/src/subgraph/instance_manager.rs, graph/src/components/store.rs, mock/src/store.rs, store/postgres/src/network_store.rs, store/postgres/src/primary.rs, store/postgres/src/sharded_store.rs, tests/integration-tests/non-fatal-errors/test/test.js, tests/tests/tests.rs
It seems more consistent for a non-fatal error to always be transacted to the DB in the same way, but still we can unassign to prevent a subgraph that hasn't synced yet from moving forward after encountering an error.
This adds a `store.unassign` to remove the assignment for a subgraph id.
=> Unassign, not fail, pending subgraph on error

store/postgres/src/deployment.rs, store/postgres/tests/subgraph.rs
This is a bit subtle: When the instance manager calls `fail_subgraph` at block N, that block has not been transacted into the store, and is therefore N is beyond the subgraph head block.  But right now because the error is deterministic we'd consider it non-fatal. To fix this, `non_fatal_error` will not check if any determinstic error exists, but if one exists up to the subgraph head block and therefore is an error that has been transacted. The test demonstrates this situation.
Resolves #2093.
=> Fix has_non_fatal_errors

graphql/src/execution/execution.rs
`QUERY_CACHE_MAX_MEM` is the total memory budget, not per shard.
=> Fix max memory of the lfu cache

store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs
Resolves #1766, resolves #1474
This fixes the `*_not_contains` graphQL operator from returning the same output as the `contains` operator.
The current code does not handle the negation of the `contains` filter, so the two operators produced the same result.
This PR contains two tests that handle populated lists, but empty lists and `null` values are still untested, as I think it would be best to discuss thoughts on how to handle those two possibilities for the absence of value.
=> Fix not contains filter

graph/src/components/store.rs, graphql/src/runner.rs, graphql/tests/query.rs, mock/src/store.rs, server/websocket/src/server.rs, store/postgres/src/deployment_store.rs, store/postgres/src/primary.rs, store/postgres/src/query_store.rs, store/postgres/src/store.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/chain_head.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/test-store/src/store.rs
The store fns `deployment_state` and `query_store` are made async so that we avoid blocking DB queries in the async parts of query execution.
=> Asyncify blocking store operations used in async context

graph/src/data/subgraph/schema.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, tests/integration-tests/non-fatal-errors/package.json, tests/integration-tests/non-fatal-errors/test/test.js
Since https://github.com/graphprotocol/graph-node/pull/2121 we check for errors up to the subgraph current block, but when `insert_subgraph_errors` is called the subgraph pointer hasn't been advanced yet.  So `check_health` needs to be aware of the block it is checking. This slipped through because integration tests are always passing on CI as reported here https://github.com/graphprotocol/graph-node/issues/2159.
=> Fix subgraph unhealthy check

server/websocket/src/connection.rs
This happens sometimes but instead of unwrapping we can let the outer loop detect that the connection was closed an shut things down.
=> Silence panic

.github/workflows/ci.yml
Hopefully, this gets us out of build failures because we run out of disk space
=> github: Do not cache target/

core/src/subgraph/instance_manager.rs, graph/src/components/store.rs, mock/src/store.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/store.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/subgraph.rs
This fixes the `has_non_fatal_errors` check in the case described here https://github.com/graphprotocol/graph-node/pull/2121#issuecomment-767538602.
But unfortunately it means that errors will be recreated upon restart and it will again be hard to tell which errors are new.
=> Delete fatal error on unfail

node/tests/cli.rs
The test function `node_fails_to_start_with_invalid_ipfs` relies on
async and results in variable results, so we are ignoring it for now.
=> node: ignore non-deterministic test

docs/getting-started.md
geth docs have moved from Github wiki to its own site. If you click on current link, it will show you a wiki page with a link to the new docs.
=> Update link to geth docs

graph/src/data/query/result.rs, graph/src/log/elastic.rs, server/http/src/service.rs, server/http/src/test_utils.rs, server/http/tests/response.rs, server/index-node/src/explorer.rs, server/index-node/src/service.rs, server/metrics/src/lib.rs, server/websocket/src/server.rs
Resolves #2193
This PR inserts `Access-Control-Alllow-Origin: *` on all response headers.
Also, all header names were refactored to constants so the type checker can protect us from possible typing mistakes.
=> Add CORS for all HTTP responses

core/src/subgraph/instance_manager.rs
We don't want any errors to be silent in the logs.
=> Log non-fatal errors

graph/src/components/store.rs, store/postgres/src/relational.rs, store/postgres/tests/store.rs
We only pay attention to the EntityType in StoreEvent, but not the entity id or the change operation. This change will significantly reduce the size of notifications that we send.
=> graph, store: Simplify the changes we send with StoreEvent

runtime/wasm/src/to_from/mod.rs
This is clearly deterministic and avoids a panic.
=> Mark utf16 parse error as deterministic

.github/workflows/audit.yml
Until we get it passing again we don't want to be reminded on every PR that it isn't passing.
=> Disable audit on push

Cargo.lock, core/src/subgraph/instance_manager.rs, graph/src/components/ethereum/types.rs, runtime/wasm/src/module/mod.rs, store/postgres/src/relational.rs
Stacktraces look nicer on separate lines, but that messes with how we sort logs based on the id tag. Not sure why this only became a problem now, maybe a slog dependency bump changed something.
Also log block hashes as hex strings.
=> Log subgraph errors in a single line

docker/start
By default, GRAPH_NODE_CONFIG is set but empty, which the start script correctly interprets as to not use a configuration file; but argument parsing inside graph-node still thinks the variable is set. We explicitly unset the variable when running without a configuration file.
Fixes https://github.com/graphprotocol/graph-node/issues/2271
=> docker: Make sure empty GRAPH_NODE_CONFIG does not trip us up

Cargo.lock, node/src/main.rs, node/src/store_builder.rs, store/postgres/Cargo.toml, store/postgres/migrations/2021-03-11-010830_fdw/down.sql, store/postgres/migrations/2021-03-11-010830_fdw/up.sql, store/postgres/src/catalog.rs, store/postgres/src/connection_pool.rs, store/postgres/src/deployment_store.rs, store/postgres/src/notification_listener.rs, store/test-store/src/store.rs
This PR sets up foreign data wrappers for cross-shard communication. For now, this doesn't do much other than expose `deployment_schemas` and `chains` in other shards, but using them will be important for cross-shard grafting and copying which will happen in future PR's.
=> Set up foreign data wrappers for cross-shard communication

docs/environment-variables.md, store/postgres/src/relational.rs
This isn't great since the timeout is set through an environment variable - it would be better to derive it from the overall timeout for GraphQL queries, but that's a little more work.
=> store: Allow enforcing a timeout for SQL queries

runtime/wasm/src/module/mod.rs
This is a strange thing to do anyways and hopefully nobody is doing it and we can quickly remove this. The goal is to make things a bit simpler for multiblockchain if chain specific host exports don't need to worry about being called to initialize a global variable.
The first commit clarifies some outdated comments.
=> Deprecate calling `ethereum.call` to initialize a global

graph/src/log/elastic.rs, graph/src/log/mod.rs, graph/src/log/split.rs
It's already big, but I've seen messages lost due to buffer overflow in the hosted service. Also increase the log level of the ES log count, to see if we are sending requests that are too big.
=> Increase log buffer

chain/ethereum/src/block_ingestor.rs, chain/ethereum/src/ethereum_adapter.rs, graph/src/components/ethereum/adapter.rs, node/src/main.rs, node/src/store_builder.rs, store/postgres/src/block_store.rs, store/postgres/src/chain_store.rs, store/test-store/src/store.rs
Previously, an eth client that would not successfully respond to our `net_version` request (for example, by returning `429 Too Many Requests`) would block the startup of `graph-node` indefinitely. With this PR, if we can not get a valid response within 30s, we continue startup hoping that the `net_version` hasn't changed since the last run. If the misbehaving client is for a new chain, startup will still fail (though much more loudly than before)
This PR also fixes a bug introduced by various refactorings where we would not detect a change in net version because we were checking our database state against our database state ...
=> Make graph-node startup more resilient in the face of misbehaving eth providers

store/postgres/migrations/2021-03-12-014815_subgraph_deployment_pkey/down.sql, store/postgres/migrations/2021-03-12-014815_subgraph_deployment_pkey/up.sql, store/postgres/src/deployment.rs, store/postgres/src/detail.rs
This PR switches the primary key for `subgraph_deployment` to be the same as the pk for `deployment_schemas`. It does the bare minimum necessary to arrange for that in the database, but does not yet contain the code changes required to move away from identifying deployments internally by their IPFS hash. That will come in a future PR.
This PR sits on top of #2267 since manual intervention is needed in the sharded setup in the hosted service between these two PR's.
=> Use a synthetic primary key for subgraph_deployment

NEWS.md, chain/ethereum/src/ethereum_adapter.rs, graph/src/components/ethereum/network.rs, node/src/config.rs, node/src/main.rs
This is necessary support fuse until their OpenEthereum version is updated.
I removed the previous global escape hatch `GRAPH_ETH_CALL_BY_NUMBER` since with OpenEthereum 3.2 released, indexers should now all have access to an EIP-1898 compatible node.
=> Allow network to opt out of eip-1898

core/src/subgraph/instance_manager.rs
We've seen this happen on some chains.
=> Improve error log

graph/src/ipfs_client.rs
This seems necessary for compatibility with the ipfs server on staging.
=> Set content length for empty body

node/src/config.rs
This fixes a mistake in #2328.
=> Disable `no_eip1898` by default

Cargo.lock, graph/Cargo.toml, runtime/wasm/Cargo.toml
Resolves #2325. Fixes the memory leak introduced by wasmtime 0.25.
=> Update wasmtime to 0.26

chain/ethereum/src/ethereum_adapter.rs, tests/tests/common/docker.rs
The old format is not returned by Geth since the Berlin fork. A few subgraphs have hit the `stack limit reached` error, which is deterministic.
=> Drop support for old Geth revert format, detect stack limit

core/src/link_resolver.rs, core/src/subgraph/provider.rs, node/src/main.rs
I believe #2324 accidentally applied infinite retries to the link resolver used by the runtime, this was meant to apply only to the assignment provider.
=> Do not retry `ipfs.cat` indefinitely

core/src/subgraph/instance_manager.rs, core/src/subgraph/registrar.rs, graph/src/lib.rs, graph/src/task_spawn.rs, node/src/main.rs
This issue was introduced when upgrading to tokio 1.0, the `#[tokio::main]` syntax changed and the number of blocking threads was inadvertently lowered from 2000 to the default 512. I was able to reproduce the issue locally. This fixes the root cause which is the incorrect use of the blocking thread pool. At least in the critical locations, we still use it incorrectly in others, #905 tracks getting this right in all places.
There are at least two ways we where using the blocking thread pool incorrectly:
- The code path to start a subgraph had a few nested calls to `spawn_blocking`. This leads to a "double dip" deadlock, the nested calls are waiting on the callers to release a blocking threads, but the callers are of course waiting on the nested call to complete.
- We were using …
=> Fix hanging when starting over 512 subgraphs

core/src/subgraph/instance_manager.rs, docs/environment-variables.md, graph/src/lib.rs, graph/src/task_spawn.rs, node/src/main.rs
On a high load node such as the community nodes, some subgraphs were observed to hang, as if the `run_subgraph` future was never polled again. I was unable to reproduce this locally, it might be some obscure tokio issue caused by changes in https://github.com/graphprotocol/graph-node/pull/2354. So this tries to make things more like they were before the tokio 1.0 upgrade, with a large blocking thread pool and `run_subgraph` executed by `spawn_blocking`.
=> Go back to running subgraphs with `spawn_blocking`

Cargo.lock, core/Cargo.toml, core/src/subgraph/instance_manager.rs, docs/environment-variables.md, graph/src/lib.rs, graph/src/task_spawn.rs, node/src/main.rs
This PR:
1. Reverts #2357, that was being done in lack of a better idea, and this is a better idea.
2. Updates futures 0.1.x from 0.1.30 to [0.1.31](https://github.com/rust-lang/futures-rs/pull/2359), which fixes a potential deadlock in `FuturesUnordered` when combined with the tokio cooperative scheduler, we use `FuturesUnordered` in the block stream so this may be affecting us.
3. While 2 might be sufficient to fix the deadlock, to be sure this disables cooperative scheduling for `run_subgraph`. It's being run in its own thread so there is nothing to gain from cooperative scheduling anyways.
=> Use unconstrained tokio budget for `run_subgraph`.

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/lib.rs, chain/ethereum/src/transport.rs, graph/Cargo.toml, graph/src/components/ethereum/types.rs, node/src/main.rs, runtime/wasm/Cargo.toml
I've rebased web3 to the upstream master in the `leo/test-rebase-upstream-master` branch, if this change is successful that can be made the new master. The primary goal is to have web3 use tokio 1.0, mixing tokio 1.0 with 0.1 might be the potential cause of the deadlocks we're seeing after upgrading to tokio 1.0. Our ethabi patches have been upstreamed (thanks @vkgnosis), so we can switch back to upstream ethabi.
This leaves the jsonrpc server as the only outdated tokio, which is sufficiently isolated to not cause problems.
=> Rebase web3, use upstream ethabi

chain/ethereum/src/block_stream.rs, core/src/subgraph/instance_manager.rs, graph/src/components/ethereum/listener.rs, graph/src/components/ethereum/mod.rs, graph/src/components/ethereum/stream.rs, graph/src/components/store.rs, graph/src/lib.rs, mock/src/block_stream.rs, mock/src/store.rs, store/postgres/src/chain_head_listener.rs, store/postgres/src/chain_store.rs, store/postgres/src/notification_listener.rs, store/postgres/src/store_events.rs
As I've been able to reproduce locally, under a sufficent load of concurrent subgraphs and with many fast networks connected, there is a high probability of the mainnet chain head update being overwritten with that of another network before all subgraphs can read the update, to the point where the subgraphs can seem deadlocked. So this may very well be the cause for the subgraph deadlocks observed in prod.
The important change is in `chain_head_listener.rs`, which now demultiplexes the DB notifications into one watcher per network. This also does a bit of modernizing in `store_events.rs` and `notification_listener.rs` to use more of tokio 1.0 and futures 0.3.
=> chain head listener: Use separate watchers per chain

chain/ethereum/src/block_stream.rs, core/src/subgraph/instance_manager.rs, graph/src/components/ethereum/stream.rs, graph/src/components/store.rs, graph/src/lib.rs, mock/src/block_stream.rs, mock/src/store.rs, store/postgres/src/chain_head_listener.rs, store/postgres/src/chain_store.rs
This is a correction to #2365. There is a race condition in the `else` branch where the watcher could be overwritten, and a subscriber might end up with a receiver that has no sender and would error.
This keeps it simple by using a Mutex, and switching to a sync Mutex since that's what tokio recommends for short critical sections.
=> chain head listener: Fix race condition

graph/src/log/elastic.rs
This was issue was introduced in #2334, where as soon as there are no logs to flush, the log task would end. I don't think this is the end of our logging issues, but it should resolve the memory leak of logs accumulating endlessly.
=> ES: Fix memory leak and logs not flushing

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/lib.rs, chain/ethereum/src/transport.rs, core/src/link_resolver.rs, graph/Cargo.toml, graph/src/components/ethereum/types.rs, node/src/main.rs, runtime/wasm/Cargo.toml
Both this and #2374 were tested in the community nodes and worked ok, so it seems that reverting the web3 update is necessary but reverting the tokio update is not, so we should prefer this over #2374. Also adds an unrelated log to `link_resolver.rs`.
=> Revert web3 update

runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs
Don't know what others think, but the 'start' and 'done' logs are basically redundant, but the 'done' includes the timing so I downgraded the 'start' to trace level. Also the contract call log isn't very useful so I downgraded it to 'trace' as well. The goal is to make logs a bit more scrollable and readable at debug level, which is what the hosted service uses.
=> Downgrade noisy logs to trace

chain/ethereum/src/ethereum_adapter.rs, docs/environment-variables.md
This reduces the default range size to 50, so each request is less likely to timeout, but makes requests in parallel for a potential performance improvement.
=> Parallel trace_filter calls

store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs
This PR chunks the application of entity modifications as an attempt to fix #2330.
Given that the maximum number of PostgreSQL bind parameters per query is 65535, it makes sense to use N chunks where:
chunk size =  65535 / number of fields per entity
Nonetheless, we must remain wary that parameters other than entity fields are also bound in each query, such as block numbers and auxiliary data.
Therefore, it would be reasonable for us to discuss ways to accommodate those extra bindings, probably by reducing `chunk size` by an arbitrary amount.
=> Chunk application of entity modifications

graph/src/components/ethereum/network.rs, node/src/bin/manager.rs, node/src/main.rs, store/postgres/src/block_store.rs
In general, we don't want graphman to use the configured pool size to
reduce the risk of running out of database handles. Instead, `graphman`
uses a pool size of 3 by default for everything which should be plenty for
its purposes
I also tacked a small logging change that should make it easier to understand when we skip creating a block ingestor onto the PR
=> node: Have `graphman` override configured pool sizes

chain/ethereum/src/ethereum_adapter.rs
Resolves #2312. I'd expect some subgraphs to be affected, hopefully the calls will revert and the subgraph will move on. I believe no subgraph included in the testnet is affected because if they were indexers running against Geth would have reported it.
For reference 25 million is twice the gas limit of an Ethereum block, so not a small value.
=> Limit gas of eth_call

docs/subgraph-manifest.md
First PR raised in this project, having read the contribution guidelines and attempts to align to previous PRs and commits as best as I saw from history. Please do let me know if you'd like me to do any further revisions to any part.
I was looking to build and deploy a subgraph for BSC and could not find the network information required for the data source inside the subgraph-manifest docs. I found the information I needed on discord as an adhoc answer to my specfic question, but also wanted to find the source information for the options available. I eventually found this inside https://github.com/graphprotocol/graph-cli/blob/master/src/commands/init.js#L43-L57, which I have linked to in this tiny update. 
I would have loved to have this information easily available, and I am hoping it …
=> docs: Added up to date network options for Ethereum data source

runtime/wasm/src/module/mod.rs
This should fix creating data sources in `ipfs.map`.
=> runtime: enter_handler() in handle_json_callback

graph/src/components/ethereum/types.rs
At `master` this log is like this:
```
Apr 22 09:20:09.150 TRCE Subgraph pointer, number: 12289149, hash: Some(BlockHash([199, 141, 161, 107, 48, 115, 24, 183, 143, 41, 208, 195, 92, 3, 224, 68, 51, 67, 124, 214, 47, 99, 80, 137, 149, 221, 70, 31, 244, 51, 6, 190])), sgd: 52675, subgraph_id: QmZ2xEvr9MtPAGjuUQehKbGTo5178VhuQQpCjh7okdt8xr, component: SubgraphInstanceManager > BlockStream
```
It was using hex format before, we should go back to it. This happened because of [this change](https://github.com/graphprotocol/graph-node/commit/70f33788d64b15ca93e513651676a59477d282e2#diff-6169304ef93f023c417eb[…]61d35214ab9f8106c5b9ee1R417).
To fix the problem I've changed so we use the `Display` implementation instead of the `Debug` one, that's defined …
=> chains: change ethereum BlockHash logs back to hex format

store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/primary.rs, store/postgres/src/relational.rs, store/postgres/src/subgraph_store.rs
We were filtering out inactive instances because that's what we look at for
deployment status, but for locators, we need to consider active and
inactive instances of a deployment.
=> store: Make sure SubgraphStore.locators returns all deployment instances

node/src/bin/manager.rs, node/src/manager/commands/mod.rs, node/src/manager/commands/query.rs, node/src/manager/mod.rs
This makes it possible to execute a GraphQL query with
```
graphman query sub/graph '{ .. GraphQL .. }' var1=val1 ...
```
By passing `GRAPH_LOG_QUERY_TIMING=gql,sql GRAPH_LOG=debug` in the environment, the command will log a lot of info about query execution.
For now, it's probably best to not run this against production directly though. Amongst other things, the code sets up notification listeners as a side-effect of creating the store.
=> node: Add `graphman query`

chain/ethereum/src/block_ingestor.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/lib.rs, graph/src/blockchain/block_ingestor.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/mod.rs, graph/src/components/ethereum/adapter.rs, graph/src/components/ethereum/mod.rs, graph/src/components/ethereum/types.rs, graph/src/components/store.rs, graph/src/data/store/scalar.rs, graph/src/lib.rs, mock/src/store.rs, node/src/config.rs, node/src/main.rs, store/postgres/src/chain_store.rs, store/postgres/tests/chain_head.rs, store/postgres/tests/store.rs
This PR started out as a simple refactor of some ingestion logic, but now has the code to make block ingestion independent of Ethereum by introducing an `IngestorAdapter`.
This is what I had to say on the initial PR:
The code looked like we could try to find multiple missing ancestors for a  chain head candidate. But the logic of a chain dictates that we can only    ever find one block that we are missing when checking whether we have a    long enough chain in our database. Therefore, the vecs of missing parents    that we were passing around could only ever contain 0 or 1 element.
The code now clearly spells out that we will only ever know about one    missing parent at a time.
=> Make the BlockIngestor independent from Ethereum (was: Simplify ingestion logic)

core/tests/interfaces.rs, graph/src/data/store/mod.rs, graph/src/runtime/asc_heap.rs, graphql/tests/query.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/to_from/external.rs, runtime/wasm/src/to_from/mod.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs, store/test-store/src/store.rs
Currently they are passed in the random order given by the hash map. Remove `Deref` and `DerefMut` from `Entity` to prevent bugs like this.
=> Serialize entity fields in defined order

node/src/bin/manager.rs, node/src/manager/commands/create.rs, node/src/manager/commands/mod.rs
This is the same as the `subgraph_create` json rpc call.
=> graphman: Add `graphman create`

graph/src/log/mod.rs, graph/src/util/timed_rw_lock.rs
These `unwrap_or`s will allocate a String even when they're not needed. They were replaced by methods that only allocate the strings if necessary
=> graph: Replace unwrap_or by lazily evaluated counterparts

graph/src/data/graphql/ext.rs, graph/src/data/schema.rs, graph/src/log/mod.rs, graph/src/util/cache_weight.rs
I guess this is a personal preference but I feel like using `is_empty()` is 'clearer' than comparing `.len()` to zero
=> graph: Replace .len() comparisons with zero with .is_empty()

graph/src/data/graphql/ext.rs, graph/src/data/graphql/values.rs, graph/src/data/schema.rs, graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/query/ast.rs, graphql/src/schema/api.rs, graphql/src/schema/ast.rs, graphql/src/store/prefetch.rs, graphql/src/store/query.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/src/values/coercion.rs, graphql/tests/introspection.rs, server/index-node/src/resolver.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
This PR replaces graph-node's usage of `&String` with `&str`
`&str` is preferable since it allows for more generic code, removing the need of the argument to be allocated on the heap (e.g., can remove the several instances of `&"some-term".to_string()` from the code, probably increasing performance).
This new change also removes a layer of indirection since you no longer need to deref `&String` to get a `String` and then deref that to get a `&str`
[Related Clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg)
P.S.: this is the same as #2426 but with a cleaner git history
=> graph, graphql, store, server: Replace &String by &str

Cargo.lock, chain/ethereum/Cargo.toml, graph/Cargo.toml
The `data-source-revert` integration test wasn't really doing what it should, the feature wasn't set so the `failpoints!` macro was a noop.
=> Fix failpoints

chain/ethereum/src/chain.rs, graph/src/runtime/asc_heap.rs, graph/src/runtime/asc_ptr.rs, graph/src/runtime/mod.rs, runtime/derive/src/lib.rs, runtime/wasm/src/asc_abi/class.rs
This will work better for multiblockchain.
=> runtime: Make `to_asc_bytes` take `self` instead of `&self`

graph/src/runtime/asc_heap.rs, runtime/wasm/src/module/mod.rs
Since `api_version` defines the AS serialization format, having this in AscHeap will be convenient.
=> Add `fn api_version` to `AscHeap`

chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/block_stream.rs
Trigger filters grow with the number of dynamic data sources, so they can become large data structures. Some clones are hard to avoid, but this PR handles some easy cases. Ultimately these filters need to be written to a network request so there will always be at least that allocation, so I wouldn't be too concerned about the remaining clones unless we can measure the impact.
=> block stream: Less trigger filter cloning

core/src/subgraph/instance.rs, graph/src/blockchain/mod.rs, graph/src/components/ethereum/types.rs, graph/src/components/subgraph/host.rs, graph/src/data/subgraph/data_source.rs, runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/mapping.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs
This allows replacing the full block in `MappingContext` with just a `BlockPtr` which is a nice simplification.
=> Put the block for triggers in the trigger itself

node/src/main.rs
The thing is that `net_identifiers` will retry forever. So even if it tries 15 times and returns an error every time, it will continue retrying until the outer timeout is hit, so we will try to use the provider even if it is evidently defective. @lutter interested to know if you have a better solution for this.
=> Consider providers that timeout as broken

runtime/wasm/src/module/mod.rs
Wasmtime now has a safe memory API.
=> runtime: Remove outdated comment

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/data_source.rs, chain/ethereum/src/lib.rs, chain/ethereum/src/network_indexer/subgraph.rs, core/src/subgraph/instance.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/loader.rs, core/src/subgraph/registrar.rs, graph/Cargo.toml, graph/src/blockchain/mod.rs, graph/src/components/store.rs, graph/src/components/subgraph/host.rs, graph/src/data/subgraph/mod.rs, graph/src/data/subgraph/schema.rs, graph/src/lib.rs, graph/tests/manifest.rs, graphql/Cargo.toml, graphql/tests/query.rs, runtime/wasm/src/host.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/test.rs, store/postgres/tests/graft.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/test-store/Cargo.toml, store/test-store/src/store.rs
This does the minimal necessary to move the module `graph/src/data/subgraph/data_source.rs` to `chain/ethereum/src/data_source.rs`, which unblocks other refactorings. There are still a lot of Ethereum dependencies in the manifest data structures.
=> Move the `DataSource` type from `graph` to `ethereum`

Cargo.lock, Cargo.toml, chain/ethereum/src/chain.rs, graph/src/runtime/asc_ptr.rs, graph/src/runtime/mod.rs, runtime/derive/Cargo.toml, runtime/derive/src/lib.rs, runtime/wasm/src/asc_abi/class.rs, runtime/wasm/src/module/test/abi.rs
I've done some simple fixes as well as removing the generic type parameter.
One of them is to rollback this PR: https://github.com/graphprotocol/graph-node/pull/2457
This is being done so that its a bit easier to do the AssemblyScript update (that I'm working on).
=> Remove generic type parameter from ArrayBuffer

node/src/main.rs
We weren't sorting them at all, so `cheapest` was selecting the first adapter, not the cheapest adapter. See also #2466 which I've found out about.
=> Sort network adapters

chain/ethereum/tests/triggers.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/mod.rs, graph/src/components/ethereum/types.rs
The call to `sort()` was lost when refactoring from `EthereumBlockWithTriggers` to `BlockWithTriggers`.
=> Fix trigger ordering

store/postgres/migrations/2021-05-21-165219_add_created_at_columns_for_deployment_schemas/down.sql, store/postgres/migrations/2021-05-21-165219_add_created_at_columns_for_deployment_schemas/up.sql, store/postgres/src/primary.rs
=> Add timestamps for deployment_schemas and unused_deployments tables

store/postgres/src/dynds.rs
This is called on every `apply_entity_modifications`, and I believe even if empty diesel will still generate trivial SQL for the DB to execute.
=> Dont try to insert 0 ddses

Cargo.lock, chain/ethereum/tests/manifest.rs, graph/Cargo.toml
Having it in the graph crate requires that to depend on chain, which it
shouldn't and causes a lot of headaches.
=> chain, graph: Move manifest tests to chain crate

graph/src/runtime/asc_heap.rs, graph/src/runtime/asc_ptr.rs, graph/src/runtime/mod.rs, runtime/wasm/src/asc_abi/class.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/test.rs, runtime/wasm/src/module/test/abi.rs, runtime/wasm/src/to_from/external.rs, runtime/wasm/src/to_from/mod.rs
By moving `try_asc_get`, `asc_get` and `asc_new` out of the trait.
The only real change is in `graph/src/runtime/asc_heap.rs`, the rest is just mechanical refactoring from the fallout.
=> Make `AscHeap` dyn-safe

runtime/wasm/src/host_exports.rs
Truncating utf-8 is tricky! But this is a panic-free way to do it.
=> runtime: Fix string truncation

chain/ethereum/src/data_source.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/tests/network_indexer.rs, graph/src/components/ethereum/types.rs, store/postgres/src/chain_store.rs
In #2482 performance regressed due to [this](https://github.com/graphprotocol/graph-node/blob/2abd2f3626ea570d8b213cd4cc9ebebdbae13256/chain/ethereum/src/data_source.rs#L49), the `light_block()` call would actually clone the entire block, and we went from doing that once per block per subgraph, to once trigger per subgraph.
In this PR the block is wrapped in an Arc so no deep cloning is necessary at all, making for a performance gain relative to pre-#2482.
=> Wrap 'LightEthereumBlock' in an Arc

node/src/bin/manager.rs, node/src/manager/commands/mod.rs, node/src/manager/commands/stats.rs, store/postgres/examples/layout.rs, store/postgres/migrations/2021-06-01-222649_create_stats/down.sql, store/postgres/migrations/2021-06-01-222649_create_stats/up.sql, store/postgres/src/catalog.rs, store/postgres/src/deployment_store.rs, store/postgres/src/lib.rs, store/postgres/src/primary.rs, store/postgres/src/relational.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/relational.rs
With these changes, which tables are 'account like' is set through a database table, and the corresponding information is refreshed every 5 minutes, making it possible to change query behavior without restarting query nodes.
A future enhancement would be to gather information about which tables are 'account like', i.e., with a high ratio of entity versions to entities automatically, and base the decision on that data. Gathering this data isn't entirely trivial, and is therefore left out of this PR.
=> Control which tables are 'account like' without query node restarts

chain/ethereum/tests/manifest.rs, chain/ethereum/tests/network_indexer.rs, graphql/tests/query.rs, store/postgres/tests/chain_head.rs, store/postgres/tests/graft.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/test-store/src/store.rs
We used the `STORE_RUNTIME` to both force tests to run sequentially, and to run async tasks. That created a chicken-and-egg problem where setting up the store in `test-store` would deadlock during a test. Tests sidestepped that by causing store setup to run before locking the `STORE_RUNTIME`, but that meant that each test could hold a connection while waiting to get the `STORE_RUNTIME`, exhausting the connection pool and ultimately deadlocking the tests; an unnerving experience since it's never clear whether new code or the test harness causes such deadlocks.
This PR separates using the runtime and running tests sequentially by using a standalone lock; for this to work, it was necessary to switch to the threaded scheduler.
It is now possible to run the tests with a pool as small as 5 …
=> Change how tests ensure that store tests run sequentially

store/postgres/src/chain_store.rs
Profiling data suggests that for busy chains with lots of subgraphs indexing the same contracts, inserting new calls can take 300-400ms because all the conflicting inserts need to wait for locks to do the update. With this change, updates are performed at most once a day which should reduce the amount of time indexing has to wait for these cache operations.
This only changes things for per-chain call caches, not for a shared call cache. If this proves to be effective, we'll figure out the diesel gyrations to make that work in that case, too.
=> store: Avoid unnecessary updates in call_meta

chain/ethereum/src/ethereum_adapter.rs
This is an useful log and it's already at `trace` level, no need for an additional env var.
=> Unconditionally log eth_call details

core/src/link_resolver.rs, docs/environment-variables.md
To avoid hitting external timeouts from gateways, since we rely on timing out on our side to detect a missing file.
=> ipfs: Lower default timeout

NEWS.md, README.md, docker/Dockerfile, store/postgres/src/subgraph_store.rs
They got broken in https://github.com/graphprotocol/graph-node/pull/2576 when sharding.md was renamed to config.md. Also formats the Dockerfile. Resolves #2582.
=> docs: Fix config.md links

core/src/subgraph/instance_manager.rs, core/src/subgraph/registrar.rs, docs/environment-variables.md
#2556 didn't get it right, because in `instance_manager.rs` we were still requesting infinite retries for ipfs.cat. Also we had two different env vars for the IPFS timeout which confused me, I think we can do with just one.
=> Fix ipfs timeout detection

chain/ethereum/src/lib.rs, chain/ethereum/src/runtime/abi.rs, chain/ethereum/src/runtime/mod.rs, runtime/wasm/src/asc_abi/class.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/lib.rs, runtime/wasm/src/mapping.rs, runtime/wasm/src/module/into_wasm_ret.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/module/stopwatch.rs
As per work being done for the development of a subgraph unit testing framework, we need to be able to access fields form graph-node, which are currently private/package private. This PR aims to make those public.
PS I know it's a lot of commits (sorry, needed to commit in order to test), whoever merges it - be sure to squash and merge.
=> Making structs, functions and fields public to be used in testing framework

core/src/subgraph/instance_manager.rs, graph/src/components/store.rs, graphql/src/execution/resolver.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/tests/query.rs, store/postgres/src/deployment_store.rs, store/postgres/src/query_store.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/store.rs
We noticed that if one DB shard is overloaded, that causes contention in the query nodes' non-blocking tokio threadpool. This is likely caused by a blocking DB operation being done in an async context in the query execution path. The only case I could find of this was in `throttle_while_syncing` for subscriptions, the solution was to asyncify the `is_deployment_synced` store operation.
To facilitate this change, the first commit checks the synced status for subscription throttling only when the subscription is first created. Hopefully this is ok.
=> Asyncify is_deployment_synced

core/tests/interfaces.rs, graph/src/data/query/error.rs, graphql/src/execution/query.rs
A few changes to improve guarding against overflows:
- Explicitly validate against cyclical fragments.
- Validate complexity before fields.
- Validate query depth even if the complexity is unlimited.
- Add a test that previously caused a stack overflow.
=> Improve query validation robustness

NEWS.md, graph/src/components/graphql.rs, graph/src/components/store.rs, graph/src/data/graphql/effort.rs, graph/src/util/stats.rs, graphql/src/execution/execution.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, node/src/bin/manager.rs, node/src/main.rs, server/index-node/src/resolver.rs, store/postgres/src/block_store.rs, store/postgres/src/connection_pool.rs, store/postgres/src/deployment_store.rs, store/postgres/src/query_store.rs, store/postgres/src/store.rs, store/test-store/src/store.rs
This moves the query semaphore implementation from the `LoadManager` to the per-shard (or replica) `ConnectionPool`s, with a capacity equal to the shard's (or replica's) connection pool size. It is accessed through the resolver. The indexing status queries are now also guarded by the primary shard semaphore.
=> Revamp query semaphore to be by shard

chain/ethereum/src/runtime/abi.rs, chain/ethereum/src/trigger.rs
For clarity this renames `AscEthereumTransaction` to `AscEthereumTransaction_0_0_1`. The actual fix is to switch `AscEthereumCall_0_0_3` to use `AscEthereumTransaction_0_0_2`.
=> ethereum: Fix accessing call handler transaction input

Cargo.lock, chain/ethereum/src/chain.rs, core/src/subgraph/instance_manager.rs, graph/Cargo.toml, graph/src/blockchain/block_stream.rs, graph/src/blockchain/mod.rs, graph/src/data/subgraph/mod.rs
=> Prohibit subgraphs from using different api_versions

NEWS.md, chain/ethereum/src/data_source.rs
This is a nicely written log, but for some subgraphs it logs too often during normal execution. In the hosted service, this logs thousands of times per second!
=> ethereum: Downgrade spammy log to trace

chain/ethereum/src/runtime/abi.rs, chain/ethereum/src/trigger.rs
It was never the gas used, which is in the receipt not the transaction.
=> Rename gas used to gas limit

chain/ethereum/src/data_source.rs, core/src/subgraph/instance_manager.rs
Since #2618 these are unnecessary.
=> ethereum: Cleanup needless associated type bounds

graph/src/components/metrics/stopwatch.rs, store/postgres/src/subgraph_store.rs
We've seen subgraphs take a lot of time in the `transact_block` section, this will break it down further.
=> stopwatch: Add send_store_event section

chain/ethereum/src/data_source.rs, chain/ethereum/src/runtime/runtime_adapter.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/mod.rs, graph/src/data/subgraph/mod.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs
`Source` is an Ethereum-specific type. It's still used in more places than we'd like, but this is a start.
=> blockchain: Remove `DataSource::source`

chain/ethereum/src/adapter.rs, chain/ethereum/src/capabilities.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/lib.rs, chain/ethereum/src/network.rs, chain/ethereum/src/runtime/runtime_adapter.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/mod.rs, graph/src/components/ethereum/mod.rs, graph/src/data/subgraph/mod.rs, graph/src/log/mod.rs, node/src/config.rs, node/src/main.rs
This removes the last case in which the instance manager was constraining an associated type of `Blockchain` to something ethereum specific. Also removes `Blockchain::Manifest` since I think we'll keep the manifest as a shared structure.
=> multichain: Abstract NodeCapabilities

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/mod.rs, graph/src/components/ethereum/mod.rs, graph/src/components/ethereum/types.rs, graph/src/components/mod.rs, graph/src/components/store.rs, graph/src/components/transaction_receipt.rs, graph/src/data/subgraph/mod.rs, graph/src/lib.rs, mock/src/store.rs, store/postgres/migrations/2021-06-14-201635_add_ethereum_hex_to_bytea_function/down.sql, store/postgres/migrations/2021-06-14-201635_add_ethereum_hex_to_bytea_function/up.sql, store/postgres/src/chain_store.rs
Resolves #2409
This PR adds a verification step to call-handler execution that filters off traces with failed transactions.
For **non-final blocks**, we determine failure by inspecting each transaction receipt and gas usage, which are already present in program memory, so it should be fast. 
For **final blocks**, we search the database once for each block. If that data is absent, we call an external API once for each transaction receipt.
=> Prevent handling triggers for failed transactions

store/postgres/migrations/2021-06-14-201635_add_ethereum_hex_to_bytea_function/up.sql
The previous function, `starts_with` didn't exist in Postgres 9.6 version.
This fix uses the `substring` function for the same effect.
=> store, migration: Use a different functon that works in PSQL 9.6

graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/schema/api.rs, graphql/src/schema/ast.rs
Fixes #2652
There's currently a redundant implementation for `get_named_type`:
https://github.com/graphprotocol/graph-node/blob/42bd19e47a94d9900b4fdb18619f69482003543a/graph/src/data/graphql/ext.rs#L169-L184
https://github.com/graphprotocol/graph-node/blob/42bd19e47a94d9900b4fdb18619f69482003543a/graphql/src/schema/ast.rs#L169-L185
There's also a third `get_named_type` in `graphql/src/execution/execution.rs`: 
https://github.com/graphprotocol/graph-node/blob/42bd19e47a94d9900b4fdb18619f69482003543a/graphql/src/execution/execution.rs#L236-L242
This one _has been kept_, as well as references to it, as to still allow for look-ups into the introspection document.
Usages of the removed `get_named_type` function were replaced
=> graphql: remove duplication of `get_named_type`

graph/src/data/graphql/ext.rs, graph/src/data/schema.rs, graphql/src/introspection/resolver.rs, graphql/src/schema/api.rs, graphql/src/schema/ast.rs
Closes #2498
Validates usage of reserved types in `Schema::validate`, aiming to provide clearer error messages when an input schema uses said types. Adds a new variant to `SchemaValidationError`.
There's also been changes to `DocumentExt` and `ast.rs`:
* `get_object_type_definitions` in `ast.rs` was duplicated and removed in favour of `Document`'s implementation of `get_object_type_definitions`
* `get_interface_type_definitions` was added to `DocumentExt` and removed from `ast.rs`
=>  graph: check usage of reserved types on `Schema::validate`

Cargo.lock, graph/Cargo.toml
When starting a lot of subgraphs graph-node will make thousands of IPFS requests in parallel, which can overload the DNS server. Trust DNS is a rust implementation of a DNS client, and it will cache requests by default.
=> Enable trust-dns for dns caching

Cargo.lock, chain/ethereum/src/network_indexer/mod.rs
Updating for https://github.com/graphprotocol/rust-web3/pull/6.
=> ethereum: Update rev of the ethereum fork

chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, server/http/tests/server.rs
As it turns out, the optimization in https://github.com/graphprotocol/graph-node/pull/1477 was incorrect wrt reverts.
The block stream relies on this function to check with the Ethereum node if a block is on the main chain, but it is assuming that the block being checked is final if it is past the reorg threshold. If the current subgraph head is in the cache when passed into `is_on_main_chain`, as long as it is present in the block cache it will be assumed to be final, which can lead to it not being reverted when it should be.
The most likely way for this bug to affect a subgraph is if a large reorg happens, such that by the time the last blocks are having the reorg processed by graph node they have fallen out of the threshold and are passed into `is_on_main_chain` and considered final. …
=> ethereum: Don't use cached block on `is_on_main_chain`

store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs
This reduces one roundtrip to the DB when transacting a block by leveraging the `forward_block_ptr` where clause to check for duplicate block processing. Part of #2649.
=> Optimize duplicate block processing error check

chain/ethereum/src/chain.rs, chain/ethereum/src/data_source.rs, chain/ethereum/src/ethereum_adapter.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/mod.rs
Celo has special events that have the transaction hash == block hash and are returned from eth_getLogs but not included as transaction receipts. See code comments for details.
Closes #2648. Closes #2353.
=> ethereum: Support Celo block reward events

chain/ethereum/src/runtime/mod.rs, chain/ethereum/src/runtime/runtime_adapter.rs, runtime/test/Cargo.toml, runtime/test/src/common.rs, runtime/test/src/lib.rs, runtime/test/src/test.rs, runtime/test/src/test/abi.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs
We need these fields, functions and the whole test crate to be public in order to reuse as much as possible in the [unit testing framework](https://github.com/LimeChain/matchstick).
PS I know there's lots of commits 😢  If you guys can do "Squash and merge" upon merging that'll be awesome.
=> Create public common module in test crate

graph/src/data/subgraph/mod.rs
This error message is currently being displayed with a line break:
```
Failed to deploy to Graph node http://127.0.0.1:8020/: subgraph resolve error: resolve error: This Graph Node only supports manifest spec versions between 0.0.2 and 0.0.3,
but subgraph `QmNj41SDq75ryMGvjpCSTARvXNNGRPEoWg9RwWiZiawxc9` uses `0.0.4`
^^^^^^^^^^^^^^^^^^^^
```
This PR fixes it.
=> Quick fix: Unintend line break in error message

chain/ethereum/src/chain.rs, graph/src/blockchain/mod.rs
This is not currently being used and I don't anticipate that it will be needed. Anyways it can always be re-added if necessary.
=> Remove Blockchain::reorg_threshold

node/src/config.rs, node/src/main.rs
(and made Provide a little bit more extensible along the way)
There is a backward compatible handling of config that at some point should be converted to the new syntax form. The new syntax form is
```toml
[chains]
[chains.ropsten]
provider = [
{ label = "firehose", details = { type = "web3", transport = "rpc", url = "https://ropsten.sf.io/rpc", features = [] } },
]
```
While a Firehose provider now looks like:
```toml
[chains]
[chains.ropsten]
provider = [
{ label = "firehose", details = { type = "firehose", url = "https://ropsten.streamingfast.io" } },
]
```
This is for now undocumented and is first step towards Firehose integration in the codebase directly.
=> node: Refactor config to accept Firehose provider 

tests/integration-tests/api-version-v0-0-4/package.json, tests/integration-tests/data-source-context/package.json, tests/integration-tests/data-source-revert/package.json, tests/integration-tests/fatal-error/package.json, tests/integration-tests/ganache-reverts/package.json, tests/integration-tests/host-exports/package.json, tests/integration-tests/non-fatal-errors/package.json, tests/integration-tests/overloaded-contract-functions/package.json, tests/integration-tests/package.json, tests/integration-tests/remove-then-update/package.json, tests/integration-tests/value-roundtrip/package.json, tests/integration-tests/yarn.lock
This PR removes the dangling references from the AssemblyScript update.
For most of the integration tests, we want to point to the `master` branch of `graph-cli` and `graph-ts`. Only for the `api-version-v0-0-4` we need to point to an older version than `0.22.0` because of the AssemblyScript breaking changes.
Also `graph-cli` needs a new flag from version `0.21.0` and beyond, `--version-label`, so this has been added as well.
=> integration-tests: Update graph-cli and graph-ts references

node/src/config.rs, node/src/main.rs
This reverts commit 1415d5b4742942da6a546cd9321d494d95d82500 due to backwards compatibility issues. Namely existing configurations were crashing with:
```
configuration error: missing field `transport` for key `chains`
```
=> Revert node: Refactor config to accept Firehose providers

graph/src/data/subgraph/mod.rs, tests/tests/parallel_tests.rs
This should be merged after both:
- https://github.com/graphprotocol/graph-cli/pull/690
- https://github.com/graphprotocol/graph-ts/pull/185
=> graph: Bump default max api version

node/resources/tests/full_config.toml, node/src/config.rs, node/src/main.rs
**Re-submit of #2647**
There is a backward compatible handling of config that at some point should be converted to the new syntax form. The new syntax form is
```
{ label = "node0", details = { type = "web3", transport = "rpc", url = "...", features = [...] } }
```
While a Firehose provider now looks like:
```
{ label = "firehose0", details = { type = "firehose", url = "..." } }
```
This is for now undocumented and is first step towards Firehose integration in the codebase directly.
The `transport` has been fixed to be optional.
=> node: Refactor config to accept Firehose providers 

core/src/subgraph/registrar.rs, graph/src/data/store/mod.rs
While doing some development, I had a misconfiguration where my `node_id` was not in sync with my configuration file.
This led to a deployment to be immediately removed on the receiving node leading to the deployment not starting.
To alleviate that problem a bit, I added some log lines that should make it clearer about what is happening and more especially why it's happening.
I choose to go with `debug` level but willing to switch to a `trace` level if you think it would be more appropriate.
=> Added tracing logs when a giving deployment is assigned/not assigned

docs/environment-variables.md, runtime/wasm/src/mapping.rs
Just an environment variable to set the maximum stack size for the WASM runtime.
If not set, the default is 512KiB, half of what it was before (default from `wasmtime` crate was 1MiB).
=> runtime: Add env var for maximum stack size

store/postgres/src/transaction_receipt.rs
This fixes a bug introduced in PR #2708 that led PostgreSQL to quote the `"public.ethereum_blocks"` table and ignore its namespace, treating its fully qualified name as a single string.
=> Use push_sql instead of push_identifier

core/src/subgraph/instance_manager.rs, graph/src/blockchain/block_stream.rs, graph/src/components/store.rs, store/postgres/src/subgraph_store.rs
That makes it possible to distinguish between failed and not-failed subgraphs in Prometheus
=> Add a 'deployment_failed' metric

chain/ethereum/src/chain.rs, chain/ethereum/tests/manifest.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/registrar.rs, graph/src/blockchain/mod.rs, graph/src/data/query/error.rs, graph/src/data/subgraph/mod.rs, node/src/main.rs, server/index-node/src/resolver.rs
This introduces the `BlockchainMap` in which `Blockchain` instances are stored, keyed by their `BlockchainKind` and network. This is used in the entry points that need to call functions which are generic on `C: Blockchain`, which are: `InstanceManager::start_subgraph`, `SubgraphRegistrar::create_subgraph` and `IndexNodeResolver::resolve_subgraph_features`.
Part of #2732.
=> blockchain: Introduce `BlockchainMap` and `BlockchainKind`

store/postgres/src/transaction_receipt.rs
I'm writing a follow up PR with tests for that query.
=> Hotfix: Fix typo in sql query when fetching transaction receipts

store/postgres/src/chain_head_listener.rs
In hosted a subgraph was observed to hang in `new_block_stream`, which could mean hanging in `ChainHeadListener::subscribe`, so this lock might be involved. This switches the Mutex to an RwLock which will only see write locks when the networks are first inserted, so it practically removes contention. This should at least reduce the impact of a task hanging while holding the lock. The implementation is basically what it was before #2366, but being mindful of race conditions.
=> chain head listener: Reduce locking

store/postgres/src/connection_pool.rs
This introduces two new environment variables that allow setting the
minimum number of idle connections and the timeout when a connection is
considered idle. If the variables are not set, the behavior defaults to the
current behavior of keeping all connections and never reaping idle ones,
and an idle timeout of 10 minutes.
=> store: Allow setting min_idle and idle_timeout

chain/ethereum/src/ethereum_adapter.rs
Previously if `GETH_ETH_CALL_ERRORS_ENV` is not set, then any error returned from eth_call would be considered deterministic. This is because calling `split` on an empty string returns `[""]`, not `[]` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2909ff731dc3a055983463cfe619f8ff)), and all strings contain `""`. This affects release 0.24 and can cause subgraph failures on subgraphs using contract calls, and most severely incorrect data on subgraphs using `try_` calls, which would return a `reverted` result when it fact it was a spurious error.
This did not affect the hosted service because it has `GETH_ETH_CALL_ERRORS_ENV` set to `"out of gas"`.
=> ethereum: fix GETH_ETH_CALL_ERRORS_ENV

docs/environment-variables.md, store/postgres/src/subgraph_store.rs
The notifications we send when transacting entity changes are only needed
for updating GraphQL subscriptions. When that is not needed, disabling
these notifications will reduce the load on Postgres' message queue
=> store: Allow disabling some notifications

chain/ethereum/tests/manifest.rs, core/src/subgraph/registrar.rs, graph/src/data/subgraph/mod.rs, server/index-node/src/resolver.rs
-------
This PR adds a flag parameter to the `UnvalidatedSubgraphManifest::validate` function to skip graft base validation. At the moment, this will only be used by the feature detection GraphqQL endpoint to statically validate a manifest so it can properly inspect its features.
=> Optionally validate subgraph graft base

.github/workflows/ci.yml, Cargo.toml, chain/ethereum/build.rs
Fixes a couple of issues falling out from https://github.com/graphprotocol/graph-node/pull/2716. One is the build failing with incremental compilation, which is fixed by disabling that. The other is having rustfmt as a build-time dependency, which is failing the docker build, this is worked around by formatting the tonic generated file only in debug builds.
=> build: Fix issues post-firehose

chain/ethereum/build.rs, docker/Dockerfile, graph/build.rs
This fixes two small things:
* only regenerate protobuf definitions if the `.proto` files have changed
* install `rustfmt` in the docker build container so docker builds work again
=> Small fixes around protobuf generation

chain/ethereum/src/capabilities.rs, chain/ethereum/src/data_source.rs, graph/src/data/subgraph/mod.rs, graph/src/log/mod.rs, node/src/config.rs, runtime/wasm/src/to_from/mod.rs, server/websocket/src/server.rs, store/postgres/src/catalog.rs, store/postgres/src/relational.rs
Continuation of #2816
As previously discussed with @otaviopace,  I believe that having Clippy run as a continue-on-error step on CI could prove quite beneficial.
In order for something like that to happen, we have to fix the present Clippy warnings/errors first. 
This PR is the third in a series of low-hanging fruits that we can pick through `cargo clippy --fix` alone (lints deemed machine-applicable).
This one solves instances of [single_char_pattern](https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern)
=> clippy: single-character string constant used as pattern

chain/ethereum/src/adapter.rs, chain/ethereum/src/network_indexer/network_indexer.rs, graph/examples/stress.rs, graph/src/blockchain/firehose_block_stream.rs, graphql/src/execution/execution.rs, graphql/src/store/prefetch.rs, graphql/src/store/resolver.rs, mock/src/metrics_registry.rs, runtime/wasm/src/module/stopwatch.rs, server/index-node/src/explorer.rs, store/postgres/src/block_store.rs, store/postgres/src/relational.rs
As previously discussed with @otaviopace,  I believe that having Clippy run as a continue-on-error step on CI could prove quite beneficial.
In order for something like that to happen, we have to fix the present Clippy warnings/errors first. 
This PR is the first of a series of low-hanging fruits that we can pick through `cargo clippy --fix` alone (lints deemed machine-applicable).
This one solves instances of [needless_return](https://rust-lang.github.io/rust-clippy/master/index.html#needless_return)
=> clippy: unneeded `return` statement

chain/ethereum/src/adapter.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/network.rs, chain/ethereum/src/runtime/runtime_adapter.rs, chain/ethereum/tests/network_indexer.rs, core/src/link_resolver.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/data/graphql/effort.rs, graphql/src/execution/execution.rs, graphql/src/execution/query.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, graphql/src/values/coercion.rs, node/src/config.rs, node/src/manager/commands/copy.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/mapping.rs, server/http/src/service.rs, store/postgres/src/deployment_store.rs, store/postgres/src/primary.rs, store/postgres/src/relational.rs, store/postgres/tests/chain_head.rs, store/postgres/tests/relational.rs, tests/tests/common/helpers.rs
Continuation of #2816
As previously discussed with @otaviopace,  I believe that having Clippy run as a continue-on-error step on CI could prove quite beneficial.
In order for something like that to happen, we have to fix the present Clippy warnings/errors first. 
This PR is the second in a series of low-hanging fruits that we can pick through `cargo clippy --fix` alone (lints deemed machine-applicable).
This one solves instances of [clone_on_copy](https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy)
=> clippy: using `clone` on type that implements the `Copy` trait

graph/src/task_spawn.rs, store/postgres/src/notification_listener.rs
This will prevent the notification listener from blocking forever and letting the PG queue fill up. The timeout is large so the queue might still fill up, but at least we have a log to inform further debugging.
=> store: DB notification timeout

core/src/metrics/registry.rs, graph/src/components/metrics/mod.rs, mock/src/metrics_registry.rs, node/src/bin/manager.rs, node/src/main.rs, node/src/store_builder.rs, store/postgres/src/block_store.rs, store/postgres/src/chain_head_listener.rs, store/postgres/src/functions.rs, store/postgres/src/jobs.rs, store/postgres/src/lib.rs, store/postgres/src/notification_listener.rs, store/postgres/src/primary.rs, store/postgres/src/store_events.rs, store/postgres/src/subgraph_store.rs
This adds the following metrics to help monitor the Postgres notification queue:
* `notification_queue_usage`: gauge between 0 and 1 that shows the result of `pg_notification_queue_usage()`, updated every minute
* `notification_queue_sent`: counter (labeled with channel and network) for the number of messages sent; for the `store_events` channel, the network is `none`
* `notification_queue_recvd`: counter (labeled with channel and network) for the number of messages received; for the `store_events` channel, the network is `none`
=> Add Prometheus metrics to monitor the notification queue

graph/src/components/store.rs, server/index-node/src/explorer.rs, store/postgres/src/primary.rs, store/postgres/src/store.rs, store/postgres/src/subgraph_store.rs
This PR adds a new explorer HTTP endpoint for querying deployments for a given subgraph Qm-hash.  
The route is: `/explorer/deployments-for-subgraph/<Qm-hash`.
For example, the following request
```
HTTP GET host:8030/explorer/deployments-for-subgraph/QmTKXLEdMD6Vq7Nwxo8XAfnHpG6H1TzL1AGwiqLpoae3Pb
```
would be responded with a list of all subgraph names and their versions _(`current`, `pending` or `unused`)_ for that subgraph identifier:
```json
[
{
"name": "subgraph/name",
"version": "current"
}, 
{
"name": "another-subgraph/name",
"version": "pending"
}
]
```
=> Add `subgraphs-for-deployment` explorer route

graph/src/blockchain/firehose_block_stream.rs
The state machine of the FirehoseBlockStream was not properly resetting the state to disconnected on error leading to the usage of an already completed future leading to a panic.
All code paths are not properly returning the state to Disconnected so the stream can be re-created to contact the remote Firehose endpoint.
=> graph, firehose: fix panick because of re-use of an already completed stream

chain/near/src/runtime/abi.rs
The received bytes from the Firehose NEAR blocks are not in the endianess expected directly by the `BigInt` within AssemblyScript. To fix the issue, we simply reverse the bytes prior turning them into the `Uint8Array` AscObj which ultimately get written to the WASM memory.
While the original issue listed `gasPrice` a being problematic, the bug actually affected all `BigInt` types coming from the Firehose NEAR blocks which means quite a lot of fields.
All NEAR subgraphs using such affected fields will need to be re-synced from their `startBlock`.
Fixes #2955
=> Serialize the BigInt bytes to the correct endianess expected by BigInt

graph/src/data/query/error.rs, graph/src/data/query/result.rs
This change sets the Graph-Attestable header on query results to signal
to the indexer-service whether it should include an attestation for the
client. Unattestable responses are those that are nondeterministic,
according to [GIP 20](https://hackmd.io/@CGmldHLrTRaYRnAva-HoPQ/S1W2vMjEt).
=> Report nondeterministic errors as unattestable

graphql/src/query/ext.rs, graphql/src/schema/api.rs, graphql/src/schema/meta.graphql, graphql/src/store/resolver.rs, graphql/tests/query.rs
This PR adds support for a minimum block constraint on queries via the `number_gte` block argument. The minimum block constraint will be used by the gateway to reduce the likelihood that a client receives query results from blocks prior to those from past queries from the same client.
=> Add support for minimum block constraint

graph/src/data/subgraph/mod.rs
Graph node doesn't particularly care about this, and rules on names are better set at the GNS or explorer layers.
=> Remove subgraph name length limit

store/postgres/src/chain_head_listener.rs
With the logs we were able to confirm that this deadlocks within the tokio watcher implementation, this has been reported upstream https://github.com/tokio-rs/tokio/issues/4246. This PR hacks around that until it is fixed by detecting a deadlocked watcher and continuing to pull notifications, if only to discard them.
=> chain head listener: workaround watcher deadlock

Cargo.lock, graph/Cargo.toml
Somehow, graph node is able to flood the DNS server with requests to resolve the IPFS name. It's mysterious to me how can that be since it makes a single test request to IPFS as the very first thing on startup, which in theory should warm up the DNS caches.
Anyways, it seems the trust-dns resolver doesn't limit the number of simultaneous requests to the DNS server, so the default OS-based resolver might be better to handle backpressure since it uses a thread pool with limited capacity for simoultaneous requests.
=> reqwest: Disable trust-dns

chain/ethereum/src/chain.rs, chain/near/src/chain.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/polling_block_stream.rs
When firehose sends an undo event from an older block, the
instance-manager would try to fetch the block from RPC to
retrieve its parent block info.
Now, the firehose will include the parent's hash and num in
the Revert event to remove that extraneous RPC call
=> fix firehose UNDO case on old blocks

graph/src/components/store.rs, graph/src/data/graphql/object_or_interface.rs, graph/src/data/query/error.rs, graphql/src/store/prefetch.rs, store/postgres/src/relational_queries.rs
This fixes errors in prefetching phase for queries that orders the selection set with the `orderBy` attribute.
The changes rely on complementing the selection set with the fields used for ordering. The problematic part is that each visited selection set is unaware of those ordering fields due to them not being in the scope during the recursive invocations of the `execute_selection_set` function.
This led to malformed SQL queries that tried to `ORDER BY` columns that were not being selected in sub-queries.
The solution presented here was to pass those complementary fields as arguments along with the recursive traversal and injecting them into their respective selection sets.
=> Fix prefetching bug when selecting by specific attributes: allow `orderBy` 

node/src/store_builder.rs, store/postgres/src/block_store.rs, store/postgres/src/chain_store.rs, store/postgres/src/lib.rs, store/postgres/src/primary.rs
Adds a startup operation to check if `db_version` is less than `3`.
If not, performs full cleanup on all block cache tables _(using `TRUNCATE TABLE`)_ and then sets the `db_version` to `3`.
=> Update `db_version` to version 3 at startup

graphql/src/schema/meta.graphql
This field should only be present in the generated `Block_height` type.
=> Remove `number_gte` constraint from `_Meta_`

core/src/subgraph/instance_manager.rs, graph/src/components/store.rs, store/postgres/src/deployment_store.rs, store/postgres/src/detail.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/subgraph.rs
Before the "PoI for failed subgraphs" feature, where we advance the
deployment head a block if the error is deterministic, we would do
the `unfail` logic after a block is successfully processed, like this:
```rust
match process_block() {
Ok(needs_restart) => {
if first_run {
store.unfail();
}
// ...
}
// ...
}
```
With this feature the `unfail` mechanism had to change, we did that by
changing two things about it:
- It would run before `process_block`
- Making it revert to the parent block if the error was deterministic
This worked fine for deterministic cases, however for non-deterministic
ones we faced an issue.
We need to run `unfail` after `process_block` went successful (returned
`Ok`). This is necessary because we can only unfail the deployment if
the subgraph actually advanced past …
=> Fix unfail mechanism based of determinism

graph/examples/stress.rs, graph/src/util/cache_weight.rs, graphql/src/store/prefetch.rs
This PR does the following:
* fix a bug in `CacheWeight.weight` that caused us to assume any struct has size 8
* improve the estimate for `BTreeMap` by following the structure of a B-Tree much more closely; that is now precise for maps up to size about 20
* improve the `stress` example to make it a little more versatile and representative of real-life data that we cache
=> Improve our CacheWeight estimates

node/src/store_builder.rs, store/postgres/src/connection_pool.rs
The previous code didn't parallelize setup, since setup makes blocking
calls, and so databases still started up one after the other.
=> node, store: Actually setup databases in parallel

store/postgres/migrations/2021-07-09-144144_firehose_cursor/down.sql
Removes extra 'text' type.
@tilacog made this snippet to show the migration fails: https://dbfiddle.uk/?rdbms=postgres_12&fiddle=5f8f28f9afb8eae17c481e2f3c0fb777
=> store: Fix firehose migration syntax

Cargo.lock, Cargo.toml, core/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, graphql/src/schema/api.rs, node/Cargo.toml, server/http/Cargo.toml, server/index-node/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml, store/test-store/Cargo.toml
v0.4 was released a few days ago, here's the changeset: https://github.com/graphql-rust/graphql-parser/releases/tag/v0.4.0 
It also includes a bugfix we needed (so we no longer need a patch in the root Cargo file). 
Also, there was a minor breaking change to Directive, I added a `repeatable: false` to all existing directives, to preserve to previous behavior.
=> Update graphql-parser to v0.4.0

chain/ethereum/src/trigger.rs, graph/src/firehose/endpoints.rs, graphql/src/introspection/resolver.rs, node/src/manager/commands/copy.rs, server/websocket/src/connection.rs, store/postgres/src/catalog.rs, store/postgres/src/primary.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, tests/tests/parallel_tests.rs
Unused fields were prefixed with an underscore. 
Fields from de/serialization structs kept their names and were annotated with `#[allow(dead_code)]`.
=> Fix warnings about fields never being read

chain/ethereum/src/adapter.rs
This will help debug this issue: https://github.com/graphprotocol/graph-ts/issues/211.
Before the same parameter would be printed twice like:
```
Failed to call function "hashOrder_" of contract "WyvernExchange": type mismatch, token
Array([Address(0x7be8076f4ea4a4ad08075c2508e481d6c946d12b), Address(0xb13c38273e001f0427c26f15b79b57db90606a91), Address(0x0000000000000000000000000000000000000000), Address(0x0000000000000000000000000000000000000000), Address(0x79986af15539de2db9a5086382daeda917a9cf0c), Address(0x0000000000000000000000000000000000000000), Address(0x0000000000000000000000000000000000000000)])
is not of kind
Array([Address(0x7be8076f4ea4a4ad08075c2508e481d6c946d12b), Address(0xb13c38273e001f0427c26f15b79b57db90606a91), Address(0x0000000000000000000000000000000000000000), …
```
=> chain/ethereum: Fix ethabi type mismatch error msg

core/src/subgraph/instance_manager.rs, graph/src/components/store.rs, graph/src/data/subgraph/schema.rs, graph/src/util/backoff.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/subgraph.rs
After extensive testing, I think this is finally correct 🙌 
This PR adds an exponential backoff to keep retrying non-deterministic errors until they get solved and the subgraph unfails.
Main changes:
- Re add block range confidence check for non-determinstic errors on unfailure. Aka reversal and fix of this PR: https://github.com/graphprotocol/graph-node/pull/3015
- Use the `ExponentialBackoff` structure to keep retrying non-deterministic errors
Solves #2945
=> Add exponential backoff retry for non deterministic errors

docs/environment-variables.md, node/src/bin/manager.rs, node/src/manager/commands/unused_deployments.rs, store/postgres/src/jobs.rs, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs
With these changes, `graph-node` will automatically remove unused deployments, and it therefore won't be necessary to manually run `graphman unused record` and `graphman unused remove`. When a deployment is detected to be unused, `graph-node` will wait for `GRAPH_REMOVE_UNUSED_INTERVAL` minutes (default: 6hrs) before actually deleting the deployment's data. 
As a reminder, a deployment is considered unused if it is neither the current or pending version of a subgraph, and also not assigned to any indexing node.
=> Automatically remove unused deployments

chain/ethereum/src/ethereum_adapter.rs
Currently the following retries use hard-coded retry limits that cannot be configured:
- `eth_call RPC call`: `10`
- `batch eth_getTransactionReceipt RPC call`: `16`
This PR fixes it by replacing the hard-coded values with `*REQUEST_RETRIES`.
=> Fix hard-coded retry limits being used instead of REQUEST_RETRIES

chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/network_indexer/network_indexer.rs, chain/ethereum/tests/network_indexer.rs, docs/environment-variables.md, graph/src/blockchain/mod.rs
Replaces `Web3:Batch` with buffered, concurrent RPC calls when fetching transaction receipts for a block.
The `fn load_full_block` was updated to use `std::future::Future` and the actual handling of fetching transaction receipts was moved to a dedicated function called `fn resolve_transaction_receipts`, which uses a retry strategy for each request.
Fixes #3018
=> Update block ingestor to fetch receipts in parallel.

docs/config.md, node/resources/tests/full_config.toml, node/src/config.rs, node/src/manager/commands/config.rs, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs, store/test-store/src/store.rs
With this change, deployment rules in `graph-node.toml` accept multiple shards, e.g. with
```
[[deployment.rule]]
shards = [ "primary", "shard_a" ]
indexers = [ "index_node_1_a",
"index_node_2_a",
"index_node_3_a" ]
```
Similar to how multiple index nodes are used, when a rule specifies multiple shards, the deployment is placed into the least used shard.
=> Allow placing new deployments onto one of several shards

graph/src/components/store.rs, graph/src/data/subscription/result.rs, graphql/src/execution/resolver.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/tests/query.rs, node/src/manager/mod.rs, store/postgres/src/store_events.rs
By using a watcher instead of a channel, the back pressure is removed and notifications won't pile up in the DB due to a slow subscription. After #2922 this became easy to implement, however keeping compatibility with `throttle_while_syncing` became difficult. The watcher naturally collapses notifications which is part of what that did, but the actual throttling is no longer done. However this optimisation seems more critical at the moment, if the throttling again proves necessary we can rework it and use it again.
=> Prevent subscriptions from back-pressuring the notification queue

core/src/subgraph/registrar.rs, graph/src/components/store.rs, graph/src/data/store/mod.rs, graphql/src/store/query.rs, node/src/manager/commands/listen.rs, node/src/manager/mod.rs, store/postgres/src/store_events.rs, store/postgres/tests/store.rs
The `subscriptions` map of the SubscriptionManager could become very large and be expensive to clone. This optimizes the no payload case to share a watcher between subscriptions with the same filter, and to not require cloning the map, which should resolve any performance concerns here.
Notes to reviewer:
- Read with whitespace diff disabled.
- `Vec<SubscriptionFilter>` was changed to a `BTreeMap<SubscriptionFilter>`, so that equal sets of filters have equal hashes.
- It was necessary to split the map for subscriptions with no payload into a separate `subscriptions_no_payload` field. I tried avoiding this in #3053 with the `EventSink` trait, but that wasn't workable anymore, so that trait was removed. This leads to a bit of code duplication in `periodically_clean_up_stale_subscriptions` …
=> subscriptions: Share watcher among subscriptions of same filter

NEWS.md, graph/src/data/query/error.rs, store/postgres/src/relational.rs, store/postgres/tests/relational.rs
=> store: Fix fulltextsearch space handling

chain/ethereum/src/codec.rs, chain/near/proto/codec.proto, chain/near/src/codec.rs, chain/near/src/lib.rs, chain/near/src/protobuf/sf.near.codec.v1.rs, graph/src/blockchain/firehose_block_ingestor.rs, graph/src/blockchain/mod.rs, graph/src/components/store.rs, graph/src/firehose/endpoints.rs, graph/src/firehose/helpers.rs, graph/src/firehose/mod.rs, node/src/main.rs, store/postgres/migrations/2021-12-02-212506_chain_store_firehose_cursor/down.sql, store/postgres/migrations/2021-12-02-212506_chain_store_firehose_cursor/up.sql, store/postgres/src/chain_store.rs
The actual FirehoseBlockIngestor is generic enough to be re-usable on all chains that have Firehose support. This is the initial implementation that just follow chain head and update the head blocks. Rather naive in its approach right now.
Current limitations that I would like to discuss:
- ~Chain net_version and genesis_hash already exist with a default value. Now the value is fetched from Firehose correctly so there is a mismatch. How we should handle that, just delete the prior record "manually" before deploying? Automatically override if current value is XYZ? I would opt for the latter~. Going to fix it in the migrations that adds the `head_block_cursor` directly.
- ~Still need to discuss how we want to handler backfilling. There is different options available: backfill straight …
=> Initial addition of FirehoseBlockIngestor for NEAR (and other Firehose chains)

Cargo.lock, core/src/subgraph/instance_manager.rs, graph/Cargo.toml, graph/src/blockchain/block_stream.rs, graph/src/blockchain/firehose_block_stream.rs
The implementation of the never ending Firehose stream of blocks have been re-implemented using `async-stream` library. This will makes the implementation much more readable and maintainable in the future. This should enable re-using `TriggersAdapter::triggers_in_block` directly instead of having to defer to `firehose_triggers_in_block` (subsequent PR to come).
This also removes the `notify_block_consumed` callback on the `FirehoseBlockStream` and the latest active cursor to reconnect to is now saved inside the FirehoseBlockStream directly. This will make it easier to implement the `BufferedBlockStream` in the future.
*Caveats* Formatting of code inside `try_stream!` macro doesn't work, unclear if it's a general limitation in macros in general or this very specific macro.
=> Re-written FirehoseBlockStream using `async-stream`

chain/ethereum/src/chain.rs, chain/near/src/chain.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/firehose_block_stream.rs
With the revamped `FirehoseBlockStream`, it's now possible to directly re-use the `TriggerAdapter::triggers_in_blocks` code instead of relying on our specialized `firehose_triggers_in_block`. This make the code more re-usable.
Eliminated at the same time a useless close in `NearChair::TriggersAdapter`. Also make some `NearChain` now panics instead of silently returning something that is not good.
Linked to #3080
Based on #3078
=> Replace specialized `firehose_triggers_in_block` by direct usage of TriggerAdapter::triggers_in_blocks`

chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs
When a filter is empty, it means it cannot match anything. By guarding the parsing of the triggers upfront, we avoid looping through lot's of element in the blocks, this is especially true for full blocks that contain all the transactions.
Fixes #3080
=> Avoid parsing X triggers if the filter is empty

Cargo.lock, runtime/wasm/Cargo.toml
The branch being now deleted, the `master` branch is failing to compile properly. This fixes it by changing the location and rev where to find the dependency.
=> Fixed build now that `sign-ext-feature-flag` branch has been merged upstream

chain/ethereum/src/ethereum_adapter.rs
This PR attempts to fix memory usage spikes introduced in #3030.
=> Optimize parallel receipt fetching

chain/ethereum/src/chain.rs, chain/near/src/chain.rs, chain/near/src/codec.rs
This PR is a continuation of #2979 adding the required support for NEAR. 
At the same time, this PRs turns some no-op silent returns into panics in NEAR, all those around the `IngestorTrait` now that it's clear it's an Ethereum specific thing. We should probably actually move it out completely to an `EthereumBlockIngestor` and refactor the `Chain` implementation to get rid of it. I did not investigate the implications and might prove hard.
=> chain/near,chain/ethereum: improved revert code and fixed NEAR on revert to pass parent_ptr

chain/ethereum/src/chain.rs, chain/near/src/chain.rs, graph/src/firehose/endpoints.rs, node/src/chain.rs, node/src/main.rs
When a provider is faulty, it's removed from the list of endpoints for this particular chain. This means later on, places where at least one valid provide must exists panicked, this is the case for the `FirehoseBlockIngestor`.
As well as removing the faulty provider in `connect_firehose_networks`, we also completely remove the chain itself if at the end the chain has 0 providers.
Alternative would be to keep the chain but make downstream users to deal with the fact that providers could be 0. I decided on removing at the source instead since a chain with 0 providers is like no chain at all since nothing could run.
I took the opportunity to trimmed down the structs where firehose providers and chain id to providers are stored. I was always finding hard to reason about those struct where …
=> node: fix a potential crash when Firehose provider is faulty

core/src/subgraph/instance_manager.rs
The `continue` in the `instance_manager` run loop are actually doing a `continue` that continue to the next block in the stream.
That meant to be `break`s instead so they actually go up to the outer loop which restart the subgraph.
=> core: subgraph might continue processing to next block when an error occurred on a revert

chain/ethereum/src/ethereum_adapter.rs, docs/environment-variables.md
- Inverts the logic in `ethereum_adapter` module to make fetching receipts concurrently the default behaviour.
- An environment variable `GRAPH_ETHEREUM_FETCH_TXN_RECEIPTS_IN_BATCHES` is provided for reverting to the previous, batching strategy.
=> Default to fetching receipts concurrently

chain/ethereum/src/adapter.rs, chain/ethereum/src/ethereum_adapter.rs
Updated `retry` log messages context with identifiers (transaction hashes, block hashes/numbers, block ranges).
=> Add more context when logging RPC calls

Cargo.lock, core/tests/interfaces.rs, graph/src/data/query/error.rs, graphql/Cargo.toml, graphql/src/execution/query.rs, graphql/tests/query.rs
While @lutter worked on a refactor for the GraphQL execution (https://github.com/graphprotocol/graph-node/pull/3005), we needed a way to make sure some aspects of execution are valid after merging the refactor PR. 
We also noticed that the current implementation of the GraphQL engine does not include a validation phase (https://github.com/graphprotocol/graph-node/issues/3013). 
This PR uses `graphq-tools` crate (https://github.com/dotansimha/graphql-tools-rs, a set of utils on top of `graphql_parser` crate) for validations, using visitor pattern (similar to GraphQL-JS ecosystem). 
The following rules are now running: 
- `UniqueOperationNames` (https://spec.graphql.org/draft/#sec-Operation-Name-Uniqueness)
- `SingleFieldSubscriptions` …
=> graph, graphql: introduce GraphQL spec-compliant `validation` phase and rules

chain/ethereum/src/adapter.rs, chain/ethereum/src/data_source.rs
This was a sneaky consequence of `Transaction.from` being made optional which we missed #2896. This caused a panic in the runtime here https://github.com/graphprotocol/graph-node/blob/b710b90131d3b7dddbf9021cef178cc0552b6452/chain/ethereum/src/trigger.rs#L368.
=> ethereum: Fix Celo reward event

graph/src/data/subgraph/api_version.rs, graph/src/data/subgraph/mod.rs
Moves things related to api version and spec version to its own module.
=> refactor: Add `api_version` module

chain/ethereum/src/ethereum_adapter.rs
=> chain/ethereum: Remove `no_logging` from `retry` operation

chain/ethereum/src/chain.rs
If the environment is **not** set, the current behavior and Firehose is automatically picked up if there is endpoints configured with it.
If the environment set, firehose is preferred only if the variable is true and there is endpoints configured with it.
=> Added an environment to control if Firehoe is preferred or not when present

Cargo.toml
This doesn't seem to reproduce in 1.58
=> Update comment on incremental compilation

chain/ethereum/src/chain.rs, chain/near/src/chain.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/polling_block_stream.rs, graph/src/components/store.rs, graph/tests/entity_cache.rs, store/postgres/src/deployment_store.rs, store/postgres/src/writable.rs, store/postgres/tests/graft.rs, store/test-store/src/store.rs
This PR ensures that the Firehose cursor is saved properly even on revert operations.
=> core,graph,store: on block revert, Firehose should save the cursor to the database

core/src/subgraph/instance_manager.rs
When [POI for failed subgraphs](https://github.com/graphprotocol/graph-node/pull/2748) got introduced, [it added a condition](https://github.com/graphprotocol/graph-node/commit/5ede5efa1309e4b7c7126e0e8637370dd3bddb42#diff-8fa50af0e3a188e9a051db274063ed209f669b71c01bc7ae47f1e40f290cff08R914) in the instance manager that filters entity changes that will be transacted to the database.
Because of this (and other changes that might get introduced in the future), we should clear the entity cache so that it's safe to assume it's on sync with the database.
=> instance_manager: Clear entity cache when subgraph errors/starts

graphql/src/execution/execution.rs, graphql/tests/query.rs
Fixes https://github.com/graphprotocol/graph-node/issues/3114
Given the following query: 
```graphql
{
__typename # this one is the problematic one
purposes {
__typename
}
}
```
Should return: 
```json
{
"__typename": "Query",
"purposes": [
{
"__typename": "Purpose"
}
]
}
```
But it fails to resolve `"__typename": "Query",`, because we don't handle `__typename` not only for root types but all other types.
It works for `Purpose` for example because `__typename` is added by resolvers level(prefetch) for other object types.
=> graphql: resolve __typename if not exists in the resolved object

chain/ethereum/src/runtime/runtime_adapter.rs
This lowers the mapping gas cost of an eth call from 25 to 5 billion.
By benchmarking a uniswap-like subgraph, I've observed that the eth call gas cost causes the overall gas cost to be way overestimated. And 400 calls per mapping might just not be enough for some real world subgraphs.
=> ethereum: Lower mapping gas cost of ethereum call

chain/ethereum/src/chain.rs, chain/near/src/chain.rs, core/src/subgraph/instance_manager.rs, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, node/src/bin/manager.rs, node/src/manager/commands/run.rs
Running `graphman run` with the `PollingBlockStream` could lead to an infinite loop.
This can happen because `graphman run` keeps an [infinite loop](https://github.com/graphprotocol/graph-node/blob/399ee444d1023a95f82404d14bb5e4534d827678/node/src/manager/commands/run.rs#L189) checking if the `deployment_head` passed the `stop_block`, however the `instance_manager` would [stop processing](https://github.com/graphprotocol/graph-node/blob/399ee444d1023a95f82404d14bb5e4534d827678/core/src/subgraph/instance_manager.rs#L622) once the `PollingBlockStream` would get to the `stop_block` and not the `deployment_head`.
I've changed so that we keep the `deployment_head` state in the `instance_manager` and compare the `stop_block` to that.
I've also took the opportunity to remove the last store …
=> Fix `graphman run` for the `PollingBlockStream`

core/src/subgraph/instance_manager.rs
This removes the deployment head state from the instance manager which
could be a point of failure since it wasn't being updated in reverts,
etc.
And moves the stop block logic right after we progress a block since we
don't store the state anymore.
=> Remove deployment head state from instance manager

chain/ethereum/src/data_source.rs
Adds transaction hash information in log messages when processing triggers.
=> Add transaction hash to trigger logs

graphql/src/store/prefetch.rs
This fixes the current query errors when `GRAPH_ENABLE_SELECT_BY_SPECIFIC_ATTRIBUTES` is turned on.
Currently, introspection fields are included in the `SelectedAttributes` value and would later be inadequately selected as columns in SQL queries.
This PR prevents such fields from being collected by filtering out field names that start with double underscores.
Fixes #2938.
=> Prefetching: don't collect introspection fields
