graphprotocol/graph-node

chain/ethereum/src/ethereum_adapter.rs
This early return prevents an unecessary iteration over the block transactions, where each would be checked for containment against an empty vector.
=> minor optimization: Return early if there are no transaction hashes

node/src/bin/manager.rs, node/src/main.rs, store/postgres/src/fork.rs
A small PR to make the ending slash for the fork-base URL optional. (It simply adds it if it's not there.)
=> node: make terminating slash in fork-base optional

graphql/src/schema/api.rs, graphql/src/schema/meta.graphql
Closes https://github.com/graphprotocol/graph-node/issues/3203
=> graphql: refactor and prefer static GraphQL where possible

node/src/bin/manager.rs, node/src/manager/commands/index.rs, node/src/manager/commands/info.rs, node/src/manager/commands/rewind.rs, node/src/manager/commands/run.rs, node/src/manager/commands/stats.rs, node/src/manager/deployment.rs, store/postgres/src/catalog.rs, store/postgres/src/deployment_store.rs, store/postgres/src/subgraph_store.rs
This PR adds two new `graphman** subcommands:
Lists all indexes for the given Entity table.
Each index will be printed to `stdout` as its own definition command, like:
```
CREATE [UNIQUE] INDEX <index-name> ON <table-name> USING <index-method> (<columns>)
```
Drops the given index, concurrently.
If the index does not exist, an error message will be displayed to the user.
=> Add `graphman` commands: `index list` and `index drop`

chain/ethereum/src/chain.rs, chain/ethereum/src/data_source.rs, chain/near/src/data_source.rs, core/src/subgraph/instance.rs, core/src/subgraph/runner.rs, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, graph/src/components/subgraph/host.rs, runtime/wasm/src/host.rs
Previously the `deployment_trigger_processing_duration` metric would count triggers that do not match, so it wasn't very useful.
This also adds a note about `match_and_decode` being hot code, and optimizes so we don't have to clone an `Arc` when checking if a trigger matches a data source address. After https://github.com/graphprotocol/graph-node/issues/3257 this will be called much more often when templates are present, so it's good to keep it as efficient as possible by avoiding atomic instructions.
=> core, metrics: observe processing time only for processed triggers

core/src/subgraph/runner.rs, runtime/wasm/src/mapping.rs
Previously such errors in the WASM start function would generate a `"WASM runtime thread terminated abnormally"` with newlines in it, making it impossible to search for in logging tools. Now it properly bubbles up.
=> runtime: Improve error message for error initing AS global

core/src/subgraph/runner.rs, graph/src/components/store.rs, store/postgres/src/deployment_store.rs, store/postgres/src/writable.rs
This PR does two things:
1. Stop skipping blocks if the subgraph is synced
2. Ignore a revert of a block that wasn't processed
It's necessary because of a bug introduced in #3223 
**Edit**: I'm still testing this locally with a subgraph that's close to chain head. (probably with the [debug forking tool](https://thegraph.com/docs/en/developer/subgraph-debug-forking/))
=> Fix skip block pointer update

store/postgres/src/deployment.rs
When we start a subgraph, we determine whether we need to do a graft based
on the subgraph's block pointer: if that is behind the graft point, or not
set at all, we do all the steps needed for grafting. When the graft
finishes successfully, we set the block pointer to the graft point.
The method deployment::graft_pending checked whether the graft point was >=
the block pointer so that we erroneously believed we still had to graft
when we finished grafting, but the subgraph did not progress beyond that
block for some other reason (e.g., because it immediately failed)
We now check whether the graft point is > the block pointer to avoid that
situation.
=> store: Fix detection of whether a graft is still pending or not

docs/implementation/schema-generation.md, docs/implementation/time-travel.md, graph/src/data/store/mod.rs, store/postgres/src/block_range.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/graft.rs, store/postgres/tests/relational.rs
A lot of entities are immutable, e.g., data that is copied directly from chain data into the subgraph such as transfers, but our store architecture assumed it was mutable, and subgraph authors had no way to indicate that a certain type is immutable.
With this PR, it is now possible to do that by declaring the type with `type Thing @entity(immutable: true) { .. }`. That is the only change needed to take advantage of this feature.
The storage for such types is much simpler and faster than the storage for mutable types since it avoids using GiST indexes which are expensive to maintain and slower to query than the BTree indexes we can use with immutable entities. The real-life impact of this improvement still needs to be measured in a controlled environment, but subgraph authors should be …
=> Add special treatment for immutable entities

graph/src/components/store.rs, graph/src/data/graphql/ext.rs, graph/src/data/schema.rs, graph/src/data/store/mod.rs, graphql/src/schema/ast.rs, runtime/wasm/src/host_exports.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/relational_bytes.rs
This PR makes it possible to declare entities with an `id` type of `Bytes`; building on previous support that was committed a long time ago, with this PR, the `Bytes` are not converted to a string before handing them to mappings. Instead, such entities show up in the mappings with a bytes value for their ID. Companion PR's for `graph-ts` and `graph-cli` will make that more usable.
An example of what it takes to convert a subgraph to all `Bytes` ids can be found [here](https://github.com/lutter/uniswap-v2-subgraph/tree/bytes)
=> Allow using `Bytes` as well as `String`/`ID` for the `id` of entities

store/postgres/src/deployment.rs
The previous version of the code was being too clever: the signal for
whether a graft is pending is whether the subgraph's block ptr is null or
not. The check whether the block ptr had progressed beyond the graft point
was too defensive and made it impossible to graft onto block 0, as well as
breaking a test.
=> store: Fix the logic for determining if a graft was pending (again)

graph/src/components/store.rs, graph/src/data/value.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql, store/postgres/src/block_range.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/src/subgraph_store.rs
Closes https://github.com/graphprotocol/graph-node/issues/3274.
The GraphQL API implemented here looks like the following (a bit different from #3274's first draft; after collecting feedback):
```graphql
type Query {
entityChangesInBlock(subgraphId: String!, blockNumber: Int!): EntityChanges!
}
type EntityChanges {
updates: [EntityData!]!
deletes: [String!]!
}
type EntityData {
name: String!
fields: [EntityField!]!
}
type EntityField {
field: String!
valueAsJSON: String!
}
```
=> GraphQL route for dumping entity changes in subgraph and block

node/src/bin/manager.rs, node/src/manager/commands/run.rs
One can now run:
```
graphman --ipfs=localhost:5001 run {...}
```
or leave the default value `https://api.thegraph.com/ipfs/`
=> add --ipfs flag to 'graphman run' to control the IPFS URL

.github/workflows/ci.yml
See discussion in #3304. The CI will *not* break if Clippy complains; that seems way too daunting and unforgiving. We just want to keep an eye out for antipatterns.
I'm also removing caching + dependencies install for `rustfmt` since it doesn't benefit from it.
=> Add non-intrusive Clippy linting to the CI

core/src/subgraph/runner.rs
Right now it can be hard to reconstruct how the subgraph pointer is moving from the logs, because we don't log anything when moving forward if the block had zero relevant triggers.
=> runner: More subgraph ptr logs

chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, chain/near/src/chain.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/runner.rs, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, graph/src/blockchain/polling_block_stream.rs
Now that the block stream is pipelined, it should not be starting sections concurrently with the runner. This removes the `"filter_call_triggers_from_unsuccessful_transactions"` which was the only one within the block stream. The `deployment_head` metric is moved from the block stream to the runner. This made the metrics dead parameters in many places.
It's likely that we'll want to reintroduce stopwatch metrics in the blockstream, separating the metrics for each stage as done in #3177, but it seems best to remove them now and start from a clean slate when reintroducing them with pipelining and firehose in mind.
=> block stream: Cleanup block stream metrics

graph/src/components/server/index_node.rs, graph/src/components/store/traits.rs, node/src/main.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql, server/index-node/src/server.rs, server/index-node/src/service.rs, store/postgres/src/store.rs
Closes #3311. This is the type signature of the GraphQL route:
```graphql
type Query {
blockData(network: String!, blockHash: Bytes!): JSONObject
}
```
I'm also introducing a new `Store` trait which maintains separation of concerns between `BlockStore` and `SubgraphStore` while replacing some clutter of generics with associated types within `index-node`.
=> Add GraphQL route for fetching block data

store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs
When updating the metadata in subgraph_deployment, we currently do two to
three roundtrips to the database to
- update the block pointer
- update the entity count
- update the firehose cursor (sometimes)
With this change, all three roundtrips are folded into one update
statement.
=> store: Reduce number of queries to update subgraph_deployment

Cargo.lock, server/json-rpc/Cargo.toml, server/json-rpc/src/lib.rs
This removes the last dependency on pre-1.0 tokio versions.
=> json-rpc: Update jsonrpc-server

runtime/wasm/src/host_exports.rs
This is redundant with https://github.com/graphprotocol/graph-node/blob/5d4006f8d9e14d08aa5ee4f91a6f44fa2cb23b9c/runtime/wasm/src/module/mod.rs#L426
=> metrics: Remove redundant store_set section

tests/integration-tests/data-source-context/package.json, tests/integration-tests/data-source-revert/package.json, tests/integration-tests/fatal-error/package.json, tests/integration-tests/ganache-reverts/package.json, tests/integration-tests/host-exports/package.json, tests/integration-tests/non-fatal-errors/package.json, tests/integration-tests/overloaded-contract-functions/package.json, tests/integration-tests/poi-for-failed-subgraph/package.json, tests/integration-tests/remove-then-update/package.json, tests/integration-tests/value-roundtrip/package.json
`master` 🔫 
`main` ❤️ 
Both `graph-cli` and `graph-ts` now have `main` as their default branch and I'm keeping up `master` while this doesn't get merged.
=> integration-tests: Point to branch main of graph-{cli, ts}

graph/src/firehose/endpoints.rs, node/src/chain.rs
It appears that requesting `start_block_num: 0, stop_block_num: 0` does not stop the stream after receiving the genesis block as I expected. Instead, the stream continue to send blocks forever.
This caused the `block_ptr_for_number` to never return properly, causing the `NET_WAIT` timeout to kick which was ultimately leading to the network not being added to the blockchain map and hence, no subgraph could run for this network.
To prevent looping infinitely, we stop as soon as a new received block's number is higher than the latest received block's number, in which case it means it's an event for a block we are not interested in.
=> Fix Firehose chains not starting properly

core/src/subgraph/runner.rs
Now that PR #3290 has been merged, which is always writing back the firehose cursor to the database, meaning it will clear any existing Firehose cursor for a subgraph that started from RPC but than switched to Firehose, it means it's not required to clear any existing cursor when starting a RPC subgraph.
=> Removes deletion of existing Firehose cursor when starting subgraph indexing

core/src/subgraph/registrar.rs, graph/src/components/store/traits.rs, graph/src/data/subgraph/schema.rs, graphql/tests/query.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/graft.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/test-store/src/store.rs
Copying a subgraph that had a start block set would fail after the fix in PR #3287; ultimately, the bug was caused because `SubgraphDeploymentEntity` allows setting things that should not be set when creating a subgraph. Improve the code by using a different struct for creating a deployment.
=> Fix 'graphman copy create'

store/postgres/src/relational_queries.rs
Fixes the current errors of prefetching optimization feature.
This PR Includes the `block_range` column in some SQL queries.
=> Prefetching optimization fix

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/codec.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/transport.rs, chain/ethereum/src/trigger.rs, core/Cargo.toml, graph/Cargo.toml, graph/examples/stress.rs, graph/src/data/subgraph/schema.rs, graphql/Cargo.toml, node/src/chain.rs, node/src/manager/commands/run.rs, runtime/derive/Cargo.toml, runtime/test/Cargo.toml, runtime/wasm/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml
This rebases our web3 fork, which reduces the [required patches](https://github.com/graphprotocol/rust-web3/commits/graph-patches-onto-0.18). They have been submitted upstream https://github.com/tomusdrw/rust-web3/pull/616 so we might be able to drop the fork.
This also does a pass at some other deps such as `rand`, `bytes` and `uuid`.
=> ethereum: Update web3 and ethabi

core/src/subgraph/registrar.rs, graph/src/components/subgraph/registrar.rs, node/src/main.rs, node/src/manager/commands/run.rs, node/src/opt.rs, server/json-rpc/src/lib.rs
I do accept any suggestions on the CLI API, I'm not sure those parameters should be passed where I've put them (and with those names).
This PR adds:
- `--debug-fork` CLI option
- `--start-block` CLI option
With those you can basically get **any subgraph** from the Hosted Service and debug it at **any block** without having the source code to change the **start block**, which debug forking currently requires ([docs](https://thegraph.com/docs/en/developer/subgraph-debug-forking/)).
Eg (enzyme fork that I've been able to reproduce #3236) :
```
cargo run -p graph-node -- \
--postgres-url $THEGRAPH_STORE_POSTGRES_DIESEL_URL \
--ethereum-rpc $ETHEREUM_RPC_URL \
--subgraph QmTBxvMF6YnbT1eYeRx9XQpH4WvxTV53vdptCCZFiZSprg \
--ipfs $IPFS_URL \
--debug-fork …
```
=> Improve debug forking

.github/workflows/ci.yml, Cargo.lock, NEWS.md, chain/ethereum/Cargo.toml, chain/near/Cargo.toml, chain/tendermint/Cargo.toml, core/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, mock/Cargo.toml, node/Cargo.toml, runtime/derive/Cargo.toml, runtime/test/Cargo.toml, runtime/wasm/Cargo.toml, scripts/README.md, scripts/abort.sh, scripts/lines-unique.sh, scripts/toml-utils.sh, scripts/update-cargo-version.sh, server/http/Cargo.toml, server/index-node/Cargo.toml, server/json-rpc/Cargo.toml, server/metrics/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml, store/test-store/Cargo.toml, tests/Cargo.toml
This Pull Request does a few things:
- Updates the `NEWS.md`, cherry-picked from: https://github.com/graphprotocol/graph-node/pull/3317;
- Adds a new `scripts` folder with bash commands to change the `Cargo.toml`/`Cargo.lock` versions automatically;
- Updates the `Cargo.toml`/`Cargo.lock` files (done using the new script ✨ );
- Adds a check to the CI so that no new `crate` can be added to the repo without having the correct version (aka the same as the rest).
=> Release 0.25.2 + new update version script 🪄 

docker/docker-compose.yml
This should fix issue https://github.com/docker/for-linux/issues/264
Also file `./docker/setup.sh` shouldn't be needed anymore
This step shouldn't be required anymore https://thegraph.academy/developers/local-development/
=> Fix docker-compose host IP for linux

chain/ethereum/tests/manifest.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/registrar.rs, core/src/subgraph/runner.rs, core/tests/interfaces.rs, graph/src/components/store/traits.rs, graph/src/data/subgraph/mod.rs, graph/tests/entity_cache.rs, graphql/src/store/resolver.rs, node/src/manager/commands/copy.rs, node/src/manager/commands/run.rs, runtime/test/src/test.rs, runtime/test/src/test/abi.rs, runtime/wasm/src/host_exports.rs, server/index-node/src/resolver.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/query_store.rs, store/postgres/src/subgraph_store.rs, store/postgres/src/writable.rs, store/postgres/tests/chain_head.rs, store/postgres/tests/graft.rs, store/postgres/tests/relational.rs, store/postgres/tests/subgraph.rs, store/test-store/src/store.rs
Also asyncify a bunch of dependencies transitively that were using those.
- `block_ptr`
- `block_cursor`
- `delete_block_cursor`
- `start_subgraph_deployment`
- `block_ptr`
- `writable_for_network_indexer`
- `least_block_ptr`
=> Asyncify various methods in `WritableStore` abd `SubgraphStore`

docs/environment-variables.md, graph/src/log/mod.rs
This pr to add a feature which be requested in #3349 .
This feature seems not be applicable with unit test.So I tested it in this way:
After run a node.I got those log:
```shell
Mar 21 21:35:33.589 INFO Graph Node version: 0.25.1 :: fraction+6 (9c3952d69 2022-03-15) dirty 110 modifications
Mar 21 21:35:33.590 INFO Generating configuration from command line arguments
Mar 21 21:35:33.590 WARN No fork base URL specified, subgraph forking is disabled
Mar 21 21:35:33.590 INFO Starting up
Mar 21 21:35:33.590 INFO Trying IPFS node at: http://127.0.0.1:5001/
```
Add a  environment variable:
```shell
export GRAPH_LOG_TIME_FORMAT="%Y-%m-%d %H:%M:%S"
```
Run a node again,time format be changed:
```shell
2022-03-21 21:40:34 INFO Graph Node version: 0.25.1 :: fraction+6 (9c3952d69 2022-03-15) dirty …
```
=> Add environment variable `GRAPH_LOG_TIME_FORMAT`

store/postgres/examples/layout.rs, store/postgres/migrations/2022-03-21-172028_add_use_bytea_prefix/down.sql, store/postgres/migrations/2022-03-21-172028_add_use_bytea_prefix/up.sql, store/postgres/src/catalog.rs, store/postgres/src/deployment.rs, store/postgres/src/detail.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/store.rs
We now remember for each subgraph whether it was created with indexes on the entire value of `bytea` columns or just a prefix, and generate queries accordingly.
=> Reenable prefixing of `bytea` columns and avoid performance regression

chain/ethereum/src/data_source.rs
Subgraph gets terminated when the graph-node fails to decode the call data with function_abi here: `function_abi.decode_input(&call.input.0[4..])`
failing transaction: https://etherscan.io/tx/0x5f0b0ea26e74c9d796209920bbae08f5ebb4ae053ef8b01c7848bd0a2b85691d
Failing on the graph studio and etherscan also fails to decode this data. This PR skips the transaction that we aren't able to parse using the abi, logs the warning, and continues instead of completely failing the subgraph.
Without this, to fix and continue, we need to do something similar to the following which is not efficient time + replicating data: 
1. new subgraph needs to be deployed with a shortened `function_abi` but this isn't an issue with subgraphs itself
2. start indexing all over for the new subgraph which would take a …
=> ethereum: log warning and continue on parse input failures

chain/ethereum/src/chain.rs, graph/src/blockchain/mod.rs, graph/src/components/store/cache.rs, graph/src/components/store/mod.rs, graph/src/components/store/traits.rs, graph/src/data/graphql/object_macro.rs, graph/src/data/value.rs, graph/src/lib.rs, node/src/main.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql, server/index-node/src/server.rs, server/index-node/src/service.rs, store/postgres/migrations/2022-03-09-07000_call_cache_block_number_idx/down.sql, store/postgres/migrations/2022-03-09-07000_call_cache_block_number_idx/up.sql, store/postgres/src/chain_store.rs
Closes #3312.
Initially, I tried to retrace all contract calls in the given block using the logic inside `EthereumAdapter`, then query the cache to see which of those calls were present in the cache, if any. This operates under the assumption that the data coming from the `EthereumAdapter` at the time of cache insertion and cache lookup are identical, which is not necessarily true, as we wouldn't need this debugging API in the first place if that was the case.
After some back and forth, I realized there was no way I could guarantee total consistency of the results obtained this way with the actual contents of the cache and I landed on the original, simpler design - an additional index to the `call_cache` tables.
=> GraphQL route to expose call cache contents by block

node/src/bin/manager.rs, node/src/manager/commands/assign.rs, node/src/manager/commands/copy.rs, node/src/manager/commands/index.rs, node/src/manager/commands/info.rs, node/src/manager/commands/listen.rs, node/src/manager/commands/rewind.rs, node/src/manager/commands/run.rs, node/src/manager/commands/stats.rs, node/src/manager/deployment.rs, store/postgres/src/primary.rs
The `graphman index` commands wouldn't work if the same deployment is used by multiple names.
This PR also overhauls the logic for how deployments are looked up to make the lookup uniform across various commands
=> Fix some graphman bugs and improve usability

core/src/subgraph/instance.rs, core/src/subgraph/runner.rs, core/src/subgraph/stream.rs, graph/src/components/store/traits.rs, graph/tests/entity_cache.rs, store/postgres/src/deployment_store.rs, store/postgres/src/writable.rs, store/postgres/tests/store.rs, store/test-store/src/store.rs
This is a refactor that removes unnecessary:
- Parameters/Arguments;
- Variables;
- Clones.
And chooses usage of `self.` or `&` (references) instead 😉 
Related issue #3246
=> Remove SubgraphRunner Clones 🔫 

chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, core/src/metrics/registry.rs, graph/src/components/metrics/mod.rs, mock/src/metrics_registry.rs
I noticed the following errors being logged frequently:
ERRO registering metric [deployment_eth_rpc_request_duration] because it was already registered, component: MetricsRegistry
ERRO registering metric [deployment_eth_rpc_errors] because it was already registered, component: MetricsRegistry
I also noticed that graph-node wouldn't correctly observe these metrics because of this. The reason for the errors was that the metrics were recreated each time a new block stream for a deployment was created.
This commit changes it so we remember the `SubgraphEthRpcMetric` associated with each deployment instead of trying to recreate them each time.
=> chain/ethereum: Fix broken deployment_eth_rpc_* metrics registration

Cargo.lock, NEWS.md, chain/ethereum/Cargo.toml, chain/near/Cargo.toml, chain/tendermint/Cargo.toml, core/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, mock/Cargo.toml, node/Cargo.toml, runtime/derive/Cargo.toml, runtime/test/Cargo.toml, runtime/wasm/Cargo.toml, server/http/Cargo.toml, server/index-node/Cargo.toml, server/json-rpc/Cargo.toml, server/metrics/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml, store/test-store/Cargo.toml, tests/Cargo.toml
This used `./scripts/update-cargo-version.sh` to update the `Cargo` files.
The commit range we're releasing here is: https://github.com/graphprotocol/graph-node/compare/v0.25.2...ae6951328df4270e3153897220fdef1822055859 (the one that ran on the integration tests/cluster).
=> Release 0.26.0

chain/ethereum/src/chain.rs, chain/near/src/chain.rs, chain/tendermint/src/chain.rs, core/src/metrics/registry.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/components/metrics/mod.rs, mock/src/metrics_registry.rs, node/src/main.rs
This adds a few metrics for Firehose block streams, all labeled with deployment and provider. Things that these metrics are tracking:
- How often do we reconnect block streams?
- How long do connection attempts take until they succeed/fail?
- How many of these reconnection attempts are successful/fail?
- How much time do we spend receiving and processing stream events?
- What kinds of events (proceed, revert, error) are we receiving?
=> Add Firehose blockstream metrics

graph/src/data/store/mod.rs, graph/src/data/store/scalar.rs
Nobody likes staring at `Bytes(Bytes([156, 141, 1, 242, 5, 212, 149, 165, 242, 63, 230, 46, 11, 121, 199, 233, 63, 47, 100, 71]))` or `BigInt(BigInt(BigInt { sign: Plus, data: BigUint { data: [1994] } }))` without a prescription
=> Streamline the debug output for a few types

chain/ethereum/src/codec.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/runtime/abi.rs, chain/ethereum/src/trigger.rs, graph/src/components/ethereum/types.rs
This PR aims to improve performance issues introduced in #3373.
It envelops `TransactionReceipt`s in `Arcs`s to share them without cloning inside the `parse_log_triggers` function.
=> Put receipts into `Arc`s to prevent excessive cloning.

chain/ethereum/src/ethereum_adapter.rs
This PR aims to improve performance issues introduced in #3373.
It reestablishes concurrency when scanning for triggers in a block range and resolving a block hash.
=> Restore lost concurrency when scanning for triggers

graph/src/blockchain/types.rs, graph/src/components/store/mod.rs, graph/src/components/store/traits.rs, graph/src/lib.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql, store/postgres/src/store.rs, store/postgres/src/subgraph_store.rs
This allows to retrieve comparable POIs that can be shared in public without anyone being able to submit these to get for rewards without doing any work.
=> Add publicProofOfIndexing resolver to the indexing status API

graph/src/components/store/cache.rs, graph/src/data/graphql/ext.rs, graph/src/data/schema.rs, graphql/src/introspection/mod.rs, graphql/src/introspection/schema.rs, graphql/src/lib.rs, server/index-node/src/schema.rs, store/postgres/src/fork.rs, store/postgres/src/relational.rs
This is a better approach to get to the same result as in PR #3449 - we already know that there shouldn't be any point in trying to look up new immutable entities from the store.
We therefore optimize the code for the common happy path, that users use immutable entities correctly to avoid store interactions that are useless in that case to improve indexing performance.
=> Assume that immutable entities are actually new during indexing 

graph/src/components/store/cache.rs
Commit 34147541 made it impossible to lookup a previously written immutable
entity. But doing that is entirely reasonable and legitimate.
=> graph: Fix lookup of immutable entities

docs/implementation/README.md, docs/implementation/add-chain.md
This document describes how developers can add a new chain to `graph-node`.
It doesn't go over everything in detail, but it's a generalized guide that we can start with and improve on top of.
=> docs: Add how to implement a new chain

chain/ethereum/tests/manifest.rs, core/src/metrics/registry.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/runner.rs, core/tests/interfaces.rs, graph/src/components/metrics/mod.rs, graph/src/components/metrics/stopwatch.rs, graph/src/components/store/err.rs, graph/src/components/store/mod.rs, graph/src/components/store/traits.rs, graph/src/env/store.rs, graph/src/util/bounded_queue.rs, graph/src/util/mod.rs, graph/tests/entity_cache.rs, graphql/tests/query.rs, mock/src/metrics_registry.rs, node/src/store_builder.rs, runtime/test/src/test.rs, store/postgres/src/deployment_store.rs, store/postgres/src/dynds.rs, store/postgres/src/lib.rs, store/postgres/src/subgraph_store.rs, store/postgres/src/writable.rs, store/postgres/tests/graft.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/postgres/tests/writable.rs, store/test-store/src/store.rs
This PR makes it possible to perform database writes in parallel with the rest of processing during indexing. The size of the write queue can be set with the environment variable `GRAPH_STORE_WRITE_QUEUE` which defaults to 5 write or revert operations. Setting this to 0 makes writing synchronously and reinstates the previous behavior, also bypassing a bunch of new code.
=> Pipeline store writes

core/src/subgraph/runner.rs
This is more correct, since the block processing could return `Action::Restart` for other reasons.
=> runner: move static filter check

core/src/subgraph/runner.rs
This will make the `sync status` more robust, since the `skip block pointer updates timer` will be skipped if the subgraph is close to the chain head.
=> runner: Ignore skip block ptr if close to chain head

node/src/bin/manager.rs, node/src/manager/commands/copy.rs
Otherwise, a typo can create a deployment that is hard to get rid of
=> node: Check that the shard for 'copy create' exists

runtime/wasm/src/host_exports.rs
The exponentiation algorithm for `x^y` will do `O(log2(y))` multiplications. The current gas costing for this is wildly overestimating.
=> runtime: adjust exp gas cost

core/src/subgraph/runner.rs
This was accidentally in https://github.com/graphprotocol/graph-node/pull/3367
=> runner: fix subgraph cancelation

node/src/bin/manager.rs, node/src/manager/commands/assign.rs
Without them, it's possible that subgraphs get indexed by two nodes.
=> node: Make sure that graphman unassign/reassign send store events

chain/ethereum/src/adapter.rs, chain/ethereum/src/ethereum_adapter.rs
The `EthereumBlockFilter.extend` was not properly extending the base structure with the extension struct.
The new code reduces drasticly the cloning behavior that was happening way too much in the previous implementation.
Fixes #2314
=> Fixed BlockHandler with Call filter

store/postgres/src/relational_queries.rs, store/postgres/tests/relational.rs
Partial fix for https://github.com/graphprotocol/graph-node/issues/3476
=> store: Make conflicting_entity check work for Bytes id

chain/ethereum/src/chain.rs, chain/ethereum/src/codec.rs, graph/src/blockchain/firehose_block_stream.rs
This fixes #3460 by using `TryFrom` when decoding Ethereum Firehose blocks and then handling the error by retrying the same block over and over again (with exponential back-off). Before, graph-node would crash completely.
=> Handle Ethereum Firehose decoding issues without crashing

graph/src/env/store.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
There will also be tests that expose this issue, and make sure it stays fixed. But since that involves an extensive rewrite of `graphql/tests/query.rs`, it will happen in a separate PR so we can at least roll out this fix first.
=> Make traversing derived relationships work when using `Bytes` ids

chain/ethereum/src/ethereum_adapter.rs
This resolves #3487 and #3453. This trusts that any message with "revert" in it is a deterministic error, so we don't have to whitelist each of them.
=> Make call revert detection more sensitive

graph/examples/stress.rs, graph/src/components/store/traits.rs, graph/src/data/value.rs, graph/src/util/cache_weight.rs, graphql/src/execution/query.rs, graphql/src/store/prefetch.rs, graphql/src/store/query.rs, graphql/src/store/resolver.rs, graphql/src/values/coercion.rs, server/index-node/src/resolver.rs, store/postgres/src/query_store.rs, store/postgres/src/relational_queries.rs
I've been looking for ways to reduce the size of the internal representation of query results since that often takes up much more space then the resulting JSON. I suspect that a big driver of that is that `String` is very memory-inefficient for short strings - the string `id` as a `String` takes 24+2 bytes.
One way to reduce the amount of space taken by short strings, and there are a lot of them in query results, would be string interning, where we could get away with as little as 2 or 4 bytes of storage per string, depending on how we intern strings. But interning the map keys that we use in `r::Value::Object` is a bit of an undertaking: we'd want to build a string pool for the API schema, and then put a string pool derived from additional keys (field aliases) introduced by the GraphQL …
=> graph, graphql: Represent map keys in GraphQL query results as Box<str>

graph/src/components/store/mod.rs, graphql/tests/query.rs, store/postgres/src/block_range.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/test-store/src/store.rs
The rewrite was prompted by needing to run the same tests with `Bytes` and `String` as the `id` type in a subgraph. It also streamlines writing tests a lot and reduces the notational overhead of existing tests. That should make it easier to write more tests.
=> Rewrite graphql query tests

Cargo.lock, docker/start, store/postgres/Cargo.toml, store/postgres/src/notification_listener.rs
Hi, this PR implements TLS PSQL connections support for the `notification_listener`, as various managed database providers allow encrypted connections only, and it is generally a bad idea to disable encryption.
Related issue: https://github.com/graphprotocol/graph-node/issues/2097
With these changes it is possible to connect to databases with both TLS support and without. Please note that certificate verification is currently **disabled**, because it fits my use-case, and I don't have any experience with Rust whatsoever to make it configurable to support more use-cases. So I would be grateful if someone takes it over from here.
You can test it e.g. locally when running Postgres with the following command:
```yaml
version: '3'
services:
postgres:
image: postgres
ports:
- '5432:5432' …
```
=> Support TLS PostgreSQL connections in notification_listener

docs/environment-variables.md, graph/src/env/mappings.rs, graph/src/env/mod.rs
This PR adds an entry for the `GRAPH_MAX_SPEC_VERSION` in the environment variables markdown file.
It also updates docs and comments for the latest default versions of:
- `GRAPH_MAX_SPEC_VERSION`
- `GRAPH_MAX_API_VERSION`
=> Fix documented defaults for environment variables: Api & Spec versions

graph/src/env/graphql.rs, graphql/src/execution/execution.rs
This also makes it possible to turn the LfuCache off by setting GRAPH_QUERY_LFU_CACHE_SHARDS to 0
=> graphql: Use the correct setting for number of LfuCache shards

docker/docker-compose.yml
Running the latest on master was giving this error:
```
docker-postgres-1    | selecting default max_connections ... 100
docker-postgres-1    | selecting default shared_buffers ... 128MB
docker-postgres-1    | selecting default time zone ... Etc/UTC
docker-postgres-1    | creating configuration files ... ok
docker-postgres-1    | running bootstrap script ... 2022-04-28 21:25:23.577 UTC [40] LOG:  could not open file "pg_wal/000000010000000000000001": No such file or directory
docker-postgres-1    | 2022-04-28 21:25:23.577 UTC [40] FATAL:  could not open file "pg_wal/000000010000000000000001": No such file or directory
docker-postgres-1    | child process exited with exit code 1
docker-postgres-1    | initdb: removing contents of data directory "/var/lib/postgresql/data"
docker-postgres-1 …
```
=> fix: missing env var causing pg crash on startup

graph/examples/stress.rs, graph/src/data/query/result.rs, graph/src/util/lfu_cache.rs
The only commit with an impact on production code is the last commit in this PR which tries to account for the fact that we cannot free the `CacheEntry` itself from the `LfuCache`
The rest of the changes expand what can be tested with the cache stress testing tool, and try to get it closer to how we actually use the `LfuCache`
=> Small change to memory accounting in `LfuCache` and various changes to the cache stress testing tool

graph/src/env/store.rs, store/postgres/src/relational.rs
Setting tables to account-like should now be done with `graphman stats account-like`. This setting was a holdover from before this command was available.
=> graph, store: Remove GRAPH_ACCOUNT_TABLES setting

docker/Dockerfile
Requirement was added in this PR:
https://github.com/graphprotocol/graph-node/pull/3531
=> docker: Install cmake which is required by prost

graph/src/data/subgraph/mod.rs
With the addition of additional protocols, deploying a subgraph with an invalid upstream provider would return an error String that incorrectly states Ethereum network not supported. This just removes the Ethereum part of the string to allow it to make more sense
=> Modify error string to remove Ethereum

graph/src/components/store/err.rs, graph/src/components/store/mod.rs, store/postgres/migrations/2022-04-26-125552_alter_deployment_schemas_version/down.sql, store/postgres/migrations/2022-04-26-125552_alter_deployment_schemas_version/up.sql, store/postgres/src/primary.rs, store/postgres/src/writable.rs
The plan is to use this column to control migrations such as the one to a dedicated data source table described in #3405.
This changes that column to be an integer rather than an enum, so we don't need to add a DB enum variant on each new version.
=> store: alter deployment_schemas.version column to int

graph/src/data/subgraph/features.rs
This PR adds an alias for the `ipfsOnEthereumContracts` feature named `nonDeterministicIpfs`.
Related to https://github.com/graphprotocol/graph-cli/pull/889
=> Add an alias for the `ipfsOnEthereumContracts` feature

store/postgres/src/catalog.rs, store/postgres/src/deployment.rs, store/postgres/src/relational.rs, store/postgres/src/relational/ddl.rs
PR https://github.com/graphprotocol/graph-node/pull/3383 neglected to set this, so that sugraphs did not get marked properly, resulting in queries that could not use the index on the prefix of `bytea` columns.
=> store: Mark new subgraphs to index only a prefix of bytea columns

.github/workflows/ci.yml, .travis.yml, core/src/link_resolver.rs, docker/docker-compose.yml, graph/src/ipfs_client.rs, store/test-store/devel/docker-compose.yml, tests/tests/common/docker.rs
It turns out the `object` API has been deprecated for a while. Resolves #3565.
=> ipfs: Switch from object stat to dag stat

chain/ethereum/src/codec.rs
`gas_used` was being incorrectly set as the transaction header `gas` which is the gas limit.
=> ethereum firehose: tx gas is gas limit

chain/arweave/src/adapter.rs
Fixes https://github.com/graphprotocol/graph-node/issues/3608
Match-all
```
source:
owner: ""
startBlock: 0
```
Invalid
```
source:
startBlock: 0
```
=> Arweave: allow owner match-all filter

Cargo.lock, runtime/test/src/test.rs, runtime/wasm/Cargo.toml, runtime/wasm/src/mapping.rs
Fixes https://github.com/graphprotocol/graph-node/issues/3500.
Waiting on https://github.com/paritytech/wasm-instrument/pull/16 and https://github.com/paritytech/parity-wasm/pull/328 to  be merged and tagged, will fix revert to upstream once those are available.
=> Fix subgraph stacktrace

graph/src/log/elastic.rs, node/src/main.rs
This is less overhead than creating a new client for each request. Particularly we were seeing this generate excessive DNS requests.
=> elasticsearch: Use connection pool

graph/src/components/store/mod.rs, graphql/src/store/prefetch.rs, graphql/tests/query.rs, store/postgres/src/relational_queries.rs, store/postgres/tests/relational_bytes.rs
When we stitch the result of a query of type d back into the parents, we need to make sure that the parent ids we pass through the query use the type of the parent's id field. Previously, the code was using the type of the child's id field but that has no relation to the correct type.
Fixes https://github.com/graphprotocol/graph-node/issues/3600
=> graph, graphql, store: Use the correct parent type for type d queries

chain/cosmos/src/codec.rs
I'm unsure of why these would be `None`, but we've seen this crash. Resolves #3621.
=> cosmos: handle nones

chain/cosmos/src/chain.rs, chain/cosmos/src/codec.rs, chain/cosmos/src/data_source.rs, chain/cosmos/src/trigger.rs
Related to https://github.com/graphprotocol/graph-node/issues/3621
Wherever possible, instead of unwrapping Option fields turn them into Results with "missing field" errors.
The only places still unwrapping are implementations of `graph::blockchain::Block` because its methods don't return Results.
=> Cosmos: return results

chain/ethereum/src/env.rs, chain/ethereum/src/ethereum_adapter.rs, docs/environment-variables.md
Currently, the genesis block fixed with `0`, but there are some chains, the genesis block start from `1`. 
This PR support specify the genesis block by `GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER`, default value is `0`.
Related Issue: https://github.com/graphprotocol/graph-node/issues/3648
=> chore: specify genesis block via env

chain/ethereum/src/adapter.rs, chain/ethereum/src/data_source.rs
We don't have to check whether the call.input.len() is multiple of 32 because we now skip invalid decoding of calls.
- https://github.com/graphprotocol/graph-node/pull/3326
- ae6951328df4270e3153897220fdef1822055859
This is essentially reverting https://github.com/graphprotocol/graph-node/pull/3219 because of the new change introduced in https://github.com/graphprotocol/graph-node/pull/3326.
Related `ethabi` patch: https://github.com/graphprotocol/ethabi/commit/441c09f1e688f8c63c80dbe7ecc36fd64c745a9e
=> chain/ethereum: Remove call.input.len() validation

store/postgres/src/catalog.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs
In release builds, we create the same index as the exclusion constraint but not the constraint since constraint enforcement is fairly slow. Keeping the constraint for debug builds will have tests that violate the constraint blow up.
We could make that an explicit configuration, but we have so many of them already.
=> store: Only create exclusion constraints in debug builds

docs/implementation/metadata.md, graph/src/data/subgraph/mod.rs, graph/src/data/subgraph/status.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/tests/query.rs, server/index-node/src/schema.graphql, store/postgres/migrations/2022-06-12-003442_move_earliest_to_manifest/down.sql, store/postgres/migrations/2022-06-12-003442_move_earliest_to_manifest/up.sql, store/postgres/src/deployment.rs, store/postgres/src/detail.rs, store/postgres/tests/store.rs, store/test-store/src/store.rs
This change is needed to implement subgraph pruning - for that, we do not want to track the hash of the earliest block so that we can perform a large prune operation in batches and update the earliest block after each batch. Since we don't have a reliable way to get the hash for a block number from deep inside the store, we need to not track that.
So far, the earliest block was always the start block of a subgraph; with pruning that will change. To clarify that, we now store the start block ptr in `subgraph_manifest` and only keep the earliest block number in `subgraph_deployment`. The table still has the `earliest_ethereum_block` block pointer, but that is only there to simplify rollbacks and will be removed in a future PR once this PR has been deployed and looks stable.
The PR changes …
=> Revamp handling of earliest block

chain/near/src/adapter.rs, chain/near/src/chain.rs, chain/near/src/data_source.rs, graph/proto/near/transforms.proto, graph/src/firehose/sf.near.transform.v1.rs
Fixes https://github.com/graphprotocol/graph-node/issues/3628
=> add partial account filters for near

chain/ethereum/src/network.rs, docs/config.md, node/src/chain.rs, node/src/config.rs, node/src/manager/commands/run.rs
Introduce a `limit` for the configuration of web3 providers. The limit is enforced through an approximation, but will be usable to roughly shield a provider from getting too much traffic. There needs to be an unlimited provider for each chain, otherwise `graph-node` may not be able to handle all subgraphs for that chain.
=> Allow limiting the number of subgraphs using a web3 provider

chain/ethereum/src/ethereum_adapter.rs
We've seen [this subgraph](https://thegraph.com/hosted-service/subgraph/superfluid-finance/protocol-dev-xdai?selected=logs) get stuck on this. The RPC response is:
```
Error { code: ServerError(-32015), message: "VM execution error.", data: Some(String("revert")) }
```
=> ethereum: Detect xdai eth_call revert

graphql/src/store/query.rs, graphql/tests/query.rs, store/postgres/src/relational_queries.rs
Seems like child filtering on derived fields is broken. 
This PR adds two tests to cover derived fields (see below) and of course a fix.
```
songs: [Song]!  @derivedFrom(field: "writtenBy")
band:   Band    @derivedFrom(field: "originalSongs")
```
=> Fix child basis filtering on derived fields

docker/start
This PR updates the start script in the docker directory to support the fork-base graph-cli argument.  The argument is always passed to graph-node command and defaults to `https://api.thegraph.com/subgraphs/id/` if no fork_base environment variable is present.  This should make it easy to use debug forking while running graph-node locally with Docker.
=> Enable fork base for graph-node Docker image

NEWS.md, graph/src/env/mod.rs
This matches the value currently used in the hosted service.
=> env vars: set high gas default

docs/environment-variables.md, graph/src/data/query/query.rs, graph/src/env/graphql.rs, graphql/src/execution/query.rs
Closes https://github.com/graphprotocol/graph-node/issues/3715 
- Change `ENABLE_GRAPHQL_VALIDATIONS` to be enabled by default.
- Added `SILENT_GRAPHQL_VALIDATIONS` env var that is (enabled by default)
- Document environment variables related to GraphQL validations 
- No breaking changes are expected by this PR. 
- For every given incoming query, the GraphQL validations will run now, but will report the results silently to the log in case of an error.
=> feat(graph, graphql): allow to run GraphQL validations silently

chain/ethereum/src/ethereum_adapter.rs
We're getting 413s on subgraphs with lots of templates with call handlers.
=> ethereum: avoid large trace filter requests

chain/ethereum/src/codec.rs
fixes POI discrepancies seen during comparison, ex: subgraph `QmcskbugoHafPJC4EcFzkPNc2ExNPY8L32QagCn5qrtQU5`
=> add totalDifficulity from firehose block ver.2

chain/ethereum/tests/manifest.rs, graph/src/data/subgraph/api_version.rs, graph/src/data/subgraph/mod.rs, graph/src/lib.rs, graph/src/offchain/mod.rs, graphql/tests/query.rs, store/postgres/tests/graft.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/postgres/tests/writable.rs, store/test-store/src/store.rs
This adds offchain data source definitions to the subgraph manifest as part of #3072.
=> Add initial support for offchain data sources in manifest

chain/ethereum/src/codec.rs
firehose exposes calls that are "failed" or "reverted". current behavior is to only filter out the transactions that are completely reverted (from the status in the Receipt).
This fixes POI inconsistencies seen in QmPDp878JK2RcvXNhWX1UQHYbhF8iEcWPTdnP9bJvy6L6P (and hopefully QmUrfWjK7rdXzbr3q6D2DVDapCw4yWBU88qjrNvZUewoNy too)
* Current filtering from RPC `traces` is done on the existence of the `error` field. This field does not exist in firehose calls, so we must use another firehose-specific field.
- UPDATE -
* issue #3701 shows us that we shouldn't only skip calls that are failed, but any call that is reverted too (calls are reverted if their parent is reverted).
* In firehose, this means that we must use `state_reverted` field to correctly skip calls that had no effect on the chain.
* …
=> fix firehose eth CallHandler triggering on reverted calls

Cargo.lock, core/Cargo.toml, core/src/lib.rs, core/src/link_resolver.rs, core/src/polling_monitor/ipfs_service.rs, core/src/polling_monitor/metrics.rs, core/src/polling_monitor/mod.rs, graph/src/blockchain/block_stream.rs, graph/src/components/metrics/aggregate.rs, graph/src/components/metrics/mod.rs, graph/src/ipfs_client.rs, graph/src/lib.rs, graph/src/log/mod.rs, graph/src/util/mod.rs, graph/src/util/monitored.rs
As part of #3072, this adds the components to poll IPFS for the availability of a file. This does _not_ track unavailability, once a file is found it is not polled again.
The load management approach is to have a configurable capacity for the IPFS service, which is shared among all subgraphs, and then a per-subgraph queue of pending requests. This should effectively distribute the service capacity fairly among subgraphs.
The implementation has two pieces, the monitoring algorithm which is generic over any `tower::Service` and an implementation of `Service` for IPFS.
=> Polling file monitor

Cargo.lock, graphql/Cargo.toml, graphql/src/execution/query.rs
I ran the same query ~55 times and got these results:
```
No caching (58 samples)
p95:      47.75µs
p99:      73.83µs
average:  24.85µs
median:   20.13µs
Caching (56 samples)
p95:       4.63µs
p99:       4.92µs
average:   2.08µs
median:    1.67µs
```
Part of https://github.com/graphprotocol/graph-node/issues/3077
=> graphql: cache GraphQL validation

graph/src/env/mappings.rs, graph/src/util/lfu_cache.rs
`DEAD_WEIGHT` is currently read into a `pub static` via `lazy_static`, rather than using `graph::env::EnvVars`. The value of the flag is now available via `ENV_VARS.mappings.entity_cache_dead_weight` (is that a good name / place to put it? Accepting suggestions).
=> Move `DEAD_WEIGHT` env. flag initialization logic under the global `struct EnvVars`

graph/src/components/graphql.rs, graph/src/lib.rs, graphql/src/execution/query.rs, graphql/src/lib.rs, graphql/src/metrics.rs, graphql/src/runner.rs, graphql/src/store/prefetch.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, node/src/main.rs, server/http/src/server.rs, server/http/src/service.rs, server/http/tests/server.rs, server/index-node/src/service.rs, store/test-store/src/store.rs
New Prometheus metrics
- `query_parsing_time` 
- `query_validation_time`
Closes #3752
=> graphql: metrics for validation and parsing phases

Cargo.lock, chain/cosmos/Cargo.toml, chain/ethereum/Cargo.toml, chain/ethereum/src/adapter.rs, chain/ethereum/src/lib.rs, chain/substreams/Cargo.toml, graph/tests/entity_cache.rs
Turns out we are not using it.
=> Remove `mockall` dependency

node/src/main.rs, node/src/opt.rs
This pull request replaces the defined constant with EXPENSIVE_QUERIES with a parameter of a similar name. It also adds documentation in the testament describing the functionality exposed with the expensive queries file. Logs into the information log which file is used.
=> Expose expensive queries file as an option

Cargo.lock, NEWS.md, chain/arweave/Cargo.toml, chain/cosmos/Cargo.toml, chain/ethereum/Cargo.toml, chain/near/Cargo.toml, chain/substreams/Cargo.toml, core/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, mock/Cargo.toml, node/Cargo.toml, runtime/derive/Cargo.toml, runtime/test/Cargo.toml, runtime/wasm/Cargo.toml, server/http/Cargo.toml, server/index-node/Cargo.toml, server/json-rpc/Cargo.toml, server/metrics/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml, store/test-store/Cargo.toml, tests/Cargo.toml
All of the release notes are in the `NEWS.md` file. They were taken from [here](https://github.com/graphprotocol/graph-node/compare/v0.26.0...4baec903d100178e7a4c30ec15788c5ad961972d) (~270ish commits).
=> Release 0.27.0

graph/src/components/store/traits.rs, graphql/src/store/resolver.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/query_store.rs, store/postgres/tests/subgraph.rs
Fixes: https://github.com/graphprotocol/graph-node/issues/3663
=> Refactor subgraph store tests

graph/src/firehose/endpoints.rs
This gets printed in the `Blockstream disconnected` log, and it could be sensitive.
=> firehose: dont leak url in logs

graph/src/firehose/endpoints.rs
We currently multiplex all firehose connections on a single http2 connection, and under load we're seeing possible flow control issues, possibly a [hyper bug](https://github.com/hyperium/hyper/issues/2899). The default per-connection http2 window is small and equal to the per-stream window. <strike>Enabling adaptive windows should give us a much bigger connection window, and possibly solve the issue at the current loads</strike>. This sets the connection window to the maximum value, effectively disabling it.
=> fix(firehose): http2_adaptive_window

chain/ethereum/examples/firehose.rs, chain/substreams/examples/substreams.rs, graph/src/firehose/endpoints.rs, node/src/chain.rs, node/src/config.rs, node/src/main.rs, node/src/manager/commands/run.rs, tests/src/fixture/ethereum.rs
This adds a `conn_pool_size` field to the toml configuration of firehose providers, which enables load balancing across multiple connections to the provider's endpoint. It defaults to 10.
Also does some refactoring around `FirehoseEndpoint::new`.
=> Firehose connection pool

chain/ethereum/src/network.rs, graph/src/lib.rs, node/src/bin/manager.rs, node/src/config.rs, node/src/manager/commands/config.rs, node/src/manager/commands/run.rs, tests/src/fixture.rs
Provider selection with a limit did not work as intended because the node name was not passed around correctly, so that rules to set the limit were always evaluated for the node `default` (commit 209786c9 fixes that)
To make configuring limits easier and provide more insight into provider selection, this PR also adds a command `graphman config provider` that makes it possible to see which providers are eligible. Use it as `graphman --node-id index_node_0 --config /some/where/graph-node.toml config provider mainnet`
=> Fix provider selection when limit is set

store/postgres/src/copy.rs, store/postgres/src/deployment_store.rs, store/postgres/src/dynds/mod.rs, store/postgres/src/dynds/private.rs, store/postgres/src/dynds/shared.rs
The existing coude tried to access the source schema when it was not mapped into the destination shard. It is only mapped while `copy_data` is running; move private ds copying into `copy_data`
=> store: Make cross-shard copying of priavte data sources work

graph/src/firehose/endpoints.rs
Firehose v2 does not allow the `[new, irreversible]` combination.
=> firehose: fix request for v2

core/src/subgraph/instance_manager.rs, store/postgres/src/dynds/private.rs
Fixes two issues caught in hosted, one is data sources with the same name as templates and the other not sorting the loaded data sources.
=> fix: Dynamic data sources hotfixes

graph/src/firehose/endpoints.rs
We might have seen requests hanging, this will give block streams a chance to retry hanged requests.
=> firehose: Set a timeout for grpc requests

core/src/metrics/registry.rs
-------
Small fix for a missing word in an error message.
=> core: add missing word in MetricsRegistry initialization error msg

core/tests/interfaces.rs, graph/src/components/mod.rs, graph/src/components/store/traits.rs, graph/src/components/versions/features.rs, graph/src/components/versions/mod.rs, graph/src/components/versions/registry.rs, graph/src/data/query/query.rs, graph/src/lib.rs, graphql/src/runner.rs, graphql/tests/query.rs, node/src/config.rs, node/src/manager/commands/copy.rs, node/src/manager/commands/query.rs, server/http/src/request.rs, server/http/src/service.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql, server/websocket/src/connection.rs, server/websocket/src/server.rs, store/postgres/src/deployment_store.rs, store/postgres/src/query_store.rs, store/postgres/src/store.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/chain_head.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/test-store/src/store.rs
This is the initial implementation of versioning.
I left few comments on the interesting parts of the code to make it easier to review.
- [Where do we manage versions](https://github.com/graphprotocol/graph-node/pull/3185#discussion_r791502259)
- [How do we define "latest" version](https://github.com/graphprotocol/graph-node/pull/3185#discussion_r791502627)
- [How does the Gateway fetch a list of supported versions?](https://github.com/graphprotocol/graph-node/pull/3185#discussion_r791504128)
- [How do we define feature flags?](https://github.com/graphprotocol/graph-node/pull/3185#discussion_r791501883)
- [How do we validate the version number provided by the user?](https://github.com/graphprotocol/graph-node/pull/3185#discussion_r791503067)
Continues #3155
=> all: GraphQL API Versioning

Cargo.lock, graph/src/components/store/traits.rs, graphql/src/runner.rs, graphql/src/schema/meta.graphql, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, node/src/manager/commands/rewind.rs, server/index-node/src/resolver.rs, store/postgres/src/chain_store.rs, store/postgres/src/query_store.rs, store/postgres/tests/store.rs, store/test-store/Cargo.toml, store/test-store/src/block_store.rs
Fixes: https://github.com/graphprotocol/graph-node/issues/3060
This change should add a timestamp for EVM chains, should work well for both RPC and firehose ingestors. 
The fact the query depends heavily on the format of the block means it will not work for any block format that doesn't add the expected timestamp field inside a top level block field. 
To solve this further we could ensure that all block formats have the necessary timestamp or alternative we could extract/duplicate that field outside the block and run some migrations. The downside of the migration approach is that it needs to be communicated more widely. This migration would also be potentially long due to the size of the block cache tables.
=> Add timestamp to meta block

graph/src/blockchain/firehose_block_stream.rs
We have a timeout configured on the tonic endpoint which is catching most but somehow not all hangs.
=> firehose: Add timeout to `stream_blocks` request

chain/ethereum/src/ethereum_adapter.rs
Adds a Prometheus subgraph metric for the `eth_getTransactionReceipt` call.
=> chain/ethereum: Monitor transaction receipt fetching duration

node/resources/tests/full_config.toml, node/src/chain.rs, node/src/config.rs, node/src/main.rs
Adds substreams as a provider type rather than a protocol.
=> add substreams config provider

docker/Dockerfile
suggestion: move graph-node-debug stage above the production stage graph-node
For those that don't use --target then they will always get the production image by default
This also helps for those building from Docker Hub Cloud where a target can't be specified
=> move debug stage above production

docker/start, docs/environment-variables.md, graph/src/data/store/mod.rs, node/src/main.rs
This removes the node ID check requiring that a node identifier be solely composed of A through Z, 0 through 0, or an underscore (_) character. My reasoning for removing this restriction is that it enables easier node provisioning by enabling the use of generated Kubernetes host names to name index and query nodes. This also removes confusion when a new indexer deploys the indexer stack.
=> Removed alphanumeric enforcement for node IDs

docker/start
```
27
```
the pid of graph-node is not 1
=> docker: add exec to fix graceful stop

graphql/src/execution/execution.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/store/resolver.rs, graphql/tests/introspection.rs, server/index-node/src/resolver.rs
Currently, the `subgraphFeatures` route is panicking because `Store`s implementation of `Resolver::resolve_object` calls `block_on` from within an async context.
This fix makes the `Resolver::resolve_object` an async method, allowing us to `await` instead of blocking the execution.
=> graphql,server: make `Resolver::resolve_object` async

server/index-node/src/resolver.rs
Derives `Clone` for `IndexNodeResolver`, with no functional changes.
=> Derive `IndexNodeResolver`'s `Clone` implementation

graph/src/blockchain/polling_block_stream.rs
PollingBlockStreamContext.parent_ptr contained an expect that failed if the provider didn't return a parent pointer. Turn that panic into an error.
=> graph: Remove a possible crash from the polling block stream

graphql/src/execution/execution.rs, graphql/src/execution/resolver.rs, server/index-node/src/resolver.rs, server/index-node/src/schema.graphql
This new endpoint fills a need that several services (namely EBO and indexer agent) that rely on `graph-node` have, i.e. to fetch a block hash starting from the number. The underlying implementation bridges over to the configured data ingestor for the requested network, allowing these services to get this data directly from `graph-node`.
I've used some declarative macro idiosyncracy to quickly abstract over `BlockchainMap` items with different concrete types.
```graphql
{
blockHashFromNumber(network: "mainnet", blockNumber: 15239780)
}
```
=> `index-node` endpoint to get a hash from a block number

graphql/src/schema/api.rs, graphql/src/store/query.rs, graphql/tests/query.rs, store/postgres/src/relational_queries.rs
Continuation of #3184, adds support for interfaces.
<details>
<summary>GraphQL Schema</summary>
```graphql
type Musician @entity {
id: ID!
name: String!
mainBand: Band
bands: [Band!]!
writtenSongs: [Song]! @derivedFrom(field: "writtenBy")
}
type Band @entity {
id: ID!
name: String!
members: [Musician!]! @derivedFrom(field: "bands")
reviews: [BandReview] @derivedFrom(field: "band")
originalSongs: [Song!]!
}
type Song @entity {
id: ID!
title: String!
writtenBy: Musician!
publisher: Publisher!
band: Band @derivedFrom(field: "originalSongs")
reviews: [SongReview] @derivedFrom(field: "song")
}
type SongStat @entity {
id: ID!
song: Song @derivedFrom(field: "id")
played: Int!
}
type Publisher {
id: Bytes!
}
interface Review {
id: ID!
body: String!
author: User!
}
type SongReview implements …
```
=> feat(graph,graphql): filter by child entity (interfaces)

graph/src/components/store/mod.rs, node/src/bin/manager.rs, node/src/manager/commands/mod.rs, node/src/manager/commands/prune.rs, node/src/manager/commands/stats.rs, store/postgres/src/catalog.rs, store/postgres/src/copy.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/lib.rs, store/postgres/src/relational.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs, store/postgres/src/relational/prune.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/graft.rs
This PR resolves issue #3665 and adds a command `graphman prune <deployment>` that removes all history from a deployment before a given block. By default, that block is 10,000 blocks before the current subgraph head. After pruning, the deployment can only be queried at block numbers at least as high as that block.
Here's what it looks like when pruning something:
```
prune QmRuorV4Ck1sVdpfpAAwfYXnf3cfSkbDwZvvzWud9SH8Dg[130]
latest: 15461533
final: 15461283
earliest: 15451533
Analyzed 14 tables in 80s
table              |  entities  |  versions  |  ratio
-------------------------------+------------+------------+--------
add_liquidity_event            |      41750 |      41750 | 100.0%
eth_purchase_event             |    1156610 |    1156610 | 100.0%
exchange                       | …
```
=> Pruning of subgraphs

graph/src/components/store/traits.rs, store/postgres/src/subgraph_store.rs, store/postgres/src/writable.rs
So far, if the writer for a subgraph encounterd an error, it would stick around as 'poisoned' for as long as the process lived. That made it impossible to restart a subgraph (possibly after clearing some external error condition) With this change, `SubgraphStore.writable` will create a new writer if the old one has been poisoned.
=> store: Make it possible to restart a failed writer

graphql/src/execution/query.rs
Initial testing suggests that, after the recent improvement in graphql-tools, validations are now fast enough to not need such a cache.
=> graphql: Remove validation cache

docker/start
PR https://github.com/graphprotocol/graph-node/pull/3688 introduced a regression where the setting of BLOCK_INGESTOR had to be changed from unmangled to mangled.
Fixes https://github.com/graphprotocol/graph-node/issues/3936
=> docker: Restore old behvior around BLOCK_INGESTOR

store/postgres/src/catalog.rs, store/postgres/src/copy.rs
Copying of subgraphs can create a lot of data to be replicated, which can make replicas fall hopelessly behind. With this change, the copy code checks whether there are replicas that are too far behind and backs off of copying for a bit to give them a chance to catch up.
=> store: Be considerate of replicas when copying

docker/Dockerfile, docs/config.md
`envsubst` takes care of all foreseeable templating needs that we might face for TOML configuration files.
From all `envsubst` implementations that I could find, I selected https://github.com/a8m/envsubst because it seemed to be the most complete and well adopted. More fully-fledged templating engines like http://www.confd.io/ are interesting but probably overkill.
Here's an example of a configuration pattern that `envsubst` can deal with, while our current variable expansion logic can't:
```toml
[chains.${CHAIN_0}]
shard = "${SHARD_0}"
provider = [ { label = "${CHAIN_0}", url = "${CHAIN_RPC_0}", features = ["${CHAIN_0_FEATURES}"] } ]
```
Closes #3946.
=> Ship `envsubst` with the Docker image to facilitate TOML templating

chain/ethereum/src/adapter.rs, chain/ethereum/src/trigger.rs, core/src/subgraph/error.rs, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, graph/src/data/query/error.rs, graph/src/data/subgraph/api_version.rs, graph/src/data/subgraph/mod.rs, graph/src/runtime/mod.rs, mock/src/metrics_registry.rs, runtime/wasm/src/asc_abi/class.rs, server/http/src/server.rs, server/index-node/src/server.rs, server/metrics/src/lib.rs
- Remove some hand-written `Clone` implementations and replace them with derives.
- Replace from `From` implementations for specific error variants and use the `#[from]` macro from `thiserror`.
=> Macro sugar: `#[derive(Clone)]` and `thiserror`'s `#[from]`

Cargo.lock, graph/Cargo.toml, graph/examples/stress.rs, node/Cargo.toml, node/src/bin/manager.rs, node/src/main.rs, node/src/opt.rs, store/postgres/Cargo.toml
The `structopt` crate is in maintenance mode, and authors suggest that users migrate to `clap`, which now has derive macros in a similar fashion.
This PR updates all `structopt` occurrences in favor of `clap` without altering the CLI usage.
=> graph,node: Migrate from structopt to clap v3

store/postgres/src/catalog.rs
The old query was returning just the millisecond portion of the lag, not the lag in milliseconds
=> store: Fix the query for retrieving replication lag

Cargo.lock, NEWS.md, chain/arweave/Cargo.toml, chain/common/Cargo.toml, chain/cosmos/Cargo.toml, chain/ethereum/Cargo.toml, chain/near/Cargo.toml, chain/substreams/Cargo.toml, core/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, mock/Cargo.toml, node/Cargo.toml, runtime/derive/Cargo.toml, runtime/test/Cargo.toml, runtime/wasm/Cargo.toml, server/http/Cargo.toml, server/index-node/Cargo.toml, server/json-rpc/Cargo.toml, server/metrics/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml, store/test-store/Cargo.toml, tests/Cargo.toml
This is the first release candidate for `v0.28.0`. `NEWS.md` has been updated with the release notes from [this](https://github.com/graphprotocol/graph-node/compare/v0.27.0...1435fceb5840c479209c54330ce0dc6b5a3c1b6e) commit range.
=> Release `0.28.0-rc.0`

graph/src/blockchain/firehose_block_ingestor.rs, graph/src/blockchain/substreams_block_stream.rs
This would print the error with newlines, the best is to use `{:#}` to print with causes.
=> firehose: Dont use debug format on firehose errors

core/src/subgraph/instance_manager.rs, graph/src/env/mod.rs
Add a subgraph start check for number of dynamic data sources. If above the defined threshold, force static filters.
=> enable static filters for SGs with many dynamic datasource 

core/src/subgraph/instance_manager.rs, core/src/subgraph/loader.rs, core/src/subgraph/registrar.rs, graph/src/components/store/traits.rs, graph/src/data/subgraph/mod.rs, graph/src/data/subgraph/schema.rs, graph/src/util/error.rs, graphql/tests/query.rs, store/postgres/migrations/2022-09-19-161239_add-raw-manifest-column/down.sql, store/postgres/migrations/2022-09-19-161239_add-raw-manifest-column/up.sql, store/postgres/src/copy.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/detail.rs, store/postgres/src/dynds/private.rs, store/postgres/src/subgraph_store.rs, store/postgres/tests/graft.rs, store/postgres/tests/store.rs, store/postgres/tests/subgraph.rs, store/postgres/tests/writable.rs, store/test-store/src/store.rs, tests/integration-tests/data-source-revert/grafted.yaml, tests/integration-tests/typename/subgraph.yaml
Resolves #3960. This is done by adding a `raw_yaml` column to the `subgraph_manifest` table, and using it to map the manifest idx from the source to the destination deployment. For existing deployments this column is migrated in the instance manager on subgraph startup. This also changes a bit the order in which things are done in the instance manager, now the subgraph is first fetched from IPFS before being started in the store.
The `data-source-revert` integration test was modified to also test this.
=> fix: Allow grafts to add data sources

core/src/subgraph/runner.rs
This can be useful when testing.
=> fix: Ensure retry backoff base is less than ceil

store/postgres/src/deployment_store.rs
As an alternative to the full revert in #4026, this just checks if the graft is done before calling all of the graft procedures which would be noops.
=> fix(store): Check if graft is done

node/src/bin/manager.rs, node/src/manager/commands/database.rs, node/src/manager/commands/mod.rs, node/src/store_builder.rs, store/postgres/src/catalog.rs, store/postgres/src/connection_pool.rs, store/postgres/src/relational/prune.rs
In the hosted service, restarting a node can take a long time. That can be almost entirely attributed to the fact that we rebuild the fdw mappings between shards on every start, and sometimes nodes have to wait for other activity to stop before that rebuild can happen. We rebuild the mappings on every start since we don't properly propagate whether the schema in a shard was changed to the other shards that import tables from that shard.
With this PR, the fdw mappings are only rebuilt if there were actually schema changes, i.e., in the vast majority of cases the rebuild can be skipped and startups will be much faster.
Since interrupting `graph-node` startup at the wrong time (right after migrations ran but before remapping is done) can cause fdw mappings to not be updated, `graphman` now …
=> Improve how we apply database migrations

store/postgres/src/deployment_store.rs, store/postgres/src/writable.rs
First commit reverts most of https://github.com/graphprotocol/graph-node/commit/0c4417e50da3ea40d492ee2373bbfdf82ec09f0f, which was misguided since the graft code is already only called if the graft is pending.
Second commit fixes cross shard grafting, by not assuming that `load_deployment` will succeed on the same `DeploymentStore` as the one in which the source subgraph is deployed. 
=> Fix cross shard graft

server/http/src/service.rs
Currently it returns a graphiql which returns 404 from all queries. I don't think that's useful for anyone.
=> fix(server): Make '/subgraphs' return 404

chain/ethereum/src/ethereum_adapter.rs
It's wild but we might have seen this happen.
=> fix(ingestor): Sanity check for receipt hash

node/src/bin/manager.rs
Using `-h` here conflicts with the autogenerated help option, and it seems better to keep `-h` for help even though `-y` for history is a bit goofy
The change is necessary since `graphman prune -h ..` panics since `-h` is short for both help and history
=> node: Change short for `graphman prune --history` to `-y`

docker/start
Fixes the regression introduced with https://github.com/graphprotocol/graph-node/pull/3964.
=> Forcefully set `DISABLE_BLOCK_INGESTOR=false` for combined nodes

docs/graphman.md, node/src/bin/manager.rs, node/src/manager/commands/check_blocks.rs, node/src/manager/commands/drop.rs, node/src/manager/commands/info.rs, node/src/manager/commands/mod.rs, node/src/manager/commands/remove.rs, node/src/manager/commands/unused_deployments.rs, node/src/manager/deployment.rs, node/src/manager/mod.rs, node/src/manager/prompt.rs
Introduces a new graphman command to promptly delete all data from a deployment, even if it is running.
TODO:
=> graphman: new command to hastly delete a subgraph

docker/start
The fix in https://github.com/graphprotocol/graph-node/pull/4046 was not working at all due to wrongful assumptions about `structopt`'s parsing logic.
=> Correctly unset `DISABLE_BLOCK_INGESTOR` for `combined-node`'s

Cargo.lock, NEWS.md, chain/arweave/Cargo.toml, chain/common/Cargo.toml, chain/cosmos/Cargo.toml, chain/ethereum/Cargo.toml, chain/near/Cargo.toml, chain/substreams/Cargo.toml, core/Cargo.toml, graph/Cargo.toml, graphql/Cargo.toml, mock/Cargo.toml, node/Cargo.toml, runtime/derive/Cargo.toml, runtime/test/Cargo.toml, runtime/wasm/Cargo.toml, server/http/Cargo.toml, server/index-node/Cargo.toml, server/json-rpc/Cargo.toml, server/metrics/Cargo.toml, server/websocket/Cargo.toml, store/postgres/Cargo.toml, store/test-store/Cargo.toml, tests/Cargo.toml
Cargo version updates and release notes for `v0.28.1` and `v0.28.2`, which until now were confined in their respective branches.
=> Release notes for `v0.28.1` and `v0.28.2` patches

store/postgres/src/primary.rs
In the hosted service, we have a large number of subgraphs without a current (or pending) version. Mirroring that data doesn't really serve a purpose since the mirror tables are only needed to respond to queries when the primary is down, and a subgraph without a current version will never respond to a query.
=> store: Reduce the amount of data getting mirrored from the primary

store/postgres/src/advisory_lock.rs, store/postgres/src/deployment.rs
We used 'select for update' to lock a deployment against concurrent writes. It seems that that has bad consequences for performance in general; advisory locks are more lightweight than locking table rows, hopefully using them here will help write performance.
=> store: Use a different locking strategy for deployments

core/src/subgraph/instance_manager.rs, core/src/subgraph/provider.rs, graph/src/components/store/traits.rs, graph/src/components/subgraph/instance_manager.rs, graph/src/util/timed_cache.rs, store/postgres/src/deployment.rs, store/postgres/src/relational.rs, store/postgres/src/subgraph_store.rs, store/postgres/src/writable.rs
In development and similar settings, often a subgraph gets deleted, completely removed and then immediately redeployed. This usually fails because of some internal caches that `graph-node` keeps. This PR removes these failures on indexing nodes. If there are dedicated query nodes, they will still not pick up the deployment until their internal caches get updated (by default in at most 5 minutes) Installations that use a single node, or when the main concern is the index node, will no longer be affected by this cache issue.
=> Handle rapid deletion and recreation of subgraphs more gracefully

node/src/bin/manager.rs, node/src/chain.rs, node/src/main.rs, node/src/manager/commands/config.rs, node/src/manager/commands/run.rs
https://github.com/graphprotocol/graph-node/pull/3079 introduced some code duplication between `manager/run.rs` and `main.rs`, the intention was to fix things in an upcoming PR but we never came around to it.
=> Code reuse between `graphman` and `graph-node`

docs/graphman.md, node/src/bin/manager.rs, node/src/manager/commands/check_blocks.rs
=> Add `--delete-duplicates` flag to `graphman check-blocks`

node/src/bin/manager.rs, node/src/manager/commands/database.rs, store/postgres/src/connection_pool.rs
The current code fails when adding a new shard since it tries to issue a bunch of DDL against replicas. This PR fixes that, and makes the `graphman database remap` command more usable.
=> Fixes to how we map/remap shards into other shards

chain/arweave/src/chain.rs, chain/cosmos/src/chain.rs, chain/ethereum/examples/firehose.rs, chain/ethereum/src/chain.rs, chain/near/src/chain.rs, chain/substreams/examples/substreams.rs, chain/substreams/src/block_stream.rs, core/src/subgraph/runner.rs, core/src/subgraph/stream.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/components/metrics/subgraph.rs, graph/src/firehose/endpoints.rs, node/src/chain.rs, node/src/config.rs, tests/src/fixture/ethereum.rs
Fixes https://github.com/graphprotocol/graph-node/issues/3879
=> firehose connection loadbalance

docker/Dockerfile
Closes https://github.com/graphprotocol/graph-node/issues/3863.
=> Use `bullseye-slim` as base image

.dockerignore, docker/Dockerfile
Cargo is not very Docker-friendly by default and even a small change to any source file results in rebuilding the whole dependency tree. There's several known workarounds for this behavior, most of which boil down to "build the dependencies separately from the workspace, so that they get placed in a different caching layer".
[`cargo-chef`](https://github.com/LukeMathWalker/cargo-chef) is a simple tool that fits our use case: it creates a recipe of all dependencies from both `Cargo.toml` and `Cargo.lock`, builds those, and then lets you build the rest of your workspace with a normal `cargo build` that leverages Docker's cache. All builds that don't alter our dependency list will be faster.
This PR also removes `rustfmt` from the `graph-node-build` stage, which doesn't seem to be necessary.
=> Make Docker builds faster by caching dependencies

docker/docker-compose.yml
We are mounting our volume at `/var/lib/postgresql/data` while telling the container to use `/data/postgres` instead, fix the inconsistency so db persistency works as expected.
=> fix(docker): incorrect config PGDATA

chain/ethereum/src/codec.rs
RPC endpoint does not return the "to" address in a transaction with a CREATE call as the main call.
This patch makes the firehose behave the same way.
Example subgraphs that showed different POIs on their first block between firehose and RPC, that are fixed with this patch:
* QmVaFg6W4vofpNSsMNVx1SNDn4n8bQm9ou95JH6FDiKqQ1
* QmamFNdNEe8M6Gwo831LrxwAUSGswJ1cfjHyKvne7EsTy1
=> firehose: remove 'to' address on eth trx when root call is CREATE

.github/workflows/ci.yml, rust-toolchain.toml
Would avoid bug reports like https://github.com/graphprotocol/graph-node/issues/4097 and https://github.com/graphprotocol/graph-node/issues/3230 in the future.
=> Use a `rust-toolchain.toml` to simplify CI and minimize confusion

.github/workflows/ci.yml, tests/tests/parallel_tests.rs
- Switch to `swatinem/rust-cache@v2` for caching Cargo dependencies, which automatically takes care of many subtleties for us and caches as much as possible without reusing artifacts which it shouldn't.
- Set `RUSTFLAGS` as a job-wide environment variable, thus ensuring it becomes part of the cache key.
- Cache `yarn` dependencies - not sure how effective this will be, maybe we'll remove it if it doesn't help.
- Run integration tests concurrently. This is a big one and should help quite a bit, @tilacog the integration testing framework still supports concurrent tests without issues, correct? Setting this to `N_CONCURRENT_TESTS` to 4 because it seems to get the best times out of the GitHub runners. Setting it too high (e.g. 15, the default) results in starvation and the job takes too long. …
=> Make our CI faster

docker/README.md
I've encountered this while using the docker-compose in my linux machine.
The linux specific instructions in the README are no longer needed as per fixes in https://github.com/graphprotocol/graph-node/pull/3031
=> doc: remove linux specific instructions in docker readme

Cargo.lock, core/Cargo.toml, core/src/polling_monitor/ipfs_service.rs, core/src/polling_monitor/mod.rs, core/src/subgraph/context.rs, core/src/subgraph/instance_manager.rs, docs/environment-variables.md, graph/src/env/mappings.rs, graph/src/ipfs_client.rs, graph/src/util/monitored.rs, node/src/main.rs, node/src/manager/commands/run.rs, tests/src/fixture.rs
Resolves https://github.com/graphprotocol/graph-node/issues/4088.
The first commit is a fix for metrics.
The second refactors the ipfs service and adds a rate limit. The refactor seeks to better use tower composability and built-ins.
The third adds a backoff to errored requests in the polling monitor.
=> Ipfs polling rate limiting and backoff from errors

docs/graphman.md, graph/src/components/store/traits.rs, node/src/bin/manager.rs, node/src/manager/commands/chain.rs, store/postgres/src/chain_store.rs, tests/tests/runner.rs
=> graphman command for clearing the call cache for a given chain

Cargo.lock, core/src/polling_monitor/mod.rs, tests/tests/runner.rs
The tower bug that caused a deadlock in `call_all` was fixed in https://github.com/tower-rs/tower/pull/709. This bug surfaced after the refactors in https://github.com/graphprotocol/graph-node/pull/4117. A test in graph node was also added.
=> fix(offchain): Update tower to fix polling monitor deadlock

runtime/wasm/src/host_exports.rs
This `network` value is not taken directly from the data source but from the network for the whole subgraph. This is a relevant distinction because offchain data sources don't have a network.
=> refactor(runtime): More precise variable name

node/Cargo.toml, rust-toolchain.toml
We're currently enforcing the same `rustc` version all across the codebase (1.64). However, when setting `rust-version` in `Cargo.toml` instead of `rust-toolchain.toml`, we now allow all `rustc` versions that are 1.64 *or higher*.
=> Use `rust-version` to specify minimum supported `rustc`

graph/src/components/store/mod.rs, node/src/manager/commands/prune.rs, store/postgres/src/advisory_lock.rs, store/postgres/src/catalog.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/primary.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs, store/postgres/src/relational/prune.rs
The pruning code could cause long running transactions which are problematic because they cause bloat in frequently updated tables, most notably `subgraph_deployment`. This PR changes the pruning code to perform all operations in transactions that are time-limited (no more than 5 minutes)
=> Improve pruning

tests/integration-tests/api-version-v0-0-4/package.json, tests/integration-tests/data-source-revert/package.json, tests/integration-tests/dynamic-data-source/package.json, tests/integration-tests/fatal-error/package.json, tests/integration-tests/file-data-sources/package.json, tests/integration-tests/ganache-reverts/package.json, tests/integration-tests/host-exports/package.json, tests/integration-tests/non-fatal-errors/package.json, tests/integration-tests/overloaded-contract-functions/package.json, tests/integration-tests/poi-for-failed-subgraph/package.json, tests/integration-tests/remove-then-update/package.json, tests/integration-tests/typename/package.json, tests/integration-tests/value-roundtrip/package.json
So we don't leave the directory with dirty changes.
=> Skip migrations in integration tests

docs/environment-variables.md, graph/src/env/store.rs, store/postgres/src/copy.rs, store/postgres/src/relational_queries.rs
Only the second one, making the target duration for batch operations configurable, is somewhat interesting
=> Two simple config changes

docs/implementation/metadata.md, graph/src/data/subgraph/schema.rs, store/postgres/migrations/2022-11-03-213140_drop_earliest_block/down.sql, store/postgres/migrations/2022-11-03-213140_drop_earliest_block/up.sql, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/detail.rs, store/postgres/src/subgraph_store.rs
These columns weren't really used since PR #3673 but left in place in case we needed to go back to them. This PR completely removes them.
=> Remove `subgraph_deployment.earliest_ethereum_block_*`

chain/ethereum/src/ethereum_adapter.rs
Fix #4130 
Prevent deterministic issue by taking the decision to *always* remove failed transactions from call handlers.
=> skip v0_0_5 check: always remove unsucessful trxs on call handlers

store/postgres/src/relational/prune.rs
The change in aea5b577 has a logic error in that we look at a fixed number of rows from the table, filter out the ones we don't need to copy, and then insert the remaining rows. The error is that the logic assumes that if we do not insert any rows that we are done with copying, but that's wrong, since not inserting rows now just means that no rows in the batch needed to be copied even though a subsequent batch might still have such rows.
This reverts commit aea5b577db0fc5f08e8de17267c859186d917448.
=> store: Go back to the less clever but correct way of pruning

docs/environment-variables.md, graph/src/env/graphql.rs, graphql/src/schema/api.rs, graphql/src/schema/ast.rs, graphql/src/store/query.rs, graphql/tests/query.rs
introduces alternative syntax for doing `AND/OR` filters.
Generated filter will have these new types
```graphql
input Proposal_fitler {
id: ID
collection: String
and: [Proposal_filter]
or: [Proposal_filter]
}
```
1. using multiple AND filters
```graphql
query {
proposals(
where: { and: [{ id_in: "111" }, { collection_contains_nocase: "a" }] }
) {
id
}
}
```
2. Using multiple OR filters
```graphql
query {
proposals(
where: { or: [{ id_in: "111" }, { collection_contains_nocase: "a" }] }
) {
id
}
}
```
3. Using AND/OR combined
```graphql
query {
proposals(
where: {
or: [{ id_in: "111" }, { collection_contains_nocase: "a" }]
and: [{ owner_contains: "0x2" }]
}
) {
id
}
}
```
Downside with this approach is users can still have nested `AND`/`OR` which can be quite expensive example
```graphql …
```
=> graphql: AND/OR filter

core/src/subgraph/runner.rs, graph/src/data/subgraph/schema.rs, graph/src/data_source/mod.rs, graph/src/data_source/offchain.rs, runtime/wasm/src/host_exports.rs, store/postgres/src/subgraph_store.rs, tests/integration-tests/file-data-sources/src/mapping.ts, tests/integration-tests/file-data-sources/subgraph.yaml, tests/src/fixture.rs, tests/tests/runner.rs
First part of #3770.
This enforces that file data sources can only call `entity.get`, `entity.set` and `entity.remove` on entity types they've declared in the `entities:` array in the manifest.
=> fix(offchain): Enforce entities list on offchain data sources

core/src/subgraph/runner.rs, graph/src/components/store/entity_cache.rs, graph/src/components/store/mod.rs, graph/src/components/subgraph/instance.rs
This is now tracked directly in the `BlockState`, so that the entity cache is only about entities. Also renames the module from `cache` to `entity_cache` and moves out the unrelated `CachedEthereumCall`.
=> Refactor: move data_sources out of EntityCache

store/postgres/src/subgraph_store.rs
I noticed that the `./docker/build.sh` script currently fails due to a Rust [E0599](https://doc.rust-lang.org/error_codes/E0599.html) error. I initially thought I had an isolated issue related to my own machine (M1 Mac, Mac OS Ventura 13.0.1) but then realized the method in question was [introduced in a recent PR](https://github.com/graphprotocol/graph-node/commit/a8d184c87555967769e71c7a8c2bfb6f0e070b91#diff-fbebe8c1d9a66d5a40732d736208ae22810af9d9f5c321c0d7da9f23d3d8385eR835) to this repository, which made me suspect the `./docker/build/sh` may not have been tested with the new code.
In this PR I'm introducing a proposal to fix the `./docker/build.sh` script by including the `SubgraphStore::status_for_id` method in the default compilation step. I considered adding a new compilation …
=> Fix `./docker/build.sh`

.github/workflows/ci.yml
They were removed in https://github.com/graphprotocol/graph-node/pull/4099 but we want to reintroduce them. See https://github.com/graphprotocol/graph-node/pull/4166.
=> `cargo check --release` in the CI

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/stale.yml
Sometimes jobs hang and we don't want to waste compute.
=> Set reasonable timeouts for GH Actions jobs

.github/workflows/stale.yml
The `stale` GH Action works, but it's marked as failed because of a borked final step that invokes `echo`.
=> Fix non-0 return code of `stale` action

chain/substreams/src/block_stream.rs, graph/src/blockchain/substreams_block_stream.rs
Fixes https://github.com/graphprotocol/graph-node/issues/4195
This feature was omitted in substreams initially, but it is needed for `--start-block` feature, rewind, and probably in other "recovery" scenarios where we cannot start from a cursor.
=> ensure substreams-based-subgraphs can be started at specific block or rewound

node/src/bin/manager.rs, node/src/manager/commands/stats.rs, store/postgres/src/block_range.rs, store/postgres/src/catalog.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/subgraph_store.rs
Show, set or reset the target for a deployment. The statistics target determines how much of a table Postgres will sample when it analyzes a table. This can be particularly beneficial when Postgres chooses suboptimal query plans for some queries. Increasing the target will make analyzing tables take longer and will require more space in Postgres' internal statistics storage.
See also https://www.postgresql.org/docs/15/planner-stats.html#id-1.5.13.5.3
=> Manage the statistics target for a deployment

NEWS.md, store/postgres/src/catalog.rs, store/postgres/src/connection_pool.rs, store/postgres/src/primary.rs
This PR is a variation of PR #3671 It does two things:
* check that collation and ctype are set to `C` and that encoding is `UTF8`
* panic if this is an empty `graph-node` installation, otherwise log a warning
=> store/postgres: insist on a database with C locale

store/postgres/src/writable.rs
We already get this env. var. from `ENV_VARS` yet this `lazy_static!` survived the refactoring.
=> Remove dead code in a `lazy_static!`

.github/workflows/ci.yml, docker/docker-compose.yml, store/postgres/src/connection_pool.rs, tests/tests/common/docker.rs
PR #4163 introduced a locale check, which runs before migrations are applied.
This PR alters this check, so it runs immediately after migrations.
=> Fix: run locale check after migrations

Cargo.lock, chain/ethereum/src/codec.rs, graph/src/blockchain/mod.rs, node/src/main.rs, store/postgres/tests/store.rs, store/test-store/Cargo.toml, store/test-store/src/block_store.rs
Fixes https://github.com/graphprotocol/graph-node/issues/4059
=> enable firehose eth block ingestor

chain/substreams/src/mapper.rs, graph/proto/substreams.proto, graph/src/blockchain/substreams_block_stream.rs, graph/src/substreams/sf.substreams.v1.rs
The production mode is required to benefits from automatic backprocessing and downloading of block scoped data message as they are produced. This will drastically improve the ingestion speed of a substreams (time to gather some metrics!).
Updated also the instructions to re-generate the `substreams.proto` file with more instructions of how we do it.
=> Updated `Substreams` to latest version of Protobuf definition and activated `ProductionMode` by default

graph/src/blockchain/substreams_block_stream.rs
The `request.clone()` does not correctly use the `latest_cursor` value which is the valid up to date in memory cursor to use on re-connection. This led to poisining error in `graph-node` where the same block was processed multiple time because the cursor was not correctly used.
Fixed by moving the request creation directly where it's needed which will use the correct up to date `latest_cursor` value now.
=> The `SubstreamsBlockStream` was using `request.clone()` side stepping latest cursor value

graph/src/components/store/traits.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs
Closes https://github.com/graphprotocol/graph-node/issues/4206
=> fail when ens rainbow not present

docker/Dockerfile
the `CMD start` is equal with `CMD sh -c start`, so pid of graph node is not 1
#4186
=> docker: use exec form for CMD directive

Cargo.lock, graph/src/components/graphql.rs, graphql/Cargo.toml, graphql/src/execution/query.rs, graphql/src/metrics.rs, server/http/src/service.rs, server/http/tests/server.rs, server/index-node/src/service.rs
This PR adds a Counter metric for Prom, which counts validation error instances, with the `deployment_id` and `error_code` metrics. 
This is needed because we can't use/search/aggregate the logs of validations in Grafana (queries are very limited). Using metrics instead of logs should allow us to get better insights.
=> graph, graphql: expose metrics for GraphQL validations failures

docker/Dockerfile, node/Cargo.toml, rust-toolchain.toml
1. Removes `cargo-chef` from the Docker image, because there's no easy way to do layer caching in Cloudbuild. With this, CloudBuild times are back to normal.
2. After making sure that a new Rust release wouldn't break our build or invalidate our GH Actions caches, I feel confident reverting https://github.com/graphprotocol/graph-node/pull/4127.
See the `7ad9b110-50b9-4d59-a57f-4b9b55cb8dd2` build for an example build.
=> Remove usage of `cargo-chef`

core/tests/interfaces.rs, docs/environment-variables.md, graph/src/components/store/mod.rs, graph/src/data/query/query.rs, graph/src/data/query/result.rs, graph/src/data/query/trace.rs, graph/src/env/graphql.rs, graphql/src/execution/execution.rs, graphql/src/query/mod.rs, graphql/src/runner.rs, graphql/src/store/prefetch.rs, graphql/src/subscription/mod.rs, graphql/tests/introspection.rs, graphql/tests/query.rs, node/src/manager/commands/query.rs, server/http/src/request.rs, server/http/src/service.rs, server/index-node/src/service.rs, server/websocket/src/connection.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/tests/relational.rs, store/postgres/tests/relational_bytes.rs, store/test-store/src/store.rs, tests/src/fixture.rs
With these changes, if the request header `X-GraphTraceQuery` is set to the right value, the response to a GraphQL query will include a trace of the SQL queries that were run to generate the GraphQL response. That trace looks like
```
{
"data": { .. },
"trace": {
"query": "<GraphQL query>",
"query_id": "e89d81e9ce262e07-d019a5d7d56a8920",
"block": 10096796,
"elapsed_ms": 6,
"pairs": {
"query": "/* controller='filter',application='sgd44',route='e89d81e9ce262e07-d019a5d7d56a8920',action='10096796' */\tselect 'Pair' as entity, to_jsonb(c.*) as data from (select  * \t  from \"sgd44\".\"pair\" c\t where c.block_range @> $1\t\t order by \"id\", block_range\t limit 2) c -- binds: [10096796]",
"elapsed_ms": 0,
"entity_count": 2,
"token0": {
"query": "<SQL query>",
"elapsed_ms": 0,
"entity_count": …
```
=> Allow retrieving query traces over HTTP

docs/subgraph-manifest.md
Looks like the link to the graph-cli repo for the updated list of supported networks was obsolete. Updating the link to point to the current list.
=> Updated link to graph-cli networks list link

graph/src/data/query/error.rs
It seems that `ValueParseError` should be attestable. Feel free to quickly scan through to check for other miscategorizations.
=> Fix attestability of ValueParseError, EnumCoercionError, ScalarCoercionError

docker/start
When using Infura as an IPFS provider, they require you authenticate the requests either by providing an Authorization header or by using basic authentication.
As graph-node doesn't support authentication by header for IPFS, the only way to use Infura is to use basic authentication.
The URL looks like this:
```
https://project_id:project_secret@ipfs.infura.io:5001/
```
The docker start script doesn't take into account that there could be a basic auth user and pass in the IPFS url and parses it incorrectly making the container stall for a long time on startup without any output. When used in K8S with liveness probes, the service keeps restarting.
I also added support for uppercase letters (`HTTP://LOCALHOST`).
I tested it with the following types or URLs and it seems to work properly:
``` …
```
=> docker: adds support for IPFS auth urls

Cargo.lock, Cargo.toml, NEWS.md
Supersedes https://github.com/graphprotocol/graph-node/pull/4199.
=> `v0.29.0` release notes, `NEWS.md` and Cargo package version

graph/src/env/store.rs, rust-toolchain.toml, store/postgres/src/block_store.rs, store/postgres/src/chain_store.rs
Closes https://github.com/graphprotocol/graph-node/issues/4154.
=> Cache recent blocks in memory to reduce load on the db

docs/environment-variables.md, node/src/opt.rs
Supersedes https://github.com/graphprotocol/graph-node/pull/3408 (rebased and added `GRAPH_` prefix to the env. vars.).
=> Env. vars. for forking

store/postgres/migrations/2023-01-24-192319_chain_size_view/down.sql, store/postgres/migrations/2023-01-24-192319_chain_size_view/up.sql
This is just a convenience for admins to make it easier to understand how storage is used in the DB (similar to the already existing `info.subgraph_sizes` and `info.table_sizes`)
=> store: Add a materialized view 'info.chain_sizes'

graph/src/log/elastic.rs, graph/src/log/factory.rs, node/src/main.rs, node/src/manager/commands/run.rs, server/http/tests/server.rs, tests/src/fixture.rs, tests/src/fixture/ethereum.rs
This log is very noisy, and can perfectly be substituted by a metric.
=> improve(metrics): Turn "Flushing logs to Elasticsearch" log into metric

store/test-store/devel/docker-compose.yml
while working on tests for #3214 I had to make this change. But useful to just land it upstream since it is unrelated to that PR
=> store(test-store): use C locale for DB

chain/ethereum/examples/firehose.rs, chain/substreams/examples/substreams.rs, graph/src/firehose/endpoints.rs, node/src/chain.rs, node/src/config.rs, tests/src/fixture/ethereum.rs
- Fixes issue #4338
- Adds rules to ProviderDetails::Firehose
- FirehoseEndpoints::random now checks for capacity before returning an endpoint
=> Extend provider load control (match config) to substreams

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/network.rs, chain/ethereum/src/runtime/runtime_adapter.rs, node/resources/tests/full_config.toml, node/src/chain.rs, node/src/config.rs, tests/src/fixture/ethereum.rs
- Always prefer web3call adapter for runtime adapter on ethereum if available
- Prevent non call functions on call_only adapters
- Add web3call type configuration
- Require Web3Call endpoints to have the "archive" feature
=> Add support for Web3Call adapter

docs/environment-variables.md, graph/src/components/store/mod.rs, graph/src/env/graphql.rs, graph/src/lib.rs, graphql/src/schema/api.rs, graphql/src/store/query.rs, graphql/tests/query.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
#3737
Given this schema:
```graphql
type Country @entity {
id: ID!
capital: City!
cities: [City!]!
}
type City @entity {
id: ID!
name: String
population: Int
landmarks: [String!]!
}
```
It adds fields of child entity to `*_orderBy` enum:
```diff
enum Country_orderBy {
id
capital
cities
+  capital__id
+  capital__name
+  capital__population
}
```
=> graph,graphql,store: nested sorting

store/postgres/src/deployment_store.rs
The old behavior would throw away all the error details which contained much more useful information than the error that was actually returned.
=> store: Do not intercept error from layout.delete

chain/ethereum/src/network.rs, docs/config.md, graph/src/firehose/endpoints.rs, node/src/chain.rs, node/src/config.rs
- Set 0 for Disabled
- Omitted hosts can are disabled if list of rules is not empty
- Empty rules = Unlimited
- Limit != 0 does exactly what you'd think it does
=> Fix limit handling on rpc configuration

chain/arweave/src/chain.rs, chain/cosmos/src/chain.rs, chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/env.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/network.rs, chain/ethereum/src/runtime/runtime_adapter.rs, chain/near/src/chain.rs, chain/substreams/src/block_stream.rs, chain/substreams/src/chain.rs, core/src/subgraph/stream.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/client.rs, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, node/src/main.rs, node/src/manager/commands/run.rs, tests/src/fixture/ethereum.rs
- Remove IS_FIREHOSE_PREFERRED env var as it was being poorly handled in different parts of the code
- Introduce EthereumClient which decouples the decision of which endpoint to use
- Remove is_firehose_supported in favour of checking the endpoint type
- Building blocks to refactor the ingestor, block stream building and TriggersAdapter for firehose
- Try to fix the flaky createdb operation
=> Refactor firehose/rpc decision to happen earlier in the flow

.cargo/config.toml, .github/workflows/ci.yml, chain/ethereum/src/adapter.rs, chain/ethereum/src/chain.rs, chain/ethereum/src/ethereum_adapter.rs, graph/src/data/graphql/effort.rs, graph/src/data/store/mod.rs, graph/src/data/subgraph/api_version.rs, graph/src/firehose/endpoints.rs, graphql/src/schema/ast.rs, graphql/src/store/query.rs, node/src/config.rs, node/src/main.rs, node/src/manager/commands/copy.rs, node/src/manager/commands/prune.rs, node/src/manager/commands/txn_speed.rs, runtime/derive/src/generate_array_type.rs, runtime/derive/src/generate_network_type_id.rs, runtime/test/src/test.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, tests/src/docker_utils.rs, tests/tests/integration_tests.rs
Now that we've merged https://github.com/graphprotocol/graph-node/pull/4349, we can start enforcing Clippy on the CI. The defaults look like a good choice for now.
=> Enforce Clippy in the CI

docs/implementation/metadata.md, node/src/bin/manager.rs, node/src/manager/commands/copy.rs, store/postgres/migrations/2023-02-15-184255_add_manifest_on_sync/down.sql, store/postgres/migrations/2023-02-15-184255_add_manifest_on_sync/up.sql, store/postgres/src/copy.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/detail.rs, store/postgres/src/lib.rs, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs, store/postgres/src/writable.rs, store/postgres/tests/graft.rs
Fixes #4371 (which also describes how this is intended to be used)
=> Implement moving of subgraphs

docs/environment-variables.md, graph/src/data/subgraph/mod.rs, graph/src/env/graphql.rs, graph/src/env/mod.rs, node/src/main.rs
- `SUBSCRIPTION_THROTTLE_INTERVAL` is currently not referenced anywhere in the code, so it's safe to delete.
- `GRAPH_DISABLE_GRAFTS` is a remnant from the dark old days when we grafting was still in development and performance was unacceptable, so we wanted to disable it on the hosted service. I think it's safe to delete now.
- We don't use `unsafe_env_vars`, it's effectively dead code, so it should be removed.
=> Remove unused env. vars.

core/src/subgraph/context.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/runner.rs, graph/src/components/metrics/subgraph.rs
- Always modify alive instances alongside metrics
Ran locally with a forced error, the count is now correctly decreased while waiting for the retry sleep
=> Improve running subgraph metric accuracy

.github/workflows/ci.yml, core/src/subgraph/registrar.rs, graph/src/components/store/traits.rs, graphql/tests/query.rs, store/postgres/src/subgraph_store.rs
The reassign_subgraph JSON-RPC call will fail if a deployment exists in multiple shards. To disambiguate that, change the call so that it only affects the active deployment.
Fixes https://github.com/graphprotocol/graph-node/issues/4394
=> all: Indicate whether to only locate active deployment

node/src/bin/manager.rs, node/src/manager/deployment.rs
=> Add a flag to graphman to list all deployments

README.md
The protobuf-compiler is needed to build the full project, it should be added as prerequisites in README.md.
=> add protobuf-compiler to prerequisites

store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs
We used to send very clever SQL to the database on every block to make it possible to force a recount of the entities in a subgraph by setting the entity_count to -1 or null. The SQL that got sent could be very complicated, and might introduce some overhead.
This facility hasn't been used in a very long time, and since it might cause an overhead, it's better to remove it. If recounting entities is something that we do need, it should be added as a `graphman` command and not be something that might cause headaches on the busiest code path.
=> store: Remove ability to recount entities

chain/arweave/src/chain.rs, chain/cosmos/src/chain.rs, chain/near/src/chain.rs, graph/src/blockchain/builder.rs, graph/src/blockchain/mod.rs, node/src/main.rs
NEAR, Cosmos and Arweave all share the same `Chain::new` type signature. By putting that method into a trait, we can reduce code duplication in the `_networks_as_chains` family of functions in `main.rs`.
=> `BlockchainBuilder` abstraction to simplify instantiating chains

graph/src/util/backoff.rs
This PR fixes an issue with `backoff` left shift overflow #4420 
Also adds tests for that struct.
=> graph: fix backoff overflow

node/src/manager/commands/assign.rs, store/postgres/src/lib.rs, store/postgres/src/primary.rs
Making a sharp edge a little less sharp by warning users that they might have typoed a node name
=> node, store: Warn if reassigning to a new node

chain/cosmos/src/trigger.rs
1. `CheapClone::cheap_clone` mirrors `Clone` functionality by default, so it rarely needs to use custom code.
2. ~~Although not immediately obvious, I'm pretty sure the custom implementation of `PartialEq` is identical to what `derive` what do, so I'm removing it.~~ nvm, I don't want to deal with determinism issues at this time so I'll leave it as it is.
=> Refactor some code in Cosmos' `trigger.rs`

Cargo.lock, chain/ethereum/examples/firehose.rs, chain/ethereum/src/chain.rs, chain/substreams/examples/substreams.rs, graph/Cargo.toml, graph/src/blockchain/client.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/endpoint.rs, graph/src/firehose/endpoints.rs, graph/src/firehose/interceptors.rs, graph/src/firehose/mod.rs, graph/src/firehose/sf.firehose.v2.rs, graph/src/lib.rs, node/src/chain.rs, node/src/config.rs, node/src/main.rs, node/src/manager/commands/run.rs, tests/src/fixture/ethereum.rs
Add a generic mechanism to count errors based on host url
=> graph: Add endpoint metrics

store/postgres/src/connection_pool.rs
So far we treated the Postgres error "no connection to the server" as not indicating that the database was not available. It's a little murky what exactly that error indicates, but it seems to indicate that an existing connection got killed, e.g., because the database crashed.
We now treat this as an indication that the database is not available, which will trigger the right action further up in the stack. For example, on indexing, db operations will be retried instead of causing the subgraph to fail. Queries will be aborted with an error message.
=> store: Treat 'no connection to the server' as db not available

chain/substreams/src/trigger.rs, core/src/subgraph/context.rs, core/src/subgraph/inputs.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/runner.rs, core/src/subgraph/trigger_processor.rs, graph/src/components/store/traits.rs, graph/src/components/subgraph/host.rs, graph/src/components/trigger_processor.rs, runtime/test/src/common.rs, runtime/wasm/src/host.rs, runtime/wasm/src/mapping.rs, runtime/wasm/src/module/mod.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/subgraph_store.rs
These changes make it so that an individual deployment can be set to log all store interactions to help diagnose problems with the deployment.
Right now, this is turned on by manipulating the database directly; if it turns out to be useful, we should add a `graphman` command to turn this on.
=> Add facilities to gte more details during indexing

graph/src/components/store/mod.rs, graphql/src/schema/api.rs, graphql/src/store/query.rs, graphql/tests/query.rs, store/postgres/src/relational_queries.rs
After some conversations in #4413, I splitted the PR and this is the filter for fulltext search queries.
This PR partially fixes #4412, at least the filter part.
There's also another issue #1823, where this PR can be useful.
As requested by @lutter in #4413, I added some tests for fulltext search and full text search filter.
=> Fulltext filter

graph/src/data/schema.rs, graph/src/data/subgraph/mod.rs
This removes code that allowed composing schemas; the feature was only implemented for schemas, but could never actually run queries against the composed schema. It's very unlikely that we will finish this and we should therefore remove the unneeded code.
=> Remove unfinished schema composition

NEWS.md, store/postgres/src/deployment_store.rs, store/postgres/src/jobs.rs, store/postgres/src/subgraph_store.rs
We have some materialized views that contain information about the size of various things in the database. So far, they had to be refreshed manually and could therefore fall out of sync by a lot.
With this change, they get refreshed automatically every 6 hours. For very large databases, a refresh takes a little over a minute.
=> Automatically refresh materialized views

node/src/bin/manager.rs, node/src/store_builder.rs, store/postgres/src/block_store.rs, store/postgres/src/chain_store.rs, store/postgres/src/lib.rs
Fixes #4391. These new metrics could help us with identifying and root-causing performance and load issues on the database.
=> Instrument `RecentBlocksCache` with metrics

graph/src/components/metrics/registry.rs
`MetricsRegistry` is intended to always be wrapped in an `Arc`, and never be cloned directly. Removing `derive(Clone)` makes this more clear, and it also allows us to remove some internal useless `Arc`s.
=> Make `MetricsRegistry` uncloneable

chain/substreams/src/data_source.rs, graph/src/blockchain/substreams_block_stream.rs
This fixes #4449 by choosing `initial_block` of the module provided in the manifest.
It also verifies that module name provided in the subgraph manifest exists in the substreams manifest and if not, `graph deploy` errors out rather than letting it deploy and then unsuccessfully retry RPC requests to the substreams endpoint.
=> graph: fix substreams `startBlock` selection

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
This PR removes the current GitHub issue template and replaces it with two [issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). One issue form is for bug reports, while the other is for feature requests. The goal would be to get more structured information out of our GitHub issues. Users still have the freedom to select a blank template if they don't wish to use any of the two premade templates.
I have deployed this feature in my personal fork of `graph-node`, here: https://github.com/neysofu/graph-node/issues/new/choose. Feel free to try it out.
=> Use GitHub issue forms

core/src/subgraph/runner.rs, graph/src/env/mod.rs, graph/src/util/backoff.rs
Implements #4474
Used by `SubgraphRunner` with default value = 0.2
=> Add jitter to `ExponentialBackoff`

.cargo/config.toml, Cargo.lock, node/Cargo.toml, node/src/main.rs, rust-toolchain.toml
- Rust 1.67 replaces `std::sync::mpsc` with the `crossbeam-channel` implementation, improving performance.
- Rust 1.68 introduces Cargo's new "sparse indexing protocol", which TL;DR reduces download times to https://crates.io and is especially useful for CI. It's not yet the default option, so I turned it on in our `.cargo/config.toml`.
I'm also removing `crossbeam-channel` and replacing it with `std::sync::mpsc`, since now they are effectively the same thing.
=> Upgrade to Rust 1.68.0

chain/arweave/src/runtime/abi.rs, chain/arweave/src/trigger.rs, chain/cosmos/src/runtime/abi.rs, chain/cosmos/src/trigger.rs, chain/ethereum/src/runtime/abi.rs, chain/ethereum/src/trigger.rs, chain/near/src/runtime/abi.rs, chain/near/src/trigger.rs, chain/substreams/src/trigger.rs, graph/src/components/subgraph/host.rs, graph/src/runtime/asc_heap.rs, graph/src/runtime/asc_ptr.rs, graph/src/runtime/mod.rs, runtime/derive/src/generate_array_type.rs, runtime/derive/src/generate_from_rust_type.rs, runtime/test/src/test_padding.rs, runtime/wasm/src/asc_abi/class.rs, runtime/wasm/src/asc_abi/v0_0_4.rs, runtime/wasm/src/asc_abi/v0_0_5.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/to_from/external.rs, runtime/wasm/src/to_from/mod.rs
Fixes https://github.com/graphprotocol/graph-node/issues/3576.
When a timeout happened when calling `asc_type_id` this was incorrectly classified as a deterministic error. And these timeouts where happening frequently in the wild. Fixing this required correctly classifying wasm traps returned by `asc_type_id`. The second commit is the actual fix, most of the diff is from all the signatures that needed to change.
=> Detect timeouts in asc_type_id

store/postgres/src/writable.rs
It's been a long-standing annoyance that the metrics for writing keep getting updated for synced subgraphs.
=> store: Disable collecting write metrics for synced deployments

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
The rendering of bug and feature descriptions with the new issue templates doesn't use Markdown (everything is monospace). This PR fixes it. I tested it on my fork of `graph-node`, see https://github.com/neysofu/graph-node/issues/75.
=> Fix Markdown rendering in issue templates

store/postgres/migrations/2023-03-28-004152_trigger_remap/down.sql, store/postgres/migrations/2023-03-28-004152_trigger_remap/up.sql, store/postgres/src/catalog.rs, store/postgres/src/connection_pool.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/dynds/shared.rs
Fixes https://github.com/graphprotocol/graph-node/issues/4496
=> Ensure `earliest_block` on copies is set correctly

Cargo.lock, chain/ethereum/Cargo.toml, chain/ethereum/src/adapter.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/network.rs, chain/ethereum/src/transport.rs, graph/src/blockchain/firehose_block_ingestor.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/blockchain/substreams_block_stream.rs, graph/src/firehose/endpoints.rs, node/src/bin/manager.rs, node/src/chain.rs, node/src/config.rs, node/src/main.rs, node/src/manager/commands/config.rs, node/src/manager/commands/run.rs
- Wire EndpointMetrics for rpc endpoints
- Use a percentage of traffic to retest errored adapters
=> graph-chain-ethereum: Avoid adapters with errors

NEWS.md, docs/environment-variables.md, docs/implementation/README.md, docs/implementation/pruning.md, graph/src/components/store/mod.rs, graph/src/env/store.rs, node/src/bin/manager.rs, node/src/manager/commands/prune.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational/prune.rs, store/postgres/tests/graft.rs
This PR provides some user-level explanation of how pruning works and renames the copy strategy for pruning to 'rebuild'. Since we already have a 'copy' operation in `graph-node`, calling the strategy 'rebuild' reduces the risk for confusion between the two very different operations.
=> Docs for pruning and some internal renaming

chain/ethereum/src/network.rs, chain/ethereum/src/runtime/runtime_adapter.rs, node/src/chain.rs
Fixes https://github.com/graphprotocol/graph-node/issues/4304
=> chain/ethereum: RuntimeAdapter lazy EthAdapter

graph/src/data/subgraph/mod.rs, store/test-store/src/store.rs
* Do not arbitrarily truncate subgraph names to 32 characters; that can lead to strange surprises when the names of two test subgraphs only differ after the 32nd character
* Use a more direct method to get rid of test subgraphs. Using `record_unused_deployments` is a bit too roundabout for tests, and can lead to not deleting a subgraph if a previous run recorded the subgraph as unused, but didn't delete it
=> graph, test-store: Small improvements

chain/ethereum/src/ethereum_adapter.rs
Fixes https://github.com/graphprotocol/graph-node/issues/4545
=> chain/ethereum: Add provider string to logger on eth_call

node/src/main.rs
Fixes https://github.com/graphprotocol/graph-node/issues/4304
=> node: Fix fresh start with firehose only

core/src/subgraph/runner.rs, graph/src/components/store/entity_cache.rs, graph/src/components/store/mod.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, store/test-store/tests/graph/entity_cache.rs
This adds a new host fn `get_in_block` that will only look for entities that have been created or updated in the current block. This can improve indexing performance quite a bit if it is known that a certain entity has to have been created in the same block.
A typical situation for this is that one handler creates a `Transaction` from some on-chain event, and a later handler wants to access this transaction if it exists. In the case where the transaction does not exist, a normal `store.get` will have to go to the database just to find out that the entity does not exist; if the subgraph author already knows that the entity must have been created in the same block, using `store.get_in_block` avoids this database roundtrip. For some subgraphs, these missed lookups can contribute …
=> core, graph, runtime: Add store.get_in_block

core/src/subgraph/inputs.rs, core/src/subgraph/runner.rs, graph/src/components/store/traits.rs, store/postgres/src/writable.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/postgres/writable.rs
If a subgraph encountered an error, it would get restarted with some backoff. If that error was caused by some store interaction, the `WritableStore` would remain in poisoned state and refuse to process any more writes.
This PR changes that so that the `WritableStore` is restarted when a subgraph is restarted, clearing the error. That requires that we clear any internal state that is based on assumptions of what has been written so far. I am not entirely sure that the changes in `core/src/subgraph/runner.rs` is enough to do that, and would appreciate a thorough review of what other state might have to be cleared.
=> Avoid `writer poisoned` errors

core/src/polling_monitor/ipfs_service.rs, core/src/polling_monitor/mod.rs, docs/environment-variables.md, graph/src/env/mappings.rs
The concurrency limit, because it uses a semaphore, had unfortunate interactions with the use of `call_all` in the polling monitor. `CallAll` can internally have requests which are holding the semaphore, so it must be polled regularly to check on those requests. If the task holding the `CallAll` hangs on some other future, that can lead to a deadlock.
In our case, it can hang in the `response_sender.send((id, response)).await`, if the channel is full and the subgraph runner takes a long time to check it:
https://github.com/graphprotocol/graph-node/blob/9f4a1821146b18f6f49165305e9a8c0795120fad/core/src/polling_monitor/mod.rs#L155
This could be fixed, but the footgun would remain so it seemed best to rely only on the rate limit which can't deadlock.
This also adds a log when a file is not …
=> ipfs: Remove concurrency limit, rely on rate limit

core/src/subgraph/registrar.rs, graph/src/components/subgraph/registrar.rs, graph/src/data/subgraph/schema.rs, node/src/main.rs, node/src/manager/commands/run.rs, server/json-rpc/src/lib.rs, store/postgres/src/deployment.rs, store/postgres/src/subgraph_store.rs, tests/src/fixture/mod.rs
https://github.com/graphprotocol/graph-node/issues/4555
=> json-rpc: Add history_blocks as parameter to create_subgraph_version

docker/start
I ran into a very depressing issue which took me several hours to debug. Turns out I had the wrong PG host in my env.
This could have been debugged & fixed in 5 seconds if I saw a message saying it was waiting on the PG host to be connectable.
=> Log start script waiting for IPFS & Postgres

chain/substreams/src/trigger.rs
With recent changes done to the make entity, we have to send a create with the "id" field AND all the update entity changes also need to contain a "id" field change.
=> set id field downstream when making entity change

core/src/link_resolver.rs, graph/src/cheap_clone.rs, graph/src/ipfs_client.rs
- `IpfsClient` is already `CheapClone`, so we don't need to wrap it in an `Arc` to pass is around.
- `reqwest::Client` already uses an `Arc` internally (this is not an implementation detail, but something documented and intended), so we don't need to wrap it in an `Arc`,
- Many `CheapClone` implementations can and should use the default implementation of `CheapClone::cheap_clone`, because they don't need custom behavior.
=> De-`Arc` `IpfsClient`

store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs
GIN indexes are pretty expensive to build and maintain. For fields of types like `[BigInt!]!` or `[BigDecimal!]!`, they also don't help much since [they only support](https://www.postgresql.org/docs/current/gin-builtin-opclasses.html) looking for exact values, which is very unlikely to happen in a query, and even less unlikely to be the filter that the query planner would use.
=> store: Do not create GIN indexes for numeric arrays

store/postgres/src/catalog.rs, store/postgres/src/relational.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs, store/postgres/src/relational/prune.rs
Since [Postgres 14](https://www.postgresql.org/docs/current/brin-builtin-opclasses.html), BRIN indexes can be created with `*_minmax_multi_ops` instead of the default `*_minmax_ops`. The advantage is that the `multi_ops` can track several min/max pairs for each column in the BRIN index, which can make the index quite a bit more selective.
This PR uses the `*_minmax_multi_ops` whenever they are available, and falls back to the older `*_minmax_ops` otherwise.
=> store: Use minmax_multi_ops for brin indexes when available

graph/src/components/store/entity_cache.rs, graph/src/components/store/mod.rs, graph/src/data/store/mod.rs, runtime/test/src/test.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs, runtime/wasm/src/to_from/external.rs, runtime/wasm/src/to_from/mod.rs, store/test-store/tests/graph/entity_cache.rs
This should be a measurable performance improvement. And the lifetime adjustments surprisingly didn't cause much trouble. The only case where a clone is still required is if the entity needs to be mutated by applying pending updates, so we use a `Cow` to handle that. The entity sorting step is also faster now, because it no longer requires cloning the entity keys, rather we just sort the interned values.
=> perf: Avoid cloning cached entities

docs/getting-started.md
It seems like the Graph Typescript Library has been moved and we could update this link to take people directly to the new location of the Library.
=> fix: old link in `getting-started.md`

chain/arweave/src/trigger.rs, chain/cosmos/src/trigger.rs, chain/ethereum/src/trigger.rs, chain/near/src/trigger.rs, chain/substreams/src/trigger.rs, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, graph/src/data_source/mod.rs, runtime/wasm/src/module/mod.rs
Closes #4437 , Closes #3694
This PR allows details like transaction hash to be added to an `error_context()` method on `MappingTrigger`  which can then be logged or returned with `SubgraphError`
=> Add MappingTrigger.error_context()  to error logs

chain/arweave/src/trigger.rs, chain/cosmos/src/trigger.rs, chain/ethereum/src/data_source.rs, chain/ethereum/src/trigger.rs, chain/near/src/trigger.rs, chain/substreams/src/trigger.rs, core/src/subgraph/context.rs, core/src/subgraph/context/instance.rs, core/src/subgraph/runner.rs, core/src/subgraph/trigger_processor.rs, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, graph/src/components/trigger_processor.rs, graph/src/data_source/mod.rs, graph/src/data_source/offchain.rs, graph/src/env/mod.rs
We saw great effect from static filters on uniswap, stabilizing the firehose connection and the overall throughput of the subgraph. But they do cause a large number of false positive triggers to be received, resulting in a lot of time being spent by `fn match_and_decode` to discard those false positives.
Right now the total number of calls to `match_and_decode` would be: `n_triggers * n_data_sources`. This PR optimizes trigger matching by introducing a hash set of addresses to filter out triggers which are certain not to match any data sources, and this requires only a hash operation for each trigger.
The second commit turns on static filters for any subgraph with more than 10k data sources, under the assumption that with this optimization static filters will be an improvement for most …
=> Optimize match and decode, turn on static filters

CONTRIBUTING.md
Rust has deprecated the `rustfmt-preview` with the `rustfmt` component. `rustup` understands that `rustfmt-preview` is now just `rustfmt` and checks for that instead, but we could still just update this to the new command.
> Second, this is a preview, as it says in the name. rustfmt is not at 1.0 yet, and some stuff is being tweaked, and bugs are being fixed. Once rustfmt hits 1.0, we'll be releasing a rustfmt component and deprecating rustfmt-preview.
https://blog.rust-lang.org/2018/02/15/Rust-1.24.html
=> CONTRIBUTING.md: Updating deprecated rustfmt-preview

chain/arweave/src/trigger.rs, chain/cosmos/src/trigger.rs, chain/near/src/trigger.rs
Master is currently not compiling because git merged #4635 and #4631 incorrectly.
=> fix compilation errors

core/src/polling_monitor/ipfs_service.rs, core/src/polling_monitor/mod.rs, core/src/subgraph/context.rs
This addresses both sides of the issue, by making sure the task holding the `CallAll` doesn't hang, and by removing the concurrency control done by `Buffer`, which may be the reason why PR #4570 didn't fully work.
=> fix(offchain): Avoid starvation in the offchain monitor

core/src/subgraph/runner.rs, graph/src/components/store/entity_cache.rs, graph/src/components/store/mod.rs, graph/src/components/store/write.rs, graph/src/lib.rs, runtime/test/src/test.rs, store/postgres/src/writable.rs, store/test-store/src/store.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/postgres/relational_bytes.rs, store/test-store/tests/postgres/store.rs
These changes mostly clean up a little bit of code around batched writes:
* we have two structs, `EntityMod` and `EntityModification` that are almost identical. Change that so we only have one
* for immutable entities, there's no point in searching for a previous change as there can't be one
=> Small improvements for batch writes

Cargo.lock, core/src/subgraph/registrar.rs, graph/Cargo.toml, graph/src/components/subgraph/mod.rs, graph/src/components/subgraph/settings.rs, graph/src/env/mod.rs, graph/src/lib.rs, node/Cargo.toml, node/src/bin/manager.rs, node/src/config.rs, node/src/main.rs, node/src/manager/commands/config.rs, node/src/manager/commands/run.rs, store/postgres/src/chain_store.rs, tests/src/fixture/mod.rs
This PR achieves a very similar result as #4622 but with a few important differences:
* rule evaluation is predictable as rules are always evaluated in the order in which they are listed in the settings file
* the command `graphman config check` will check the settings file for validity if one is set in the environment
* the command `graphman config setting <name>` will print what setting will be used when deploying a new subgraph `name`
The syntax of the file is also slightly different to streamline it a bit:
```toml
[[setting]]
match = { name = "foo/.*" }
history_blocks = 100
[[setting]]
match = { name = ".*/bar" }
history_blocks = 200
```
=> Add subgraph-specific settings

NEWS.md, core/src/subgraph/registrar.rs, graph/src/components/store/traits.rs, node/src/bin/manager.rs, node/src/manager/commands/assign.rs, store/postgres/migrations/2023-05-23-1715-update-subgraph-deployment-assignment/down.sql, store/postgres/migrations/2023-05-23-1715-update-subgraph-deployment-assignment/up.sql, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs
=> Add ability to pause and resume subgraphs

core/src/subgraph/runner.rs, graph/src/components/store/traits.rs, graph/src/components/store/write.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/writable.rs, store/test-store/src/store.rs, store/test-store/tests/chain/ethereum/manifest.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/graphql/query.rs, store/test-store/tests/postgres/store.rs, store/test-store/tests/postgres/subgraph.rs
=> Update nonFatalErrors in subgraphs.subgraph_deployment table

graph/src/blockchain/types.rs, node/src/bin/manager.rs, node/src/chain.rs, node/src/main.rs, node/src/manager/commands/run.rs, node/src/store_builder.rs, store/postgres/src/block_store.rs, store/test-store/src/store.rs, tests/src/fixture/mod.rs
This code was a bit convoluted because we used a `Vec<ChainIdentifier>`, only to later validate in the store that the vec contained exactly one identifier, which make sense since we don't want conflicting identifiers for a same network. So the data structure is changed to `BTreeMap<String, ChainIdentifier>`, which naturally allows for de-duplicating the identifier between RPC and firehose providers, and also makes it easy to prefer the RPC identifier.
Fixes #4655.
=> Fix panic on first startup when mixing firehose and rpc

core/src/subgraph/runner.rs
* `refetch_firehose_block` is called when using filters and a dynamic datasource is added.
* If it fails, the whole subgraph fails and retries after 2 minutes
* This downtime is out of proportions with a single "failed http fetch", so a few retries make sense.
=> add a retry(5) when refetch_firehose_block fails

.github/workflows/ci.yml
We're not the only ones experiencing flaky networking on Github Actions hosted runners: https://github.com/actions/runner-images/issues/1187
Someone suggested disabling TCP checksum offloading as a possible solution as hosted runners' implementation may be buggy. Performance impact should be minimal and error rates go down significantly.
=> Reduce CI flakiness: disable TCP checksum offloading

store/postgres/src/block_store.rs
If a chain was first set up using firehose and we then try to switch to an RPC provider, we get an error on a failing safety check for net_version.
Before this fix:
```
Jun 13 09:37:26.175 ERRO the net version for chain mainnet has changed from 0 to 1 since the last time we ran, component: BlockStore
Jun 13 09:37:26.186 INFO Creating LoadManager in disabled mode, component: LoadManager
Jun 13 09:37:26.187 ERRO Failed to create block ingestor Not starting block ingestor (chain is defective), network_name mainnet, network_name: mainnet
```
After this fix:
```Jun 13 11:11:03.201 WARN the net version for chain mainnet has changed from 0 to 1 since the last time we ran, ignoring difference because 0 means UNSET and firehose does not provide it, component: BlockStore```
=> don't fail ingestor on net_version changed from zero

core/src/subgraph/registrar.rs, graph/src/components/store/traits.rs, store/postgres/src/deployment_store.rs, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs
=> Allow redeployment of grafted subgraph even when graft_base is not available

graph/src/firehose/endpoints.rs
correct header syntax is: `Authorization: bearer AAAaaBBbbbCCCcccDDddd....`
It works without the word "bearer" currently, but it does not follow the specs.
=> firehose/substreams: add 'bearer' in authorization field

chain/ethereum/src/ethereum_adapter.rs
This closes issue #4698
Example of new debug logs:
```
DEBG eth_call, block_number: 16498903, block_hash: edabdef6666290010449e023eeb28b523dea6c46235bdd8b2d46ce689478697d, data: 70a0823100000000000000000000000038a8e16951352bab0cfd8872b881cd6bfdab25c8, address: dac17f958d2ee523a2206206994597c13d831ec7, sgd: 47, subgraph_id: QmUGnnNmiB3rTi1AFY4XKZWQ1z8kxKK6p1nFXL6wyyUo2r, component: SubgraphInstanceManager
```
Bloch hash does not have 0x at the start as all log entries that I saw in this repo had the same format
=> [Feature] Include blockhash and number in eth_call debug logs

graph/src/runtime/gas/costs.rs, runtime/wasm/src/host_exports.rs, runtime/wasm/src/module/mod.rs
This is expected to be used in the network. We will still error if the table is not populated, but will no longer gate on setting any env var.
=> Undeprecate ens_name_by_hash

chain/substreams/src/data_source.rs
If params is provided on the substreams-based subgraph manifest then replace all the existing params on the output module with the provided list.
FIxes https://github.com/graphprotocol/graph-node/issues/4577
=> substreams: Add support for overriding module params

graph/src/components/store/traits.rs, server/index-node/src/resolver.rs, store/postgres/src/store.rs, store/postgres/src/subgraph_store.rs
Resolves #4730 by fetching the block on-the-fly if it is not found in the block cache.
=> Fix null public pois

core/src/subgraph/runner.rs, store/postgres/src/deployment_store.rs, tests/src/fixture/mod.rs, tests/tests/runner_tests.rs
Requesting a POI for a deterministically failed subgraph on a block past the failure will now return the last valid POI.
https://github.com/graphprotocol/graph-node/issues/4777
=> Return valid POI for deterministically failed SGs

graph/src/firehose/endpoints.rs, node/src/chain.rs, node/src/config.rs
- Duplicated labels no longer allowed on config
- Endpoints get tested/connected to per provider label instead of per endpoint
=> Handle conn pool initialization gracefully

store/postgres/src/writable.rs, store/test-store/tests/postgres/writable.rs
In cases where the queue had multiple entries, and an entity was modified by more than one entry, we would return the oldest value in the queue instead of the newest one from `WritableStore::get_many` and `get_derived`.
This change makes sure that we always return the correct (newest) value in these situations
=> Fix WritableStore::get_many and get_derived to not return stale values

graph/src/data/subgraph/status.rs, node/src/manager/deployment.rs, server/index-node/src/schema.graphql, store/postgres/src/detail.rs, store/postgres/src/primary.rs
=> Add subgraph paused status to index node API

store/postgres/src/dynds/mod.rs, store/postgres/src/dynds/private.rs, store/postgres/src/relational.rs
The `fn revert` was correct if blocks are reverted one by one, as in typical subgraph operation. But on a `graphman rewind` to block `N` it would fail to remove data sources created past block `N`.
=> fix(store): Fix rewinding of dynamic data sources

core/src/subgraph/registrar.rs, graph/src/data/subgraph/mod.rs, graph/src/lib.rs, graph/src/util/futures.rs
Add retry to avoid a single failure while making the call prevent the subsgraph from being deployed Add warning for failed attempts
Closes https://github.com/graphprotocol/graph-node/issues/4724
=> Retry block_pointer_from_number on deploy

graph/src/components/store/mod.rs, graph/src/data/query/error.rs, graph/src/data/store/mod.rs, graph/src/data/value.rs, graph/src/env/store.rs, graphql/src/execution/query.rs, graphql/src/store/prefetch.rs, store/postgres/src/relational_queries.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/postgres/relational_bytes.rs
If a query only needs to get the `id` of children, and we already have them  in memory, do not run a query to fetch them again. Instead, construct the appropriate objects in memory.
Fixes https://github.com/graphprotocol/graph-node/issues/4261
=> Avoid redundant child queries

store/test-store/tests/chain/ethereum/manifest.rs, tests/runner-tests/data-sources/abis/Contract.abi, tests/runner-tests/data-sources/package.json, tests/runner-tests/data-sources/schema.graphql, tests/runner-tests/data-sources/src/mapping.ts, tests/runner-tests/data-sources/subgraph.yaml, tests/runner-tests/package.json, tests/runner-tests/yarn.lock, tests/tests/runner_tests.rs
=> Support DataSourceContext in manifest

node/src/bin/manager.rs, node/src/manager/commands/index.rs, store/postgres/src/deployment_store.rs, store/postgres/src/subgraph_store.rs
=> Allow creating partial indexes with graphman

chain/arweave/src/data_source.rs, chain/cosmos/src/data_source.rs, chain/ethereum/src/data_source.rs, chain/near/src/data_source.rs, chain/substreams/src/data_source.rs, docs/implementation/metadata.md, graph/src/blockchain/mock.rs, graph/src/blockchain/mod.rs, graph/src/data/subgraph/mod.rs, graph/src/data_source/mod.rs, graph/src/data_source/offchain.rs, server/index-node/src/schema.graphql, store/postgres/migrations/2023-08-23-143628_add_handlers_to_subgraph_features/down.sql, store/postgres/migrations/2023-08-23-143628_add_handlers_to_subgraph_features/up.sql, store/postgres/src/primary.rs, store/test-store/tests/postgres/subgraph.rs, tests/integration-tests/block-handlers/test/test.js, tests/integration-tests/non-fatal-errors/test/test.js
=> Track handlers in subgraph_features table

Cargo.lock, chain/ethereum/src/chain.rs, chain/near/src/chain.rs, chain/substreams/examples/substreams.rs, chain/substreams/src/block_ingestor.rs, chain/substreams/src/block_stream.rs, chain/substreams/src/chain.rs, chain/substreams/src/mapper.rs, chain/substreams/src/trigger.rs, core/src/subgraph/runner.rs, core/src/subgraph/stream.rs, graph/Cargo.toml, graph/src/blockchain/block_stream.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/blockchain/mod.rs, graph/src/blockchain/polling_block_stream.rs, graph/src/blockchain/substreams_block_stream.rs, graph/src/components/store/traits.rs, graph/src/components/subgraph/proof_of_indexing/event.rs, graph/src/components/subgraph/proof_of_indexing/mod.rs, graph/src/data/store/mod.rs, graphql/Cargo.toml, runtime/wasm/src/host_exports.rs, store/postgres/Cargo.toml, store/postgres/src/writable.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/postgres/store.rs, tests/src/fixture/mod.rs
Improves perfromance based on [this issue](https://github.com/graphprotocol/graph-node/issues/4831)
=> Move substreams processing to block stream

Cargo.lock, chain/starknet/Cargo.toml, chain/starknet/build.rs, chain/starknet/proto/starknet.proto, chain/starknet/src/adapter.rs, chain/starknet/src/chain.rs, chain/starknet/src/codec.rs, chain/starknet/src/data_source.rs, chain/starknet/src/lib.rs, chain/starknet/src/protobuf/zklend.starknet.r#type.v1.rs, chain/starknet/src/runtime/abi.rs, chain/starknet/src/runtime/generated.rs, chain/starknet/src/runtime/mod.rs, chain/starknet/src/trigger.rs, core/Cargo.toml, core/src/subgraph/instance_manager.rs, core/src/subgraph/registrar.rs, graph/src/blockchain/mod.rs, graph/src/runtime/mod.rs, node/Cargo.toml, node/src/main.rs, server/index-node/Cargo.toml, server/index-node/src/resolver.rs
This PR brings initial support for Starknet into `graph-node`. The implementation comes from [starknet-graph](https://github.com/starknet-graph), and has been used in production by the [zkLend](https://zklend.com/) team for around a year. That said, the support enabled by this PR is not production ready:
- Trigger filter is not implemented, and `graph-node` would always consume the entire Firehose block stream and build all possible triggers. No benchmark has been done yet, but this should hurt performance pretty bad.
- Data source templates are not supported. This hasn't been tested yet, but technically `graph-node` would panic if someone deploys a subgraph with Starknet data source templates defined.
- Substream support has not been added (will take inspiration from #4887). …
=> feat: initial Starknet support

runtime/test/src/test/abi.rs, runtime/wasm/src/lib.rs, runtime/wasm/src/module/mod.rs
After https://github.com/graphprotocol/graph-node/pull/4475, a timeout trap might be hidden in a host function error. And those timeouts wouldn't get a nice error message. This hopefully addresses that by detecting timeouts anywhere in the anyhow error chain.
=> fix(runtime): improve error message for timeouts

node/src/bin/manager.rs, node/src/manager/commands/deploy.rs, node/src/manager/commands/mod.rs
=> Graphman deploy command

graph/src/env/store.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs
Experience has shown that these indexes are very expensive to update and can have a very bad impact on the write performance of the database, but are hardly ever used or needed by queries.
=> graph, store: Do not create GIN indexes on array attributes

server/http/assets/index.html
https://unpkg.com seems to have some [weird CORS issues](https://github.com/mjackson/unpkg/issues/174) so swapping to JS Deliver
=> fix(graphql): change CDN to JS Deliver for GraphiQL

.github/workflows/ci.yml, tests/integration-tests/api-version-v0-0-4/package.json, tests/integration-tests/package.json, tests/integration-tests/yarn.lock, tests/runner-tests/api-version/package.json, tests/runner-tests/arweave-file-data-sources/package.json, tests/runner-tests/block-handlers/package.json, tests/runner-tests/data-source-revert/package.json, tests/runner-tests/data-source-revert2/package.json, tests/runner-tests/data-sources/package.json, tests/runner-tests/derived-loaders/package.json, tests/runner-tests/dynamic-data-source/package.json, tests/runner-tests/fatal-error/package.json, tests/runner-tests/file-data-sources/package.json, tests/runner-tests/package.json, tests/runner-tests/yarn.lock
building on top of #4954
1. Make sure we are installing everything for the `yarn workspace` not all the test folders were listed part of workspace and it is much easier to have it install all dependencies for the test folders
2. I saw that for `runner-tests` we are not setting Node.js version, so set that up
3. Upgraded to use Node 20 so we are on LTS version
=> fix(tests): yarn workspace to install all subfolders

graph/src/components/store/traits.rs, graph/src/data/query/trace.rs, graphql/src/execution/execution.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/store/resolver.rs, server/index-node/src/resolver.rs, store/postgres/src/block_store.rs, store/postgres/src/connection_pool.rs, store/postgres/src/deployment_store.rs, store/postgres/src/query_store.rs, store/postgres/src/store.rs, store/test-store/tests/graphql/introspection.rs
There are other places during query execution where we might be waiting for connections, but this at least records the times for getting the actual data.
=> Track per query connection and permit wait times

chain/ethereum/src/ethereum_adapter.rs, graph/src/util/futures.rs
Graph Node tends to spam failing network requests of different kinds, often giving the impression that we have no backoff at all. Starting at a slightly higher base backoff might help.
Also add a newly discovered deterministic Geth error.
=> fix: Increase RPC base backoff

chain/substreams/src/block_ingestor.rs
=> Make `SubstreamsBlockIngestor` start at chain's head if no cursor already exist

.github/workflows/ci.yml, tests/src/fixture/mod.rs
Set it to 10 minutes for github actions. Default is 1 minute
=> tests: Make how long runner tests wait for sync configurable

NEWS.md, README.md, docs/graphman.md
=> docs: fix typos

graph/src/schema/mod.rs, graphql/src/store/resolver.rs, store/test-store/tests/graphql/query.rs
include `__schema` and `__type` part of the result when there is an indexing error and the error policy is deny.
Fixes #2443
----
There is another issue I found (could just be how tests are setup) but I wasn't really able to fix. In the example below if there is an indexing error this will return `null` but I would imagine that we return partial result i.e. `__schema` is returned in the `data` 
```graphql
query { musician(id: "m1") { id } __schema { queryType { name } } }
```
=> fix(graphql): include introspection fields in error

graph/src/log/elastic.rs, graph/src/log/factory.rs
ElasticSearch has dropped support for the `_type` field
=> fix(logs): Fix for ElasticSearch 8.X

graph/src/env/store.rs, store/postgres/src/block_range.rs, store/postgres/src/relational_queries.rs
A query has a where clause which filters by id is best served by the GiST index on `(id, block_range)`. However when the table is set to account-like, the BRIN index is sometimes chosen by the query planner even though it can have much worse performance.
We've encountered this repeatedly on some large subgraphs and even had to turn off `account-like` on some tables to resolve the situation, which is of course not ideal because some queries do benefit from it. This happened even with BRIN indexes using using `*_multi_ops`.
This proposes addressing this by not adding the BRIN-friendly clauses on queries that we know are filtering by id. Which include type C and D queries, and top-level queries explicitly filtering by `id`.
Impact to be tested in real-world scenarios.
=> perf(store): Avoid the BRIN index for queries that filter by id

node/src/manager/commands/index.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational/ddl.rs
=> Refactor index creation and fix unncessary prefix

graph/src/components/store/entity_cache.rs, graph/src/data/store/id.rs, graph/src/data/store/mod.rs, graph/src/data/value.rs, graph/src/env/mod.rs, graph/src/schema/api.rs, graph/src/schema/ast.rs, graph/src/schema/entity_type.rs, graph/src/schema/input_schema.rs, graph/src/schema/mod.rs, graphql/examples/schema.rs, graphql/src/store/query.rs, store/postgres/src/deployment_store.rs, store/postgres/src/fork.rs, store/postgres/src/relational.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational_queries.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/graphql/introspection.rs, store/test-store/tests/graphql/mock_introspection.json
This is all groundwork for aggregations; in an effort to not produce a gigantic PR, I am putting up somewhat smaller ones. The biggest change this PR introduces is our own structs for object and interface type that are easier/saner to work with than the raw GraphQL AST
=> More `InputSchema` refactorings

README.md
Since nowhere on the main README of this repo it mentions docker, when I had first look at it, I did not realize it already had a docker compose file. It's only when someone point out to me that it had a docker folder that I realize it was there. 🤦‍♂️ 
So I'm suggesting simply adding a small mention about it
=> Add docker instruction on main Readme

graph/src/schema/entity_type.rs, graph/src/schema/input_schema.rs
The conflicting entity check in DeploymentStore expects that the type itself is not in the list of types that share an interface; if it is, the check causes spurious failures when entities are updated.
=> graph: Exclude Self from ObjectType.share_interfaces()

docs/metrics.md, graph/src/components/graphql.rs, graphql/src/metrics.rs, graphql/src/store/resolver.rs, server/http/src/service.rs, server/http/tests/server.rs, server/index-node/src/service.rs
A small thing but should be great help for pruning decisions. Note that this will not record for queries that are refused due to being behind the minimum block, so there is a bit of "survivorship bias".
=> metrics: Add metric for query blocks behind

core/src/subgraph/registrar.rs, graph/src/data/subgraph/api_version.rs, graph/src/data/subgraph/mod.rs, store/test-store/src/store.rs, store/test-store/tests/chain/ethereum/manifest.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/graphql/query.rs, store/test-store/tests/postgres/graft.rs, store/test-store/tests/postgres/store.rs, store/test-store/tests/postgres/subgraph.rs, store/test-store/tests/postgres/writable.rs
=> Add history_blocks to manifest

store/postgres/src/chain_store.rs, store/test-store/src/block_store.rs, store/test-store/tests/graphql/query.rs, store/test-store/tests/postgres/chain_head.rs, store/test-store/tests/postgres/store.rs, store/test-store/tests/postgres/subgraph.rs
I was hoping that these tests would illuminate why the recent blocks cache isn't very effective in practice, but it seems to work as expected. We should probably add some more direct tests for the recent blocks cache on top of these.
=> Add some tests for the recent blocks cache

graph/src/blockchain/types.rs, store/postgres/src/chain_store.rs
This makes sure that the recent blocks cache gets populated on nodes that don't call upsert_blocks, i.e., index nodes that are not the block ingestor.
=> Add blocks loaded from the database to the recent blocks cache

core/src/subgraph/runner.rs, graph/src/components/store/traits.rs, store/postgres/src/chain_store.rs
With recent changes where the recent blocks cache gets populated on index nodes that are not the block ingestor (#5059), the recent blocks cache can have a notion of chain head pointer that is very far behind the actual chain head pointer. In fact, there is no safe way to get the real chain head pointer from the cache.
A side-effect of using the wrong chain head pointer is that a subgraph gets marked as synced too early, which in turn turns off write batching.
Caching the chain head pointer is also a bit of a premature optimization as looking up the chain head pointer should be very cheap as it does a lookup in the very small `ethereum_networks` table.
If we do want to cache the chain head pointer, we will have to use the ChainHeadUpdate notifications to update such a cache.
=> core, graph, store: Do not use recent blocks cache for chain head

core/src/subgraph/runner.rs, store/postgres/src/dynds/mod.rs, store/postgres/src/dynds/private.rs, store/postgres/src/relational.rs, tests/src/fixture/ethereum.rs, tests/src/fixture/mod.rs, tests/tests/runner_tests.rs
#4810 was wrong. And that wasn't the only thing, the way the runner reverted in-memory state also didn't seem quite right. This adds a test which uncovered these issues. Should resolve #4994, unless that was hitting the assert for a different cause.
Needs an integration cluster run, of course.
=> Fix data source rewind across more than one block

store/postgres/src/copy.rs
We reset the progress to 0 every time a node was restarted instead of using what we had stored in the database.
=> store: Report accurate progress after node restart

core/src/subgraph/context/mod.rs
#5083 exposed this metrics issue, right now it's getting incremented on every block stream restart.
=> fix: Fix `deployment_running_count` metric

chain/ethereum/src/ethereum_adapter.rs
This PR closes https://github.com/graphprotocol/graph-node/issues/4756 
It changes caching logic to cache only correct and decodable eth_calls to prevent cache from providing faulty data
=> Cache only correct eth_call data

graph/src/util/futures.rs
The futures tests take a long time, partly because they use a maximum delay of 30s in backoff. This change uses a much shorter maximum delay for tests than for production builds.
=> graph: Speed up some of the futures tests

chain/cosmos/src/trigger.rs
fixes issue: #5111
Introduces additional checks in the event PartialEq comparison check so that no event is missed due to the dedup operation.
=> fix dedup issue for cosmos attributes

core/src/subgraph/runner.rs, graph/src/components/metrics/stopwatch.rs, graph/src/components/metrics/subgraph.rs
We don't have a metric that accurately reflects the time it takes to process a block. This PR introduces two new metrics for each deployment, one for the total time taken to process a block, and one for the number of blocks that should make it possible to calculate an overall processing speed. The metrics we have only cover a specific section of processing (and I am not sure how useful the histograms in `SubgraphInstanceMetrics` actually are)
There's a bit of handwaving since we can't account for the time a task is not actively running with this, but it should give us a reasonably close idea of overall timing.
=> core, graph: Add a metric to capture entire processing time for a block

tests/src/fixture/mod.rs, tests/tests/runner_tests.rs
I think this is happening because we have two runner tests using the same subgraph, `fatal_error` and `poi_for_deterministically_failed_sg`. I ended up addressing this by merging the tests.
The first commit is a refactor that ended up not being relevant, but is maybe still worth it as a refactor for readability. The second commit is the actual fix.
I'll run this a few times in CI to check if we don't get the spurious failure anymore.
=> Attempted fix for `fn fatal_error` test spurious failure

chain/near/src/chain.rs, chain/substreams/examples/substreams.rs, chain/substreams/src/block_ingestor.rs, chain/substreams/src/block_stream.rs, core/src/subgraph/runner.rs, graph/src/blockchain/block_stream.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/blockchain/polling_block_stream.rs, graph/src/blockchain/substreams_block_stream.rs, graph/src/ext/futures.rs, store/postgres/src/deployment.rs, tests/src/fixture/mod.rs
- Surface substreams errors
- Fail subgraph if a substreams error is marked as deterministic
- Consider substreams errors deterministic if `Code::InvalidArgument` is returned as the grpc status code
- Replace a few `Option<String>` with `FirehoseCursor`.
- Remove deterministic error on None block assertion
=> Improve substreams error handling

node/src/bin/manager.rs, node/src/manager/commands/unused_deployments.rs, node/src/manager/deployment.rs, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs
=> graphman: Add ability to list removed unused deployment by id

store/postgres/src/relational.rs, store/postgres/src/relational/prune.rs
When pruning by delete, it's overzealous to analyze. When combined with auto-prune on large tables, I've seen shards struggle with one long analyze after the other.
It can also conflict with the lock for autovacuum and result in a long running transaction waiting for the lock.
=> perf(prune): Only analyze when rebuilding

graph/src/data/subgraph/mod.rs
Fixes https://github.com/graphprotocol/graph-node/issues/5131
=> graph: Disallow grafts within the reorg threshold

core/src/subgraph/registrar.rs, graph/src/components/store/traits.rs, graph/src/components/subgraph/registrar.rs, server/json-rpc/src/lib.rs, store/postgres/src/subgraph_store.rs
=> server: add pause and resume to admin json rpc api

Cargo.lock, chain/ethereum/src/adapter.rs, chain/ethereum/src/ethereum_adapter.rs, chain/ethereum/src/runtime/runtime_adapter.rs, graph/Cargo.toml, graph/src/data/subgraph/api_version.rs, graph/src/env/mappings.rs, tests/contracts/out/LimitedContract.sol/LimitedContract.json, tests/contracts/out/OverloadedContract.sol/OverloadedContract.json, tests/contracts/out/RevertingContract.sol/RevertingContract.json, tests/contracts/out/SimpleContract.sol/SimpleContract.json, tests/docker-compose.yml, tests/integration-tests/eth-get-balance/abis/Contract.abi, tests/integration-tests/eth-get-balance/package.json, tests/integration-tests/eth-get-balance/schema.graphql, tests/integration-tests/eth-get-balance/src/mapping.ts, tests/integration-tests/eth-get-balance/subgraph.yaml, tests/integration-tests/yarn.lock, tests/tests/integration_tests.rs
=> Support eth_getBalance in mapping

docs/aggregations.md, graph/src/schema/input_schema.rs, graph/src/schema/mod.rs, graph/src/schema/test_schemas/ts_invalid_cumulative.graphql, graph/src/schema/test_schemas/ts_valid_cumulative.graphql, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs, store/postgres/src/relational/prune.rs, store/postgres/src/relational/rollup.rs
This PR allows aggregates that are cumulative from the beginning of time rather than just within a time interval. That is indicated by declaring the aggregate as `@aggregate(fn: "sum", arg:"amount", cumulative: true)`
Check the docs in ./docs/aggregation.md for more details.
Note that this PR is on top of PR #5208
=> Support cumulative aggregations

core/src/subgraph/runner.rs
It has interesting info but it logs very frequently and isn't actually read often. Better left outside the default logs.
=> monitoring: Downgrade 'Entity cache statistics' log to trace

store/postgres/src/deployment_store.rs
=> fix(store): Remove panic from `rewind` and `truncate`

graph/src/util/timed_rw_lock.rs, store/postgres/src/chain_head_listener.rs
This was added in a time when we were having problems with receiving chain head updates and were trying workarounds. This one had a hypothesis of a deadlock in tokio Watch::send. I was never able to corroborate this, no other tokio user ever reported something like this and improvements have since been made to the internals of `Watch`. So there isn't much justification for keeping this hack.
=> Remove hack in chain_head_listener

Cargo.lock, docs/aggregations.md, graph/Cargo.toml, graph/src/lib.rs, graph/src/schema/entity_type.rs, graph/src/schema/input/mod.rs, graph/src/schema/input/sqlexpr.rs, graph/src/schema/mod.rs, graph/src/schema/test_schemas/ts_expr_random.graphql, graph/src/schema/test_schemas/ts_expr_simple.graphql, graph/src/schema/test_schemas/ts_expr_syntax_err.graphql, store/postgres/src/relational/rollup.rs, store/test-store/tests/postgres/aggregation.rs
It is now possible to use a restricted subset of SQL expressions in the `arg` of `@aggregate` annotations. Some examples of what's possible now:
* `@aggregate(fn: "sum", arg: "price * amount")`
*  `@aggregate(fn: "max", arg: "greatest(amount0, amount1)")`
* even conditional aggregations like `@aggregate(fn: "sum", arg: "case when amount0 > amount1 then amount0 else 0 end")`
This will help reduce the values that a timeseries needs to store; without this addition, all of the above would have required that mappings calculate these expressions and store them in a separate field in the timeseries.
=> Support expressions in the `arg` of `@aggregate`

store/postgres/src/writable.rs
We use sleep as a fallback in case the notification to write does not work. Unfortunately, this leads to much smaller write batches than configured for busy subgraphs as the check whether a batch should be written seems to conflict with appending to a batch (we start a new batch in that case)
By raising the safety sleep from 2s to GRAPH_STORE_WRITE_BATCH_DURATION we make these collisions much less likely; there should not be any adverse consequences. If the notifications don't work, we'd still wait at most the configured time to write.
=> store: Increase sleep time in write queue processing

node/src/bin/manager.rs, node/src/manager/commands/chain.rs, store/postgres/src/block_store.rs, store/postgres/src/chain_store.rs, store/postgres/src/lib.rs
Closes [#5137](https://github.com/graphprotocol/graph-node/issues/5137)
=> Add graphman command to change block cache shard

docs/aggregations.md
Removed a bunch of more speculative todos - if these are actually needed by users they will let us know ;)
Contrary to what's described in the doc, queries can actually filter on all attributes; I am still not 100% sure if this is a good idea in terms of performance or if we should restrict filtering in the way described in the doc.
=> docs: Update aggregation docs

graph/src/blockchain/types.rs, graph/src/components/store/traits.rs, graphql/src/query/ext.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, graphql/src/subscription/mod.rs, store/postgres/src/chain_store.rs, store/postgres/src/query_store.rs, store/test-store/src/store.rs
The lookup needed for block constraints by hash is now done with one query  instead of one query for each such constraint. None of the other types of  constraints need a query any more.
=> Resolve block constraints in bulk

store/postgres/src/relational_queries.rs
Otherwise, if GRAPH_ENABLE_SELECT_BY_SPECIFIC_ATTRIBUTES=true, queries will fail on immutable tables.
=> store: Make select by attribute work with immutable tables

chain/ethereum/src/codec.rs
The decoder for Ethereum firehose is full of `unwrap`, `expect` and `panic`. This removes two potential crashes that we encountered in production.
The code is still pretty scary as it takes in data from the network and will crash when it doesn't conform to its implicit assumptions. For example, even though the block header is in an `Option` in the protobuf, the code will just panic when it is ever `None`.
=> Make the ethereum firehose codec less crashy

core/src/subgraph/runner.rs, store/postgres/src/deployment.rs
And also drastically reduce the number of unfail calls.
=> Optimize subgraph ptr update

store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
The FindDerivedQuery would contain a clause `id not in (<lots of values>)` where each entry in the list is a separate bind variable. If we have more than 65k derived entities already loaded into memory, this would require more bind variables than what Postgres supports. With this change, we pass those values as one array and therefore only need one bind variable.
=> store: Avoid 'too many bind params' error in FindDerivedEntityQuery

chain/ethereum/examples/firehose.rs, graph/src/blockchain/firehose_block_ingestor.rs, graph/src/blockchain/firehose_block_stream.rs, graph/src/blockchain/substreams_block_stream.rs, graph/src/firehose/endpoints.rs
Fixes #5098 
When running firehose infrastructure it helps to know which subgraph is consuming substreams modules that are failing.
This PR makes it possible by adding deployment id to firehose/substreams request via `x-deployment-id` header
=> Add deployment id to firehose connection headers

core/src/polling_monitor/ipfs_service.rs, graph/src/components/link_resolver/ipfs.rs, graph/src/ipfs_client.rs, node/src/main.rs, node/src/manager/commands/run.rs, tests/src/fixture/mod.rs, tests/tests/runner_tests.rs
To reduce the total number of calls to IPFS, and to generally simplify our interface on IPFS, this stops using the `stat` API to check existence and control file size. Both can be achieved efficiently with the more usual cat api.
Relying on files/stat was questionable anyways, since we don't know to what extent IPFS clients actually enforce that the declared metadata size value matches the real file size.
Resolves https://github.com/graphprotocol/graph-node/issues/5087.
=> ipfs: Stop using the stat API

store/postgres/src/deployment.rs
The check for a deterministic error in deployment::state was wrong in that it claimed that it contained a `sql::<Integer>` but a query using `min` will return null when there are no rows. The query needs to say `sql::<Nullable<Integer>>`
=> store: Fix check for deterministic error

graph/src/data/query/result.rs, server/http/tests/server.rs
Commit f06c6061 mistakenly dropped several HTTP headers from GraphQL responses, including the Graph-Attestable header. This commit adds them back and also adds a test for their presence.
=> graph, server: Reinstitute Graph-Attestable header

store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs
For cumulative aggregations, the code was confused about the table on which the index should be created. It needs to go on the aggregation table, not the underlying source table. These indexes have a significant impact on the performance of rollups, and having them on the wrong table makes rollups very slow.
Fixes https://github.com/graphprotocol/graph-node/issues/5280
=> store: Change which indexes are created to support aggregations

graph/src/env/mod.rs, graphql/src/execution/ast.rs, graphql/src/store/query.rs
With these small fixes, a test run with the setting on and off did not produce any material differences in the query results. The only differences were in a few error messages that contained a debug dump of the query (where we now have a list of column names instead of `*`)
=> Use 'select by specific attributes' by default

graph/examples/validate.rs, graph/src/env/store.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/query_store.rs, store/postgres/src/relational.rs, store/postgres/src/subgraph_store.rs
The internal cache for layouts used to keep entries indefinitely. With these changes, we go through the cache periodically and remove entries.
=> Periodically remove entries from the `LayoutCache`

chain/ethereum/src/codec.rs
Use the same logic in both places where we parse it. An empty `to` is now assumed to be a contract creation.
=> firehose: Try to be more consistent in parsing to address

graph/src/data/store/id.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs, store/test-store/tests/graphql/query.rs, store/test-store/tests/postgres/graft.rs, store/test-store/tests/postgres/relational.rs
We used to run one query for each entity that was created or updated if it was of a type that implemented an interface. These single-entity queries can become quite time consuming during syncing.
With this change, we check all the entities of a given type with a single query, so that uniqueness checking for interfaces causes as many queries as there are types (with new/updated entities) rather than as many as there are entities of such types.
=> store: Check interface uniqueness in bulk

Cargo.lock, Cargo.toml, graph/Cargo.toml, graph/examples/stress.rs, graph/examples/validate.rs, node/Cargo.toml, node/src/bin/manager.rs, node/src/opt.rs, runtime/test/src/test.rs, store/postgres/Cargo.toml
Upgrade clap to latest version
Blocked by rust upgrade - https://github.com/graphprotocol/graph-node/pull/4985
=> upgrade clap

node/src/bin/manager.rs, node/src/manager/commands/assign.rs, node/src/manager/commands/rewind.rs
This PR refactors the `graphman rewind` command to use the pause and resume function.
=> Refactor `graphman rewind` to use pause and resume logic

graph/src/components/store/err.rs, graph/src/components/store/write.rs, store/postgres/src/relational.rs, tests/tests/runner_tests.rs
When a write fails because Postgres is unhappy with it, e.g., because of an invalid block_range, it is very hard to understand what happened from the error message. This change improves that by including the entity type and the block at which the write failed as well as some other detail in the error message.
=> graph, store: Improve error message when write fails

graph/src/components/metrics/stopwatch.rs, graph/src/env/mod.rs
With this PR, debug builds (and only debug builds) pay attention to an environment variable `GRAPH_SECTION_MAP` which will make it print a list of the parent/child relations of stopwatch sections. That can then be turned into an image, e.g. with `dot` to visualize the nesting.
=> Allow generating a map of section nesting in debug builds

graphql/src/store/resolver.rs
When we resolve a single-object reference from the store, but find multiple children, we need to return an error. We did that already for derived fields, but for non-derived fields that was an expect. For non-derived fields, we can only hit that when the id of the parent entity is not unique, which can happen because we stopped enforcing exclusion constraints a while ago for mutable entities. For immutable entities, we still enforce uniqueness of ids
=> graphql: Make an expect an error with better explanation

core/src/subgraph/runner.rs, tests/src/fixture/mod.rs
Otherwise, looking for the parent ptr will fail and the subgraph simply won't start, logging `Trying again after load block 0x2a74…e47e failed`. When a chain does a re-genensis or re-hashing this can happen en masse so we need to deal with it.
=> Check if subgraph head exists before trying to unfail

graph/src/env/mod.rs, node/src/manager/commands/rewind.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/detail.rs, store/postgres/src/subgraph_store.rs
=> graphman: Check if its safe to rewind by comparing block to earliest block

graph/src/env/mod.rs, store/postgres/examples/layout.rs, store/postgres/src/catalog.rs, store/postgres/src/copy.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs, store/postgres/src/relational/index.rs, store/postgres/src/relational/prune.rs, store/postgres/src/subgraph_store.rs, store/postgres/src/writable.rs, store/test-store/tests/postgres/relational.rs, store/test-store/tests/postgres/relational_bytes.rs
Addresses the https://github.com/graphprotocol/graph-node/issues/5140 issue. The tests are still pending.
=> Graphman copy indexing improvements

graph/src/firehose/endpoints.rs
It was missing from two other places where the client is constructed.
=> consistently apply the max decode size

core/src/subgraph/runner.rs
`handle_process_wasm_block` was not causing the deployment_head metric to follow the block_ptr.
Copied over the call from `handle_process_block`
=> fix deployment_head metrics not progressing for substreams (sps)

chain/ethereum/src/chain.rs, graph/src/components/store/traits.rs, node/src/manager/commands/chain.rs, store/postgres/src/chain_store.rs, store/test-store/tests/postgres/chain_head.rs
Block data is not guaranteed to have a fixed format, so it was not a reliable source from which to extract the block ptr required by the `graphman chain info` command. Skipped the block data parsing and returned block ptr directly from the store.
Fixes #5268
=> graphman: skip parsing block data in chain info

store/postgres/src/copy.rs, store/postgres/src/dynds/private.rs
The second commit actually fixes [this bug](https://github.com/graphprotocol/graph-node/issues/5465)
=> store: Better error message for missing template during grafting

graph/src/components/store/mod.rs, tests/runner-tests/file-data-sources/abis/Contract.abi, tests/runner-tests/file-data-sources/schema.graphql, tests/runner-tests/file-data-sources/src/mapping.ts, tests/runner-tests/file-data-sources/subgraph.yaml, tests/src/fixture/ethereum.rs, tests/tests/runner_tests.rs
=> Derived fields should respect causality region + Improve tests

chain/ethereum/src/ethereum_adapter.rs
The Nethermind-based clients use a similar format to Parity ones, but we've seen messages like `"Reverted ERC721"` so we need the message detection to be broader than `"Reverted 0x"`.
=> fix(ethereum): Detect Nethermind eth_call reverts

graph/src/firehose/endpoints.rs
After #5337 substreams support is broken for some chains.
The issue is when fetching genesis block, [we stream only block 0](https://github.com/graphprotocol/graph-node/blob/08f10a86bbbb14ea0fa1e5575e8d7a552b7867d2/graph/src/firehose/endpoints.rs#L119-L127). For some chains genesis block number is 2 (EOS, WAX), 3 (Telos) or even 79123881 (Sei).
This PR fixes it by removing `stop_block_num` from the request, so the first block we receive is the genesis block no matter where it is.
=> Fix genesis block fetching for substreams

graph/src/components/adapter.rs, node/src/bin/manager.rs, node/src/network_setup.rs
- Add timeout when checking providers
- When running graphman patch the pool-size to avoid unnecessary errors
=> Improve net_identifiers call with timeout

graph/src/components/adapter.rs, graph/src/firehose/endpoints.rs, node/src/bin/manager.rs, node/src/chain.rs, node/src/main.rs, node/src/manager/commands/config.rs, node/src/manager/commands/run.rs, node/src/network_setup.rs
1. If an error occurs during startup net_identifier calls, just ignore an use a default value 
2. If validation is enabled, this will cause the adapter to eventually fail because whatever genesis the adapter returns won't match the default (0x00) genesis value. 
This change prevents the graph-node from failing to start due to broken adapters but if genesis validation is enabled it should eventually update the store
=> timeout when trying to get net_identifiers at startup

server/json-rpc/src/lib.rs
Closes #5531 
`subgraph_resume` was mislabelled as `subgraph_pause` on `resume_handler`
=> fix: subgraph_resume mislabelled as pause

graph/src/data/subgraph/schema.rs, store/postgres/migrations/2024-07-22-140930_track_synced_date/down.sql, store/postgres/migrations/2024-07-22-140930_track_synced_date/up.sql, store/postgres/src/deployment.rs, store/postgres/src/detail.rs, store/postgres/src/primary.rs
We migrate `synced` from a boolean value to a nullable `synced_at` timestamp on `subgraphs.subgraph_deployment` and `unused_deployments`. The default timestamp used in the migration is the unix epoch, `1970-01-01 00:00:00+00`.
Note that in the down migration we skip removal of the `DEFAULT false` on `unused_deployments.`
=> Store timestamp when marking subgraph as synced

server/index-node/src/schema.graphql
This PR fixes #5550 by making the `paused` field in the status graphql nullable, which matches the struct field of `Option<bool>` and allows the indexer-agent to handle the `None/null` case when appropriate.
=> fix: resolves #5550 - make graphql  value nullable

store/postgres/src/subgraph_store.rs
Previously, we were trying to load indexes from the store corresponding to the subgraph being deployed. This was the wrong shard, resulting in deployment failures when a subgraph is on a different shard from its graft based.
This updates the call to use the correct store.
=> Use correct store when loading indexes for graft base

store/postgres/src/relational/rollup.rs
=> "count" aggregations fix 

chain/substreams/proto/codec.proto, chain/substreams/src/mapper.rs, chain/substreams/src/protobuf/substreams.entity.v1.rs
Implements #5637
Adds support for `Timestamp` decoding in `EntityChanges`
Needed for aggregation support in substreams-powered subgraphs.
=> Add `timestamp` support to substreams 

runtime/test/src/test.rs, runtime/wasm/src/module/instance.rs
rustc 1.81 produces a warning (see
https://github.com/rust-lang/rust/issues/123748) in a few places. This change fixes that.
=> runtime: Fix compiler warning

graph/src/data/subgraph/mod.rs
Closes https://github.com/graphprotocol/graph-node/issues/5197
Fix graft validation checks
- Removed the conditional compilation for reorg threshold checks in debug builds
This will be good to go as we have `reorg_threshold` set to 0 on debug builds.
https://github.com/graphprotocol/graph-node/blob/b0c89526fd932393f3e43350ee664404eb858040/graph/src/env/mod.rs#L238-L241
=> Enable graft validation checks for debug

graph/src/components/store/traits.rs, store/postgres/migrations/2024-08-14-205601_store_synced_at_block/down.sql, store/postgres/migrations/2024-08-14-205601_store_synced_at_block/up.sql, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/detail.rs, store/postgres/src/primary.rs, store/postgres/src/writable.rs, store/test-store/tests/graph/entity_cache.rs, store/test-store/tests/postgres/graft.rs, store/test-store/tests/postgres/subgraph.rs, store/test-store/tests/postgres/writable.rs
This is a follow up to #5566 
We use both `INTEGER` and `NUMERIC` types in the database to match how other block numbers are stored in the same table.
=> Store `synced_at_block_number` when a deployment syncs

Cargo.lock, Cargo.toml, graph/Cargo.toml
This supersedes some dependabot PRs:
- Closes #5655: Dependabot missed the `async-graphql-axum` dependency, leading to a failed build
- Closes #5613: Rolled into this PR
- Closes #5559: Rolled into this PR
- Closes #5632: Rolled into this PR
Additionally, we bump `diesel` to 2.2.4 for [`RUSTSEC-2024-0365`](https://rustsec.org/advisories/RUSTSEC-2024-0365).
=> Update various dependencies

core/graphman/src/commands/deployment/pause.rs, core/graphman/src/commands/deployment/resume.rs, core/graphman/src/deployment.rs
There was an issue that prevented `graphman restart` from running if a deployment ID was referenced by multiple subgraph names. This PR fixes that.
Closes #5670
=> Graphman restart: Handle cases where multiple subgraph names reference a deployment ID

Cargo.toml, graph/src/data/store/scalar/bigdecimal.rs, graph/src/data/store/scalar/bytes.rs, graph/src/data/store/scalar/timestamp.rs, graph/src/data/value.rs, graph/src/data_source/causality_region.rs, store/postgres/src/block_range.rs, store/postgres/src/primary.rs, store/postgres/src/relational.rs, store/postgres/src/relational/dsl.rs, store/postgres/src/relational/query_tests.rs, store/postgres/src/relational/value.rs, store/postgres/src/relational_queries.rs
Our queries all ultimately get their data by doing something like `select to_jsonb(c.*) from ( ... complicated query ... ) c` because when these queries were written it was far from obvious how to generate queries with Diesel that select columns whose number and types aren't known at compile time.
The call to `to_jsonb` forces Postgres to encode all data as JSON, which graph-node then has to deserialize which is pretty wasteful both in terms of memory and CPU.
This commit is focused on the groundwork for getting rid of these JSON conversions and querying data in a more compact and native form with fewer conversions. It only uses it in the fairly simple case of `Layout.find`, but future changes will expand that use
=> graph, store: Avoid using to_jsonb when looking up a single entity

graph/src/blockchain/types.rs, graph/src/data/store/scalar/timestamp.rs, graph/src/env/store.rs, server/graphman/tests/deployment_query.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/relational/rollup.rs
When graph-node is restarted, we need to determine for subgraphs with aggregations when the last rollup was triggered to ensure aggregations get filled without gaps or duplication.
The code used the `block_time` column in the PoI table for that but that is not correct as the PoI table only records blocks and times for which the  subgraph actually has writes. When the subgraph scans through a largish number of blocks without changes, we only update the head pointer but also do rollups as aggregation intervals pass. Because of that, we might perform a rollup without a corresponding entry in the PoI table.
With this change, we actually find the maximum timestamp from all aggregation tables to tell us when the last rollup was triggered as that data reflects when rollups happened accurately. …
=> Do not repeat a rollup after restart in some corner cases

graph/src/ipfs/error.rs
In the integration tests, some subgraphs will sync on fraction3, leading to an error as they failed to sync on integer.
Coincidentally, on some runs, fraction3 will also error leading to a _successful_ test; this happens when the subgraph _fails_ to sync due to an HTTP 521 error received when querying the testnet IPFS node. This is a non-deterministic error, and the request can simply be retried.
=> Retry IPFS request on Cloudflare 521 Web Server Down

store/postgres/src/relational/dsl.rs
- Remove `tsvector` columns from `SELECT` clauses in entity queries
- Filter out full-text search columns from the list of selected columns
Full-text search columns (`tsvector` type) are used for indexing and efficient text searching, but they are not part of the entity's data model and are not meant to be directly queried or returned. This fixes a bug where trying to load a tsvector column fails, as diesel does not natively have tsvector support, and we don't explicitly handle the type in `relational::value::OidValue::from_sql`.
=> Exclude full-text search columns from entity queries

Cargo.lock, core/Cargo.toml, core/src/polling_monitor/ipfs_service.rs, graph/src/components/link_resolver/ipfs.rs, graph/src/ipfs/client.rs, graph/src/ipfs/content_path.rs, graph/src/ipfs/error.rs, graph/src/ipfs/gateway_client.rs, graph/src/ipfs/mod.rs, graph/src/ipfs/pool.rs, graph/src/ipfs/retry_policy.rs, graph/src/ipfs/rpc_client.rs, graph/src/ipfs/server_address.rs, runtime/test/src/common.rs, tests/src/fixture/mod.rs
This PR reduces the number of unnecessary IPFS retries by requiring an explicit retry policy, so that different components of the graph-node can decide to use different types of retries, or not use retries at all.
Closes #5696
**Other improvements:**
IPFS client pool now reuses the initial response instead of doubling the number of requests.
**Future improvements:**
This PR includes the first steps in defining deterministic IPFS errors so that some retries can be eliminated altogether. This functionality is not part of this PR as it requires more thought and testing and will be added in a future PR.
=> Optimize IPFS retries

docker/Dockerfile
In #5620, we updated our base Debian image tag, resulting in our installation of the `netcat` package failing due to being made a virtual package (provided by either `netcat-openbsd` and `netcat-traditional`). Here, we opt to specifically use `netcat-openbsd` to match Bullseye's default.
=> Install correct netcat package in Docker builds

docker/Dockerfile
This PR updates the graph-node image to solve this issue with missing libssl
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
=> updated graph-node image to solve the missing libssl

docker/Dockerfile
This PR updates all images to the same bookworm and fix the dockerfile deprecations syntax
=> graph-node docker image

core/src/subgraph/context/mod.rs, core/src/subgraph/instance_manager.rs, core/src/subgraph/runner.rs, store/postgres/src/writable.rs
This PR fixes a long-standing bug that caused many subgraphs to fail repeatedly when a simple sequence of errors, retries, and restarts occurred.
Closes #5452
There have been multiple reports of some subgraphs failing randomly, and restarts only helping temporarily. 
I have examined several days of logs for some subgraphs and found patterns that lead to this strange state when nothing seems to help recover the subgraphs. 
Based on that, I started to reproduce the bug locally and looked for a way to fix it with minimal refactoring.
- I set up a minimal subgraph to record block numbers and timestamps and deployed it locally.
- Modified the graph-node code _([here](https://github.com/graphprotocol/graph-node/blob/6b48bfda297eb253e9e802eed53452b9dc1b88d2/core/src/subgraph/runner.rs#L378))_ to …
=> Do not allow multiple active runners for a subgraph

graph/src/data/query/mod.rs, graph/src/data/query/result.rs, graphql/src/runner.rs, store/test-store/src/store.rs
This adds a `graph-indexed` header to query responses. The header value contains the block hash, number, and timestamp for the most recently processed block in the subgraph. This avoids the need to rewrite all queries to include `_meta { block { hash number timestamp } }` in either the indexer-service or gateway.
Related: https://github.com/edgeandnode/gateway/issues/900, https://github.com/graphprotocol/indexer-rs/issues/494
=> Add graph-indexed header

chain/substreams/src/trigger.rs, core/src/subgraph/runner.rs, graph/src/components/store/entity_cache.rs, graph/src/components/subgraph/instance.rs, graph/src/env/mod.rs, runtime/wasm/src/host_exports.rs, store/postgres/src/deployment_store.rs, store/test-store/tests/graph/entity_cache.rs
Also updates an out of date comment
=> Add config option for cache stores

core/src/subgraph/context/instance/hosts.rs, graph/src/util/lfu_cache.rs
Rust 1.83 is more strict with implicit lifetimes. This fixes a couple of warnings.
=> compiler fix

graph/src/ipfs/client.rs, graph/src/ipfs/gateway_client.rs, graph/src/ipfs/mod.rs, graph/src/ipfs/retry_policy.rs, graph/src/ipfs/rpc_client.rs
This PR improves IPFS client selection by sending concurrent requests to all supported IPFS APIs and selecting the first one that responds with the expected status code.
Also, logging of IPFS test request retries has been disabled to not make it look like something is not working correctly.
=> Improve IPFS client selection

store/postgres/src/relational/dsl.rs, store/test-store/tests/postgres/relational.rs
Roundtripping arrays of enums would fail because we would read an array of enums back as a single string "{yellow,red,BLUE}" instead of the array ["yellow", "red", "BLUE"]. Storing an update to such an entity, even if users make no changes to that field, would fail because Postgres expects an array and we were sending a scalar value.
This fixes a bug introduced in PR
https://github.com/graphprotocol/graph-node/pull/5372
=> store: Fix handling of enum arrays

core/src/subgraph/runner.rs
Fixes #5749 
Deployed a SPS to studio with error - `QmRxqwbpjKxmAQkXVgAwS65xvtAyyoVSpxd1J554AxYFN6 `
```curl
curl --location 'https://api.thegraph.com/index-node/graphql' \
--header 'Content-Type: application/json' \
--data '{"query":"{\n        indexingStatuses(subgraphs: [\"QmRxqwbpjKxmAQkXVgAwS65xvtAyyoVSpxd1J554AxYFN6\"]){\n            subgraph\n            synced\n            health\n            fatalError {\n                message\n                handler\n                deterministic\n            }\n            nonFatalErrors{\n                message\n                block{number}\n            }\n        }\n    }","variables":{}}' | jq .
```
This request returns subgraph is still healthy and doesn't add any error to fatal Errors field
```
{
"data": {
"indexingStatuses": [
{ …
```
=> improve error handling of substreams powered subgraphs

NEWS.md, core/src/subgraph/instance_manager.rs, core/src/subgraph/runner.rs, graph/src/blockchain/block_stream.rs, graph/src/components/metrics/registry.rs, graph/src/components/metrics/subgraph.rs, tests/src/fixture/mod.rs
This PR adds a new `deployment_status` metric with the following behavior:
- Once graph-node has figured out that it should index a deployment, `deployment_status` is set to `1` _(starting)_;
- When the block stream is created and blocks are ready to be processed, `deployment_status` is set to `2` _(running)_;
- When a deployment is unassigned, `deployment_status` is set to `3` _(stopped)_;
- If a temporary or permanent failure occurs, `deployment_status` is set to `4` _(failed)_;
- If indexing manages to recover from a temporary failure, the `deployment_status` is set back to `2` _(running)_;
_No other values for `deployment_status` should be expected._
Closes #5405
The `deployment_failed` metric is removed and the failures are reported by the new `deployment_status` metric.
Node …
=> Add `deployment_status` metric

graph/src/util/mod.rs, graph/src/util/ogive.rs, store/postgres/src/catalog.rs, store/postgres/src/copy.rs, store/postgres/src/lib.rs, store/postgres/src/relational/prune.rs, store/postgres/src/vid_batcher.rs
When we copy/graft/prune, we split the entire work that needs to be done into batches that are meant to take roughly three minutes to avoid bloating the `subgraph_deployment` table. Pruning causes a very serious problem with that, and when that happens it can be crippling for the performance of the overall system.
The code that adjusts the size of the batch to hit that target tacitly assumes that the actual work is distributed linearly, i.e., if we ask for work covering 10,000 rows (going by `vid`), we are fine with getting fewer rows, maybe even just a handful, but this needs to be uniform: any 10,000 row batch needs to have roughly the same number of rows. Pruning breaks this assumption since in a pruned subgraph, the beginning of the subgraph (as determined by block numbers) will be …
=> Make copy/graft/prune work with unevenly distributed rows

graph/src/data/store/mod.rs, graph/src/schema/entity_type.rs, graph/src/schema/input/mod.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/dsl.rs, store/postgres/src/relational/prune.rs, store/postgres/src/relational_queries.rs
Addressing some of the remaining remarks in regards to the VIDs.
=> VID related fixes and improvements

graph/src/data/subgraph/mod.rs, graph/src/data_source/subgraph.rs, store/test-store/tests/chain/ethereum/manifest.rs
This PR
- Sets a hard limit (5) on the number of datasources that can be composed together 
- Prevents nesting of subgraph datasources
=> Subgraph Composition: More validations

graph/src/components/metrics/registry.rs
This PR updates the metric registration mechanism so that the most recent metric registration attempt is considered valid and the previous registration is discarded, fixing a long-standing issue that caused multiple metrics to fail to report new values.
Closes #5758 
In the previous implementation, only the first metric registration was considered valid, and all subsequent attempts to create the same metric were internally considered invalid. External modules always get a metric on calls to register, even if the registration fails internally. This was a problem because many operations in graph-node are expected to be executed multiple times, and the limited cleanup of old metrics was not working as expected. The result was that many operations in graph-node had non-working metrics after …
=> Fix metrics not reporting new values

NEWS.md, core/src/subgraph/runner.rs, graph/src/components/metrics/subgraph.rs
This PR adds a new `deployment_synced` metric that indicates whether a deployment has reached the chain head since it was deployed.
Possible values for the metric:
- `0` - means that the deployment is not synced;
- `1` - means that the deployment is synced;
If a deployment is not running, the metric reports no value for that deployment.
Closes #5813
_* All values in the example are for the same subgraph deployment._
=> Add `deployment_synced` metric

server/graphman/src/entities/warning_response.rs, server/graphman/tests/deployment_mutation.rs
This PR ensures that the correct node ID is used by tests, as there are some differences between running tests locally and on the CI.
=> Graphman: Do not use hardcoded node ID in tests

node/src/bin/manager.rs, node/src/manager/commands/deployment/info.rs, node/src/manager/display.rs
graphman info prints one fairly big block of text for each subgraph version. A lot of the information is repetetive since it is tied to a deployment, not a subgraph name. To make the output more usable, it is now organized around deployments, and lists all the names for a deployment in one place, like:
```
Namespace        | sgd114 [primary]
Hash             | QmVsp1bC9rS3rf861cXgyvsqkpdsTXKSnS4729boXZvZyH
Versions         | u65281/s53035/latest (current)
| u65281/s53035/v2 (current)
Chain            | mainnet
Node ID          | default
Active           | true
Paused           | false
Synced           | false
Health           | healthy
Earliest Block   | 9923743
Latest Block     | 9931270
Chain Head Block | 20988707
Blocks behind | 11057437
```
The new options `--brief` and `--no-name` …
=> node: Make output of `graphman info`more concise

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/code-coverage.yml
Some outdated GH actions that can be upgraded
=> upgrade GH actions

store/postgres/src/catalog.rs, store/postgres/src/connection_pool.rs
This PR adds views for the sharded metadata tables in the primary. The views are created in the `sharded` namespace and cover all the tables that are maintained in individual shards:
```
copy_state
copy_table_state
dynamic_ethereum_contract_data_source
ethereum_networks
subgraph_deployment
subgraph_error
subgraph_features
subgraph_manifest
table_stats
```
It also removes a few tables that are not sharded from the `shard_<name>_subgraphs` namespace, namely `subgraph`, `subgraph_version` and  `subgraph_deployment_assignment`. Those can be accessed through the `primary_public` namespace.
=> Add views across all shards

store/postgres/src/copy.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/relational_queries.rs
We used to count all entities in the destination after all data had been copied; for large subgraphs, that can be a very slow operation, and in some cases makes the copy operation fail because the underlying fdw connection times out.
With this PR, we now update the entity count with every batch we copy.
=> Remove separate entity counting step at end of copy

graph/src/schema/api.rs, graph/src/schema/input/mod.rs, graphql/src/store/prefetch.rs
=> Add ability to order by fields other than timestamp for aggregation entities

store/postgres/src/relational.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/index.rs, store/postgres/src/relational/prune.rs
Fixes #5787 and bug mentioned in previous [PR](https://github.com/graphprotocol/graph-node/pull/5791#discussion_r1950129026)
=> pass list of indexes when pruning a subgraph

graph/src/env/store.rs, store/postgres/src/connection_pool.rs
Changing the fetch_size to 10,000 from its default of 100 will have a dramatic effect on the time copy operations take.
The fetch_size can be controlled with the environment variable `GRAPH_STORE_FDW_FETCH_SIZE`
=> graph, store: Use a much larger fetch_size for fdw

graph/src/data/subgraph/mod.rs
Improve the `BlockNotFound` error when deploying subgraphs by adding the block number in the error message
=> graph: improve error message for block not found in Ethereum network

graph/src/data/subgraph/mod.rs, graph/src/data_source/common.rs
The other day with @marcusrein we've ran into an issue with Explorer for one of the chains supplying slightly invalid ABI (one of the required fields was being lost during serialization). 
`graph init` would scaffold subgraph for this ABI but `graph deploy` request to Graph Node would fail with a very generic error:
`
✖ Failed to deploy to Graph node http://localhost:8020/: subgraph resolve error: resolve error: failed to resolve data source Contract with source_address Some(0x88b8e2161dedc77ef4ab7585569d2415a1c1055d) and source_start_block 4900000
`
Deployment: `QmejLsgNNWCWT25HqVsgWZ6VgDBWpaR7RijQeYdcDZn6k3`
This PR makes error message more descriptive for the subgraph developer:
`
✖ Failed to deploy to Graph node http://localhost:8020/: subgraph resolve error: resolve error: failed to …
=> More descriptive manifest resolve error

chain/substreams/src/trigger.rs, core/src/subgraph/context/mod.rs, core/src/subgraph/runner.rs, core/src/subgraph/trigger_processor.rs, graph/src/components/store/traits.rs, graph/src/components/subgraph/proof_of_indexing/mod.rs, runtime/test/src/common.rs, runtime/wasm/src/host_exports.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/writable.rs, store/test-store/tests/graph/entity_cache.rs
Subgraphs have in fact supported proof of indexing for almost 5 years since commit 40fd330c and we can therefore stop pretending that `WritableStore.supports_proof_of_indexing` would ever return `false`
=> Stop pretending that there are subgraphs that don't support PoI

Cargo.lock, Cargo.toml, chain/ethereum/Cargo.toml, chain/ethereum/src/network.rs, core/Cargo.toml, core/src/polling_monitor/ipfs_service.rs, runtime/wasm/Cargo.toml, runtime/wasm/src/mapping.rs, store/postgres/Cargo.toml, store/postgres/src/store_events.rs
These changes are mostly housekeeping and update some of our dependencies and/or remove the use of some like `uuid` which can be easily replaced in a few places with atomic counters.
=> Update a few dependencies

store/postgres/src/copy.rs, store/postgres/src/deployment_store.rs, store/postgres/src/subgraph_store.rs
=> A couple copy improvements

store/postgres/src/vid_batcher.rs
When setting up a `VidBatcher` we have both accurate values for the range of vids as well as Postgres' estimate of bounds for a histogram with roughly the same number of entries in each bucket.
As an example, say we have min and max of 1 and 100, and histogram bounds [5, 50, 96]. We used to then add min and max to these bounds resulting in  an ogive over [1, 5, 50, 96, 100]. With that, it seems that there is a  bucket [1, 5] with just as many entries as the bucket [5, 50], which is not what the Posgres staistics indicate. Using this ogive will cause
e.g. pruning to increase batch size quickly as it tries to get out of the  [1, 5] bucket resulting in a batch size that is way too big for the next  bucket and a batch that can take a very long time.
The first and last entry of the bounds are …
=> Fix a mistake in handling histogram bounds for batching prunes and copies

store/postgres/src/relational_queries.rs
When grafting from a spec version bellow 1.3.0 to it the VID insertion criteria was used based on source subgraph rather than the destination one as it should be.
=> Fix a grafting bug

store/postgres/src/copy.rs, store/postgres/src/relational/ddl.rs, store/postgres/src/relational/ddl_tests.rs, store/postgres/src/relational/index.rs
This fixes two issues with postponed index creation:
(1) When the table has a user-supplied `block` column, we created the index on `block$` twice
(2) We did not create postponed indexes on `(<attr>, block$)`
=> Index creation fixes

store/postgres/src/dynds/private.rs, store/postgres/src/relational_queries.rs
Currently, private data sources are copied one-by-one which can be very slow for deployments with huge numbers of data sources (say, 100's of thousands)
This PR changes that so that we copy data sources in bulk
=> Copy private data sources in batches

chain/ethereum/src/chain.rs, chain/ethereum/src/env.rs, graph/src/env/mod.rs, graph/src/firehose/endpoints.rs, node/src/chain.rs
Composable subgraphs need to fetch block ptrs to handle reorgs, when its not in the cache graph-node uses firehose endpoint to fetch the block using a `SingleBlockRequest` but this is currently slower than RPC.
This PR
- Adds an option to force using RPC to fetch block ptrs when an RPC endpoint is available
- Parralize fetching blocks when using firehose
- Added some refactoring in `FirehoseEndpoints` code
=> Subgraph Composition: Option to force rpc to fetch block ptrs

Cargo.toml, graph/src/firehose/endpoints.rs
Fix GRPC TLS invalid peer error
=> fix firehose tls

Cargo.lock, graph/Cargo.toml, graph/src/components/subgraph/proof_of_indexing/online.rs
When grafting from a spec_version before 0.0.6 towards 0.0.6 or above the grafting fails because of the change in the hashing format.
=> Grafting issue

graph/src/components/metrics/registry.rs, graph/src/components/store/err.rs, graph/src/components/store/traits.rs, graph/src/data/query/trace.rs, graph/src/task_spawn.rs, graphql/src/execution/resolver.rs, graphql/src/introspection/resolver.rs, graphql/src/runner.rs, graphql/src/store/resolver.rs, node/src/bin/manager.rs, node/src/store_builder.rs, server/index-node/src/resolver.rs, store/postgres/src/advisory_lock.rs, store/postgres/src/block_store.rs, store/postgres/src/connection_pool.rs, store/postgres/src/deployment_store.rs, store/postgres/src/primary.rs, store/postgres/src/query_store.rs, store/postgres/src/store.rs, store/test-store/tests/graphql/introspection.rs, tests/src/config.rs
With multiple nodes, they could race each other and cause database errors.
I've reworked the startup code to be (a) race-proof (I hope) and (b) easier to follow. Any node that wants to run database setup now gets a lock on the primary, and runs all code needed for setup while holding that lock. That way, nodes can't interfere with each other. In the common case, where there are no database changes, be it because of migrations, configuration changes, or code changes that map different tables, the time during which any node holds the lock is very brief. This could be further optimized but let's first see how this performs in practice.
=> Store startup fixes

store/postgres/src/relational/ddl.rs
When index creation was postponed, we would create aggregate indexes twice. They could also be postponed, but we'll leave that for another day.
=> store: Do not create aggregate indexes twice

store/postgres/src/copy.rs
We used to only try to spawn a new copy worker when we were finished copying a table. But that can take a long time, and in between some connections might have become available. We now check every few minutes if a connection is available and spawn a new worker if it is
=> store: Try to spawn copy workers more frequently

store/postgres/src/copy.rs, store/postgres/src/deployment_store.rs, store/postgres/src/primary.rs, store/postgres/src/subgraph_store.rs
Copying checks the active_copies table through the primary_public.active_copies foreign table to determine whether the copy has been cancelled and it should stop.
With a large number of copies running, that causes a large number of postgres_fdw connections into the primary, which can overwhelm the primary.
Instead, we now pass the connection pool for the primary into the copy code so that it can do this check without involving postgres_fdw.
=> store: Do not use a fdw connection to check active_copies

graph/src/components/store/write.rs
If subgraphs delete entities without checking if they exist, we get two removes in a row. In the database, the second remove would just lead to a query that changes nothing. We'll do the same when putting a write batch together.
Fixes https://github.com/graphprotocol/graph-node/issues/5449
=> graph: Allow remove followed by remove in write batches

chain/ethereum/src/chain.rs, graph/src/data/subgraph/mod.rs, graph/src/env/mod.rs, node/src/chain.rs, node/src/manager/commands/prune.rs, node/src/manager/commands/rewind.rs, store/postgres/src/block_store.rs, store/postgres/src/deployment.rs, store/postgres/src/deployment_store.rs, tests/src/config.rs, tests/src/fixture/ethereum.rs, tests/tests/runner_tests.rs
Addressing the review comments from https://github.com/graphprotocol/graph-node/pull/5804 and squashed previous commits to one verified commit.
=> Fix reorg threshold

graph/src/env/store.rs, store/postgres/src/deployment_store.rs, store/postgres/src/relational.rs, store/postgres/src/writable.rs
This flag was only meant as a safety switch in case the fixed behavior caused trouble. Since it's not been needed in several months, it's safe to remove it.
=> graph, store: Remove GRAPH_STORE_LAST_ROLLUP_FROM_POI

core/graphman/src/commands/deployment/reassign.rs, node/src/manager/commands/deployment/reassign.rs, server/graphman/src/resolvers/deployment_mutation/reassign.rs
When reassigning subgraphs, the current assigned node is not displayed. This PR solves this issue.
=> display current node when reassigning subgraph

core/src/subgraph/inputs.rs, core/src/subgraph/registrar.rs, core/src/subgraph/runner.rs, graph/src/blockchain/block_stream.rs, graph/src/components/subgraph/instance.rs, graph/src/ext/futures.rs
There's lots more that could and should be done, but it's a start to make the runner more readable
=> Simplify the SubgraphRunner a little

Cargo.lock, Cargo.toml, graph/src/components/store/err.rs, graph/src/components/store/mod.rs, graph/src/env/store.rs, node/src/bin/manager.rs, node/src/manager/commands/copy.rs, node/src/manager/commands/prune.rs, node/src/manager/commands/stats.rs, node/src/manager/fmt.rs, node/src/manager/mod.rs, store/postgres/migrations/2025-04-08-224710_add_prune_state/down.sql, store/postgres/migrations/2025-04-08-224710_add_prune_state/up.sql, store/postgres/src/deployment_store.rs, store/postgres/src/lib.rs, store/postgres/src/pool/mod.rs, store/postgres/src/primary.rs, store/postgres/src/relational.rs, store/postgres/src/relational/prune.rs, store/postgres/src/subgraph_store.rs
So far, the intial prune of a subgraph had to be done synchronously in a terminal. This PR makes it possible to modify the amount of history a subgraph should keep but have the initial and all subsequent prunes happen in the background.
To that end, this PR changes the `graphman` commands used for pruning. `graphman prune` now has subcommands:
* `graphman prune run` behaves as `graphman prune` did before this PR
* `graphman prune set` just changes how much history a subgraph keeps. The actual pruning happens in the background
* `graphman prune status` shows the details of pruning runs
Most of this PR is concerned with keeping information in the database that is shown by `graphman prune status`. The output of the status command is something like
```
prune Qm...[19] (run #5)
range: 12834375 …
```
=> Async pruning

node/src/manager/deployment.rs
This makes cut&paste from various places much easier since now `sgdNNN` and just `NNN` mean the same thing for graphman
=> node: Accept a bare number as a deployment id in graphman

store/postgres/src/relational/prune.rs
Since it is used for the default value, we get an error
```
sequence sgdNNN.<table>_vid_seq membership in
replication set default depends on sequence sgdNNN.<table>_vid_seq
```
That makes all pruning by rebuilding tables fail
=> store: Drop the vid sequence with 'cascade'

core/src/subgraph/runner.rs, graph/src/components/store/traits.rs, store/postgres/src/writable.rs, store/test-store/tests/graph/entity_cache.rs
Unassigning subgraphs has a number of unwanted side-effects, e.g., canceling copies. Pausing is safer alternative to avoid spending cycles on a subgraph we know will not make progress.
=> core, graph, store: Pause failed subgraphs instead of unassigning

graph/src/ipfs/retry_policy.rs, graph/src/util/futures.rs
We add a new configurable max delay between retries, which defaults to 60 seconds for requests made via the IPFS client.
=> Bump IPFS client max retry delay to 60 seconds

docs/environment-variables.md, graph/src/env/mappings.rs, graph/src/ipfs/retry_policy.rs
This PR changes the hardcoded DEFAULT_MAX_ATTEMPTS to a configurable env var GRAPH_NODE_IPFS_MAX_ATTEMPTS to avoid spamming the IPFS on deterministic errors
=> graph: IPFS_MAX_ATTEMPTS ani-smap mechanism env var

graphql/src/store/query.rs
=> graphql: Avoid cloning a list

store/test-store/tests/graphql/query.rs
Check the situation where an entity that has empty relations to other entities is followed by one that does have them and ensure that we link up the children correctly in that situation.
Found this change cleaning up old branches, but don't remember what prompted writing it. But another test won't hurt either way
=> graphql: Add a query test

docs/environment-variables.md, store/postgres/src/copy.rs, store/postgres/src/relational/prune.rs, store/postgres/src/vid_batcher.rs
Uses the same timeout as copying. If a prune operation now takes longer than `GRAPH_STORE_BATCH_TIMEOUT` it is aborted and retried with a batch size of 1
=> Kill and retry pruning batch operations

store/postgres/migrations/2025-05-13-173523_split_subgraph_deployment/up.sql
For this migration, we need to hold all necessary locks before we start making changes, otherwise concurrent operations can cause deadlocks and abort the migration.
=> store: Add explicit locking to a migration

graph/src/components/store/mod.rs, graph/src/env/store.rs, node/src/manager/commands/stats.rs, store/postgres/src/catalog.rs, store/postgres/src/lib.rs, store/postgres/src/relational/prune.rs, store/test-store/tests/postgres/graft.rs
Pruning can use one of two strategies to get rid of unneeded rows in a table: deleting or rebuilding. Rebuilding is better when we remove more than 50% of a table, otherwise, deletion should be used.
Currently, we estimate how much of a table will be removed by looking at the percentage of historical blocks we prune weighted by the ratio of entity versions to entities. This basically assumes that entity changes are very evenly distributed across blocks. In practice, this leads to serious overestimation of how much of a table will be removed. In one case, the estimate was that 58% of a table would be removed, when in reality only 2% of the table would be removed.
With this change, we use database statistics to improve the estimates which reflect reality much more closely.
=> Improve how pruning estimates how much of a table will be removed

Cargo.lock, Cargo.toml, docs/environment-variables.md, graph/Cargo.toml, graph/src/components/link_resolver/ipfs.rs, graph/src/env/mappings.rs, graph/src/env/mod.rs, graph/src/ipfs/cache.rs, graph/src/ipfs/error.rs, graph/src/ipfs/gateway_client.rs, graph/src/ipfs/mod.rs
This change adds a variable `GRAPH_IPFS_CACHE_LOCATION`, which, when set, needs to point at a directory writable by `graph-node`. All files that `graph-node` will fetch from IPFS will be cached in that directory so that subsequent requests to fetch these files, e.g., after a restart, will use those cached files rather than issuing another IPFS request.
Caching files has obvious security implications in that it is possible to modify files in the cache, and thereby change a subgraph. In other words, the cache needs to be in a trusted location with restricted access.
=> Allow caching of IPFS files in file system

chain/ethereum/src/trigger.rs
This reverts an inadvertent change that was introduced in PR https://github.com/graphprotocol/graph-node/pull/5867
=> chain/ethereum: Use the log_index as the transaction_log_index

core/src/polling_monitor/mod.rs, graph/src/env/mappings.rs
This changes
1. Files that are not found are now subject to backoff - the longer a file hasn't been found, the less likely it will ever appear
2. The maximum backoff for fds can be configured with `GRAPH_FDS_MAX_BACKOFF` (in seconds) The default is 600 as it was before this PR
=> Small scalability improvements for offchain data sources

.github/workflows/ci.yml, graph/src/components/link_resolver/file.rs, graph/src/components/link_resolver/mod.rs, graph/src/data/subgraph/mod.rs, graph/src/env/mod.rs, tests/runner-tests/file-link-resolver/abis/Contract.abi, tests/runner-tests/file-link-resolver/package.json, tests/runner-tests/file-link-resolver/schema.graphql, tests/runner-tests/file-link-resolver/src/mapping.ts, tests/runner-tests/file-link-resolver/subgraph.yaml, tests/runner-tests/yarn.lock, tests/src/fixture/mod.rs, tests/src/lib.rs, tests/src/recipe.rs, tests/tests/file_link_resolver.rs, tests/tests/runner_tests.rs
This PR implements a file system based link resolver aimed to replace IpfsLinkResolver for local development, this is in preparation for #5977
=> Implement a File Link Resolver

store/postgres/src/relational/prune.rs
When we start copying nonfinal entities, we need to reset the start_vid and next_vid. They don't necessarily have a direct connection to the same values for nonfinal entities; e.g., it is possible that the start_vid for nonfinal entities is smaller than the one for final entities.
This change only affects how we report the completion of prune operations; it has no effect on what gets pruned and how.
=> store: Fix a mistake in how pruning status is reported

.github/workflows/gnd-binary-build.yml
This workflow builds the gnd binary and upload it to the release.
This has been tested out on my graph-node fork, here is an example [run](https://github.com/incrypto32/graph-node/actions/runs/15556403573)
=> Workflow to build the gnd binary

core/graphman/src/commands/deployment/reassign.rs, node/src/manager/commands/deployment/reassign.rs, server/graphman/src/resolvers/deployment_mutation.rs
Improve response type of `graphman reassign` as per  #5822
=> improve graphman reassign response type

graph/src/components/store/write.rs
Immutable entities were bypassing our memoization indexing system. Here's what was happening:
1. Immutable entities were added directly to the batch rows via `append_row()`
2. This skipped the memoization index that `push_row()` normally maintains
3. When the system later tried to look up these entities, it couldn't find them despite being present in memory
4. This caused `store.get()` to return `None` while the entity existed in cache, triggering assertion panics
Change `append_row()` to use `self.push_row(row)` instead of `self.rows.push(row)` for immutable entity inserts. This ensures they're properly indexed while preserving the intended performance benefits.
```rust
// Before: self.rows.push(row);
// After:  self.push_row(row);
```
=> Fix bug where immutable entities bypass memoization index during batch processing

store/postgres/src/relational/query_tests.rs, store/postgres/src/relational_queries.rs, tests/integration-tests/source-subgraph/schema.graphql, tests/integration-tests/source-subgraph/src/mapping.ts, tests/integration-tests/subgraph-data-sources/schema.graphql, tests/integration-tests/subgraph-data-sources/src/mapping.ts, tests/integration-tests/subgraph-data-sources/subgraph.yaml
When using subgraph composition and indexing entity of different type `id`, the subgraph wouldn't sync due to the below error
```
UNION types bytea and text cannot be matched
```
This was because the `FindRangeQuery` SQL generator wasn't casting entity IDs to a consistent type, causing `UNION ALL` operations to fail when merging results from subgraphs with different ID types
=> store: ensure consistent id type in FindRangeQuery SQL output

.github/workflows/ci.yml, tests/docker-compose.yml
It seems that anvil 1.2.3 is the last version to produce deterministic block hashes reliably. The 'grafted' test really needs deterministic block hashes as they influence the PoI which this test checks.
If [this foundry bug](https://github.com/foundry-rs/foundry/issues/9570) gets fixed, we should try again with latest stable foundry.
I spent way too much time trying to work around the nondeterministic block hashes - anything we can do there is way grosser and more brittle than just pinning anvil until upstream is fixed and makes block hashes deterministic.
=> tests: Pin anvil to version 1.2.3

core/src/subgraph/instance_manager.rs, core/src/subgraph/provider.rs, graph/src/components/subgraph/instance_manager.rs, node/src/launcher.rs, node/src/manager/commands/run.rs, tests/src/fixture/mod.rs
The current code in `SubgraphAssignmentProvider.start` fetched the manifest from IPFS before starting a subgraph. But the code calling `start`, ultimately `SubgraphRegistrar.start_assigned_subgraphs` waited for all subgraphs to start successfully before processing assignment events.
That could lead to a situation where a slow IPFS server, even if it was slow for just one subgraph, could keep a node from processing assignment events.
With these changes, interacting with IPFS is deferred to the future that is spawned for running the subgraph so that slow IPFS can slow how long it takes for a subgraph to start, but not the system overall.
=> all: Defer getting manifest from IPFS when starting subgraph
